kubernetes-sigs/gateway-api

apis/v1alpha2/grpcroute_types.go, apis/v1alpha2/tcproute_types.go, apis/v1alpha2/tlsroute_types.go, apis/v1alpha2/udproute_types.go, apis/v1beta1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind feature
This updates the spec to note that ServiceImport has "Extended" support as a BackendRef per GEP #1748.
```release-note
ServiceImports now have "Extended" support in BackendRefs
```
Adding a hold until #1843 merges.
/hold
=> Marking ServiceImport as Extended support

apis/v1beta1/validation/gateway.go
/kind cleanup
Fields that must be unique currently return a `Forbidden` error when validation fails. To better represent the error, this change replaces calls to `field.Forbidden()` with `field.Duplicate()` where appropriate.
This was flagged in the v0.7.0 API review PR (see https://github.com/kubernetes-sigs/gateway-api/pull/1923#discussion_r1160331103)
```release-note
NONE
```
=> cleanup: Replace error types when validating unique fields

apis/v1beta1/gateway_types.go, apis/v1beta1/httproute_types.go
/kind cleanup
The v0.7.0 API review PR had some wordsmithing suggestions around the type doc comments (e.g https://github.com/kubernetes-sigs/gateway-api/pull/1923#discussion_r1162142228). This change addresses the feedback
```release-note
NONE
```
=> cleanup: Touch up some of the doc comments

site-src/api-types/httproute.md
Since we change "custom" to "implementation-specific", I changed the legacy "custom" to "implementation-specific" in docs.
Fixes #
```release-note
```
=> Change Custom to Implementation-specific in Httproute api types docs.

conformance/conformance_test.go, conformance/utils/flags/flags.go, conformance/utils/suite/suite.go, site-src/concepts/conformance.md
/kind test
Some improvements to enable the conformance suite to run mesh tests and to allow the core gateway feature to be excluded from testing. This includes initializing RESTClient, needed to exec into pods for mesh tests.
With these changes, the mesh tests can be run by passing the following args:
```
"--supported-features", "Mesh", "--exempt-features", "Gateway"
```
Fixes #
```release-note
NONE
```
=> Fixes to allow the mesh feature to be tested, including alone

apis/v1alpha2/validation/grpcroute.go, apis/v1beta1/validation/gateway.go
/kind cleanup
This PR includes some cleanup in response to some of @khenidak's feedback on https://github.com/kubernetes-sigs/gateway-api/pull/1923.
```release-note
NONE
```
=> Validation cleanup from v0.7.0 API Review

apis/v1beta1/validation/gateway.go, apis/v1beta1/validation/gateway_test.go
/kind feature
Add validation for `Gateway.Spec.Addresses` field.
Fixes #1960 
no
=> Add validation for `gateway.spec.addresses` to validate whether fields of addresses are set according to the Gateway API specification

geps/gep-1619.md
/kind gep
This update adds concrete configuration for session persistence and affinity to help lay a framework for future potential API design.
We are building iteratively on GEP-1619 by taking small steps towards a workable solution. This PR does not introduce concrete API design yet, but that is expected to come in the near future.
Review this GEP PR with Markdown Rendered: https://github.com/gcs278/gateway-api/blob/gep-1619-cookie-configuration/geps/gep-1619.md
NONE
```release-note
NONE
```
=> GEP-1619: Enumerate common configuration for session persistence and affinity

apis/v1beta1/validation/common.go, apis/v1beta1/validation/common_test.go
/kind bug
Currently, we cannot have:
```yaml
parentRefs:
- name: gw1
port: 80
- name: gw1
port: 8080
```
This seems like an oversight; our validation only takes sectionName into consideration.
Note: this DOES allow overlapping parentSection selection. For exampe, i may select port=80 and sectionName=http which refer to the same thing. This is not something we can catch in validation. Perhaps we need to clarify the behavior here in the spec, if its not clear. Note this could always happen with 2 different routes anyways, though.
Fixes #
```release-note
```
=> validation: take parentRef.port into account

conformance/utils/kubernetes/apply.go, conformance/utils/kubernetes/apply_test.go, conformance/utils/suite/suite.go
/kind cleanup
Due to a recent change from servicelb to metallb for our k3s e2e test environment, this functionality is no longer needed. servicelb allocates a port on the same IP for every LoadBalancer Service, so ports had to be non-overlapping, where metallb allocates a new IP for each LoadBalancer Service.
This functionality is already broken in `main`, see #1217 which aimed to fix it. _This_ PR removes the functionality instead.
```release-note
NONE
```
=> conformance: remove broken ValidUniqueListenerPorts runner functionality

conformance/mesh/manifests.yaml
/kind cleanup
This is the logical next step now that #1991 has merged. I considered just pointing to `:latest` but that would require for us to flip versions with every release to ensure conformance tests at a given release were consistent. Instead pinning to a version seems fine and matches what we're already doing for the other image we're using for conformance tests.
Fixes #1895
```release-note
NONE
```
=> Updating mesh conformance images to point to k8s registry

apis/v1beta1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, conformance/base/manifests.yaml, conformance/tests/httproute-redirect-port-and-scheme.go, conformance/tests/httproute-redirect-port-and-scheme.yaml, conformance/utils/http/http.go, conformance/utils/tls/tls.go
/kind test
Clarify port redirect behaviour and add conformance tests for the same:
```
// When empty, the redirect port MUST be derived using the following rules:
//
// * If redirect scheme is not-empty, the redirect port MUST be the well-known
//   port associated with the redirect scheme. Specifically "http" to port 80
//   and "https" to port 443. If the redirect scheme does not have a
//   well-known port, the listener port of the Gateway SHOULD be used.
// * If redirect scheme is empty, the redirect port MUST be the Gateway
//   Listener port.
```
Proposal doc: https://docs.google.com/document/d/1fx8kuWh2bmBge9IRGn7NlhGqTP0Kj21Cz5RZyUW6428
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1805
Fixes …
=> Clarify port redirect behaviour and add conformance tests for the same

conformance/tests/httproute-redirect-host-and-status.go, conformance/tests/httproute-redirect-host-and-status.yaml
/kind cleanup
This was not really a practical form of redirect as it would just result in a redirect loop or similar.
Fixes #1928
```release-note
Conformance: Remove a test that only covered redirect status without any other changes. 
```
=> Conformance: Removing status-only redirect test

conformance/tests/mesh-split.go, conformance/utils/echo/pod.go
/kind test
/area mesh
Make mesh conformance tests more reliable and fix path matching bug. Split from #44894 since it includes new conformance tests
```release-note
NONE
```
=> Fixes for mesh conformance tests

apis/v1beta1/validation/gateway.go, apis/v1beta1/validation/gateway_test.go
/kind cleanup
This addresses a couple final comments from @thockin on https://github.com/kubernetes-sigs/gateway-api/pull/1923.
```release-note
NONE
```
=> Replacing fmt.Sprintln with plain strings

CHANGELOG.md, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml, config/webhook/admission_webhook.yaml, pkg/generator/main.go
This adds the changelog for v0.7.0. By approving this release, you're approving the release of v0.7.0 based on this commit.
```release-note
NONE
```
=> Adding changelog for v0.7.0 release

conformance/utils/http/http.go
/kind test
This was a regression in 0.7.0-rc2. We generated invalid IPv6 address
Fixes #
```release-note
Fixed an issues causing conformance tests to fail when using IPv6 addresses
```
=> conformance: fix ipv6 addresses

config/webhook/0-namespace.yaml, config/webhook/admission_webhook.yaml, config/webhook/certificate_config.yaml
/kind feature
This PR provides defaults compatible with pod admission controller restricted policy for the webhook config.
Fixes #
```release-note
Webhook config works with PodAdmission restricted
```
=> Deploy webhook in pod admission restricted mode

conformance/tests/httproute-reference-grant.go
/kind test
Fixes #1838
```release-note
HTTPRoute connectivity is in now enforced in conformance tests if a relevant ReferenceGrant gets deleted.
```
=> conformance: check HTTPRoute connectivity after deleting relevant ReferenceGrant

apis/v1beta1/gateway_types.go
/kind cleanup
Fixes stale comment for ListenerConditionAccepted (Pretty much copy pasting Nick's suggestion https://github.com/kubernetes-sigs/gateway-api/issues/1896#issuecomment-1493840812 :) )
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1896
```release-note
NONE
```
=> Update stale comment for ListenerConditionAccepted

README.md, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml, pkg/generator/main.go, site-src/guides/index.md
/kind cleanup
This makes two changes:
* CRDs are labeled as v0.7.0-dev
* Docs point to v0.7.0
```release-note
NONE
```
=> Fixing version refs now that v0.7.0 has been released

apis/v1beta1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, conformance/tests/httproute-hostname-intersection.go
/kind test
Add clarification for ignoring port while matching HTTPRouteSpec.Hostnames. Update conformance test to add test case covering this scenario
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1936
```release-note
Implementations MUST ignore any port value specified in the HTTP Host header while performing a match against HTTPRoute.Hostnames
```
=> Add clarification for ignoring port while matching hostnames and update conformance

apis/v1alpha2/object_reference_types.go, apis/v1alpha2/shared_types.go, apis/v1beta1/object_reference_types.go, apis/v1beta1/shared_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind cleanup
Updates slightly ambiguous behaviour.
**_Notes for the Reviewer:_** 
I decided to use the term "local namespace" due to my inability to find a better name and since it's already being used elsewhere too. I feel this should be enough to clarify any ambiguity while still being brief.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1944
```release-note
NONE
```
=> Improve documentation to clarify ambiguity regarding same namespace reference grants.

mkdocs.yml
Doc update: moving Response Header from Experimental to Standard with v0.7.0 release
**Does this PR introduce a user-facing change?:**
No
```release-note
Minor doc update
```
=> Moved Response Header from Experimental to Standard

conformance/tests/httproute-redirect-port-and-scheme.go, conformance/utils/kubernetes/certificate.go, conformance/utils/suite/suite.go
/kind bug
/kind cleanup
Tests expected redirect host was not consistent with request host, were sending HTTPS requests send inconsistent SNI and Host, cert presented by Gateway did not have the correct SANs.
Fixes #2038
```release-note
NONE
```
=> conformance: Fixes to port and scheme redirect tests

conformance/conformance_test.go, conformance/tests/httproute-request-mirror.go, conformance/tests/httproute-request-mirror.yaml, conformance/utils/http/http.go, conformance/utils/http/mirror.go, conformance/utils/kubernetes/logs.go, conformance/utils/suite/features.go, conformance/utils/suite/suite.go
Following https://github.com/kubernetes-sigs/gateway-api/pull/1912
cherry picking request mirroring conformance checks to 0.7.
Let me know if I did not do it correctly.
```release-note
Added: conformance tests for http request mirroring.
```
/cc @robscott
=> [release-0.7] Request mirroring conformance (#1912)

geps/gep-1709.md
/kind gep
In support of #1709 this cleans up our alternatives considered and TODO list. It moves some TODO items as blocking for post-`experimental` as opposed to blocking `implementable` based on our recent experience that suggests blocking at that level is not needed.
=> chore: cleanup TODO list and alternatives considered for GEP 1709

apis/v1beta1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml
The go comment for the Gateway's AttachedRoutes field has been updated
by adding the condition that the Routes need to be accepted to be
considered successfully attached to a listener.
Fixes #1913
```release-note
NONE
```
=> docs: `AttachedRoutes` docs update

apis/v1beta1/httproute_types.go, conformance/tests/httproute-exact-path-matching.go
/kind cleanup
This clarifies that exact path matches in HTTPRoute are truly exact. Both trailing slashes and capitalization are meaningful. This matches the consensus on https://github.com/kubernetes-sigs/gateway-api/issues/1953 and from our community meeting today. It also largely matches what our conformance tests already covered, this just slightly expands that coverage.
Fixes #1953
```release-note
HTTPRoute: Clarified that exact path matches are truly exact, both trailing slashes and capitalization are meaningful.
```
=> Clarifying HTTPRoute exact match behavior

apis/v1beta1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, conformance/tests/httproute-method-matching.go
/kind cleanup
/kind test
Clarify the precedency that Method matching has while comparing similar HTTPRouteRules.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1993
```release-note
HTTPRoute Method matching precedence has been clarified
```
=> Add method matching to HTTPRoute matching precedence order

site-src/implementations.md
Update the Flagger integration section to reflect its support for Gateway API `v1beta1`
```release-note
NONE
```
=> Update flagger integration to show v1beta1 support

conformance/tests/tlsroute-simple-same-namespace.go
/kind test
Since the TLSRoute test creates a new Gateway, wait for
the namespace/contained pods to be ready before
proceeding.
```release-note
NONE
```
=> conformance: wait for namespace to be ready in TLSRoute test

apis/v1beta1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml
Part of https://github.com/kubernetes-sigs/gateway-api/issues/1842
Unblocks - https://github.com/kubernetes-sigs/gateway-api/pull/1859
```release-note
Define Core supported Listener Port and Protocol Combinations.
```
=> define core protocol/port combinations

geps/gep-1867.md
Reviewer note: this was split from https://github.com/kubernetes-sigs/gateway-api/pull/1757 
/kind feature
This PR introduces a new GEP on Per-Gateway Infrastructure. Read the GEP for details :-)
Fixes #1867
```release-note
NONE
```
=> GEP-1867: Per-Gateway Infrastructure

CHANGELOG.md, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml, config/webhook/admission_webhook.yaml, pkg/generator/main.go
This adds the changelog for v0.7.1. By approving this PR, you're approving the release of v0.7.1 based on this commit.
```release-note
NONE
```
=> Adding changelog for v0.7.1

apis/v1alpha2/gateway_types.go, apis/v1alpha2/gatewayclass_types.go, apis/v1alpha2/httproute_types.go, apis/v1alpha2/referencegrant_types.go, apis/v1beta1/referencegrant_types.go, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
/kind cleanup
This PR makes the following changes:
* v1alpha2 of Gateway, GatewayClass, and HTTPRoute is no longer served
* v1alpha2 of ReferenceGrant is deprecrated
* v1beta1 is now the storage version for ReferenceGrant
The following guidance applies:
* Users and implementations that were reading or writing from v1alpha2 of Gateway, GatewayClass, or HTTPRoute MUST upgrade to use v1beta1.
* Users and implementations that were reading or writing from v1alpha2 of ReferenceGrant SHOULD upgrade to use v1beta1.
```release-note
Changes:
* v1alpha2 of Gateway, GatewayClass, and HTTPRoute is no longer served
* v1alpha2 of ReferenceGrant is deprecrated
* v1beta1 is now the …
```
=> Updating storage and served versions for beta resources

geps/gep-1709.md
/kind gep
In support of https://github.com/kubernetes-sigs/gateway-api/issues/1709, the GEP-1709 has been updated with content on how to detect the `gatewayAPIVersion` and the `gatewayAPIChannel` and how to check their consistency.
```release-note
NONE
```
=> chore: conformance profiles API version and channel

apis/v1beta1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind cleanup
Adds clarification to the spec to go along with existing conformance test from #1980.
Fixes #2091
```release-note
Clarify that implementations must not modify HTTP Host header. Adds specificity alongside spec that port in Host header must be ignored when matching on host.
```
=> apis/v1beta1: Host header must not be modified

geps/gep-1426.md
/kind gep
IMO, this does not make sense as SHOULD. It should be a MUST or not in the spec.
I have proposed removal for the following reasons:
* Inconsistent with Gateway parent ref (which also means you cannot possibly have a service parent and gateway parent)
* Limits ability to have non-Service parents, as it implies the frontend and backend are the same object
```release-note
NONE
```
=> gamma: drop provision to omit backendRef

site-src/implementations.md
This is a documentation / marketing PR.
Documents the Knative integration with Gateway API, which (AIUI) has driven several real-world API improvements in the Gateway API.
None
```release-note
NONE
```
=> Add Knative to integrations

conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
/kind cleanup
Simply switches a constant used in conformance testing to the correct one. They both have the same value, so there's no functional impact.
N/A
```release-note
NONE
```
=> Use correct constant for listener reason "Programmed"

site-src/implementations.md
update APISIX Ingress implementation status
Fixes #
```release-note
```
=> docs: update APISIX Ingress implementation status

geps/gep-1016.md, geps/gep-1323.md, geps/gep-1748.md, geps/gep-713.md, geps/gep-957.md, geps/overview.md, site-src/concepts/conformance.md, site-src/contributing/enhancement-requests.md
/kind gep
To better imitate upstream Kubernetes, we need to enact "probationary periods" for GEPs during the `Experimental` phase.
This will help us:
* avoid GEPs spending inordinately long times in the `Experimental` phase without forward momentum
* better establish and enforce graduation criteria for GEPs
* better indicate to implementations that unfinished `Experimental` features may be removed in future releases
Additionally this removes our old "quick start" section of the enhancement page on the website in favor of a "how to", the main reason for this being we want to consult with community members before GEPs are created so that we can help contributors avoid frustration and pitfalls.
=> docs: add probationary step to Experimental GEP phase

conformance/tests/gateway-secret-reference-grant-all-in-namespace.go, conformance/tests/gateway-secret-reference-grant-all-in-namespace.yaml, conformance/tests/gateway-secret-reference-grant-specific.go, conformance/tests/gateway-secret-reference-grant-specific.yaml
/kind bug
/kind flake
Two conformance tests are currently using the same name for their Gateway resource. This leads to contention when one test is actively deleting its Gateway and the other test is actively modifying the same Gateway. The second test then attempts to retrieve the Gateway to verify expected conditions; however, the deletion has completed by that time, causing the second test to fail as it can't find the Gateway in question.
The changes in this PR use distinct names for the Gateway in each test so that this contention does not occur. Tests reliably pass with these changes included using the Consul implementation of the Gateway API deployed on GKE.
```shell
$ cd ./conformance && gotest …
```
=> conformance: use distinct resource names for test isolation

conformance/mesh/manifests.yaml, conformance/tests/mesh-consumer-route.go, conformance/tests/mesh-consumer-route.yaml, conformance/utils/echo/pod.go, conformance/utils/suite/suite.go
/kind test
Tests the namespace-dependent behavior of HTTPRoute aka consumer routes.
```release-note
NONE
```
=> conformance: add MeshConsumerRoute case for GAMMA

geps/gep-696.md
/kind cleanup
This PR adds a "Conformance Details" section to the GEP template, which will encourage us all to ensure that we agree on the names to be used for the feature or features in conformance tests and profiles.
```release-note
GEPs now must have a Conformance Details section that specifies the feature's name for conformance purposes.
```
=> Add Conformance Details section to GEP template

apis/v1beta1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Make example text clearer and add table of replacement cases.
The docstring is a bit unclear, and edge cases are not explicitly defined.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2078
```release-note
NONE
```
=> Clarify docstring for ReplacePrefixMatch.

conformance/utils/kubernetes/helpers.go
/kind bug
/kind cleanup
/kind test
/kind flake
In NamespacesMustBeReady helper that checks if all pods in a namespace are ready, used to gate test runs to ensure we're not making requests to backends that are still coming up, etc.
As tests create/delete Gateways (and associated infrastructure components, e.g. control/data planes) in commonly used namespaces, there are often Terminating pods that the helper waits for, which significantly increases test runtime and causes timeouts.
Instead, if a pod has a deletion timestamp, indicating it is being shut down, we ignore that when checking the pods in a namespace.
Fixes #2102 …
=> conformance: Ignore state of terminating pods

hack/make-docs.sh, hack/mkdocs-copy-geps.py, mkdocs.yml
/kind cleanup
This PR adds a hook and tweaks the mkdocs build process to copy the geps into the site-src folder. It will also watch the GEPs directory and rebuild when changes occur.
```release-note
NONE
```
=> live update site when geps are changed

.golangci.yml, apis/v1alpha2/validation/common.go, apis/v1beta1/validation/common.go, apis/v1beta1/validation/common_test.go, conformance/tests/gateway-modify-listeners.go, conformance/tests/gateway-observed-generation-bump.go, conformance/tests/gateway-with-attached-routes.go, conformance/tests/httproute-invalid-backendref-nonexistent.go, conformance/tests/httproute-invalid-backendref-unknown-kind.go, conformance/tests/httproute-invalid-cross-namespace-backend-ref.go, conformance/tests/httproute-partially-invalid-via-reference-grant.go, conformance/tests/httproute-path-match-order.go, conformance/tests/httproute-redirect-host-and-status.go, conformance/tests/httproute-redirect-path.go, conformance/tests/httproute-redirect-port-and-scheme.go, conformance/tests/httproute-redirect-port.go, conformance/tests/httproute-redirect-scheme.go, conformance/utils/http/http.go, conformance/utils/http/mirror.go, conformance/utils/kubernetes/certificate.go, conformance/utils/kubernetes/helpers.go, conformance/utils/suite/suite.go, pkg/admission/server.go
=> ci(linter): enable several linters

geps/gep-1742.md
Adjust the Nginx timeout diagram according to the Envoy's. For example, adding missing client side request timeout, moving connect timeout.
Fixes #
```release-note
NONE
```
=> Edit Nginx timeouts diagram to match Envoy's in gep-1742.md

Makefile
/kind cleanup
- Running make conformance with a flag (eg. -gateway-class=istio) would fail since the package `./conformance/utils` doesn't import the conformance suite test flags
- Allow test runners to pass set `GO_TEST_FLAGS` to customize the test invocation (used for debugging)
```release-note
NONE
```
=> Conformance - Fix Makefile 

docker/Dockerfile.webhook
/kind bug
Presubmits are currently failing ([example](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_gateway-api/2155/pull-gateway-api-verify/1674112294809767936)) with the following error:
```
#3 [internal] load metadata for docker.io/library/golang:1.20
#3 ERROR: failed to copy: httpReadSeeker: failed open: content at https://mirror.gcr.io/v2/library/golang/manifests/sha256:344193a70dc3588452ea39b4a1e465a8d3c91f788ae053f7ee168cebf18e0a50?ns=docker.io not found: not found
#4 [internal] load metadata for gcr.io/distroless/static:nonroot
#4 DONE 0.8s
------
> [internal] load metadata for docker.io/library/golang:1.20:
------
Dockerfile.webhook:16
--------------------
14 |     
15 |     ARG …
```
=> Fixing broken presubmits by bumping base image version

apis/v1beta1/gateway_types.go
/kind cleanup
Fixes typo GatewaReasonUnsupportedAddress -> GatewayReasonUnsupportedAddress
```release-note
Fix typo: rename GatewaReasonUnsupportedAddress -> GatewayReasonUnsupportedAddress
```
I am not sure, how safe is that to do that
=> Fix typo GatewaReason -> GatewayReason

conformance/base/manifests.yaml, conformance/tests/httproute-invalid-reference-grant.go, conformance/tests/httproute-invalid-reference-grant.yaml, conformance/tests/tlsroute-invalid-reference-grant.go, conformance/tests/tlsroute-invalid-reference-grant.yaml, conformance/utils/config/timeout.go, conformance/utils/kubernetes/helpers.go, conformance/utils/suite/experimental_suite.go, conformance/utils/suite/suite.go
/kind test
This PR adds two new conformance tests to test that invalid ReferenceGrants are not getting programmed as well as checking that they are indeed not. It does this check for both HTTPRoutes and TLSRoutes. The list of invalid ReferenceGrants is based on the test in https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/gateway-secret-invalid-reference-grant.go
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2075
```release-note
Add conformance tests against accepting invalid ReferenceGrants in HTTPRoute and TLSRoute
```
=> conformance against invalid ReferenceGrants in HTTPRoute and TLSRoute

site-src/references/policy-attachment.md
Fix typo
Fixes #
```release-note
NONE
```
=> Add missing '`' in policy-attachment.md

apis/v1alpha2/referencegrant_types.go, apis/v1beta1/shared_types.go, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
/area mesh
Updates API documentation support for ParentRef targeting a Kubernetes Service, as proposed in [GEP-1426](https://gateway-api.sigs.k8s.io/geps/gep-1426/).
Fixes #2139
Service port targeting refs #1995 
**Links:**
- https://kubernetes.io/docs/concepts/services-networking/service/
```release-note
Adds support for ParentRef targeting a Kubernetes Service resource for mesh implementations.
```
=> apis: document ParentRef functionality for GAMMA

conformance/conformance_test.go, conformance/utils/flags/flags.go, conformance/utils/suite/suite.go
/kind feature
The `--skip-tests` flag has been added to the conformance CLI to enable tests opt-out when using it.
Fixes #
```release-note
The `--skip-tests` flag has been added to the conformance CLI to enable tests opt-out when using it.
```
=> feat: skip-tests flag added to conformance CLI

geps/gep-1323.md, site-src/guides/http-header-modifier.md
Update gep-1323
Fixes #
```release-note
NONE
```
=> ResponseHeaderModifier is already standard since the version now is 0.7+

geps/gep-1742.md
according to the suggestion in https://github.com/kubernetes-sigs/gateway-api/pull/2117#pullrequestreview-1484544095
Improve https://github.com/kubernetes-sigs/gateway-api/pull/2117
Fixes #
```release-note
NONE
```
=> Update gep-1742.md to add more Nginx's timeout settings

mkdocs.yml, site-src/api-types/gateway.md, site-src/api-types/gatewayclass.md, site-src/api-types/grpcroute.md, site-src/api-types/httproute.md, site-src/api-types/referencegrant.md
This PR creates a standard format for specifying version status of CRDs on the reference pages.
This also adds the `pymdownx.details` markdown extension to support expandable code blocks. 
This PR is related to https://github.com/kubernetes-sigs/gateway-api/issues/1823 but will not fix it entirely.
```release-note
NONE
```
=> Add version information to docs for api types

apis/v1beta1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Update PathPrefixRewrite spec to include compatible match types.
This PR updates the httproute spec to clarify that PathPrefixRewrite can only be used with a match of type PathPrefix.
None
```release-note
NONE
```
=> Clarify usage of matches with PathPrefixRewrite

conformance/tests/gateway-routability-bad-mutation.yaml, conformance/tests/gateway-routability-broken.yaml, conformance/tests/gateway-routability-cluster.yaml, conformance/tests/gateway-routability-default.yaml, conformance/tests/gateway-routability-private.yaml, conformance/tests/gateway-routability-public.yaml, conformance/tests/gateway-routability.go, conformance/utils/suite/features.go
This PR depends on the following PRs merging
- https://github.com/kubernetes-sigs/gateway-api/pull/2157
- https://github.com/kubernetes-sigs/gateway-api/pull/2144
View just the commit with the conformance test here - https://github.com/kubernetes-sigs/gateway-api/pull/2171/commits/4298344aa7a2f4659a3c310b4c7ab43c15c2972b
/kind feature
/kind gep
/kind test
This adds conformance tests for the Routability feature
Part of https://github.com/kubernetes-sigs/gateway-api/issues/1651
```release-note
Add conformance tests for Gateway Routability
```
=> [GEP 1651]: Routability Conformance

site-src/contributing/index.md
Per discussion in the GAMMA meeting, let's meet every other Tuesday.
FTR the next meeting will be 25 July 2023 at 0800 US/Pacific (1100
US/Eastern, 1500 UTC).
Signed-off-by: flynn@buoyant.io
```release-note
NONE
```
=> Update GAMMA meetings to every other week, per discussion in the GAMMA meeting.

geps/gep-1709.md, geps/overview.md, mkdocs.yml
/kind cleanup
/kind gep
In support of #1709 this moves the GEP to `Experimental` status, ready for implementations to start submitting their reports.
=> Conformance Profiles (GEP 1709) to Experimental status

conformance/experimental_conformance_test.go
/kind bug
Minor fixes to correct some bad behaviors and improve the usability of the conformance profiles CLI.
Fixes #
```release-note
NONE
```
=> conformance-profiles CLI fixes

apis/v1beta1/validation/gateway_test.go, conformance/base/manifests.yaml, conformance/tests/gateway-observed-generation-bump.go, conformance/tests/httproute-redirect-port-and-scheme.go, conformance/tests/httproute-redirect-port-and-scheme.yaml, conformance/utils/suite/features.go
**What type of PR is this?** /kind test /area conformance 
Conformance tests only use ports 80 and 443 in base manifests.  This PR removed the Gateway w/ port 8080 in the base.yaml manifest, adds it to the tests yaml that was using it, and adds a `SupportedFeature` for port 8080
**Which issue(s) this PR fixes**: 
Fixes #https://github.com/kubernetes-sigs/gateway-api/issues/2094
**Does this PR introduce a user-facing change?**: 
```release-note
NONE
```
=> Add SupportedFeature for port 8080 on Gateway

conformance/utils/http/mirror.go, conformance/utils/kubernetes/logs.go, conformance/utils/suite/suite.go
/kind cleanup
Preferred to use interface generally than the concrete implementation
Fixes #
```release-note
NONE
```
=> conformance: use interface instead of concrete impl for Kubernetes client

conformance/utils/suite/suite.go
/kind test
When the conformance tests run, they require that a GatewayClass exists and that it has been accepted.  However, this is not appropriate when testing mesh only conformance because mesh implementations do not necessarily have a GatewayClass.  This change moves the GatewayClass requirement into the Gateway suite so that this is only checked when the Gateway feature is enabled.
```release-note
NONE
```
=> Only require a GatewayClass if the gateway suite is being run

conformance/tests/tlsroute-invalid-reference-grant.yaml
/kind test
Fixes Gateway name to be consistent between
YAML and Go, and to not conflict with other
TLSRoute tests.
(See https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/tlsroute-invalid-reference-grant.go#L45 for where Gateway name is referenced).
Fixes # NA
```release-note
NONE
```
=> fix Gateway name in TLSRoute invalid reference grant test

conformance/apis/v1alpha1/profilereport.go, conformance/experimental_conformance_test.go, conformance/utils/suite/experimental_suite.go
Update the `ConformanceReport` tags to make the status inline. Additionally, a conversion between `json` and `yaml` is necessary to exploit the `json` tags.
Fixes #
```release-note
NONE
```
=> `conformanceReport` api update

conformance/utils/suite/experimental_suite.go
/kind bug
/kind test
Add missing fields that were not carried over to the experimental conformance reporting suite setup. The k8s clientset especially is required for the mirror tests.
N/A
```release-note
NONE
```
=> Fix missing fields in experimental conformance suite setup

conformance/tests/gateway-modify-listeners.go, conformance/tests/gateway-observed-generation-bump.go, conformance/tests/gateway-routability.go, conformance/utils/kubernetes/helpers.go
/kind flake
Fetches the Gateway from the client each time through
the polling loop in GatewayMustHaveLatestConditions,
so updates to the conditions can be observed.
The current code is checking the same object over and
over again.
Updates #1883
```release-note
NONE
```
=> conformance: fetch Gateway in GatewayMustHaveLatestConditions loop

geps/gep-91.md
/kind gep
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/91
=> GEP: Client Certificate Validation for TLS terminating at the Gateway Listener

apis/v1beta1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, conformance/tests/gateway-routability-default.yaml, conformance/tests/gateway-routability.go, conformance/utils/suite/features.go, geps/gep-1651.md
/kind bug
/kind cleanup
/kind test
The new routability tests are not runnable, they are not included in the set of all features and also have various issues
- fix manifest file names
- gateway names/typos
- move to testify require statements to prevent tests to continue to execute when preconditions not met (to prevent panics) and to simplify test logic
Other issues still remain and will be covered in subsequent issues for discussion, this does not make a guarantee the logic of these tests is correct since there is no implementation that supports them yet.
Fixes #2204
```release-note
NONE
```
=> conformance: Make routability tests runnable

OWNERS_ALIASES, conformance/OWNERS
/kind cleanup
This adds @arkodg, @mlavacca, @sunjayBhatia as conformance approvers. It also gives GAMMA leads (@howardjohn, @keithmattix, @kflynn) the same approval abilities. A big thanks to all of them for their reviews and contributions to our conformance tests! For more information on what this means, refer to the [contributor ladder](https://gateway-api.sigs.k8s.io/contributing/contributor-ladder/).
```release-note
NONE
```
=> Adding new approvers for conformance tests

apis/v1beta1/gatewayclass_types.go, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
Clarifies that we expect implementations to handle the `.status` for `GatewayClass` resources which carry their `controllerName`.
Resolves #1822 in support of #1781.
=> Clarify necessity for implementations to handle GWC .status

conformance/tests/gatewayclass-observed-generation-bump.go, conformance/utils/suite/features.go
The additional feature `GatewayClassObservedGenerationBump` has been removed, and the test is now executed as a core one.
Fixes #1780 
```release-note
NONE
```
=> `GatewayClassObservedGenerationBump` as a core feature

conformance/tests/gateway-with-attached-routes.go, conformance/tests/gateway-with-attached-routes.yaml
/kind test
Fixes #2058 
```release-note
NONE
```
=> Improve AttachedRoutes conformance test

site-src/faq.md, site-src/index.md
Clarify potential terminology confusion around Gateway API & API Gateway
Fixes #1157
Yes.
```release-note
Clarify wording on website around Gateway API vs API Gateway
```
=> Clarify different between API Gateway and Gateway API

conformance/results/contour.yaml
Adds initial conformance results for Contour's Gateway API implementation
N/A
```release-note
NONE
```
=> Add initial conformance results for Contour

conformance/conformance_test.go, conformance/utils/echo/pod.go, conformance/utils/suite/experimental_suite.go, conformance/utils/suite/suite.go
/kind cleanup
Simplifies the `suite.Options` interface, we can use the `Clientset` to get a `RESTClient`.
```release-note
NONE
```
=> conformance: remove RESTClient in suite.Options, use interface where possible

apis/v1beta1/gateway_types.go, apis/v1beta1/gatewayclass_types.go, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, hack/cel-validation/gateway_test.go, hack/cel-validation/gatewayclass_test.go, hack/cel-validation/main_test.go, hack/run-cel-validation-test.sh
/kind feature
Add support for CEL based validation for `Gateway` and `GatewayClass`. This allows us to have more complex validations than those supported by the OpenAPIv3 spec without the need of an additional validation webhook. Upcoming PRs will gradually extend this to HTTPRoutes (and other remaining resources) as well.
References:
* https://kubernetes.io/docs/reference/using-api/cel
* https://kubernetes.io/blog/2022/09/23/crd-validation-rules-beta/
Notes for the reviewers:
* The tests included in this PR perform error string comparisons. I understand that this may not be the most ideal choice but it helps establish some confidence that the validations are in fact working correctly.
* Tests aren't currently being run …
=> Introduce validations through CEL for Gateway and GatewayClass.

apis/v1beta1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, examples/standard/gateway-addresses.yaml, examples/standard/simple-gateway/gateway.yaml, hack/cel-validation/gateway_test.go, hack/invalid-examples/v1beta1/gateway/invalid-addresses.yaml, pkg/generator/main.go
/kind cleanup
This is a follow up to @gauravkghildiyal's PR that added CEL validation (#2226). It contains a few things:
* IPAddress validation (using ~~https://regex101.com/r/Kzijkp/1~~ our custom CRD generation + `oneOf`)
* Validation for GatewayStatusAddress
* A few typo fixes
```release-note
NONE
```
=> Completing CEL validation for Gateway

apis/v1beta1/httproute_types.go, apis/v1beta1/object_reference_types.go, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, hack/cel-validation/httproute_test.go
/kind feature
Add initial set of CEL validations for HTTPRoute. 
This includes most (but not all) of the HTTPRoute validations offered by the webhook. 
**Only 2 kinds of validations remain.**
The validations which have not been ported along with the reason and details are available in https://github.com/gauravkghildiyal/gateway-api/blob/pending-httproute-validations/apis/v1beta1/validation/httproute.go. All validations which were successfully ported have been removed from this file.
Since namespace is a reserved word, a validation that involves a field named `namespace` seems to getting rejected. We need to figure out if there is a way around this. 
CEL attempts to estimate the [runtime cost of a validation](https://kubernetes.io/blog/2022/09/23/crd-validation-rules-beta/#estimated-cost-li …
=> Add initial set of CEL validations for HTTPRoute

mkdocs.yml
/kind cleanup
This removes a broken link from the contributing nav. Fortunately any external links to https://gateway-api.sigs.k8s.io/contributing/gamma will continue to work because there's already a redirect in place (thanks @kflynn!). 
Fixes #2259
```release-note
NONE
```
=> Removing broken GAMMA link

conformance/experimental_conformance_test.go
To avoid compile issue if the experiment tag is enabled.
The below PR remove RestClient option in suite.Options, but the same is not remove in Conformance Profile file, probably it's overlooked because of the build tag (e.g. experiment).
Relates: #2241
```release-note
NONE
```
=> conformance: Remove already deleted option RestClient

apis/v1alpha2/grpcroute_types.go, apis/v1beta1/gateway_types.go, apis/v1beta1/httproute_types.go, apis/v1beta1/shared_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, hack/cel-validation/gateway_test.go, hack/cel-validation/httproute_test.go
/kind cleanup
This addresses feedback from #2245.
```release-note
NONE
```
=> Addressing v0.8.0 API Review feedback

geps/gep-1898.md, geps/gep-2257.md, mkdocs.yml
This PR creates GEP-2257 to define a Gateway API Duration format, as
discussed in today's SIG-Network meeting.
Fixes #2257.
Signed-off-by: flynn@buoyant.io
/kind gep
Release note:
```release-note
None
```
=> GEP-2257: Gateway API Duration Format

config/webhook/certificate_config.yaml
Properly reads the namespace from the actual deployment
Do not hardcode the namespace for Pod arguments. The existing 'POD_NAMESPACE' variable suggests that the namespace should have actually been read at runtime. Similar to nginx-ingress in https://github.com/kubernetes/ingress-nginx/blob/d712dd9d92f1f46eab5f55d4643f3a45a7a97f90/charts/ingress-nginx/templates/admission-webhooks/job-patch/job-createSecret.yaml#L52C15-L52C43
Addtionally, this should enable easier deployments into non default namespaces with (i.e -) kustomize namespace setting
Fixes #
```release-note
* Enable deployments to non-default namespaces
```
=> Use '$(POD_NAMESPACE)' instead of hardcoded namespace

site-src/implementations.md
* bumped support to `beta`, well because Envoy Gateway supports beta APIs :)
* fixed a broken link for Gateway API support
* bumped the quickstart docs to v0.5
=> Update docs for Envoy Gateway

geps/gep-713.md
**What type of PR is this?** /kind documentation
**What this PR does / why we need it**: Updates several typos in gep-713
Fixes #
**Does this PR introduce a user-facing change?**: No
```release-note
NONE
```
=> Update typos in gep-713

apis/v1beta1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, hack/invalid-examples/v1alpha2/grpcroute/invalid-filter-duplicate-header.yaml, hack/invalid-examples/v1beta1/httproute/invalid-filter-duplicate-header.yaml
/kind cleanup
This fills one more gap in our CRD validation that we've historically relied on the validating webhook to cover. As documented in https://github.com/kubernetes-sigs/gateway-api/issues/2277, the webhook ensures that header names have case-insensitive uniqueness. The built-in CRD validation uses `+listType=map` and `+listMapKey=name` to ensure that names are unique (unfortunately still case-sensitive, but better than nothing). We were missing equivalent CRD validation on the `Remove` field, this adds that. 
As we're moving away from webhook-based validation, adding as much validation we can directly to the CRD will be helpful, so this takes one more step in that direction.
**Does this PR introduce a …
=> Using "Set" list type for "Remove" in Header Modifier Filters

conformance/tests/mesh-consumer-route.yaml, conformance/tests/mesh-frontend.yaml, conformance/tests/mesh-ports.yaml, conformance/tests/mesh-split.yaml
Signed-off-by: flynn@buoyant.io
/kind bug
/kind test
Many mesh conformance tests specify `parentRefs` with `kind: Service`, but don't specify the `group`. That will default the `group` to `gateway.networking.k8s.io`, which won't work for `kind: Service`.
Fixes #2309
```release-note
NONE
```
=> [conformance] Specify group: "" for mesh conformance parentRefs

apis/v1alpha2/grpcroute_types.go, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, pkg/test/cel/grpcroute_test.go
/kind feature
Add CEL validation for GRPCMethodMatch
Fixes https://github.com/kubernetes-sigs/gateway-api/pull/2305#pullrequestreview-1577991344
```release-note
GRPCRoute: The default match has been removed as it was invalid (it only specified a type of "Exact" without a corresponding Service or Method). Note that the match type still defaults to "Exact".
```
=> Add CEL validation for GRPCMethodMatch

conformance/conformance_test.go, conformance/experimental_conformance_test.go, conformance/tests/mesh-frontend-hostname.go, conformance/utils/flags/flags.go, conformance/utils/kubernetes/apply.go, conformance/utils/kubernetes/helpers.go, conformance/utils/suite/experimental_suite.go, conformance/utils/suite/suite.go, conformance/utils/suite/suite_test.go, site-src/concepts/conformance.md
/kind bug
This PR makes some small changes to allow conformance to work for Linkerd and, most likely, other meshes that don't also provide gateway controllers. Huge props to @adleong for doing most of the heavy lifting on this, weeks ago. :slightly_smiling_face:
Like most nontrivial PRs of mine, it is best reviewed commit by commit.
- Allow `-namespace-annotations` to annotate namespaces created by the tests
We already had `-namespace-labels` to supply labels on test namespaces. Linkerd needs annotations rather than labels, so we add a new parallel flag to set annotations on test namespaces.
- Document `-namespace-annotations`
Documentation is in a separate commit.
- comment fix
This just triggered me so I had to fix it. :slightly_smiling_face:
- Split out …
=> Conformance tweaks for Linkerd and other meshes

site-src/implementations.md
=> Add Tyk Implementation progress

apis/v1beta1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Enhance RequestMirrorFilter doc string to be explicit about sending the mirrored request to a single destination endpoint within the backendRef specified.
**Does this PR introduce a user-facing change?:**
```release-note
RequestMirrorFilter: Enhanced the doc string to be explicit about sending the mirrored request to a single destination endpoint within the backendRef specified.
```
=> Add more clarity around RequestMirrorFilter dest

apis/v1alpha2/grpcroute_types.go, apis/v1alpha2/referencegrant_types.go, apis/v1beta1/referencegrant_types.go, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml, conformance/utils/suite/features.go, conformance/utils/suite/suite.go
/kind cleanup
The concept of conformance levels has gotten rather confusing as we've added both new features and resources. Some resources (GRPCRoute and ReferenceGrant) had conformance levels defined while the rest did not. This does some refactoring to try to make our documentation and lists of conformance features more consistent. This gets us to a point where:
1. Resources don't have support levels, implementations can choose to support whichever set of resources they want
2. Claiming the Support_Resource_ feature when running conformance tests means that you support the resource and all the core features it contains
As a result, the most notable change is that …
=> Removing concept of resource-level support levels

site-src/guides/http-redirect-rewrite.md
Signed-off-by: Nico Vibert <nicolas.vibert@isovalent.com>
Removed a reference that this feature will become a Standard feature in v0.7.0. Given that we are approaching v0.8.0, we can probably remove this now.
```release-note
NONE
```
=> docs: Removed note about path redirect being experimental

conformance/utils/echo/pod.go
This builds on #2024 by applying it to the mesh conformance host logic as well
=> Mesh Conformance IPv6 fix

site-src/concepts/api-overview.md
From the api definition of `namespaces.from`, the value `SameNamespace` should be `Same`.
```release-note
NONE
```
=> Fix doc for allowed namespaces of routes.

conformance/apis/v1alpha1/conformancereport.go, conformance/apis/v1alpha1/doc.go, conformance/apis/v1alpha1/profilereport.go, conformance/apis/v1alpha1/result.go, conformance/apis/v1alpha1/statistics.go, conformance/experimental_conformance_test.go, conformance/utils/flags/experimental_flags.go, conformance/utils/suite/experimental_profiles.go, conformance/utils/suite/experimental_reports.go, conformance/utils/suite/experimental_suite.go
/kind test
Relates: #2242
```release-note
NONE
```
Testing was done as part of https://github.com/cilium/cilium/pull/27596
=> conformance-profile: Remove experimental build tag

conformance/utils/roundtripper/roundtripper.go
/kind bug
/kind test
* At present, each HTTP request creates a new TCP connection within our tests.
* We make `keep-alive` HTTP requests which means that after the HTTP request completes, we don't close the TCP connection.
* While we are waiting for convergence, we continuously make HTTP requests which keep on leaking TCP connections.
```bash
❯ ss -tan | grep 42.54.109.216 | head -n 3
ESTAB      0      0               192.168.24.68:50606           42.54.109.216:80
ESTAB      0      0               192.168.24.68:51233           42.54.109.216:80
ESTAB      0      0               192.168.24.68:41312           42.54.109.216:80
❯ ss -tan | grep 42.54.109.216 | wc -l
130
```
* If the implementation takes longer to program the Gateway, the leaks end up exhausting the maximum number of active …
=> fix leaking TCP connections which leads to consistent conformance test failures

site-src/contributing/index.md
/kind cleanup
The "Gateway API Code Jam" has historically _not_ focused all that much on Gateway API, but instead tends to span the scope of SIG Network. We've decided to intentionally rebrand it as a more inclusive meeting:
* https://groups.google.com/g/kubernetes-sig-network/c/sJtBHe0Tx5o
* https://github.com/kubernetes/community/pull/7460
And so it really doesn't make much sense anymore for us to host this Gateway API specific section for it.
```release-note
NONE
```
=> docs: remove codejam from meetings

geps/gep-1742.md
/kind gep
Completing the update that @kflynn started in #2316.
This PR includes Flynn's changes.
Fixes #
```release-note
NONE
```
=> Update GEP-1742 to use GEP-2257 Duration type

apis/v1beta1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, pkg/test/cel/gateway_test.go
/kind bug
CEL validation not handling missing listener hostname corectly.
Fixes #2369 
```release-note
NONE
```
=> Fix CEL validation for listener uniqueness

geps/gep-1897.md
/kind gep
This PR adds the API details for GEP-1897 TLS from Gateway to Backend for ingress.  GEP-1897 has already had the questions answered - what do we want to do, and why do we want to do this.  This update attempts to answer - how do we do this.
Fixes #1897
```release-note
NONE
```
=> GEP-1897 Explicit Backend TLS Connection Configuration (was TLS from Gateway to Backend...) Update with API details

geps/gep-2162.md, mkdocs.yml
/kind gep
This GEP proposes changes to GatewayClassStatus API to include the installed GatewayClass supported and unsupported features .
Fixes #2162 
```release-note
Allow end-users to see what features their installed GatewayClass support
```
=> GEP 2162 - Supported features in GatewayClass Status

cmd/admission/main.go
/kind bug
Related to https://github.com/kubernetes/kubernetes/issues/120168 
when gateway-api-webhook stop by sigterm signal in container, it always exit with -1 code. it will make error containerStatus
the log is here
```release-note
$ kubectl delete po gateway-api-admission-server-5d555f679-dm27b
pod "gateway-api-admission-server-5d555f679-dm27b" deleted
$ kubectl logs gateway-api-admission-server-6ccfb998f9-r4rfb -f
gateway-api-admission-webhook version: v0.7.1 (ab03a594e7db13b8d2579929b204d8d10990fd2b)
I0828 03:16:37.519872       1 main.go:90] admission webhook server started and listening on :8443
I0828 03:34:08.893252       1 …
```
=> update signal error log

conformance/utils/echo/pod.go, conformance/utils/http/http.go
`net.SplitHostPort` errors if ipv6 addresses aren't in brackets; previous implementation fixed a different problem (SplitHostPort removes brackets if they are passed in)
```release-note
Fix IPv6 parsing in conformance tests
```
=> IPv6 conformance: Third time's the charm

mkdocs.yml
/kind cleanup
I can't handle the randomly-sorted GEPs in the sidebar any more. :joy: Let's keep them numerically sorted, please? :slightly_smiling_face:
-->
```release-note
NONE
```
=> I can't take it any more. Sort the GEP list.

hack/verify-crds-kind.sh
/kind cleanup
/kind test
When I refactored the `fix-verify-crds.sh` script, I removed the `set -o errexit` directive, but missed that this meant that the `go test` invocation was now not updating the `$res` variable. This fixes that so that CEL test failures will now cause the tests to fail as expected.
```release-note
NONE
```
=> Fix CEL tests in fix-verify-crds.sh

conformance/tests/httproute-request-multiple-mirrors.go, conformance/tests/httproute-request-multiple-mirrors.yaml, conformance/utils/http/http.go, conformance/utils/http/mirror.go, conformance/utils/suite/features.go
/kind test
Adds a conformance test for multiple mirror filters within the same rule, tested using Contour's implementation.
Fixes #2210 
```release-note
None
```
=> Add conformance for multiple mirror filters

apis/v1beta1/gatewayclass_types.go, site-src/concepts/guidelines.md
/kind feature
This is intended to fix https://github.com/kubernetes-sigs/gateway-api/issues/2077 by adding a new SupportedVersion condition on GatewayClass and corresponding documentation.
Fixes #2077
```release-note
GatewayClass Status: A new SupportedVersion condition has been added that MUST be set when a GatewayClass is accepted.
```
=> Adding new SupportedVersion condition to GatewayClass

geps/gep-1742.md, mkdocs.yml
/kind cleanup
/kind gep
With the merge of #2013, we now have a spec and an implemenation for HTTP Timeouts, so we should move it to Experimental.
Updates #1742 
```release-note
HTTP Timeouts have moved to Experimental status.
```
=> Move GEP-1742 to experimental

CHANGELOG.md, README.md, site-src/guides/index.md
Updates docs to reflect v0.8.1 release.
```release-note
NONE
```
=> Updating docs for v0.8.1

apis/v1beta1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind cleanup
Document that the field intends to count purely Gateway<->Route relationships regardless of validity of either resource.
Fixes #1626
```release-note
Clarify that the Gateway Listener status AttachedRoutes field is a count of the number of Routes associated with a Listener regardless of Gateway or Route status.
```
=> Clarify Gateway Listener Status AttachedRoutes field

hack/build-install-yaml.sh
Fixes # https://github.com/kubernetes-sigs/gateway-api/issues/2400
```release-note
Resources related to the validating webhook such as the `gateway-system` namespace and the `gateway-api-admission-server` deployment have been removed from the installation manifests, in favor of CEL based Validations that are built into the CRD definition. These are still available in `webhook-install.yaml` in case you would like to optionally install them.
```
=> rm webhook resources from installation yaml

apis/v1beta1/shared_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, pkg/generator/main.go
/kind feature
This PR adds the feature where we can specifiy the start and end tag to the CRDs description which only need to be there in expremental channel CRDs and exclude from standard channel CRDs.
Fixes #2160
```release-note
Excluding experimental guidance in field descriptions from standard CRDs
```
=> feat: Exclude experimental guidance from standard channel CRDs

conformance/reports/v0.7.1/nginxinc-nginx-gateway-fabric.yaml, conformance/reports/v0.8.0/nginxinc-nginx-gateway-fabric.yaml, geps/gep-1619.md, geps/gep-1742.md, site-src/implementations.md
NGINX Kubernetes Gateway has been renamed to NGINX Gateway Fabric.
/kind cleanup
NGINX Kubernetes Gateway has been renamed.
```release-note
NGINX Kubernetes Gateway has been renamed to NGINX Gateway Fabric.
```
=> Rename NGINX Kubernetes Gateway

conformance/tests/gateway-modify-listeners.go, conformance/tests/gateway-secret-reference-grant-all-in-namespace.go, conformance/tests/gateway-secret-reference-grant-specific.go, conformance/tests/gateway-with-attached-routes.go, conformance/utils/config/timeout.go, conformance/utils/kubernetes/helpers.go
/kind test
Checks the `ListenerConditionResolvedRefs` value. This is needed to ensure that its value is always set, no matter if the `ConditionStatus` is true, or false.
Fixes #1315 
```release-note
None
```
=> Check ResolvedRefs condition in Gateway conformance tests

conformance/reports/v0.8.1/kong-kubernetes-ingress-controller.yaml, site-src/implementations.md
Adds Kong Kubernetes Ingress Controller conformance report for v0.8.1.
```release-note
NONE
```
=> Add Kong Kubernetes Ingress Controller conformance report for v0.8.1

geps/gep-1619.md
Adds specific details for API design as well as the documentation that support the decision of the session persistence API design.
/kind gep
N/A
```release-note
NONE
```
=> GEP-1619: Add API design for session persistence

apis/v1beta1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml
From the attached issue, `Listeners` was unclear regarding what "compatible" meant, in particular that it was more whether the implementation could serve that Listener set on the same addresses while being able to match inbound requests to a single Listener only.
Updates the `GatewaySpec.Listeners` documentation to:
- Separate the definition of and examples for "compatible". Previously "compatible" wasn't clearly defined: we said what implmentations could do with compatible Listeners and provided an example that might be compatible depending on implmentation capabilities. The definition wasn't formal, and was only implied by the surrounding language.
- Move the "same port, different hostname" rule …
=> Expand and clarify Listeners definition

conformance/tests/httproute-request-multiple-mirrors.go, conformance/tests/httproute-request-multiple-mirrors.yaml, conformance/utils/http/mirror.go
/kind test
The test in isolation is fine, but combined with the other mirror test we have problems.
1. Test 1 sets up /mirror -> v1. Passes, starts cleanup
2. Test 2 sets up /mirror -> v2. Sends request to /mirror, gets a 200. It sent to v1, though, since cleanup wasn't done.
3. We look for logs in v2 forever, never find them. :-(
This fixes things by making the two use isolated paths
Fixes #
```release-note
NONE
```
=> conformance: fix flakes in mirror tests

site-src/implementations.md
The Kong Gateway Operator has just gone GA, and now has a new URL associated with it. This patch updates that URL.
```release-note
NONE
```
=> fix: update link for kong's KGO

geps/gep-1762.md
Review note: This GEP was split into 3 - the current GEP (focusing on in-cluster deployments), https://github.com/kubernetes-sigs/gateway-api/pull/1868 (infrastructure field we depend on), and https://github.com/kubernetes-sigs/gateway-api/pull/1863/files (gateway merging)
/kind gep
This PR attempts to inject some opinions about how in-cluster deployments should work. Currently, there is a lot of different implementations behaving differently, leading to confusion and drifting user experiences.
As-is, this PR is fairly opinionated. I expect that some of the MUSTs become SHOULDs as we iterate on this PR. In its current state, this is largely meant as a discussion point. I expect there to be a lot of iteration as we learn …
=> GEP-1762: In Cluster Gateway Deployments

geps/gep-1619.md
/kind gep
There was a bit of a mixup where this GEP was merged a bit earlier than intended. Although I think there's lots of good content here, I don't think @youngnick or I have had sufficient time to look through this in detail yet, and likely won't until v1.0 is ready 😞. 
Although I haven't had time to take a detailed look at this GEP yet, I did add some initial higher level questions as part of the graduation criteria here that I think we should address before this GEP graduates. Particularly interested in how we can leave room for future expansion here.
```release-note
NONE
```
/cc @gcs278 @shaneutt @youngnick
=> Adding graduation criteria to GEP 1619

apis/v1beta1/shared_types.go, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, pkg/test/cel/httproute_experimental_test.go
/kind cleanup
Previously parents could be distinct if one specified a port and one specified a listener. Now they either both need to specify a distinct SectionName, both need to specify a distinct Port, or both. This PR replaces https://github.com/kubernetes-sigs/gateway-api/pull/2350.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2326
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1925
```release-note
Experimental Channel: For ParentRefs to be considered distinct, they either both need to specify a distinct SectionName, both need to specify a distinct Port, or both.
```
**Note For Reviewers:**
CEL is …
=> Requiring SectionName or Port to be specified for distinct parents

site-src/contributing/enhancement-requests.md
/kind cleanup
While updating GEP-1742 to experimental (#2392), I noticed that we have some redundant info about the new GEP process in the contributing section of the site. This PR updates that page to refer to the correct place (`/geps/overview`), so we only have one place to update.
```release-note
NONE
```
=> Update the contributing page about the GEP process

apis/v1alpha2/grpcroute_types.go, apis/v1beta1/httproute_types.go, apis/v1beta1/shared_types.go, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, geps/gep-1911.md, pkg/generator/main.go
/kind gep
- This takes [GEP-1911](https://gateway-api.sigs.k8s.io/geps/gep-1911/) and updates the godoc for `BackendRef`
- Mention users can signal backend protocol using `ServicePort.protocol`
Fixes #
```release-note
NONE
```
=> [GEP-1911] Update BackendRef with GEP details

conformance/utils/kubernetes/helpers.go
/kind test
Add a consistent check that all the valid gateways have all three positive-polarity conditions always set to true.
Fixes #2415 
```release-note
None
```
=> Check gateway positive-polarity conditions

apis/v1beta1/shared_types.go
/kind feature
This adds a new condition along with corresponding guidance for how to handle Routes that are partially invalid.
Note: I can't think of any way to write conformance tests for this condition since the most likely way to get into this state is when an implementation can't support a feature configured in a Route. 
Fixes #1696.
```release-note
New "PartiallyInvalid" condition has been added for all Route types.
```
=> Adding new PartiallyInvalid condition for Routes

apis/v1beta1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind cleanup
This PR is a follow up to #2416. It introduces a new concept called "Listener Isolation" to describe the recommendation that at most one Listener matches a request, and only Routes attached to that Listener are used for routing.
Originally I'd planned to consider this an "Extended" feature (see https://github.com/kubernetes-sigs/gateway-api/issues/2416#issuecomment-1731747678) but generally the idea of "Extended" and "Core" is per-field, not really a description of behavior. So instead I'm using "SHOULD" which per [RFC-2119](https://www.ietf.org/rfc/rfc2119.txt) is a recommendation and not a requirement. This does add the requirement that implementations that do not support Listener …
=> Documenting Listener Isolation in Gateway Spec

CHANGELOG.md, apis/v1beta1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, conformance/tests/gateway-static-addresses.go, conformance/tests/gateway-static-addresses.yaml, conformance/utils/config/timeout.go, conformance/utils/kubernetes/apply.go, conformance/utils/kubernetes/helpers.go, conformance/utils/suite/experimental_suite.go, conformance/utils/suite/features.go, conformance/utils/suite/suite.go
/kind test
Going into GA we have an extended field for supplying static addresses for Gateways, but no conformance tests for that feature. This patch adds the test, while also tweaking some of the related condition reasons (see the explanation in the `CHANGELOG.md`).
Resolves #2035
```release-note
NONE
```
> **Warning**: The way we're injecting the address pools into the test is bad. I don't like it. However, I think at this point with GA in the next few weeks, trying to make this better would require some kind of fundamental change to the test suite which we don't have time for. If you have any great ideas for …
=> Conformance tests for static Gateway addresses

hack/verify-yamllint.sh
/kind cleanup
When https://github.com/kubernetes/test-infra/pull/30973 merged it broken our verify-yamllint script with the following error when the script ran `pip3 install yamllint`:
```
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
```
This is an attempt to resolve that, alternatives welcome. 
```release-note
NONE
```
=> Adding venv for verify-yamllint

OWNERS_ALIASES, geps/OWNERS
Gateway API is a community first and foremost and we love to recognize individuals for their contributions.
@candita and @gcs278 have been active members of the community for a long time. Candace has notably been the champion of [GEP-1897 (BackendTLSPolicy)](https://gateway-api.sigs.k8s.io/geps/gep-1897/), and Grant has worked tirelessly on [GEP-1619 (Session Persistence)](https://gateway-api.sigs.k8s.io/geps/gep-1619/). Both of them have worked hard and proven their skills building this API, and as such we want to recognize both of them as our first GEP Reviewers so that they can continue helping us shape the future of Gateway API in an official capacity. Thank you Candace! Thank you Grant! :partying_face: 
/kind gep …
=> Adding Candace Holman and Grant Spence to GEP Reviewers

apis/v1beta1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind cleanup
This updates the Listener language to add the concept of `distinct`. Why add this when it's not a huge change? Well, we actually need to consider if things are distinct in many places in the API, and I think that standardizing on this term will help.
I've built on @rainest's great work in #2288, and attempted to incorporate some items from the discussions there and on #2416.
There's still an outstanding item here - to introduce the `GatewayListenerIsolation` concept, but I have specifically left that out of this PR, to make it easier to review. @robscott is on the hook for a follow-up to address that one.
Updates #2416
**Does this PR introduce a …
=> Add distinct concept to Listener definition

Makefile, docker/Dockerfile.echo-basic, docker/Dockerfile.webhook, hack/build-and-push.sh, hack/verify-docker-build.sh
testgrid failed building the echo-basic image because of the Dockerfile didn't copy the `go.sum` file into the build container. 
https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-gateway-api-push-images/1712549846159724544
Our Verify script should have caught this
/kind test
/kind build
/kind cleanup
This PR tweaks the docker build script to allow it to just build and not push. We then added a verify command to test the docker build.
Once we confirm the failure happens in pre-submit - I'll update the PR to include the fixes we need.
```release-note
NONE
```
=> add verify script for docker image building + fix image building

conformance/mesh/manifests.yaml
/kind bug
Reverts changes to the Mesh Pod containers in https://github.com/kubernetes-sigs/gateway-api/pull/2468. The new `echo-basic` doesn't have the `client` binary used to send requests from one `Pod` to another:
```
pod.go:65: Request [client http://echo-v1:8080 --method=GET] failed, not ready yet: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "814909cdd391efe031b521d0ff0285e21590fa08c2a40b7b61d85edc3577f2fe": OCI runtime exec failed: exec failed: unable to start container process: exec: "client": executable file not found in $PATH: unknown (after 27.225µs)
```
**Does this PR introduce a user-facing …
=> conformance: use echo-advanced in Mesh tests, echo-basic no longer has a client

conformance/tests/httproute-timeout-backend-request.go, conformance/tests/httproute-timeout-request.go
/kind bug
/kind conformance
This is a followup to  #2254 
When I switched to use the backend-v1 for the test service, the tests were no longer passing. Sorry, I forgot to mark 2254 with `do-not-merge` but this followup fixes the problem. Tests pass again (tested with Istio).
Fixes #
```release-note
NONE
```
=> Fix timeouts conformance tests

Makefile, conformance/base/manifests.yaml, conformance/mesh/manifests.yaml, hack/update-conformance-image-refs.sh
/kind cleanup
/kind test
This PR introduces a new make target - `update-conformance-image-refs` it will trigger a new bash script that will update the `echo-basic` & `echo-advanced` to the latest tag (sorted by semver)
I'm including the output of running the script - which is bumping both images to the latest semver tag
I also fixed the mesh yamls to use echo-advanced instead of basic - that was introduced in https://github.com/kubernetes-sigs/gateway-api/pull/2468/files
```release-note
Update mesh conformance to point to the correct images
```
=> Include make target for bumping echo-basic & advanced in our conformance files

conformance/tests/gateway-secret-invalid-reference-grant.yaml
ReferenceGrant's version was moved to `v1` as a mistake in the conformance test YAML
Relates to https://github.com/kubernetes-sigs/gateway-api/pull/2486
```release-note
Fixes the API version for `ReferenceGrant` from `v1` to `v1beta1` in the `GatewaySecretInvalidReferenceGrant` conformance test YAML
```
=> conformance: revert ver to v1beta1 for RefGrant

apis/v1alpha2/backendtlspolicy_types.go, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml, pkg/test/cel/backendtlspolicy_test.go
/kind test
Without it, it's awfully hard to ensure that the CEL we've written covers all the inputs we want to allow or prevent.
Fixes #2473 
```release-note
NONE
```
=> BackendTLSPolicy cel tests

apis/v1/gateway_types.go
/kind cleanup
Adds the `+optional` Marker to GatewayInfrastructure fields. These fields are optional and therefore should include this marker.
Fixes #2509 
```release-note
NONE
```
=> Adds +optional Marker to GatewayInfrastructure Fields

conformance/conformance_test.go, conformance/experimental_conformance_test.go, gwctl/pkg/common/clients.go
/kind cleanup
/kind test
Gateway API v1 APIs need to be added the scheme. Discovered in https://github.com/kubernetes-sigs/gateway-api/pull/2456#pullrequestreview-1690743992 - thanks @sunjayBhatia 
N/A
```release-note
NONE
```
=> add v1 to various client schemes

conformance/base/manifests.yaml, conformance/tests/httproute-backend-protocol-h2c.go, conformance/tests/httproute-backend-protocol-h2c.yaml, conformance/utils/http/http.go, conformance/utils/roundtripper/roundtripper.go, conformance/utils/suite/features.go
/kind test
This PR adds a conformance test validating implementations support h2c when the target Kubernetes Service Service Port has a `kubernetes.io/h2c` `appProtocol`
Depends on echo-basic changes which are being bumped here: https://github.com/kubernetes-sigs/gateway-api/pull/2456
Related https://github.com/kubernetes-sigs/gateway-api/issues/1911
```release-note
NONE
```
=> [GEP-1911] h2c backend protocol conformance

conformance/base/manifests.yaml, conformance/echo-basic/echo-basic.go, conformance/tests/httproute-backend-protocol-ws.go, conformance/tests/httproute-backend-protocol-ws.yaml, conformance/utils/suite/features.go
/kind test
This PR adds a conformance test validating implementations support websocket over cleartext when the target Kubernetes Service Service Port has a `kubernetes.io/ws` `appProtocol`
This PR includes echo-basic changes so it will need to bumped after this PR
Related https://github.com/kubernetes-sigs/gateway-api/issues/1911 https://github.com/kubernetes-sigs/gateway-api/issues/205
```release-note
NONE
```
=> [GEP-1911] websocket backend protocol conformance

conformance/base/manifests.yaml, conformance/mesh/manifests.yaml
/kind cleanup
Bump conformance images to the latest ref - this pulls in the websocket changes to echo-basic that landed with the web socket conformance test
https://testgrid.k8s.io/sig-network-gateway-api#post-gateway-api-push-images
```release-note
NONE
```
=> bump images to latest ref

conformance/tests/gateway-with-attached-routes.go, conformance/tests/gateway-with-attached-routes.yaml
/kind test
Fixes #2402
```release-note
NONE
```
=> Conformance: Adds Test to Exercise Gateway AttachedRoutes

conformance/utils/suite/experimental_suite.go
Fixes: https://github.com/kubernetes-sigs/gateway-api/issues/2513
Implement the ExemptFeatures setting in Experimental Conformance Profile
Fixes # https://github.com/kubernetes-sigs/gateway-api/issues/2513
```release-note
Implemented the `ExemptFeatures` field for Experimental Conformance Profiles
```
=> implement exemptFeatures for conformance profile

CHANGELOG.md, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml, pkg/generator/main.go
This adds the changelog for v1.0.0-rc2. By approving this PR, you're approving the release of Gateway API.
```release-note
NONE
```
/assign @shaneutt @youngnick 
/hold for #2477 to merge
=> Adding changelog for v1.0.0-rc2

site-src/implementations.md
Update Documentation for Cilium CNCF status
```release-note
NONE
```
=> Update implementations.md: Cilium is now CNCF Graduates Project

hack/update-codegen.sh
Follow up on https://github.com/kubernetes-sigs/gateway-api/pull/2531
/assign @shaneutt 
```release-note
NONE
```
=> don't hardcode go version in update codegen script

apis/v1/gatewayclass_types.go
Although this was only a new condition, it feels strange to add it immediately to a GA API without any soak period. This is not really going to have any affect on CRD generation or generated clients, this really just is meant to signal that details of the condition could still change and it does not yet have GA stabililty.
```release-note
GatewayClass "SupportedVersion" condition has been formally marked as experimental.
```
=> Marking SupportedVersion as experimental

conformance/tests/gateway-with-attached-routes.go
* Set status to `False` for `notAccepted` Route condition
* Remove `Accepted` condition from `status.listeners[0].conditions` since it is not mandatory for the `Accepted` condition to be set. In this case the `ResolvedRefs=False` due to `InvalidCertificateRef` so an implementation may choose to not generate any listener config
Also Fixes # https://github.com/kubernetes-sigs/gateway-api/issues/2526
```release-note
Fixed the status condition requirements in the `GatewayWithAttachedRoutes` test
```
=> Fix bugs in GatewayWithAttachedRoutes

CHANGELOG.md, README.md, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml, pkg/generator/main.go, site-src/guides/index.md
=> Create v1 changelog

config/webhook/admission_webhook.yaml
/kind feature
Small bit of cleanup post-v1.0.0 release - this was already accounted for in the release manifest.
```release-note
NONE
```
=> Bumping webhook install version

conformance/tests/gateway-with-attached-routes.go
/kind bug
The spec does not say that a route with invalid backendRef and/or a parentRef to a gateway that is not "Programmed" should have the "Accepted" condition set to "False" (i.e., there is no corresponding [route condition reason](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io%2fv1.RouteConditionReason)). All the spec is clear about is that the "ResolvedRefs" condition should be "False".
So, the conformance test should only be checking for the latter, not both conditions.
Fixes #
```release-note
Fixed GatewayWithAttachedRoutes conformance test to not check that the HTTPRoute status …
```
=> Fix attached routes confromance test

conformance/reports/v0.8.1/projectcontour-contour.yaml, site-src/implementations.md
Adds conformance report for Contour v1.27.0 which supports Gateway API v0.8.1 and updates implementation summary.
N/A
```release-note
NONE
```
=> Add Contour conformance report for v0.8.1

conformance/reports/v1.0.0/envoy-gateway.yaml, site-src/implementations.md
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2557
```release-note
NONE
```
=> Add v1.0.0 Conformance Report of Envoy Gateway

conformance/tests/mesh-split.go, conformance/utils/suite/experimental_profiles.go, conformance/utils/suite/experimental_reports.go, conformance/utils/suite/features.go
/kind bug
/kind conformance
Reports generated by the conformance framework are missing information about mesh tests that are using features that are not part of the `MESH` core profile. This PR adds `HTTPRouteExtendedFeatures` to the MESH profile so that several of the mesh tests that weren't showing up in the report are now included. Generating the report (for istio) only showed 2 mesh tests, but now includes all 6 in the report.
Before this PR:
```
profiles:
- core:
result: success
statistics:
Failed: 0
Passed: 2
Skipped: 0
summary: ""
name: MESH
```
After this PR:
```
profiles:
- core:
result: success
statistics:
Failed: 0
Passed: 2
Skipped: 0
summary: ""
extended:
result: partial
skippedTests:
- MeshFrontendHostname …
```
=> Fix conformance report missing tests

site-src/implementations.md
The commit 85a26eea1d8d ("docs: Add Cilium conformance report for v1.0.0") uses the wrong report file name for "Gateway API Conformance v1.0.0" link.
/kind bug
Fixes #
```release-note
"NONE"
```
=> docs: Fix Cilium conformance report v1.0.0 link error

geps/gep-1762.md, mkdocs.yml
/kind gep
Fixes #
```release-note
NONE
```
=> Some minor fixes to gep-1762 doc

conformance/utils/config/timeout.go, conformance/utils/suite/experimental_profiles.go
* Fix typo in the comment for variable TimeoutConfig.TLSRouteMustHaveCondition.
* Fix typo in the comment for function getConformanceProfileForName.
Fix typo in comments of variables and functions.
N/A
None
=> Fix typos for TimeoutConfig and getConformanceProfileForName

conformance/tests/httproute-invalid-parentref-section-name-not-matching-port.go, conformance/tests/httproute-invalid-parentref-section-name-not-matching-port.yaml
/kind test
According to the description, when both Port and SectionName are specified, the name and port of the selected listener
must match both specified values.
https://github.com/kubernetes-sigs/gateway-api/blob/e2f02aa0fc9dfa27be271397801f52f4e0a78acc/apis/v1/shared_types.go#L124C1-L130C38
Fixes #
```release-note
NONE
```
=> conformance: missmatch `SectionName` and `Port` will trigger `NoMatchingParent` 

site-src/implementations.md
Update status of Easegress to GA: https://github.com/megaease/easegress/pull/1129
```release-note
NONE
```
=> Update Easegress to GA

site-src/concepts/api-overview.md
Hi,
On this page of documentation, the setting "SectionName" is explained. While it mentions the effect of adding a "SectionName" it may be slightly lacking in clarifying the default which would be the absence of a "SectionName".  What happens without it?
My assumption, and what's added in this pull request, is that it will "attach to all listeners" of that gateway.
As evidence about the importance of addressing the topic, it seems that even Google's documentation has gotten confused? 
Consider on this page
https://cloud.google.com/kubernetes-engine/docs/how-to/deploying-gateways
"""
When configuring HTTP-to-HTTPS redirects on the Gateway, the sectionName field is optional. If you don't configure this field, the HTTPS listener is automatically selected as the default option.
"""
What they …
=> Docs: clarify SectionName

conformance/tests/gateway-modify-listeners.go, conformance/tests/gateway-observed-generation-bump.go
Start the timeout context after gateways are ready. Currently, if gateways take more than 1 minute to become programmed, when `client.Get()` is called the context is already expired.
/kind test
```release-note
NONE
```
=> Fix the timeout context creation order

conformance/reports/v1.0.0/kong-kubernetes-ingress-controller.yaml
Adds Kong Kubernetes Ingress Controller v3.0.1 conformance report for v1.0.0.
```release-note
NONE
```
=> conformance: Kong Kubernetes Ingress Controller v3.0.1 report for v1.0.0

conformance/utils/config/timeout.go, conformance/utils/kubernetes/helpers.go
/kind test
Removing concurrency from `GatewayListenersMustHaveConditions` function, as requested.
Fixes #2459
```release-note
None
```
=> Check listeners conditions serially

conformance/utils/kubernetes/helpers.go
/kind test
This PR adds support for addresses of type `Hostname` in the Address section for the status of gateway objects. This change is needed so that cloud load balancers can provide a DNS name in as the address assigned to the gateway and pass the conformance tests.
There was a TODO section in the `helpers.go` file that that PR addresses, there is no github issue for it.
```release-note
NONE
```
=> Add support for hostname address in conformance tests

conformance/tests/httproute-invalid-parentref-section-name-not-matching-port.go, conformance/utils/suite/features.go
/kind bug
The test HTTPRouteInvalidParentRefSectionNameNotMatchingPort uses a ParentRef port (extended feature). For this purpose, a new extended feature HTTPRouteParentRefPort has been introduced and used in the aforementioned test.
Context: https://github.com/kubernetes-sigs/gateway-api/pull/2582#issuecomment-1832158986
Fixes #
```release-note
NONE
```
=> fix(conformance): `parentRef` port is extended

conformance/utils/suite/experimental_reports.go, conformance/utils/suite/experimental_suite.go
/kind feature
Using `UnsortedList()` on a set and iterating over a map gives a random order of items, thus reports are not stable (the order of items in those reports changes), for example, an update of one report that only differs in the app version.
- https://github.com/kubernetes-sigs/gateway-api/pull/2611
```release-note
The order of items in a conformance report is stable.
```
=> Sort items in conformance reports to maintain stability

geps/gep-1748.md
/kind cleanup
/kind gep
This helps explain that the MCS GEP (#1748) will be stuck in experimental until the MCS API graduates to GA.
```release-note
NONE
```
=> Adding a note to explain the prolonged experimental state of MCS GEP

docker/Dockerfile.echo-advanced, docker/Dockerfile.echo-basic
In particular, the newer "advanced" echo no longer runs as root (it now has `USER` configured), which makes it possible to run in more strict environments like OpenShift.
```release-note
NONE
```
=> Bump parent images for echo apps

hack/verify-golint.sh
/kind bug
Got such errors while running `hack/verify-golint.sh`:
```
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
error obtaining VCS status: exit status 128
Use -buildvcs=false to disable VCS stamping.
```
So add `-buildvcs=false` to fix the errors
Fixes #2071
```release-note
NONE
```
=> Add -buildvcs=false flag to fix golint script

examples/standard/http-redirect-rewrite/gateway-redirect-http-https.yaml, examples/standard/http-redirect-rewrite/httproute-redirect-http.yaml, site-src/guides/http-redirect-rewrite.md
* Add example Gateway and HTTPRoute yamls for configuring HTTP-to-HTTPS redirect for Gateway.
* Rename httproute-redirect-https.yaml to httproute-redirect-http.yaml since the redirect HTTPRoute only applies on HTTP listener. Update all reference to this file.
* Include a HTTPRoute for HTTPS traffic handling in httproute-redirect-https.yaml.
Add examples for HTTP-to-HTTPS redirects.
Fixes #2622 
None
=> Add examples for HTTP-to-HTTPS redirects.

mkdocs.yml
/kind gep
/kind cleanup
Missed in #2255, refs https://github.com/kubernetes-sigs/gateway-api/issues/1651#issuecomment-1658976444, aligns website sidebar categorization with actual current status for [GEP-1651](https://gateway-api.sigs.k8s.io/geps/gep-1651/)
```release-note
NONE
```
=> [GEP-1651] Update website sidebar index to categorize as Provisional

apis/v1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, examples/standard/simple-http-https/gateway.yaml, hack/invalid-examples/standard/gateway/invalid-tls-mode.yaml, pkg/test/cel/gateway_test.go
/kind bug
This PR adds tls mode validation for https listeners.
In the current Gateway API, the tls mode can be configured as Passthrough for an https listener, which should not be allowed.  Rather than relying on the Gateway implementations to catch and handle this misconfiguration, it can be checked earlier at the Gateway creation/modification stage by the API server with a cel expression.
```release-note
NONE
```
=> Add validation for https tls mode

config/webhook/admission_webhook.yaml
* The API version and resource of the webhook should match the ones in pkg/admission/server.go
/kind bug
/area webhook
Update API resources and versions in the webhook manifest. In v1.0.0, gateway-api-addmission-server watches v1beta1 and v1 resources, while the webhook still limits to v1alpha2 and v1beta1.
Fixes #2674 
```release-note
Updated the configuration for webhook manifest. In v1.0.0, the admission webhook server only supports v1beta1 and v1 API versions for Gateway, GatewayClass, and HTTPRoute, but webhook manifest was not updated.
```
=> Update webhook manifest to match API version in code.

apis/v1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
This PR fixes #1598 by allowing an implementation to optionally implement listed order for HTTPRouteFilters in a route-rule. There are implementations (as described in #1598 and discussion #2628) where the behavior depends on certain order for the filters so we would like to have this specified as an optional behavior in the spec.
Fixes #1598
```release-note
Possibly: users of certain implementations (which will conform to this new optional behavior) may need to reorder the filters they have listed in their routes.
```
=> Allow an implementation to use listed order for HTTPRouteFilter in a route-rule

conformance/utils/http/http.go
/kind bug
running conformance test `HTTPRouteRedirectPortAndScheme`, will get a wired log in the output even if the redirect scheme is Well-Known. so add some check to ensure this log only be shown if the redirect scheme is a actual unrecognized one.
```
=== CONT  TestGatewayAPIConformance/HTTPRouteRedirectPortAndScheme/http-listener-on-80/1_request_to_'/scheme-nil-and-port-80'_should_receive_a_302
httproute-redirect-port-and-scheme.go:159: Making GET request to http://172.18.255.200/scheme-nil-and-port-80
Sending Request:
< GET /scheme-nil-and-port-80 HTTP/1.1
< ...
Received Response:
< HTTP/1.1 302 Found
< ...
http.go:348: Can't validate redirectPort for unrecognized scheme http  ### <<<=== wired log …
```
=> fix: add check for unrecognized scheme in http redirect request scheme

gwctl/Makefile, gwctl/README.md
Adds a basic Makefile to build the gwctl binary and improves the documentation in the readme.
**Which issue(s) this PR fixes**: none
```release-note
NONE
```
=> doc: gwctl - improve readme, add Makefile

.github/dependabot.yml
/kind test
This provides the actual dependabot updates with their actual labels and add ok-to-test which help reviewers save some time.
```release-note
NONE
```
=> dependabot: provide ok-to-test with default labels

config/crd/experimental/kustomization.yaml
/kind bug
BackendTLSPolicy was not included in the experimental channel kustomization config
So currently something like:
```
kubectl kustomize -o <out_file> "github.com/kubernetes-sigs/gateway-api/config/crd/experimental?ref=v1.0.0"
```
Does not include the BackendTLSPolicy CRD
N/A
```release-note
None
```
=> Update experimental channel kustomization with backendtlspolicy

geps/gep-1709/index.md
/kind cleanup
/kind gep
This adds two new pieces of graduation criteria to GEP-1709, and resolves some others.
This also includes an explicit request to extend the probationary period of the GEP a couple more months to achieve these goals, so as per our rules this will need to be approved by both my co-maintainers:
/cc @robscott @youngnick 
At this point what we consider to be blocking standard is a bit of re-organization of how `ConformanceReports` look and are stored based on recent GEP updates, and documentation for using the test suite must be present. We currently expect we should be able to get this done prior to Kubecon Paris, thus the April timeline for extension before we re-evaluate.
**Does this PR introduce a …
=> Add graduation criteria for Conformance Profiles GEP (1709)

OWNERS_ALIASES, gwctl/OWNERS
/kind cleanup
This adds an OWNERS file for gwctl and makes @gauravkghildiyal the first approver. 
```release-note
NONE
```
/assign @shaneutt @youngnick
=> Adding gwctl OWNERS, making Gaurav first approver

OWNERS_ALIASES
/kind cleanup
This moves @bowei to emeritus maintainer. He's had an especially foundational role in the success of this project and will continue to be involved, just not as an active maintainer.
```release-note
NONE
```
/assign @shaneutt @youngnick
=> Move Bowei to emeritus maintainer

site-src/api-types/httproute.md, site-src/guides/tcp.md
Add documentation for route port attachment needed to promote GEP-957 to standard.
Fixes #
```release-note
NONE
```
=> Add route port attachment doc

geps/gep-1426/index.md, site-src/api-types/backendtlspolicy.md, site-src/api-types/gatewayclass.md, site-src/api-types/grpcroute.md, site-src/api-types/httproute.md, site-src/guides/grpc-routing.md, site-src/guides/http-redirect-rewrite.md, site-src/guides/http-routing.md, site-src/guides/migrating-from-ingress.md, site-src/guides/multiple-ns.md, site-src/guides/traffic-splitting.md
broken links
Fixes #
```release-note
NONE
```
=> Fix broken doc links

conformance/utils/kubernetes/certificate.go
/kind cleanup
There is unnecessary import of `client-go/plugin/pkg/client/auth` in `conformance/utils/kubernetes/certificates.go`.
So, this PR proposes to remove the import.
Since `conformance/conformance.go` already import the auth plugin package, it is not necessary to import. 
In addition, due to this dependency, if we want to make a code based on `conformance/utils/suite` or `conformance/utils/kubernetes` package, the code should unavoidably have the auth plugin dependencies comes from `client-go/plugin/pkg/client/auth`.
```release-note
NONE
```
=> Remove hidden dependency for client-go/plugin/pkg/client/auth

conformance/apis/v1alpha1/profilereport.go, conformance/experimental_conformance_test.go, conformance/utils/suite/experimental_reports.go, conformance/utils/suite/experimental_reports_test.go
/kind feature
The conformance report `.profiles[*].summary` field is now automatically filled by the conformance test suite with a human-readable message about the outcome of the tests run.
Fixes #2235 
```release-note
The conformance report `.profiles[*].summary` field is now automatically filled by the conformance test suite with a human-readable message about the outcome of the tests run.
```
=> feat: conformance report summary field

apis/v1alpha2/backendtlspolicy_types.go, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
/kind cleanup
Changes WellKnownCACerts field of BackendTLSPolicy to Implementation-specific support
Also updates language around what to do if WellKnownCACerts is not supported
Fixes #2726
```release-note
BackendTLSPolicy WellKnownCACerts field has been updated to implementation-specific support
```
=> Move BackendTLSPolicy WellKnownCACerts field to implementation-specific

gwctl/pkg/cmd/get/get.go, gwctl/pkg/printer/gateways.go, gwctl/pkg/printer/gateways_test.go
/kind feature
/area gwctl
Implement `gwctl get gateways`.
| Output Columns     | Description                                           | Visibility |
|------------|-------------------------------------------------------|---------|
| `NAME`       | Name of the Gateway                                   |         |
| `CLASS`      | Class of the Gateway                                  |         |
| `ADDRESSES`  | Addresses of the Gateway (displayed using +n more)    |         |
| `PORTS`      | Ports exposed by the Gateway                          |         |
| `PROGRAMMED` | Whether the Gateway is programmed                     |         |
| `AGE`        | Age of the Gateway …
=> Implement `gwctl get gateways`

conformance/apis/v1alpha1/conformancereport.go, conformance/experimental_conformance_test.go, conformance/utils/flags/experimental_flags.go, conformance/utils/suite/experimental_suite.go
/kind feature
The mode field has been added to the conformance report API. This field makes customization of the implementations' operating mode possible.
Fixes #2739 
```release-note
The mode field has been added to the conformance report API. This field makes customization of the implementations' operating mode possible.
```
=> feat: mode introduced to conformance report API

gwctl/pkg/printer/gateways.go
/kind cleanup
/area gwctl
For code consistency, use `fmt.Sprintf` instead of `strconv.Itoa`.
```diff
- ports = append(ports, strconv.Itoa(int(listener.Port)))
+ ports = append(ports, fmt.Sprintf("%d", int(listener.Port)))
```
Ref. #2782 
```release-note
NONE
```
=> Use fmt.Sprintf instead of strconv.Itoa

conformance/tests/httproute-backend-protocol-h2c.yaml
/kind cleanup
/kind test
Fixes the linter warning
>  ./conformance/tests/httproute-backend-protocol-h2c.yaml
>  11:3      warning  comment not indented like content  (comments-indentation) 
N/A
```release-note
NONE
```
=> fix yaml linter warning in backend-protocol test yaml

geps/gep-696/index.md
Fix broken link for status definitions in GEP-696, which is the template GEP.
/kind cleanup
Fixes broken link the template GEP
N/A
```release-note
NONE
```
=> GEP-696: Fix broken link in template GEP

geps/gep-713/index.md
Clarifies how two policies targeting the same resource should work when one uses a `sectionName` and the other does not
created based on Slack chat https://kubernetes.slack.com/archives/CR0H13KGA/p1695713117110159
None
**Release Note**
```release-note
clarify policy attachment by two of the same policy types when using section names.
```
=> clarify attachment by two policies to the same object when one uses a sectionName

geps/gep-1709/index.md
As per the sub-tasks in https://github.com/kubernetes-sigs/gateway-api/issues/1709 all the reporting structure work has been completed (thank you @mlavacca!). This updates the GEP to reflect that, and now all that's left is documentation as per https://github.com/kubernetes-sigs/gateway-api/issues/2322 (though Mattia also added a bit of documentation as a part of the reporting work recently as well).
=> docs: mark reporting structure grad criteria as complete for GEP 1709

.golangci.yml, conformance/tests/gateway-modify-listeners.go, conformance/tests/httproute-backend-protocol-websocket.go, conformance/utils/kubernetes/certificate.go, conformance/utils/roundtripper/roundtripper.go, hack/verify-golint.sh, pkg/test/cel/httproute_test.go
/kind cleanup
Linter is blocking https://github.com/kubernetes-sigs/gateway-api/pull/2828
N/A
```release-note
NONE
```
=> bump golangci-lint to latest version

gwctl/pkg/cmd/get/get.go, gwctl/pkg/printer/gateways.go, gwctl/pkg/printer/gateways_test.go
/area gwctl
/kind test
Inject a fake clock during testing `gwctl get gateways`.
```diff
type GatewaysPrinter struct {
Out   io.Writer
+	Clock clock.Clock
}
```
Fixes https://github.com/kubernetes-sigs/gateway-api/pull/2805#discussion_r1502192342
```release-note
NONE
```
=> Inject a fake clock during testing `gwctl get gateways`

apis/v1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, pkg/test/cel/gateway_test.go, site-src/guides/implementers.md, site-src/guides/tls.md
/kind feature
This loosens TLS validation as requested by #2668 and #2713 and adds documentation for the self-service approaches and overall indirect TLS config this enables. This also adds a new `InvalidTLSConfig` reason for the `Programmed` condition on Gateways.
Fixes #763 
Fixes #2668
Fixes #2713
```release-note
TLS Configuration is no longer required on Gateway Listeners to enable more flexible TLS configuration.
```
This is a big PR, going to leave it on hold for a bit while we wait for consensus.
=> Loosening TLS validation to enable indirect TLS config

gwctl/pkg/cmd/get/get.go, gwctl/pkg/printer/httproutes.go, gwctl/pkg/printer/httproutes_test.go
/kind feature
/area gwctl
Add missing columns to `gwctl get httproutes`.
| Output Columns | Description                                                  | Visibility |
|----------------|--------------------------------------------------------------|------------|
| `NAMESPACE`      | Namespace of the HTTPRoute                                   |            |
| `NAME`           | Name of the HTTPRoute                                        |            |
| `HOSTNAMES`      | Hostnames associated with the HTTPRoute                      |            |
| `PARENT REFS`    | Count of parent references of the HTTPRoute (e.g., Gateways) |            |
| `AGE`            | Age of the HTTPRoute …
=> Add missing columns to `gwctl get httproutes`

gwctl/pkg/cmd/get/get.go, gwctl/pkg/printer/policies.go, gwctl/pkg/printer/policies_test.go
/kind feature
/area gwctl
Add missing columns to `gwctl get policies`.
| Output Columns | Description                                 | Visibility |
|----------------|---------------------------------------------|------------|
| `NAME`           | Name of the Policy                          |            |
| `KIND`           | The kind of policy in the form <kind.group> |            |
| `TARGET NAME`    | Name of the resource the policy applies to  |            |
| `TARGET KIND `   | The kind of target resource in the form     |            |
| `POLICY TYPE`    | Type of policy (Inherited or Direct)        |            |
| `AGE`            | Age of the Policy                           |            | …
=> Add missing columns to `gwctl get policies`

conformance/reports/v1.0.0/kong-kubernetes-ingress-controller/README.md, conformance/reports/v1.0.0/kong-kubernetes-ingress-controller/v3.1.1-report.yaml
Conformance report for Kong ingress Controller 3.1.1
Fixes #
```release-note
NONE
```
=> chore: conformance report for KIC 3.1.1

gwctl/pkg/policymanager/merger_test.go, gwctl/pkg/resourcediscovery/nodes.go, gwctl/pkg/resourcediscovery/resourcemodel.go, tools/tools.go
When linting some code in a PR I realized there were some other files that weren't `gofumpt`-ed
```release-note
NONE
```
=> gofumpt the repo

gwctl/pkg/printer/policies.go, gwctl/pkg/printer/policies_test.go
/kind feature
/area gwctl
Add missing columns to `gwctl get policycrds`.
| Output Columns | Description                                             | Visibility |
|----------------|---------------------------------------------------------|------------|
| `NAME`           | Name of the Policy CRD in the form <kind.group>         |            |
| `POLICY TYPE`    | Type of policy defined by the CRD (Inherited or Direct) |            |
| `SCOPE`          | Scope of the policy (Namespaced or Cluster)             |            |
| `POLICIES COUNT` | Count of policy resources of this particular type.      | `-o wide`    |
| `AGE`            | Age of the Policy CRD                                   | …
=> Add missing columns to `gwctl get policycrds`

gwctl/pkg/cmd/get/get.go, gwctl/pkg/printer/gatewayclasses.go, gwctl/pkg/printer/gatewayclasses_test.go
/kind feature
/area gwctl
Implement `gwctl get gatewayclass`.
| Output Columns | Description                                            | Visibility |
|----------------|--------------------------------------------------------|------------|
| `NAME`           | Name of the GatewayClass                               |            |
| `CONTROLLER`     | Controller managing the GatewayClass                   |            |
| `ACCEPTED`       | Whether the GatewayClass is accepted by the controller |            |
| `AGE`            | Age of the Policy CRD                                  |            |
| `GATEWAYS`       | Count of Gateways using this GatewayClass              | `-o wide`    |
| …
=> Implement `gwctl get gatewayclass`

site-src/concepts/conformance.md
This PR explicitly mentions that users are expected to provide required [NetworkPolicies](https://kubernetes.io/docs/concepts/services-networking/network-policies/) when running conformance tests in cluster with CNI plugins installed that enforce those policies.
Related discussion: https://github.com/kubernetes-sigs/gateway-api/discussions/2137
```release-note
NONE
```
=> docs(conformance): mention network policies

examples/standard/http-request-mirroring/httproute-mirroring.yaml, mkdocs.yml, site-src/guides/http-request-mirroring.md
* Added example HTTPRoute yaml for configuring HTTP request mirroring.
Added examples for HTTP request mirroring.
Fixes #2833
```release-note
None
```
=> Add doc and httproute example for HTTP request mirroring

conformance/base/manifests.yaml, conformance/tests/udproute-simple.go, conformance/tests/udproute-simple.yaml, conformance/utils/kubernetes/helpers.go, conformance/utils/suite/features.go, go.mod, go.sum
/kind test
- initial conformance tests for UDPRoute
- dedup code for Route Handler
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1792
```release-note
NONE
```
=> conformance: initial UDPRoute test

conformance/utils/suite/experimental_profiles.go
/kind feature
This PR introduces a GRPC Conformance Profile to enable downstream implementations to run the test suite in an aggregated manner.
Fixes #2871
```release-note
Added the GRPC Conformance Profile. 
```
=> Added grpc conformance profile

conformance/tests/httproute-listener-port-matching.go, conformance/tests/httproute-listener-port-matching.yaml, conformance/tests/mesh-ports.go, conformance/utils/kubernetes/helpers.go
/kind test
Conformance test needed to promote GEP-957 to standard.
Tested and passes with Istio implementation.
Fixes #
```release-note
NONE
```
=> Add route port attachment conformance test

gwctl/cmd/get.go, gwctl/pkg/printer/gatewayclasses_test.go, gwctl/pkg/printer/gateways_test.go, gwctl/pkg/printer/httproutes_test.go, gwctl/pkg/resourcediscovery/discoverer.go
Fixes #2890
```release-note
Add label filtering (-l) for get commands
```
- Correct label format output
```
➜  gwctl get httproutes -l app=backend
NAMESPACE  NAME     HOSTNAMES        PARENT REFS  AGE
default    backend  www.example.com  1            30d
```
- Error label format output
```
➜  gwctl get httproutes -l aps=dsd,adsa,=ds
Unable to find resources that match the label selector "aps=dsd,adsa,=ds": found '=', expected: identifier after ','
```
=> Add label filtering (-l) for get commands

gwctl/cmd/get.go, gwctl/pkg/printer/namespace.go, gwctl/pkg/printer/namespace_test.go
/kind feature
/area gwctl
Implement `gwctl get namespace`.
| Output Columns | Description                                | Visibility |
|----------------|--------------------------------------------|------------|
| `NAME`           | Name of the Namespace                      |            |
| `STATUS`         | Status of the Namespace                    |            |
| `AGE`            | Age of the Namespace                       |            |
| `POLICIES`       | Count of policies affecting this Namespace | `-o wide`    |
The `-o wide` format is not yet implemented, so the column `POLICIES` is excluded.
Fixes #2854
**Does this PR introduce a user-facing …
=> Implement `gwctl get namespace`

gwctl/pkg/printer/gatewayclasses.go, gwctl/pkg/printer/gatewayclasses_test.go
/kind bug
/area gwctl
Fixes #2849 
```release-note
fix(gwctl): prevent panic when describing gatewayclasses with no description
```
=> fix(gwctl): prevent panic when describing gatewayclasses with no description

conformance/tests/grpcroute-header-matching.go, conformance/tests/grpcroute-listener-hostname-matching.go, conformance/utils/kubernetes/helpers.go
Previously, there were several places in the GRPCRoute conformance tests where the `routeType` parameter was not being supplied to `GatewayAndRoutesMustBeAccepted`. Instead, the variadic `routeNNs` was being consumed as the `routeType` argument, leaving `routeNNs` with size 0. (since in all of these cases, there was only one route intended). This resulted in no routes being checked and [the type assertion helper for `HTTPRoute`-like types](https://github.com/kubernetes-sigs/gateway-api/blob/f7fa7d4d31b3d9a8c5164f573db34d75830dfafb/conformance/utils/kubernetes/helpers.go#L564) never being called.
This PR:
- Adds a call to `RouteTypeMustHaveParentsField` directly within GatewayAndRoutesMustBeAccepted to ensure such an …
=> Fix GRPCRoute parent status check

apis/v1/shared_types.go, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, geps/gep-957/index.md, geps/gep-957/metadata.yaml, mkdocs.yml
/kind gep
GEP-957 should be moved from experimental to standard channel.
Depends on: #2775 
Fixes #957
```release-note
Attaching routes to gateways by port number (GEP-957) feature moved to standard channel.
```
=> Promote GEP-957 to standard channel

OWNERS_ALIASES
@mlavacca and @LiorLieberman have both graciously agreed to help out with the GEP review cycles, as such we're promoting them both to GEP reviewers! Thank you @LiorLieberman and @mlavacca we appreciate your continued contributions to the project! :bow:
/cc @youngnick @robscott
=> Add Lior Lieberman and Mattia Lavacca as GEP Reviewers

gwctl/cmd/describe.go, gwctl/cmd/get.go, gwctl/pkg/printer/namespace_test.go
Fixes #2913
```release-note
Add label filtering (-l) for get namespaces
```
```
➜  gwctl get namespaces -l kubernetes.io/metadata.name=monitoring
NAME        STATUS  AGE
monitoring  Active  29d
```
=> Add label filtering (-l) for `get namespaces`

geps/gep-995/index.md, geps/gep-995/metadata.yaml, mkdocs.yml
/kind gep
Proposal to add a new `name` field to the route rule types ([GRPCRouteRule](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1alpha2.GRPCRouteRule), [HTTPRouteRule](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteRule), [TCPRouteRule](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1alpha2.TCPRouteRule), [TLSRouteRule](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1alpha2.TLSRouteRule) and [UDPRouteRule](https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1alpha2.UDPRouteRule)) to support referencing individual rules by name.
**Which issue(s) this PR …
=> Adding GEP-995 for support for named route rules

geps/gep-2907/index.md, geps/gep-2907/metadata.yaml, mkdocs.yml
/kind gep
This adds a new memorandum GEP that attempts to chart a vision for where our TLS configuration will live and what it will be called.
Fixes #2907
```release-note
NONE
```
/cc @arkodg @candita @youngnick
=> Adding GEP 2907: TLS Configuration Placement and Terminology

conformance/tests/httproute-timeout-backend-request.yaml
There is discrepancy between test request path (e.g. /disable-backend-timeout?delay=1s) and path prefix in http route (e.g. /disabled-backend-timeout), which will cause 404 response instead of 200.
Fixes: https://github.com/kubernetes-sigs/gateway-api/pull/2823
```release-note
NONE
```
=> conformance: Fix path prefix for disable backend timeout route

conformance/tests/gateway-static-addresses.go
Currently, this strictly enforces that spec and status addresses are 1:1. This doesn't allow variance in implementations. For example, assigning an IPv4 and IPv6 address, internal and external address, IP and hostname, etc.
```release-note
NONE
```
=> conformance: make GatewayStaticAddresses more leniant

geps/gep-91/index.md
/kind gep
**What**
Defines an API in GEP-91 to support Client Certificate Validation for TLS Terminating at the Gateway
using a CA Certificate as a trusted anchor.
**Why**
Allows the platform admin configuring the Gateway resource to only select trusted clients to connect to the Gateway
Relates to https://github.com/kubernetes-sigs/gateway-api/issues/91 & https://github.com/kubernetes-sigs/gateway-api/issues/2110
=> Adds API to GEP-91: Client Certificate Validation

geps/gep-1709/index.md, geps/gep-1709/metadata.yaml, mkdocs.yml
=> Promote GEP 1709 to "Standard"

geps/gep-1619/index.md
/kind gep
N/A
The main goal of this PR is to get https://github.com/kubernetes-sigs/gateway-api/issues/1619 ready for implementable by answering the open questions in [Graduation Criteria for Implementable Status](https://gateway-api.sigs.k8s.io/geps/gep-1619/#graduation-criteria-for-implementable-status):
4. Finish designing the Route Rule API and document edge cases in Edge Case Behavior for configuring session persistence on both `BackendLBPolicy` and route rules.
Fixes #2634 
```release-note
NONE
```
=> Finish Route Rule API design and update edge case behaviors.

conformance/tests/gateway-modify-listeners.go, conformance/tests/gateway-observed-generation-bump.go, conformance/tests/gateway-static-addresses.go, conformance/tests/gatewayclass-observed-generation-bump.go, conformance/tests/httproute-observed-generation-bump.go, conformance/utils/config/timeout.go
/kind test
This PR removes the last references to static conformance test context timeouts so that implementations can tailor the timeouts to the environment they're run in (e.g. VMs with slower LB address provisioning)
=> Remove the last references to static context timeouts in conformance tests

mkdocs.yml
GEP-957 was in both experimental and standard in the mkdocs.yml which caused some weird buggy behavior on the web page.
/kind gep
N/A
```release-note
NONE
```
=> GEP-957: Remove from experimental

conformance/conformance.go
/kind bug
If the suite is used as a library, the `DefaultOptions` method is not used, and instead the `Options` struct is provided by the implementation. In that case, the FS needs to be always set, otherwise the tests fail. We need to add a default on such a field, to that in case it is not set, we use the default FS value.
This problem has been surfaced by this discussion: https://github.com/kubernetes-sigs/gateway-api/pull/2864#discussion_r1564249514
Fixes #
```release-note
NONE
```
=> fix: the conformance suite FS is defaulted if not given

site-src/implementations.md
All the links 404 currently. Now they don't.
Notably, for the NGINX one it points to the main project README now instead of a specific version. This matches all of the others, so I think its WAI
Fixes #
```release-note
NONE
```
=> docs: fix 404s on conformance tests

geps/gep-1426/index.md, geps/gep-1426/metadata.yaml
/kind gep
The GEP is already relatively clear on needing `Service` as `parentRef` for graduating the GEP but this tweaks the language to clarify the position.
```release-note
NONE
```
=> GAMMA: update language around Service as parentRef

conformance/tests/httproute-weight.go, conformance/tests/httproute-weight.yaml, go.mod
/kind cleanup
/kind test
There currently isn't a conformance test for weighted routing. This is a core feature for HTTPRoute.
N/A
```release-note
NONE
```
=> Conformance test for HTTPRoute weights

conformance/tests/grpcroute-listener-hostname-matching.yaml
/kind bug
In https://github.com/kubernetes-sigs/gateway-api/pull/2919 the version of GRPCRoutes in conformance tests was updated from v1alpha2 to v1.
However, two GRPCRoutes were not updated.
This commits fixes the version in those omitted two GRPCRoutes.
I didn't create any issue - the problem was introduced recently and it is small.
```release-note
NONE
```
=> Fix version of GRPC routes in conformance tests

site-src/contributing/index.md, site-src/mesh/gamma.md
Website updates. See preview of [meetings section](https://deploy-preview-2982--kubernetes-sigs-gateway-api.netlify.app/contributing/#meetings) and [GAMMA page](https://deploy-preview-2982--kubernetes-sigs-gateway-api.netlify.app/mesh/gamma/) for review.
Updates meeting times to add monthly alternate time and consolidates GAMMA meetings back into main Gateway API meeting.
Fixes "add to your calendar" broken link.
```release-note
NONE
```
=> [website] update meeting times and details

gwctl/cmd/describe.go, gwctl/cmd/get.go, gwctl/go.mod, gwctl/pkg/printer/gatewayclasses_test.go, gwctl/pkg/printer/gateways_test.go, gwctl/pkg/printer/httproutes_test.go, gwctl/pkg/printer/namespace_test.go, gwctl/pkg/resourcediscovery/discoverer_test.go
Fixes #2933
```release-note
Add label filtering (-l) for describe commands
```
```
➜  gwctl describe httproute -l app=backend
Name: backend
Namespace: default
Hostnames:
- www.example.com
ParentRefs:
- group: gateway.networking.k8s.io
kind: Gateway
name: eg
EffectivePolicies:
default/eg: {}
```
```
➜  gwctl describe ns -l kubernetes.io/metadata.name=envoy-gateway-system
Name: envoy-gateway-system
Annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"name":"envoy-gateway-system"}}
Labels:
kubernetes.io/metadata.name: envoy-gateway-system
name: …
```
=> Add label filtering (-l) for describe commands

.golangci.yml, gwctl/cmd/describe.go, gwctl/pkg/common/clients.go, gwctl/pkg/policymanager/manager.go, gwctl/pkg/policymanager/merger.go, gwctl/pkg/printer/gatewayclasses.go, gwctl/pkg/printer/gateways.go, gwctl/pkg/printer/httproutes.go, gwctl/pkg/printer/namespace.go, gwctl/pkg/printer/policies.go, gwctl/pkg/resourcediscovery/discoverer.go, gwctl/pkg/resourcediscovery/discoverer_test.go, gwctl/pkg/resourcediscovery/nodes.go, gwctl/pkg/resourcediscovery/resourcemodel.go, hack/verify-golint.sh
/kind cleanup
Enabling linting for gwctl directory
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2918
```release-note
NONE
```
=> Setup golang linting for gwctl and fix existing lint errors

conformance/tests/gateway-observed-generation-bump.go, conformance/tests/gateway-observed-generation-bump.yaml
/kind cleanup
/kind test
The original intent of the test was to make sure observedGeneration was incremented when the Gateway's spec was modified. This is core functionality.
The test originally used port 8080 some time later it was put behind a feature flag. 
The changes removes the use of port 8080 in order to make the test 'core' again. It add's unique listeners with different hostnames
Fixes # N/A
```release-note
NONE
```
=> Gateway ObservedGeneration bumping should be a core test

conformance/utils/http/http.go, conformance/utils/roundtripper/roundtripper.go
/kind test
When using a custom round tripper it can useful to log messages during the request.  Propagate the `*testing.T* to the `http.Requst` to allow custom round trip implementations to log to the appropriate test stream.
Fixes #2939
```release-note
NONE
```
=> Pass testing.T to roundtripper as context value.

apis/v1alpha3/backendtlspolicy_types.go
/kind cleanup
Fixes an old reference caught by @aojea in https://github.com/kubernetes-sigs/gateway-api/pull/2997#discussion_r1577799591.
```release-note
NONE
```
/cc @candita @aojea
=> Updating one last caCertRefs reference to caCertificateRefs

CHANGELOG.md, config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml, conformance/utils/suite/suite_test.go, pkg/consts/consts.go
This adds the changelog for v1.1.0-rc1. By approving this PR, you're approving the release of RC1 based on these changes.
```release-note
NONE
```
=> Adding changelog for v1.1.0-rc1

conformance/utils/suite/profiles.go, conformance/utils/suite/reports_test.go
/kind cleanup
The conformance profiles have been renamed to allow the addition of nwe mesh profiles. Furthermore, the MESH-GRPC conformance profile has been added.
Fixes #
```release-note
The conformance profiles have been renamed according to the following format: <GATEWAY|MESH>-<HTTP|GRPC|TLS>.
```
=> Conformance profiles renamed

conformance/tests/mesh-consumer-route.go, conformance/tests/mesh-frontend-hostname.go, conformance/utils/suite/profiles.go, pkg/features/features.go
This PR moves a few mesh tests to "extended" level because they do not have widespread support
Fixes #
```release-note
NONE
```
=> mesh conformance: add extended level features

gwctl/cmd/describe.go, gwctl/pkg/common/clients.go, gwctl/pkg/printer/common.go, gwctl/pkg/printer/common_test.go, gwctl/pkg/printer/gateways.go, gwctl/pkg/printer/gateways_test.go, gwctl/pkg/resourcediscovery/discoverer.go, gwctl/pkg/resourcediscovery/nodes.go
- Add helpers to print `gwctl describe` views and Tables
- Add more information when describing Gateways (like attached routes)
- Discover events associated with Gateways and output them when describing Gateways.
<details>
<summary>Example:</summary>
```yaml
❯ gwctl describe gateways
Name: demo-gateway-1
Namespace: default
Labels: null
Annotations:
kubectl.kubernetes.io/last-applied-configuration: |
{"apiVersion":"gateway.networking.k8s.io/v1beta1","kind":"Gateway","metadata":{"annotations":{},"name":"demo-gateway-1","namespace":"default"},"spec":{"gatewayClassName":"foo-com-external-gateway-class","listeners":[{"name":"http","port":80,"protocol":"HTTP"}]}}
APIVersion: gateway.networking.k8s.io/v1
Kind: Gateway
Metadata:
creationTimestamp: …
```
=> Improve utilities for gwctl describe and add more info to gateway descriptions

conformance/reports/v1.0.0/azure-application-gateway-for-containers/README.md, conformance/reports/v1.0.0/azure-application-gateway-for-containers/v1.0.0-report.yaml, site-src/implementations.md
Adds conformance report and updates implementation page for Azure Application Gateway for Containers v1.0.0
N/A
None
=> Add conformance report for Application Gateway for Containers

gwctl/cmd/get.go, gwctl/pkg/printer/backends.go, gwctl/pkg/printer/backends_test.go, gwctl/pkg/printer/httproutes.go, gwctl/pkg/printer/policies.go, gwctl/pkg/resourcediscovery/discoverer.go
/kind feature
This PR introduces the `gwctl get backends` subcommand in favor of the requirements of this [GEP](https://deploy-preview-2723--kubernetes-sigs-gateway-api.netlify.app/geps/gep-2722/)
Fixes #2866 
Yes, it introduces the `gwctl get backends` command to support returning backends to the console.
For example:
```release-note
gwctl get backends
NAMESPACE  NAME       TYPE     REFERRED BY ROUTES                                   AGE   POLICIES
default    foo-svc-0  Service  default/foo-httproute-1                              3d    2
ns1        foo-svc-1  Service  default/qmn-httproute-100,default/foo-httproute-1    2d    3
ns2 …
```
=> [gwctl ] feat: `gwctl get backends` support

gwctl/pkg/printer/policies_test.go
/kind flake
fix: Ensure that TestPoliciesPrinter_PrintCRDs uses a function-under-test which
returns a deterministic output.
The current function being used does not sort the output, which results in a
difference in ordering across individual test runs.
```release-note
NONE
```
=> fix: Ensure that TestPoliciesPrinter_PrintCRDs uses a function-under-test which returns a deterministic output.

gwctl/cmd/describe.go, gwctl/cmd/get.go, gwctl/pkg/common/clients.go, gwctl/pkg/printer/backends_test.go, gwctl/pkg/printer/gatewayclasses_test.go, gwctl/pkg/printer/gateways_test.go, gwctl/pkg/printer/httproutes_test.go, gwctl/pkg/printer/namespace_test.go, gwctl/pkg/printer/policies_test.go, gwctl/pkg/resourcediscovery/discoverer.go, gwctl/pkg/resourcediscovery/discoverer_test.go
/kind cleanup
Use API discovery to determine the preferred API versions for Gateway API types.
Clusters may not always have the v1 CRDs installed. This means gwctl will have
to use whatever version is available in the cluster. Hence, we will use API
Discovery to determine the "preferred" API version as per the kube-apiserver and
then use a dynamic client to fetch that specific versioned resource.
Once that specific versioned resource is fetched (e.g. v1beta1.Gateway), it will
be converted to a concrete type used within gwctl (eg. v1.Gateway), which will
usually be a more newer/stable version. For most cases, this conversion should
not result in any losses. If in the future, a need arises for such special
cases, we should …
=> Properly handle different versioned resources in gwctl (eg. v1beta1 v/s v1 APIs) and related code cleanups

gwctl/cmd/describe.go, gwctl/cmd/get.go, gwctl/pkg/common/testhelpers.go, gwctl/pkg/common/types.go, gwctl/pkg/printer/backends_test.go, gwctl/pkg/relations/relations.go, gwctl/pkg/resourcediscovery/discoverer.go, gwctl/pkg/resourcediscovery/discoverer_test.go, gwctl/pkg/resourcediscovery/errors.go, gwctl/pkg/resourcediscovery/main_test.go, gwctl/pkg/resourcediscovery/nodes.go, gwctl/pkg/resourcediscovery/resourcemodel.go
/kind feature
- Use ReferenceGrants to determine if a cross-namespace reference from HTTPRoute
to a Backend is valid.
- Capture incorrect reference errors (like reference not found or not permitted)
in the resourceModel. This will be available for consumption by the views.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/3039
```release-note
gwctl now displays "incorrect" or "not-found" reference errors. It also uses ReferenceGrants to validate if a reference is correct or not (incorrect reference errors are made visible to the user)
```
/area gwctl
=> Make gwctl ReferenceGrant aware. Capture any errors observed while constructing the resource graph.

conformance/tests/gateway-http-listener-isolation-with-hostname-intersection.yaml, conformance/tests/gateway-http-listener-isolation.go, conformance/tests/gateway-http-listener-isolation.yaml, pkg/features/features.go
Takes https://github.com/kubernetes-sigs/gateway-api/pull/2669 forward
Fixes # https://github.com/kubernetes-sigs/gateway-api/issues/2416
/kind test
```release-note
```
=> Conformance test for listener isolation

apis/v1/grpcroute_types.go, apis/v1/httproute_types.go, apis/v1alpha2/backendlbpolicy_types.go
/kind bug
/kind cleanup
SessionPersistence pointer field should have an omitempty tag, this is the idiomatic way to tag such pointer fields and matches other such instances in the golang API
Not a huge issue per se, but when using the updated gateway-api v1.1.0 go module with an API server that has v1.0.0 CRDs, avoids warnings like:
```
time="2024-05-06T16:19:19Z" level=info msg="unknown field \"spec.rules[0].sessionPersistence\"" logger=KubeAPIWarningLogger
```
N/A
```release-note
NONE
```
=> SessionPersistence pointer field should have omitempty tag

CHANGELOG/1.1-CHANGELOG.md, CHANGELOG/1.1-TEAM.md, config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml, conformance/utils/suite/suite_test.go, pkg/consts/consts.go, site-src/guides/api-design.md
This adds the changelog for v1.1.0 and corresponding version bumps where needed. Approving this PR means that you're approving the release of Gateway API v1.1.0.
```release-note
NONE
```
/assign @shaneutt @youngnick
=> Adding changelog for v1.1.0

README.md
Update README to point to 1.1.0 release and mark GRPCRoute as GA.
```release-note
NONE
```
=> Update README for 1.1.0 release

site-src/api-types/backendtlspolicy.md, site-src/api-types/gateway.md, site-src/api-types/gatewayclass.md, site-src/api-types/grpcroute.md, site-src/api-types/httproute.md, site-src/api-types/referencegrant.md, site-src/blog/2021/introducing-v1alpha2.md, site-src/concepts/api-overview.md, site-src/concepts/use-cases.md, site-src/contributing/style-guide.md, site-src/guides/backend-protocol.md, site-src/guides/grpc-routing.md, site-src/guides/tcp.md, site-src/guides/tls.md, site-src/index.md, site-src/mesh/index.md
Update admonitions to correctly reflect API changes in 1.2.0, as well as fixing a bunch that were never updated in the past.
Standardize markup and wording throughout.
```release-note
NONE
```
=> Update and standardise admonitions

site-src/index.md, site-src/mesh/index.md
Follow up from https://github.com/kubernetes-sigs/gateway-api/pull/3066#discussion_r1597278249.
```release-note
NONE
```
/cc @howardjohn @keithmattix @kflynn
=> Fixing Mesh version references in docs

site-src/guides/index.md
Provides upgrade notes to help address common pain points for users upgrading to v1.1.
```release-note
NONE
```
=> Providing more detailed upgrade notes for v1.1

CHANGELOG/1.1-TEAM.md, mkdocs.yml, site-src/contributing/enhancement-requests.md, site-src/contributing/release-cycle.md
This is a follow up from a [doc I shared](https://docs.google.com/document/d/121dfFJPVkhwrS0sH_pcct5zHPEdqGvnkw70dcgBUnTA/edit#heading=h.8k4fdlynjij0) at the community meeting earlier this week. This builds on that by formally adding it to our documentation.
```release-note
NONE
```
=> Adding Release Cycle Documentation

gwctl/cmd/describe.go, gwctl/pkg/policymanager/helpers.go, gwctl/pkg/policymanager/manager.go, gwctl/pkg/policymanager/merger.go, gwctl/pkg/printer/backends.go, gwctl/pkg/printer/common.go, gwctl/pkg/printer/common_test.go, gwctl/pkg/printer/gatewayclasses.go, gwctl/pkg/printer/gatewayclasses_test.go, gwctl/pkg/printer/gateways.go, gwctl/pkg/printer/gateways_test.go, gwctl/pkg/printer/httproutes.go, gwctl/pkg/printer/namespace.go, gwctl/pkg/printer/namespace_test.go, gwctl/pkg/printer/policies.go, gwctl/pkg/resourcediscovery/discoverer.go, gwctl/pkg/resourcediscovery/nodes.go, gwctl/pkg/resourcediscovery/resourcemodel.go
/kind feature
This PR addresses missing information in the display of various resources and
enhances the presentation of printed information. After this and the related
issue #3037 get completed, all gwctl describe views will have the relevant
information and some visual appeal.
Examples:
<details>
<summary>$ gwctl describe backends</summary>
```yaml
...
(truncated)
...
ReferencedByRoutes:
Kind       Name
----       ----
HTTPRoute  default/grpc-httproute
HTTPRoute  default/grpc-httproute-2
DirectlyAttachedPolicies:
Type                                 Name
----                                 ----
HealthCheckPolicy.networking.gke.io  default/grpc-gateway-healthcheck
EffectivePolicies:
default/grpc-gateway: …
```
=> gwctl: Show Events, Analysis and few other fields for various resources.

geps/gep-713/index.md
/kind cleanup
Fix rendering of the list of conditions on policy APIs.
```release-note
NONE
```
=> Fix rendering of list in GEP-713

geps/gep-1324/index.md
2 images could not be displayed since the path was pointing to the wrong directory. The HTML side by side image box has been replaced with a markdown table (for readability on Github and on the website).
https://gateway-api.sigs.k8s.io/geps/gep-1324/#service
/
```release-note
NONE
```
=> GEP-1324: Fix image path

conformance/utils/kubernetes/helpers.go
/kind test
- prevent https://github.com/kubernetes-sigs/gateway-api/blob/7cd3c13dee528c33143b70cf9ea05bc41169f414/conformance/utils/kubernetes/helpers.go#L430 from merging `Gateway` and `err`, this will help with logs like:
```
helpers.go:711: 2024-05-27T18:29:49.249243+02:00: Gatewayexpected observedGeneration to be updated to 1 for all conditions, only 3/4 were updated. stale conditions are: Programmed (generation 0)
```
- use `client.ObjectKeyFromObject()` instead of manually providing ns and name
- add names of the relevant objects in several places when logs are emitted in conformance suite.
Fixes #
```release-note …
```
=> tests(conformance): more precise logs

pkg/features/features.go
/kind gep
This promotes backend protocol selection as part of Gateway v1.2 release
Part of https://github.com/kubernetes-sigs/gateway-api/issues/1911
```release-note
Backend Protocol Selection is no longer experimental and is now part of HTTPRoute Extended Conformance
```
=> promote HTTPRoute backend protocol from experimental to  extended

apis/v1beta1/httproute_types.go
/kind bug
Currently, the v1beta1 HTTPHeaderName aliases directly to v1.HeaderName instead of v1.HTTPHeaderName (which then aliases to v1.HeaderName).
```release-note
NONE
```
=> Fix v1beta1 HTTPHeaderName alias

gwctl/pkg/printer/gateways.go, gwctl/pkg/printer/gateways_test.go
Related to small usability for `gwctl`.
Now the following output for `gwctl get gateways -A`
```
NAMESPACE  NAME    CLASS   ADDRESSES       PORTS  PROGRAMMED  AGE
cilium     cilium  cilium  172.18.255.200  80     True        2h
default    cilium  cilium  172.18.255.201  80     True        2h
```
Related to https://github.com/kubernetes-sigs/gateway-api/issues/3133
Fixes #
```release-note
NONE
```
=> Outputs ns for gateways in gwctl

gwctl/cmd/subcommand.go, gwctl/pkg/printer/backends.go, gwctl/pkg/printer/backends_test.go, gwctl/pkg/printer/gatewayclasses.go, gwctl/pkg/printer/gatewayclasses_test.go, gwctl/pkg/printer/gateways.go, gwctl/pkg/printer/gateways_test.go, gwctl/pkg/printer/httproutes.go, gwctl/pkg/printer/httproutes_test.go, gwctl/pkg/printer/namespace.go, gwctl/pkg/printer/namespace_test.go, gwctl/pkg/printer/policies.go, gwctl/pkg/printer/printer.go, gwctl/pkg/utils/types.go
Fixes #2889
```release-note
1.Support wide output format for get commands (-o wide)
2.Replace `Print` in BackendsPrinter with `PrintTable`
```
```yaml
cat <<EOF | kubectl apply -f -
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: BackendTLSPolicy
metadata:
name: enable-backend-tls
namespace: default
spec:
targetRef:
group: ''
kind: Service
name: tls-backend
sectionName: "443"
tls:
caCertRefs:
- name: example-ca
group: ''
kind: ConfigMap
hostname: www.example.com
EOF
```
- **backend**
```
➜  ✗ gwctl get backend       
NAMESPACE  NAME         TYPE     AGE
default    backend      Service  106d
default    kubernetes   Service  106d …
```
=> Support wide output format for get commands (-o wide)

.github/dependabot.yml
/kind cleanup
One small label to simplify approving dependabot PRs.
```release-note
NONE
```
=> Adding release-note-none label to dependabot PRs

gwctl/cmd/subcommand.go, gwctl/pkg/printer/backends.go, gwctl/pkg/printer/common.go, gwctl/pkg/printer/gatewayclasses.go, gwctl/pkg/printer/gatewayclasses_test.go, gwctl/pkg/printer/gateways.go, gwctl/pkg/printer/gateways_test.go, gwctl/pkg/printer/namespace.go, gwctl/pkg/printer/namespace_test.go, gwctl/pkg/resourcediscovery/discoverer.go, gwctl/pkg/resourcediscovery/nodes.go
/kind feature
Summary of changes (details available in commit logs): 
1. Prioritize fetching resources in bulk rather than individually to reduce API call overhead. (Some simple performance tests with large number of resources indicated this provides the better overall UX)
2. Fetch events associated with resources on-demand when printing, enhancing responsiveness and minimizing unnecessary API calls (since events are not required in GET output)
Fixes #
```release-note
NONE
```
/assign @mlavacca
=> gwctl performance improvements

conformance/reports/v0.8.1/projectcontour-contour/README.md, conformance/reports/v0.8.1/projectcontour-contour/experimental-v1.27.4-default-report.yaml, conformance/reports/v1.0.0/projectcontour-contour/README.md, conformance/reports/v1.0.0/projectcontour-contour/experimental-v1.28.5-default-report.yaml, conformance/reports/v1.0.0/projectcontour-contour/experimental-v1.29.1-default-report.yaml, site-src/implementations.md
Adds conformance reports for latest Contour patch releases
N/A
```release-note
NONE
```
=> Contour 1.29.1, 1.28.5, 1.27.4 patch release reports

conformance/reports/v1.1.0/kong-kubernetes-ingress-controller/README.md, conformance/reports/v1.1.0/kong-kubernetes-ingress-controller/experimental-v3.2.0-expressions-report.yaml
Adds a Gateway API v1.1.0 conformance report for Kong's Kubernetes Ingress Controller v3.2.0. 
```release-note
NONE
```
=> chore: add conformance report for KIC 3.2.0

conformance/utils/grpc/grpc.go, conformance/utils/suite/suite.go
/kind bug
Returns the GRPCRoute conformance tests default client to instantiating a new client for every request, instead of creating one shared client for all requests, as this is leading to conflicts and closed client connections. More details in the issue: https://github.com/kubernetes-sigs/gateway-api/issues/3122
Fixes #3122 
```release-note
NONE
```
=> Return the behaviour of a new default GRPC client instantiation for every request

conformance/apis/v1/groupversion.go, conformance/utils/suite/suite.go
/kind bug
With the graduation of the conformance test suite we bumped the `ConformanceReport` API to v1. However, we did not change the `APIVersion` of the reports created by the suite accordingly. The result was that we were creating v1 reports with v1alpha1 set as `APIVersion`. This PR fixes such a problem.
Fixes #
```release-note
The generated conformance report API version is set to v1 instead of v1alpha1.
```
=> fix: change report API version

examples/standard/basic-grpc.yaml, examples/standard/grpc-filter.yaml, site-src/api-types/grpcroute.md, site-src/api-types/httproute.md
/kind cleanup
Docs clean up:
- bump `GRPC` to `v1` in several doc mentions
- bump `HTTPRoute` to `v1` in several places
- move some related manifests from `experimental` to `standard`
Fixes #
```release-note
NONE
```
=> chore(docs): GRPC and HTTP docs versions cleanup

conformance/reports/v1.1.0/cilium-cilium/README.md, conformance/reports/v1.1.0/cilium-cilium/experimental-1.16-default-report.yaml
https://github.com/kubernetes-sigs/gateway-api/pull/3137 added a new conformance report for Cilium. The report and the README were malformed in the following way:
- the link to the report in the README was broken
- the link to the cilium release was broken; Cilium v1.16.0 has not been released at the moment of writing yet, therefore I've set here the rc1 link.
- the version of the report was not set and instead was "main". Since the report was for Cilium version 1.16.0, I changed it to 1.16.0.
Once Cilium 1.16.0 gets released, we need to update this report again with the GH link to the new release.
Fixes # …
=> chore: fix cilium conformance report

geps/gep-995/index.md, geps/gep-995/metadata.yaml, mkdocs.yml
/kind gep
Changes the state of GEP-995 to `Implementable`, given it's in the [scope for v1.2](https://github.com/kubernetes-sigs/gateway-api/discussions/3103#discussioncomment-9505850).
I'll leave the next step of flagging the GEP at `Experimental` to/post #2985.
```release-note
NONE
```
=> Move GEP-995 to Implementable

apis/v1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind bug
remove unnecessary S in ProtocolType validation
Fixes #
```release-note
NONE
```
=> remove unnecessary S in ProtocolType validation

hack/api-docs/pkg.tpl
PR #1345 assumed there would be two versions of the API for the "[API Specification](https://gateway-api.sigs.k8s.io/reference/spec/)" doc page. Now we have 4 versions, and 2 are left out (v1beta1 and v1alpha3). This is a quick fix, but this will break every API version release. We should pursue a more sustainable solution.
N/A
```release-note
NONE
```
=> docs: Fix missing v1beta1, v1alpha3 API versions

gwctl/cmd/subcommand.go, gwctl/pkg/printer/backends.go, gwctl/pkg/printer/common.go, gwctl/pkg/printer/gatewayclasses.go, gwctl/pkg/printer/gateways.go, gwctl/pkg/printer/httproutes.go, gwctl/pkg/printer/httproutes_test.go, gwctl/pkg/printer/namespace.go, gwctl/pkg/resourcediscovery/discoverer.go, gwctl/pkg/resourcediscovery/nodes.go, gwctl/pkg/resourcediscovery/resourcemodel.go, gwctl/pkg/resourcediscovery/resourcemodel_test.go
/kind feature
This PR builds upon the great work by @tdn21 in https://github.com/kubernetes-sigs/gateway-api/pull/3071. I've rebased, added a new commit adding the requested tests and made some minor changes.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/3037
```release-note
The output of `gwctl describe httproute <NAME>` now includes more details
```
/assign @mlavacca 
/cc @tdn21
=> [gwctl] Expand the output of gwctl describe httproute

hack/update-codegen.sh
/kind bug
`uname -o` isn't supported on Mac. Here is the output of `man uname`:
```
UNAME(1)                                                           General Commands Manual                                                          UNAME(1)
NAME
uname – Print operating system name
SYNOPSIS
uname [-amnprsv]
DESCRIPTION
The uname utility writes symbols representing one or more system characteristics to the standard output.
The following options are available:
-a      Behave as though all of the options -mnrsv were specified.
-m      print the machine hardware name.
-n      print the nodename (the nodename may be a name that the system is known by to a communications network).
-p      print the machine processor …
```
=> make update-codegen.sh runnable on Mac

conformance/tests/gateway-infrastructure.go, conformance/tests/gateway-infrastructure.yaml, geps/gep-1867/index.md, geps/gep-1867/metadata.yaml, pkg/features/features.go
/kind test
Adds conformance tests to move in-cluster Gateway deployments GEP to standard
Part of #1762
```release-note
NONE
```
=> Add conformance tests for in-cluster Gateway infrastructure

hack/api-docs/type.tpl
Removes an extra `</p>` in the header of alias types.
For instance, `HTTPRoute` looks like this: 
However, `AddressType`, which is an alias for `string`, looks like this: 
With the fix: 
```release-note
NONE
```
=> Remove extra spacing in the API Specification aliases

apis/v1/shared_types.go, config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, geps/gep-1619/index.md, pkg/test/cel/backendlbpolicy_test.go
/kind bug
This PR scope out the header based session persistence from the validation `AbsoluteTimeout must be specified when cookie lifetimeType is Permanent`.
See https://github.com/kubernetes-sigs/gateway-api/issues/3214.
Fixes #3214
```release-note
NONE
```
=> fix: allow the header based session persistence not to have AbsoluteTimeout

geps/gep-1016/index.md, mkdocs.yml
GEP-1016 (`GRPCRoute`) was still marked as Experimental, even though it's been moved to standard since v1.1 🤯 
/kind bug
/kind cleanup
/kind gep
Updates the GRPCRoute GEP to show it's standard 
Also fixed a spacing issue where the sub bullet points were not rendering on the site
Fixes #
```release-note
```
=> Update GRPCRoute GEP to standard

conformance/reports/v1.1.0/envoy-gateway/README.md, conformance/reports/v1.1.0/envoy-gateway/experimental-v1.1.0-default-report.yaml
Add v1.1.0 conformance report for envoy gateway v1.1.0
```release-note
NONE
```
=> Add v1.1.0 conformance report for envoy gateway v1.1.0

OWNERS_ALIASES
As per the [mailing list discussion](https://groups.google.com/g/kubernetes-sig-network/c/nFN64I33zUo), this adds @mlavacca as a Gateway API maintainer.
=> docs: add Mattia Lavacca as Gateway API maintainer

conformance/reports/v1.1.0/envoy-gateway/experimental-v1.1.0-default-report.yaml
Refer: https://github.com/envoyproxy/gateway/pull/3976
```release-note
NONE
```
=> Update EG v1.1 conformance report

geps/overview.md
/kind cleanup
declined status is listed twice so I'm combining them into one
```release-note
NONE
```
=> fix: deduplicate Declined status

geps/gep-1731/index.md, geps/gep-1731/metadata.yaml, mkdocs.yml
/kind gep
Proposes configuration within HTTPRoute to retry unsuccessful requests to backends before sending a response to a client.
Fixes #1731 
```release-note
Adds `retry` stanza within HTTPRouteRule to configure retrying unsuccessful requests to backends before sending a response to a client.
```
=> gep: add GEP-1731 Configurable Retries

OWNERS_ALIASES
@kflynn has been highly active and involved in the community for some time, particularly as a GAMMA lead. We asked if he would be interested in joining the GEP reviewers to help us with incoming and maturing features and he graciously agreed. Thank you Flynn!
/cc @mlavacca @robscott @youngnick
=> docs: add Flynn as a GEP reviewer

conformance/utils/config/timeout.go, conformance/utils/suite/suite.go
It reduces the flakiness of running conformance tests sequentially. Because some test cases reuse the same Gateway and the same Service, and have the similar path matcher, it may need longer time to fully clean up the resources.
N/A
```release-note
NONE
```
=> Add timeout between conformance test cases

conformance/reports/v1.1.0/gke-gateway/README.md, conformance/reports/v1.1.0/gke-gateway/standard-1.30.3-gxlb-report.yaml, conformance/reports/v1.1.0/gke-gateway/standard-1.30.3-rilb-report.yaml, conformance/reports/v1.1.0/gke-gateway/standard-1.30.3-rxlb-report.yaml, site-src/implementations.md
Add conformance report for GKE Gateway v1.1
N/A
```release-note
None
```
=> Add GKE Gateway v1.1 conformance report

OWNERS_ALIASES
@arkodg has been a long time and very active contributor, and has agreed to take on a GEP reviewer role! Thank you, and thank you for all your work on Gateway API Arko!
/cc @mlavacca @robscott @youngnick
=> Add Arko as GEP Reviewer

apis/v1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, geps/gep-1742/index.md, geps/gep-1742/metadata.yaml, geps/gep-2257/index.md, geps/gep-2257/metadata.yaml, mkdocs.yml, pkg/generated/openapi/zz_generated.openapi.go
/kind gep
**REVIEWERS**: this PR has been rebased to be best reviewed commit by commit:
- 905d8060: Actually move from experimental to standard
- 767798b0: Fix a couple of old typos in GEP-1742
- 30d9acbd: Clean up language in GEP-2257 around repeated units
- dcc24383: Mention GEP-2257 in the CRD docstrings (I ran into this today for unrelated reasons) and clarify that if the backend request timeout isn't specified, behavior is implementation-specific.
- fc64635e: Run `make generate`
This PR moves GEPs 2257 and 1742 to Standard rather than Experimental. Conformant implementations of `HTTPRouteRequestTimeout` and `HTTPRouteBackendTimeout` as of Gateway API v1.0.0:
- Cilium v1.15.0-pre.3
- Contour v1.29.0
- Envoy Gateway …
=> Graduate GEP-2257 and GEP-1742 to standard

conformance/reports/README.md
After discussing the possibility of accepting partial reports in https://github.com/kubernetes-sigs/gateway-api/pull/3021, we eventually decided to encourage implementations to start submitting reports even if there is no full conformance. This PR updates the documentation to reflect this final decision.
Fixes #
```release-note
NONE
```
=> docs: partial reports can be submitted

gwctl/pkg/printer/backends.go, gwctl/pkg/printer/backends_test.go, gwctl/pkg/printer/gateways.go, gwctl/pkg/printer/gateways_test.go
/kind feature
Add inherited policies for Gateway and Backends. Refer test cases for sample outputs
/hold
```release-note
Describing Gateways and Backends will include a separate field showing InheritedPolicies
```
=> Add inherited policies for Gateway and Backends

hack/verify-reports.sh
Recently, many submitted reports were not compliant with the rules stated in [this document](https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/reports/README.md). This PR aims to create a script to automatically check the correctness of the uploaded reports and the structure. The following are the checks performed:
- a README file exists in the project conformance page
- such a README does not contain broken links
- the reports are named according to the pattern `<experimental | standard>-<semver>-<mode>-report.yaml`
- the project `version` is a valid semver
- the `GatewayAPIVersion` field matches the folder in which the report has been created
- the `GatewayAPIChannel` is either …
=> chore: added hack/verify-reports.sh script

apis/applyconfiguration/apis/v1/grpcheadermatch.go, apis/v1/grpcroute_types.go, apis/v1/zz_generated.deepcopy.go
/kind bug
This pull request fixes the GRPC header match type used in the `GRPCHeaderMatch` struct to `GRPCHeaderMatchType` instead of using the `HeaderMatchType` from `HTTPRoute`.
NA
```release-note
NONE
```
=> Use GRPCHeaderMatchType in GRPCHeaderMatch structure

apis/v1/gatewayclass_types.go, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
/kind bug
This PR ensures that always `Pending` is set as a default reason for the status condition `Accepted` of a new GatewayClass.
Fixes #3225 
```release-note
The default reason for GatewayClass status condition Accepted is always set to Pending.
```
=> fix: inconsistent default reason for GatewayClass status (#3225)

conformance/reports/v1.1.0/cilium-cilium/experimental-1.16-default-report.yaml
The previous version didn't show extended features properly for few conformance profiles (e.g. GATEWAY-TLS, GATEWAY-GRPC, etc). It seems like if extempt-features flag is used, none of extended features will show up in the report, hence I just use skip-test instead.
NA
```release-note
NONE
```
=> conformance: Update Conformance report

site-src/contributing/devguide.md
As a new contributor, I reviewed the Dev Guide and would like to clarify a few points I encountered while following it. I've made some structural adjustments and added a few pieces of content. I know that this may have some personal opinions, so I'm open to any feedback or comments. 
Fixes #3260 
NONE
Dear reviewers, 
You can check the latest changes at [here](https://deploy-preview-3261--kubernetes-sigs-gateway-api.netlify.app/contributing/devguide/).
=> issue-3260: Clarify a few points on Development Documentation.

conformance/utils/roundtripper/roundtripper.go
/kind test
This PR exposes the peer certificates from the http response in round tripper.
Fixes #https://github.com/kubernetes-sigs/gateway-api/issues/3020
```release-note
NONE
```
=> Expose peer certificates in round tripper response

hack/verify-all.sh
/fixed bugs
This PR explicitly tells which script has an issue in a failed test
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/3282
=> Update verify-all.sh:  added $t to explicitly tell which script had an issue during a failed test

pkg/utils/duration.go, pkg/utils/duration_test.go
Per GEP 2257, adding duration utils for [implementing GEP2257 duration format ](https://gateway-api.sigs.k8s.io/geps/gep-2257/)
/kind feature 
(not sure if this is the right kind for this 😅 )
Per GEP 2257 Duration formatting's [next step to graduation](https://gateway-api.sigs.k8s.io/geps/gep-2257/#graduation-criteria) is implementing parsers. Helping out with this push to standard channel 👍 
Fixes #
Related PRs: 
- https://github.com/kube-rs/gateway-api-rs/pull/45
- https://github.com/kubernetes-client/python/pull/2261
```release-note
NONE
```
cc: @kflynn
=> GEP2257 Duration parsing

OWNERS_ALIASES
@candita has been active in the Gateway API community, a driver behind GEPs like BackendTLSPolicy, and has agreed to help out further as a conformance reviewer! This PR adds her to the list of conformance reviewers, thank you so much for your help and contributions @candita!
=> docs: add candita as conformance reviewer

conformance/reports/v1.1.0/nginxinc-nginx-gateway-fabric/README.md, conformance/reports/v1.1.0/nginxinc-nginx-gateway-fabric/experimental-1.4.0-default-report.yaml
Updates conformance profile for NGINX Gateway Fabric.
```release-note
NONE
```
=> Add conformance profile for NGINX Gateway Fabric

OWNERS_ALIASES
@guicassolato has been working diligently on Policy Attachment and Metaresources as part of the [Kuadrant](https://github.com/Kuadrant) project. That project is heavily invested in Policy Attachment, and as such `gwctl` is important to them. He has agreed to help out with some of the review for `gwctl` going forward, which is greatly appreciated! Thank you @guicassolato!
=> docs: add guicassolato as gwctl reviewer

apis/applyconfiguration/apis/v1/gatewayinfrastructure.go, apis/v1/gateway_types.go, apis/v1/shared_types.go, apis/v1/zz_generated.deepcopy.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, pkg/test/cel/gateway_experimental_test.go
/kind feature
(see the discussion in #3197)
Fixes #3197 
```release-note
Label keys and values are validated according to the Kubernetes specification
```
=> Validation for label keys and values according to Kubernetes specification

geps/gep-3155/index.md
This commit adds the missing backtick to the gep-3155 index.md to fix markdown rendering.
/kind cleanup
This is a quick cleanup PR that adds the missing backtick to json field tag in the gep-3155's index.md. This fixes markdown rendering of this GEP when viewed in the UI or an IDE that supports markdown previewing.
Fixes #
```release-note
NONE
```
=> geps: Add the missing trailing backtick to gep-3155

Makefile, hack/test-crds-validation.sh, hack/verify-all.sh
/kind test
CEL validation tests are run against multiple clusters having different K8S versions
Fixes #3206 
```release-note
NONE
```
=> feat: cel validation on multiple K8S versions

conformance/utils/suite/profiles.go
/kind cleanup
Fix typo in MESH-GRPC conformance test profile name
Fixes #
```release-note
NONE
```
=> Fix typo in MESH-GRPC conformance test profile name

pkg/test/cel/backendlbpolicy_test.go, pkg/test/cel/backendtlspolicy_test.go, pkg/test/cel/gateway_experimental_test.go, pkg/test/cel/gateway_test.go, pkg/test/cel/gatewayclass_test.go, pkg/test/cel/grpcroute_test.go, pkg/test/cel/httproute_test.go, pkg/test/cel/main_test.go
/kind cleanup
As @mlavacca discovered in #3316, our CEL tests were failing in v1.28+. Fortunately it was just a variety of changes to how error messages are presented to users. I've also tested these changes against v1.27 and v1.29.
```release-note
NONE
```
/cc @gauravkghildiyal @jpbetz
=> Fix CEL tests for v1.28+

conformance/apis/v1/conformancereport.go, conformance/conformance.go, conformance/tests/udproute-simple.go, conformance/utils/flags/flags.go, conformance/utils/suite/conformance.go, conformance/utils/suite/reports.go, conformance/utils/suite/suite.go, conformance/utils/suite/suite_test.go
/kind feature
Fixes #3009 
```release-note
Conformance tests include a new Provisional field that signals the specific test's stability level. The conformance report has been updated to include which provisional tests have been successfully executed by the implementation. 
```
=> Signal test stability

conformance/conformance.go, conformance/utils/suite/suite.go
/kind test
/kind bug
/kind cleanup
pass options to the Kubernetes client to allow for things like schema and mapper.
Fixes #3342
```release-note
NONE
```
=> chore: add conformance suite client options

conformance/tests/gateway-with-attached-routes-with-port-8080.yaml
We had two tests that used an HTTPRoute called "http-route-4" which caused flaky tests because the first test's delete can (and sometimes does) happen after the second test's create, which means that the order of operations was:
1. create http-route-4
1. run first test
1. cleanup first test - queue a delete of http-route-4
1. set up second test - what should have been a create of http-route-4 becomes an update
1. delete from first test deletes http-route-4
1. second test fails
/kind bug
This is a rebase of https://github.com/kubernetes-sigs/gateway-api/pull/3348 onto the main branch.
Fixes #
```release-note
NONE
```
=> Fix conformance test race condition

RELEASE.md
```release-note
NONE
```
Updates the release process documentation to match the actual current state.
=> Update release docs with new details

conformance/tests/gateway-infrastructure.go
/kind test
-->
The test expects generated Gateway resources to
have the `gateway.networking.k8s.io/gateway` label set. Mark the test as provisional until these statements have moved into the API docs.
Relates to https://github.com/kubernetes-sigs/gateway-api/issues/3366#issuecomment-2384566059
```release-note
NONE
```
=> mark the GatewayInfrastructure test as Provisional

CHANGELOG/1.2-CHANGELOG.md, README.md, RELEASE.md, config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml, conformance/utils/suite/suite_test.go, pkg/consts/consts.go
This adds the changelog for v1.2.0. Merging this PR will kickoff the v1.2.0 release process.
```release-note
NONE
```
/assign @mlavacca @shaneutt @youngnick 
/hold
=> Adding changelog for v1.2.0

apis/v1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, pkg/generated/openapi/zz_generated.openapi.go
=> docs: fix a typo

site-src/guides/backend-protocol.md
/gep
Docs changes for backend protocol selection for Gateway Release v1.2
Part of https://github.com/kubernetes-sigs/gateway-api/issues/1911
```release-note
NONE
```
=> Drop experimental banner for backend-protocol selection

apis/v1/shared_types.go, pkg/generator/main.go
/kind feature
This PR adds a new tag `gateway:util:excludeFromCRD` in CRD description which allows to exclude comments in the go struct from being included in the generated CRD, preventing unnecessary clutter in the CRD specification.
Fixes #3306 
```release-note
NONE
```
/cc @LiorLieberman @robscott
=> feat: Exclude comments from CRD generation but not from go struct definition

apis/v1alpha2/grpcroute_types.go, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
/kind bug
/kind regression
Replace the kubebuilder flags for GRPCRoute v1alpha2 so that they're the same as v1. Also restore the additional printer columns.
Fixes #3411.
```release-note
Make GRPCRoute v1alpha2's status a subresource again, as it should be, and restore the previous additional printer columns.
```
=> Make GRPCRoute v1alpha2's status a subresource

geps/gep-713/index.md
Clarify why the older policy wins in GEP 713
Fixes #3434
```release-note
NONE
```
=> Clarify why the older policy wins in GEP 713

site-src/mesh/index.md
I've always been confused as to where the dangling link on this page went to, so [I've found out](https://github.com/kubernetes-sigs/gateway-api/blob/7b9876e1f1a513304bdb92e93125eb345b7b9c40/site-src/concepts/gamma.md?plain=1#L99) and recreated the heading.
I considered removing the link instead, but it makes more sense in terms of the table of contents to break this section up from the "request flow" section below and the summary above.
```release-note
NONE
```
=> Fix link in Mesh page

apis/v1/gatewayclass_types_overrides.go, apis/v1/gatewayclass_types_test.go, pkg/generated/openapi/zz_generated.openapi.go
I messed up the branch name so disregard it.
/kind bug
This change is following an issue with the breaking change we introduced in https://github.com/kubernetes-sigs/gateway-api/pull/3200/. 
Issue link - https://github.com/istio/istio/issues/53846
I added unitests which hopefully provide enough coverage but happy to add more tests if you have ideas.
Fixes #3464 
```release-note
Add backward compatibility for the older version of SupportedFeature
```
/cc @howardjohn @youngnick @mikemorris @robscott
=> override unmarshalJSON for supportedfeature to ensure comptability

geps/gep-713/index.md
Signed-off-by: Flynn <emissary@flynn.kodachi.com>
Clean up the parable in GEP-713 to use the name "Chihiro", as it
should since we long ago stopped using "Charlie". 🤦‍♂️ 
/kind gep
```release-note
NONE
```
=> Switch the GEP-713 parable to refer to Chihiro.

site-src/contributing/devguide.md
**What this PR does / why we need it**: This PR is just to fix a broken link
Fixes #3451 
```release-note
NONE
```
=> docs: fix project dashboard link

site-src/api-types/httproute.md
> Rules- Define a list of rules to perform actions against matching HTTP requests. Each rule consists of matches, filters (optional), backendRefs (optional), timeouts (optional), and [name][name] (optional) fields.
In this line, the link called `name` is not added.
Fixes #
```release-note
NONE
```
=> Update httproute.md to add link for v1.SectionName

geps/gep-696/index.md
Align GEP template conformance tests guidance with GEP-2162
```release-note
NONE
```
/cc @youngnick
=> Update GEP template with up to date conformance tests guidance

hack/test-crds-validation.sh, pkg/test/cel/main_test.go
/kind test
Kind is bumped to 0.26 and the tested kubernetes versions now are:
- 1.32.0
- 1.31.4
- 1.30.8
- 1.29.12
- 1.28.15
Fixes #
```release-note
NONE
```
=> chore: bump Kind and test k8s 1.28->1.32

geps/gep-1494/index.md, geps/gep-1494/metadata.yaml, mkdocs.yml
/kind gep
This is to get the conversation started around Auth* in Gateway API. Hopefully this part should not be too contentious yet, but reviews gratefully accepted.
Updates #1494
=> Add initial draft of Auth GEP 1494

apis/v1/gatewayclass_types.go
The description for the `GatewayClassReasonInvalidParameters` `GatewayClass` reason has been improved.
Fixes #
```release-note
NONE
```
=> docs: improve GWC `GatewayClassReasonInvalidParameters` reason description

geps/gep-91/index.md
The intention is to imply frontend/backend configuration are orthogonal, not mutex.
=> Clarify frontend/backend relationship in GEP-91.

conformance/tests/httproute-request-mirror.go, conformance/tests/httproute-request-multiple-mirrors.go, conformance/tests/httproute-request-percentage-mirror.go, conformance/tests/httproute-request-percentage-mirror.yaml, conformance/utils/http/http.go, conformance/utils/http/mirror.go, conformance/utils/kubernetes/logs.go, geps/gep-3171/index.md, pkg/features/httproute.go
/kind test
Conformance tests for #3171 plus small updates to the GEP. 
Tested with istio 1.24.1
Note: I also added a test case for fraction but it looks like it has an issue currently with the implementation I used (istio). 
The specific test is failing, (which is good) so I think its in a good merge state. I also opened https://github.com/istio/istio/issues/54357. 
Mesh tests to follow
Fixes #3171 
```release-note
NONE
```
/cc @jakebennert @robscott
=> conformance tests for percentage-based request mirroring

geps/gep-1731/metadata.yaml, geps/gep-3388/index.md, geps/gep-3388/metadata.yaml, mkdocs.yml
/kind gep
To seek consensus on the ideal configuration of a "retry budget" in HTTPRoute, allowing application developers to dynamically limit the rate of client-side retries to their service based on a percentage of the active request volume.
Extends #1731
Fixes #3388
```release-note
NONE
```
=> gep: add GEP-3388 HTTP Retry Budget

geps/gep-1713/index.md, geps/gep-1713/metadata.yaml
This replaces https://github.com/kubernetes-sigs/gateway-api/pull/1863 
/kind gep
Outlines a mechanism to merge Gateway Listeners
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1713
```release-note
NONE
```
=> GEP-1713: ListenerSets - Standard Mechanism to Merge Gateway Listeners (rev 2)

geps/gep-3567/index.md, geps/gep-3567/metadata.yaml
/kind gep
This is a relatively small GEP that may not need to be a GEP, but creating one for the purpose of record keeping. Hoping to get at least A and B in v1.3. This is tracked by #3567.
```release-note
NONE
```
=> Adding GEP-3567: Gateway TLS Updates for HTTP/2 Connection Coalescing

config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, pkg/generator/main.go
/kind cleanup
The standard CRD still contains <gateway:experimental:description> as the Custom Gateway API Tweaks in the descriptions of items are not processed. In addition, the descriptions contain many extra newlines, which cause them to fail the yaml-lint check (https://github.com/adrienverge/yamllint/blob/master/yamllint/rules/empty_lines.py).
None
```release-note
NONE
```
=> Remove extra newlines and format descriptions of items

apis/v1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, pkg/generated/openapi/zz_generated.openapi.go
For the Gateway infrastructure stanza, the `InvalidParameters` reason SHOULD be used with the `Accepted` condition in case the object referenced does not exist, is of an unsupported kind, or is malformed.
Fixes #
```release-note
For the Gateway infrastructure stanza, the `InvalidParameters` reason SHOULD be used with the `Accepted` condition in case the object referenced does not exist, is of an unsupported kind, or is malformed.
```
=> docs: setting proper reason for Gateway `parametersRef` `Accepted` condition

site-src/implementations.md
```release-note
NONE
```
/cc @kflynn @mlavacca @robscott
=> remove "experimental" language from gamma implementations

geps/gep-696/index.md
Adding a dedicated section for Gateway For Mesh to the GEP template as part of #3566 
```release-note
NONE
```
=> Add Gateway For Mesh section to the GEP template

apis/v1/object_reference_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, pkg/generated/openapi/zz_generated.openapi.go
Fixes #3322 
```release-note
NONE
```
=> fix: group description in `LocalObjectReference` 

conformance/reports/v1.2.1/cilium-cilium/README.md, conformance/reports/v1.2.1/cilium-cilium/experimental-1.17-default-report.yaml
Fixes #
```release-note
NONE
```
=> conformance: Add Cilium report for 1.2.1

site-src/guides/grpc-routing.md, site-src/guides/index.md
GRPCRoute is GA and has been included in the standard channel since v1.1.0.
Removes the experimental callout on GRPCRoute guide because is now GA and included in the standard channel as of 1.1.0.
Fixes #
```release-note
NONE
```
=> Remove experimental callout on GRPCRoute guide.

pkg/test/cel/grpcroute_experimental_test.go, pkg/test/cel/httproute_experimental_test.go
/kind cleanup
Fixes #3602 
```release-note
NONE
```
=> chore: fmt

site-src/api-types/grpcroute.md
According to the definition of [grpcroute v1](https://github.com/kubernetes-sigs/gateway-api/blob/f5b5bab2f1928dfee0ec8e0fc065ee879240f7e4/apis/v1/grpcroute_types.go#L394), the `matches[index].headers` structure in the [document](https://gateway-api.sigs.k8s.io/api-types/grpcroute/#matches) is incorrectly defined.
In addition, should the structure definition [here](https://gateway-api.sigs.k8s.io/api-types/grpcroute/#matches) be adjusted to:
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
...
spec:
rules:
- matches:
- method:
service: com.example.User
method: Login
headers:
- name: version
value: "2"
- method:
service: com.example.v2.User
method: Login
```
**Which issue(s) this PR …
=> fix(grpcroute-doc): fix grpcroute structure definition error in the document

apis/openapi/zz_generated.openapi.go, apis/v1alpha3/backendtlspolicy_types.go, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml, geps/gep-3155/metadata.yaml
Given the not triviality of supporting this feature for nginx-based implementations (such as Kong) and the fact that this feature is not mandatory to ensure core functionality in the proxy->backend encrypted communication, we can set the `SANs` field of the `BackendTLSPolicy` API as an extended feature.
/cc @robscott @shaneutt @youngnick @LiorLieberman @candita 
Fixes #
```release-note
The SANs field of `backendTLSPolicy` has been marked as an extended feature.
```
=> BackendTLSPolicy SANs field marked as extended

conformance/utils/kubernetes/helpers.go
The test helper NamespacesMustBeReady must retry if fails to list the existing gateways or pods, otherwise it may declare that the namespaces are ready without actually checking them.
/kind bug
/kind test
/kind flake
```release-note
NONE
```
/assign @robscott
=> retry failed calls when waiting for namespace ready

mkdocs.yml
This commit updates the list of GEPs displayed in the site's navigation sidebar to add missing GEPs, or move GEPs to accurately reflect their current state.
**Added**
* GEP-1767: Provisional
* GEP-3567: Implementable
**Moved**
* GEP-91: Provisional -> Implementable
* GEP-1867: Provisional -> Standard
* GEP-2649: Provisional -> Experimental
* GEP-3155: Implementable -> Experimental
* GEP-3388: Provisional -> Implementable
```release-note
NONE
```
=> docs: Update GEPs in navbar

site-src/api-types/grpcroute.md
fix(docs): grpcroute name is not set
source: https://gateway-api.sigs.k8s.io/api-types/grpcroute/#spec
```release-note
NONE
```
=> fix(docs): grpcroute name is not set

apis/v1/grpcroute_types.go, apis/v1/httproute_types.go, config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, geps/gep-3171/index.md, geps/gep-3171/metadata.yaml, mkdocs.yml, pkg/generated/openapi/zz_generated.openapi.go
/kind cleanup
Promote Percentage Based Request mirroring to standard
```release-note
promote percentage-based-request-mirroring to standard
```
=> Promote GEP 3171 - Percentage Based Request mirroring to standard

site-src/implementations.md
Avi Kubernetes Operator(AKO) 1.13.1 now supports Gateway API v1.0.0. This PR includes version changes and documentation link changes in the list of implementations for AKO
Fixes #
```release-note
NONE
```
=> Update Avi Kubernetes Operator (AKO) versions in the list of Gateway API implementations

site-src/faq.md, site-src/index.md
This site offers a comparison of an API Gateway with the Gateway API, with a very broad definition, which defines almost any ingress system or edge router as an API gateway, regardless of whether the traffic passing through it is user- or machine-facing.
The industry tends towards a more narrow definition, which is well-captured by the CNCF Glossary.  I've copied that language into the index and FAQ pages and added a link to the glossary.
```release-note
Updates comparison of Gateway API and API Gateway to use the CNCF's definition of the latter.
```
=> align API Gateway definition with CNCF Glossary

mkdocs.yml, site-src/overrides/partials/copyright.html
This PR contains several commits that resolve info and warning messages that are currently being logged by MkDocs when building the site.
* Ignore certain files from nav config
* Fix warning for invalid 'trademark' config
* Update pymdownx.emoji extensions
* Fix nav error in mkdocs.yml
More information about these changes can be found in the commit message for each commit.
Fixes #
```release-note
NONE
```
=> docs: Fix several MkDocs info and warning messages

conformance/reports/v1.2.1/envoy-gateway/README.md, conformance/reports/v1.2.1/envoy-gateway/experimental-v1.3.0-default-report.yaml, conformance/reports/v1.2.1/envoy-gateway/experimental-v1.3.1-default-report.yaml
=> v1.2.1 conformance report for Envoy Gateway

apis/v1/httproute_types.go, apis/v1/shared_types.go, apis/v1/zz_generated.deepcopy.go, applyconfiguration/apis/v1/httpcorsfilter.go, applyconfiguration/internal/internal.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, pkg/generated/openapi/zz_generated.openapi.go
/kind bug
Fixes #3650
```release-note
change `HTTPRouteFilter.CORS.AllowCredentials` to expect a boolean and not a string
```
=> fix: turn `allowCredentials` to boolean

.gitignore, hack/mkdocs-copy-geps.py, hack/mkdocs-generate-conformance.py, netlify.toml
When developing and previewing docs using `mkdocs serve`, the site gets stuck into an endless build loop when any content is changed. This is caused by two hooks that copy content into the site-src/ directory on site build, `mkdocs-copy-geps.py` and `mkdocs-generate-conformance.py`, triggering another build due to the changed content.
The solution is to use MkDocs Files API to programmatically add the files into the site instead of copying them into the site directory.
See mkdocs/mkdocs#2544 for more information.
Fixes #
```release-note
NONE
```
=> docs: Fix 'mkdocs serve' endless build loop

mkdocs.yml
GEP-1713 was previously listed under provisional in the website, but PR #3588 moved it to experimental.
Related to #1713
```release-note
NONE
```
=> GEP-1713: Move Website GEP Link to Experimental

requirements.txt
/kind cleanup
The [mkdocs-material-extensions](https://github.com/facelessuser/mkdocs-material-extensions) package is now deprecated, and it's usage in mkdocs.yaml was removed in #3663. This fix also removes it from requirements.txt to prevent unnecessary installation.
N/A
```release-note
NONE
```
CC: @blake
=> Remove mkdocs-material-extensions from requirements.txt

apis/v1/grpcroute_types.go, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml, pkg/test/cel/grpcroute_test.go
/kind feature
Fixes #3511 
-->
```release-note
Increase the `GRPCRoute` matchs limit from 8 -> 64
```
=> feat: increase `GRPCRoute` matches limit

conformance/base/manifests.yaml
/kind bug
This PR fixes conformance test when running on certain kubernetes distributions with stricter policies. The coredns deployment required by some tests would fail to start due to missing `NET_BIND_SERVICE` capability
-->
```release-note
NONE
```
=> Fix conformance coredns deployment

apis/v1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
/kind bug
Fixes #3647
```release-note
Doesn't allow a user to provide both an asterisk and another method/s along with it in `HTTPCORSFilter.AllowMethods`
```
=> fix: validate that a method and a wildcard won't appear together

geps/gep-2907/index.md
/kind gep
This PR supersedes #3190.
This PR updates GEP-2907 with two different aspects:
- definition of TLS mode (Terminate and Passthrough)
- what routes can be attached to Listeners that specify TLS configuration.
A key takeaway and most discussed point of this PR is allowing TLS termination for TLSRoute. A lot of context can be found in https://github.com/kubernetes-sigs/gateway-api/issues/2111 and https://github.com/kubernetes-sigs/gateway-api/pull/3458#discussion_r1935423388. The needs of this feature boils down to "I want to route L4 and L7 traffic on the same listener, and I want to route L4 traffic based on hostname."
This PR intends to reach an agreement that will make …
=> Gep 2907 update - TLS mode and allowed routes

conformance/utils/http/mirror.go
/kind test
/kind flake
Currently the Conformance Tests for request mirroring are flaky because the mirrored request can sometimes not be found in the log of the Pods.
```
Test:       	TestConformance/HTTPRouteRequestMultipleMirrors/1_request_to_'/multi-mirror-and-modify-request-headers'_with_headers_should_go_to_infra-backend-v1
Messages:   	Couldn't find mirrored request in "gateway-conformance-infra/infra-backend-v3" logs
```
The issue is that the logic that fetches the Pod log (`ExpectMirroredRequest`) uses the current time (`time.Now()`) on every assertion-attempt as the `sinceTime` parameter.
As a consequence, the assertion can miss messages from the Pods that have been logged between the assertion …
=> conformance-tests: fix flake in ExpectMirroredRequest

conformance/tests/httproute-request-percentage-mirror.go
Reverts part of https://github.com/kubernetes-sigs/gateway-api/pull/3508. This was a new change in 1.3
See https://github.com/kubernetes-sigs/gateway-api/pull/3708; Envoy impl cannot meet this fine grain threshold.
Fixes #
```release-note
NONE
```
=> Revert change to mirror threshold

site-src/api-types/httproute.md
Documentation clarification of the `HTTPRouteMatch` rules.
The documentation links to the following example `HTTPRoute`
https://github.com/kubernetes-sigs/gateway-api/blob/3222422bb2124d8cdd072d710ffd2474d99431e1/examples/standard/basic-http.yaml#L25-L57
with a `rules.matches` entry with three elements: `headers`, `queryParams` and `path`.
From the current wording it is unclear if you need to match the `queryParams` criterion or not.
My understand from reading the [**Matches** section](https://gateway-api.sigs.k8s.io/api-types/httproute/#matches) and [**HTTPRouteMatch** documentation](https://gateway-api.sigs.k8s.io/reference/spec/#httproutematch) is that you need to match all criteria (`headers`, …
=> Clarify HTTPRouteMatch rules

apis/v1/gateway_types.go, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind bug
`None` was accidentally added as an option for Route Namespaces as part of the ListenerSet work. This fixes that.
Fixes #3743
```release-note
`None` has been removed as option for Route Namespaces.
```
/cc @howardjohn @dprotaso
=> Removing "None" as option for Route Namespaces

conformance/utils/suite/suite.go
This spams like 60 entries that we are doing no ork - minor change to skip.
Fixes #
```release-note
NONE
```
=> conformance: do not log when we do not sleep

apisx/v1alpha1/xlistenerset_types.go, applyconfiguration/internal/internal.go, config/crd/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml, pkg/generated/openapi/zz_generated.openapi.go
/kind cleanup
We missed this when reviewing the ListenerSet GEP. Although an optional port that would require implementations to assign a port could be legitimately useful, I think we haven't fully processed this concept. Moving this back to required allows us to make it optional in the future, where starting with optional would make it much more painful to transition to required.
Some potential concerns of an optional port on ListenerSet:
* Automatic port allocation could become a bit complicated for Gateway implementations to maintain
* Spec.Listeners.Port would no longer be a reliable source for understanding which Port a Listener was listening on
* Each Listener with an optional Port would _require_ a status entry …
=> Requiring Port number on ListenerSet Listener

apisx/v1alpha1/xbackendtrafficpolicy_types.go, config/crd/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml, pkg/generated/openapi/zz_generated.openapi.go, pkg/test/cel/backendtrafficpolicy_test.go
align comment with field name
Fixes #
```release-note
NONE
```
=> fix typo in BudgetDetails

site-src/api-types/httproute.md
From looking at the API types, it looks like `RouteParentStatus.ParentRef`'s json struct tag is singular, not plural:
https://github.com/kubernetes-sigs/gateway-api/blob/1e14dd602df6c0bad62c0e7f83dd2c7d1d2d6886/apis/v1/shared_types.go#L436-L439
This just updates the docs to match.
N/A
```release-note
NONE
```
=> docs: Update HTTPRoute status example

conformance/tests/mesh/httproute-redirect-host-and-status.go, conformance/tests/mesh/httproute-redirect-host-and-status.yaml, conformance/tests/mesh/httproute-redirect-path.go, conformance/tests/mesh/httproute-redirect-path.yaml, conformance/tests/mesh/httproute-redirect-port.go, conformance/tests/mesh/httproute-redirect-port.yaml, conformance/tests/mesh/httproute-redirect-scheme.go, conformance/tests/mesh/httproute-redirect-scheme.yaml, conformance/tests/mesh/httproute-rewrite-path.go, pkg/features/mesh.go
Add mesh tests for port and scheme redirect
```release-note
Add mesh conformance tests for httproute path host and status redirect
```
=> Add mesh conformance tests for httproute path host and status redirect

apis/v1/httproute_types.go
/kind cleanup
The description of `HTTPHeaderFilter` does not accurately reflect the current CEL validation behavior. This PR corrects the description, as changing the CEL validation itself would be a breaking change.
Fixes #3407
```release-note
NONE
```
=> fix: remove misleading description

conformance/reports/v1.2.1/projectcontour-contour/README.md, conformance/reports/v1.2.1/projectcontour-contour/experimental-v1.31.0-default-report.yaml, site-src/implementations.md
Adds conformance report for new Contour 1.31.0 release which supports Gateway API 1.2.1
N/A
```release-note
NONE
```
=> Add conformance report for Contour 1.31.0

geps/gep-2162/index.md
/kind cleanup
**Which issue(s) this PR fixes:**
Fixes the incorrect description of the naming convention used in the document. Described naming convention is kebab case but document says its pascal case.
**Fixes #**
**Special notes for your reviewer:**
**Does this PR introduce a user-facing change?:**
No
**Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:**
=> Fix typo for the file name case type in GEP-2162 doc.

conformance/reports/v1.3.0/cilium-cilium/README.md, conformance/reports/v1.3.0/cilium-cilium/experimental-main-default-report.yaml
Fixes N/A
```release-note
NONE
```
=> conformance: Add Cilium report for v1.3.0

conformance/utils/suite/suite.go
/kind feature
/kind test
Add hook points support in conformance test suite
Fixes #3131
```release-note
Add hook points support in conformance test suite
```
=> conformance: add Hook in ConformanceTestSuite

site-src/implementations.md
Fixes #
```release-note
Added details about ngrok's Gateway API implementation
```
=> Updating ngrok Gateway API Implementation on Implementations page

conformance/tests/mesh/httproute-request-header-modifier-backend.yaml, conformance/tests/mesh/httproute-request-header-modifier.go, conformance/tests/mesh/httproute-request-header-modifier.yaml, conformance/utils/echo/parse.go, conformance/utils/echo/pod.go, pkg/features/mesh.go
```release-note
Add mesh conformance tests for httproute request header modifier
```
/cc @robscott
=> add mesh conformance for request header modifier

OWNERS_ALIASES
This removes some of the reviewers that have not been active for some time.
=> chore: remove inactive reviewers

conformance/tests/mesh/httproute-weight.go, conformance/tests/mesh/httproute-weight.yaml, conformance/utils/echo/pod.go
```release-note
Add mesh conformance tests for httproute weights routing
```
=> add httproute weight based routing mesh conformance tests

conformance/tests/mesh/httproute-simple-same-namespace.go, conformance/tests/mesh/httproute-simple-same-namespace.yaml
```release-note
Add mesh core conformance tests for httproute same-namespace attachment
```
=> Add mesh core conformance tests for httproute same-namespace attachment

conformance/tests/mesh/httproute-matching.go, conformance/tests/mesh/httproute-matching.yaml
```release-note
Add mesh conformance tests for core httproute matching
```
=> add httproute matching conformance mesh

geps/gep-2627/index.md, geps/gep-2627/metadata.yaml
/kind gep
Adds a draft GEP outlining more on the what and why for supporting DNS configuration as part of Gateway API
Fixes #2627
=>  GEP-2627 DNS Configuration - Initial Provisional PR

conformance/reports/v1.3.0/nginx-nginx-gateway-fabric/README.md, conformance/reports/v1.3.0/nginx-nginx-gateway-fabric/experimental-2.0.0-default-report.yaml
Adding conformance report for the v2.0 NGINX Gateway Fabric release. Now supporting Gateway API v1.3.
Adding conformance report for the v2.0 NGINX Gateway Fabric release. Now supporting Gateway API v1.3.
```release-note
NONE
```
=> Add NGINX Gateway Fabric v2.0 conformance report

conformance/tests/mesh/httproute-query-param-matching.go, conformance/tests/mesh/httproute-query-param-matching.yaml, pkg/features/mesh.go
```release-note
Add mesh conformance for httproute-queryparmas-match
```
=> add mesh conformance for httproute-queryparmas-match

pkg/features/mesh.go
/kind bug
include missing feature in extended mesh tests suite and fixing a typo 
Fixes #
```release-note
NONE
```
=> fix meshredirectport and schemeredirect mesh conformance features

conformance/utils/http/http.go, conformance/utils/roundtripper/roundtripper.go
The conformance testutil roundTripper and http.request does not allow to pass a request body into it.
This PR added the ability to set the request body which is needed in inference-gateway-extention conformance test [PR#961](https://github.com/kubernetes-sigs/gateway-api-inference-extension/pull/961) 
Fixes # N/A
```release-note
NONE
```
=> Add body to http.Request and roundTripper.request to extend conformance testutil ability to send request with body.

geps/gep-3792/index.md, geps/gep-3792/metadata.yaml
/kind gep
What/Why/Who for off-cluster Gateways being able to usefully participate in on-cluster meshes.
Fixes #3792.
```release-note
NONE
```
=> GEP-3792: Off-Cluster Gateways

geps/gep-3793/index.md, geps/gep-3793/metadata.yaml
/kind gep
What/Why/Who for Routes attaching to default Gateways, rather than needing to specify the Gateway.
Fixes #3793.
```release-note
NONE
```
=> GEP-3793: Default Gateways

site-src/contributing/release-cycle.md
This provides a clarifying note for contributors which explains what can happen when GEPs miss a release phase/timeline.
=> docs: note about expectations when a gep misses a release timeline

geps/gep-3792/index.md, geps/gep-3792/metadata.yaml, geps/gep-3793/metadata.yaml, mkdocs.yml
The `metadata.yaml` files for GEP-3792 and GEP-3793 didn't use the correct titles (and, for that matter, neither did `index.md` for GEP-3792...). 🤦‍♂️ 
/kind cleanup
```release-note
NONE
```
=> GEP-3792 and GEP-3793 title fixes :man_facepalming:

site-src/implementations.md
typo about mkdown list and add slack contents at "ngrok-kubernetes-operator"
Fixes #3873
=> docs: fix typo and add contents about "ngrok Kubernetes Operator"

conformance/tests/mesh/httproute-weight.go
Adding entropy to distribution tests as per comment https://github.com/kubernetes-sigs/gateway-api/pull/3827#discussion_r2123121430
This is done by introducing random jitter by adding either a short delay, or adding random header values, or both.
Fixes #3832 
```release-note
Improve mesh conformance distribution tests for httproute weights routing
```
=> Improve distribution tests in conformance for MeshHTTPRouteWeight

OWNERS_ALIASES
/kind cleanup
This adds @LiorLieberman to our Mesh Leads. A huge thanks to Lior for all the work he's been doing to drive Gateway for Mesh forward!
```release-note
NONE
```
**Other Mesh Leads:**
/cc @howardjohn @kflynn @mikemorris 
**Other Maintainers:**
/cc @mlavacca @shaneutt @youngnick 
/hold for a few LGTMs
=> Adding Lior to Mesh Leads

site-src/implementations.md
This PR updates the "Implementations" page with details on what implementations need to do in order to stay a current and registered implementation of Gateway API.
This includes a policy about when implementations will be removed from the page, and adds a Page Review process for the Implementations page.
This follows on and supersedes the discussion on #3814.
After this PR merges, @youngnick will perform the first Page Review process as documented in this update, which will meet the same needs as #3814.
```release-note
NONE
```
=> Update implementations.md with removal policy

mkdocs.yml
Fix a typo in `mkdocs.yml`. Sigh.
/kind cleanup
```release-note
NONE
```
=> Oops. It's GEP-3779, not GEP-3379.

conformance/conformance.go, conformance/utils/suite/suite.go, conformance/utils/suite/suite_test.go, pkg/test/cel/grpcroute_test.go
The conformance suite implementation-related flags are properly validated.
Fixes #2178 
```release-note
The conformance suite implementation-related flags are properly validated.
```
=> feat(conformance): validate implementation flags

apis/v1/grpcroute_types.go, apis/v1/httproute_types.go, config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, conformance/tests/grpcroute-named-rule.go, conformance/tests/grpcroute-named-rule.yaml, conformance/tests/httproute-named-rule.go, conformance/tests/httproute-named-rule.yaml, conformance/tests/mesh/httproute-named-rule.go, conformance/tests/mesh/httproute-named-rule.yaml, geps/gep-995/index.md, geps/gep-995/metadata.yaml, mkdocs.yml, pkg/features/grpcroute.go, pkg/features/httproute.go, pkg/features/mesh.go, pkg/generated/openapi/zz_generated.openapi.go
/kind gep
Moves HTTPRouteRule and GRPCRouteRule `name` fields (GEP-995) to **Standard**.
Fixes #995
```release-note
Promote the `name` field of the HTTPRouteRule and GRPCRouteRule types to Standard.
```
=> Move HTTPRouteRule and GRPCRouteRule 'name' fields to Standard

.custom-gcl.yml, .github/workflows/kal.yml, .golangci-kal.yml, apis/v1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind test
**What this PR does / why we need it**: This PR enables Kube API Linter with a small set of validations. The enabled validations doesn't present a breaking change on existing APIs, and the plan is to progressively enable other linters that may present more disrupting changes on follow up PRs after discussion with Gateway API group.
```release-note
NONE
```
**Note for reviewers**:
The ongoing discussion is part of the document https://docs.google.com/document/d/1DSyP7Vt9E9wX2ku1C0AvCLqQe9cCiDPCLiPP0wXFYQw/edit?tab=t.0 and the thread https://kubernetes.slack.com/archives/CR0H13KGA/p1751923997220399
The proposed changes on this PR contains fix for validations that are not breaking change, and are …
=> Enable Kubernetes API Linter

conformance/apis/v1/conformancereport.go, conformance/utils/suite/conformance.go, conformance/utils/suite/suite.go, conformance/utils/suite/suite_test.go
/kind feature
/kind gep
This is an update from boolean flag to enum for the report that should capture case when Conformance profile is Mesh without GWC and we can't infer supported features.
```
NONE
```
=> [GEP-2162] Updated a new field on supported features inference from boolean to enum and remove from report.

geps/gep-1494/index.md, geps/gep-1494/metadata.yaml
/kind gep
This adds the design rationale and API design for phase 1 of the Auth GEP, adding a Filter to HTTPRoute.
Updates #1494 
```release-note
NONE
```
=> Update Auth GEP with Implementable details

geps/gep-3798/index.md, geps/gep-3798/metadata.yaml
/kind cleanup
/kind gep
As per https://github.com/kubernetes-sigs/gateway-api/discussions/3824 the GEP was not able to meet its timelines, and so is considered deferred for now.
Resolves #3798
=> docs: move GEP-3798 to Deferred for now

geps/gep-3793/index.md, geps/gep-3793/metadata.yaml, mkdocs.yml
Add API description to GEP-3793. I'm sure this'll be totally noncontroversial. 😇 
/kind gep
```release-note
NONE
```
=> API for Default Gateways

geps/gep-3792/index.md, geps/gep-3949/index.md, geps/gep-3949/metadata.yaml, mkdocs.yml
This is a minimal GEP for the Mesh resource existing at all.
/kind gep
Fixes #3949
```release-note
NONE
```
=> Mesh resource definition

site-src/contributing/index.md
Update meeting schedule to reflect the correct alternating weekly pattern:
- Week A: Mondays at 3pm Pacific Time (23:00 UTC)
- Week B: Tuesdays at 8am Pacific Time (16:00 UTC)
This replaces the incorrect information about first Tuesday monthly + weekly Monday meetings.
```release-note
NONE
```
=> Fix Gateway API community meeting schedule documentation

.golangci-kal.yml, apis/v1/gateway_types.go, apis/v1/grpcroute_types.go, apis/v1/httproute_types.go, apis/v1/shared_types.go, apis/v1alpha2/policy_types.go, apis/v1alpha2/tcproute_types.go, apis/v1alpha2/tlsroute_types.go, apis/v1alpha2/udproute_types.go, apis/v1alpha3/backendtlspolicy_types.go, apis/v1alpha3/tlsroute_types.go, apis/v1beta1/referencegrant_types.go, apisx/v1alpha1/xlistenerset_types.go, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml, config/crd/experimental/gateway.networking.k8s.io_gateways.yaml, config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml, config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml, config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml, config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml, config/crd/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml, config/crd/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml, config/crd/standard/gateway.networking.k8s.io_gateways.yaml, config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml, config/crd/standard/gateway.networking.k8s.io_httproutes.yaml, config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml, pkg/generated/openapi/zz_generated.openapi.go
/kind cleanup
Our openapi generator also generates a report of violations of the Kubernetes API best practices. This report is "thrown away" now, but this PR suggests adding it to Git to raise awareness of the importance of API array metadata. ~I have also tried to fix all reported violations in our APIs, but please review carefully!~ UPDATE: For now, all new list type markers are set to `atomic` (default without the marker), and I have created a WIP PR (https://github.com/kubernetes-sigs/gateway-api/pull/3972) for the proposed bugfixes that we can consider after merging this.
I have also reorganized the markers on some of the affected fields, as I think it's clearer to have a consistent order of the markers.
**Which …
=> Fix OpenAPI validations by adding API list markers

geps/gep-1762/index.md
/kind gep
/kind test
This proposes adding an optional new label to generated objects. This is useful for general querying, such as "find the total CPU usage of all pods created by <implementation>".
Fixes #
```release-note
Added a new standardized label `gateway.networking.k8s.io/gateway-class-name` to be added to generated objects. This mirrors the existing `gateway.networking.k8s.io/gateway-name` label.
```
=> Add gateway class label to generated objects

conformance/tests/httproute-weight.go, conformance/tests/mesh/httproute-weight.go, conformance/utils/http/http.go
Adding entropy to distribution tests for HTTPRouteWeight as per comment https://github.com/kubernetes-sigs/gateway-api/pull/3855#pullrequestreview-2928938545
This is done by reusing the entropy method to create jitter in the requests. 
Fixes #3832
```release-note
Improve conformance distribution tests for HTTPRouteWeight
```
=> Improve distribution tests in conformance for HTTPRouteWeight

geps/gep-1767/index.md
Fixes #3988
```release-note
NONE
```
=> fix(docs): remove unnecessary array in incorrect example @ gep-1767

conformance/tests/backendtlspolicy-invalid-ca-certificate-ref.go, conformance/tests/backendtlspolicy-invalid-ca-certificate-ref.yaml, conformance/tests/backendtlspolicy-invalid-kind.go, conformance/tests/backendtlspolicy-invalid-kind.yaml, conformance/tests/backendtlspolicy.go, conformance/utils/echo/pod.go, conformance/utils/http/http.go
/kind test
This test covers the following scenarios:  
- Invalid Kind
- Malformed CA certificate `ConfigMap`  
- Missing (nonexistent) CA certificate `ConfigMap`  
- Valid CA certificate (implemented as part of the normative tests)  
Fixes #3993 
```release-note
NONE
```
=> BackendTLSPolicy conformance tests for ResolvedRefs status condition

conformance/tests/cors-allow-credentials-behavior.go, conformance/tests/cors-allow-credentials-behavior.yaml, pkg/features/httproute.go
/kind test
Test for proper cors allow-credentials behavior, and add the CORS Feature 
Fixes #3946
```release-note
NONE
```
=> conformance: add test to check for proper cors allow-credentials behvior

apis/v1/httproute_types.go, apis/v1/shared_types.go, apis/v1/zz_generated.deepcopy.go, applyconfiguration/apis/v1/httpcorsfilter.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, pkg/test/cel/httproute_experimental_test.go
/kind bug
/kind test
**What this PR does / why we need it**: 
- Adds support for a single "*" as a CORS origin
- Adds validation tests for the AllowOrigins and AllowMethods fields
Fixes #3648 
```release-note
Adds support for a single '*' character on CORS origins
```
=> Fix cors cel

apis/v1alpha3/backendtlspolicy_types.go, config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml, geps/gep-3155/index.md, pkg/generated/openapi/zz_generated.openapi.go
Documentation for BackendTLSPolicy is not complete regarding SAN validation.
Relates to https://github.com/kubernetes-sigs/gateway-api/issues/3979
```release-note
NONE
```
=> Specify SAN validation precedence over Hostname validation

conformance/conformance.go, go.mod
/kind bug
/kind test
```release-note
NONE
```
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2090
This seems to be the common solution for this problem across other projects, as seen in https://grep.app/search?f.lang=Go&q=+log.SetLogger+
No idea if these are the best options, just copied the ones from kgateway,  but anything is better than panicing in a test suite, feel free to suggest better options
=> prevent controller-runtime stack traces logger

conformance/tests/udproute-simple.go
/kind cleanup
Adding a default timeout configuration for the UDPRoute test and improving the logging structure.
This one came out during adding the test in [Envoy Gateway](https://github.com/envoyproxy/gateway/pull/6839/).
```release-note
NONE
```
=> Add default timeout to UDPRoute test and improve logs

apis/v1/httproute_types.go, config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml, pkg/generated/openapi/zz_generated.openapi.go
/kind cleanup
Update gRPC Auth config so that, if no headers are specified in `allowedHeaders`, _all_ headers must
be sent rather than a specific list.
Updates #1494 
```release-note
NONE
```
=> Update gRPC Auth config

geps/gep-1713/index.md
/kind gep
This PR is a review of ListenerSet GEP, fixing some manifests and adding some comments to be further discussed
Fixes #
```release-note
NONE
```
=> Improve some ListenetSet gep descriptions

conformance/reports/v1.3.0/cloud-provider-kind/README.md, conformance/reports/v1.3.0/cloud-provider-kind/standard-v0.8.0-alpha.1-default-report.yaml
```release-note
NONE
```
Cloud-provider-kind gateway-http profile conformance report
The conformance results can also be obtained directly from the github actions job https://github.com/kubernetes-sigs/cloud-provider-kind/actions/runs/17528832596?pr=285 , are included in the artifiact
=> submit report for cloud provider kind

conformance/tests/httproute-cors-allow-credentials-behavior.go, conformance/tests/httproute-cors-allow-credentials-behavior.yaml
/kind bug
/kind cleanup
Without any `allowOrigins` configured, it’s unlikely that any implementation would be able to pass the `CORSAllowCredentialsBehavior` test. In addition, I added a more meaningful description and updated the test name and files to match the naming conventions used by other HTTPRouteFilter tests.
Fixes #
```release-note
NONE
```
=> Add allowOrigins configuration to CORSAllowCredentialsBehavior and perform cleanup

site-src/guides/tls.md
The [TLS Configuration page](https://gateway-api.sigs.k8s.io/guides/tls/) returns a `Macro Rendering Error` because the location of the included yaml file has changed, so I changed it to the correct path.
`make live-docs` returns an expected page when I run it locally.
Fixes #4090
```release-note
NONE
```
=> Fix broken link in TLS Configuration page

OWNERS_ALIASES
Moved Mattia to emeritus maintainer status as per [this discussion](https://groups.google.com/g/kubernetes-sig-network/c/zlN8BhPxDHI). Thank you for all your hard work helping to make this project what it is today @mlavacca :vulcan_salute:
=> Update OWNERS_ALIASES for gateway-api teams

RELEASE_MANAGEMENT.md
This commit updates the deadline extension request policy with some timing details.
/kind cleanup
```release-note
NONE
```
=> Update deadline extension policy
