kubernetes-sigs/gateway-api

config/crd/bases/networking.x.k8s.io_gateways.yaml
config/crd/bases/networking.x.k8s.io_httproutes.yaml

These files somehow slipped from previous commits.
/assign @bowei

Update autogenerated stuff that somehow was missed

---

mkdocs.dockerfile
mkdocs.requirements.txt

This removes some of the non-determinism from the docs build

Freeze the mkdocs versions

---

api/v1alpha1/gateway_types.go
config/crd/bases/networking.x.k8s.io_gateways.yaml

- Fixes json tag for `Name` field.
- Expands godocs of several fields and types.
/assign @bowei 
/cc @jpeach @youngnick @ironcladlou @Miciah

Updates Gateway godocs

---

config/crd/bases/networking.x.k8s.io_gatewayclasses.yaml

Generates gatewayclasses CRD missing from PR #126.
/assign @robscott 
/cc @jpeach @Miciah

Generates missing gatewayclasses CRD

---

api/v1alpha1/gateway_types.go

Fix golint failure
```
hack/verify-golint.sh 
!!! 'golint' problems: 
/home/aojeagarcia/go/src/sigs.k8s.io/service-apis/api/v1alpha1/gateway_types.go:141:2: comment on exported const NamedAddressType should be of the form "NamedAddressType ..."
```

Fix lint error

---

docs-src/concepts.md
docs/concepts/index.html

fixec broken link for security model

---

Makefile
api/v1alpha1/generated.proto

Updates Makefile to generate v1 CRDs and generates proto missing from PR #151.

Updates Makefile and generates protos

---

api/v1alpha1/gateway_types.go

Fix Listener protocol constant spellings.

---

docs-src/concepts.md
docs/concepts/index.html

Fixes https://github.com/kubernetes-sigs/service-apis/issues/195

Describe core, extended, custom support levels

---

OWNERS

I know we want expand and diversify this list in the near future, but for now this should help get some PRs approved a bit faster.

Addding myself as a project owner

---

apis/v1alpha1/gateway_types.go

Sort gateway types in the order of introduction

---

docs-src/index.md
docs/index.html

This PR updates the introduction page of the project docs, replacing the `Gateway API` heading with `Resources`.
/assign @robscott 
/cc @bowei

Updates Introduction Docs

---

docs-src/security-model.md
docs/security-model/index.html

This patch removes git conflict log in security-model.md.

Remove git conflict log in security-model.md

---

apis/v1alpha1/gateway_types.go
config/crd/bases/networking.x-k8s.io_gateways.yaml
docs-src/spec.md
docs/spec/index.html

Fix the type of the ListenerStatus.Port.

---

docs-src/devguide.md
docs/devguide/index.html

- Adds details for cloning the repo.
- Adds details for submitting a PR.
/assign @robscott @bowei @jpeach @hbagdi 
/cc @Miciah

Updates Dev Docs

---

apis/v1alpha1/gateway_types.go

Delete the unused ListenerExtensionObjectReference.

---

docs-src/concepts.md
docs/concepts/index.html

Updates the request workflow section of the API concepts docs. This PR fixes outdated API field references and takes a more generalized approach to the documentation for simplification and to avoid future staleness.
/assign @robscott @bowei @hbagdi @jpeach

Updates Request Workflow in Docs

---

apis/v1alpha1/gateway_types.go
apis/v1alpha1/httproute_types.go
apis/v1alpha1/route_types.go
apis/v1alpha1/tcproute_types.go
apis/v1alpha1/tlsroute_types.go
apis/v1alpha1/udproute_types.go
config/crd/bases/networking.x-k8s.io_gateways.yaml
config/crd/bases/networking.x-k8s.io_httproutes.yaml
config/crd/bases/networking.x-k8s.io_tcproutes.yaml
config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
config/crd/bases/networking.x-k8s.io_udproutes.yaml
docs-src/spec.md
docs/spec/index.html

Update the condition types and reasons for the Listener condition type.
/cc @danehans @robscott

Update Listener condition types.

---

Makefile

kustomize is already included in kubectl.

remove dependency on kustomize binary

---

apis/v1alpha1/gatewayclass_types.go
apis/v1alpha1/httproute_types.go
docs-src/spec.md
docs/spec/index.html

Fixes the documentation generation issue.

Change type alias to creating a new type

---

OWNERS

/assign @robscott @hbagdi @jpeach @danehans

Add reviewers {bowei,robscott,hbagdi,jpeach,danehans}

---

hack/verify-golint.sh

Installing golint if it doesn't exist

---

examples/backendpolicy.yaml
examples/default-match-http.yaml
examples/http-filter.yaml
hack/verify-examples-kind.sh

Fixes https://github.com/kubernetes-sigs/service-apis/issues/346.
/cc @hbagdi @jpeach

Adding a way to verify examples with kind, fixing BackendPolicy example

---

CHANGELOG.md
RELEASE.md
docs-src/devguide.md
docs/devguide/index.html

also adds in a placeholder CHANGELOG.md
See #392

document the release process

---

docs-src/concepts.md
docs-src/faq.md
docs/concepts/index.html
docs/faq/index.html

Update the FAQ.

---

docs-src/releases.md
docs/releases/index.html

- Add a line jump to fix rendering
- Remove outdated release info

cleanup release.md

---

docs-src/security-model.md
docs/security-model/index.html

This is just a quick reference in the docs to the PR I created earlier. Although not ideal, I think this is probably the best reference for now.
/cc @hbagdi @danehans

Adding a reference in docs to Gatekeeper config example

---

apis/v1alpha1/httproute_types.go
config/crd/bases/networking.x-k8s.io_httproutes.yaml
docs-src/spec.md
docs/spec/index.html

clarify HTTP Header name and value matching criteria

---

apis/v1alpha1/gatewayclass_types.go
config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml

Update GatewayClass Condition flow to add `Admitted` Condition type.

---

docs-src/index.md
docs/index.html

Makes minor improvements to the introduction document.
/assign @robscott 
/cc @mark-church

Minor Intro Doc Improvements

---

CHANGELOG.md

Changes "insenstive" to "insensitive".

Fixing typo in changelog

---

docs-src/community.md
docs/community/index.html

Based on the results of https://strawpoll.com/w5p5peyq7, it seems like Wednesdays at 11am are going to work best for most people. This updates our community page to reflect that.

Updating Service APIs meeting times

---

OWNERS

/kind cleanup
Removing bowei as an explicit approver. This was added by Rob in case something went wrong during the migration to aliases. If this is not correct, please close this PR.
/cc @robscott 
None
```release-note
NONE
```

remove bowei from owners file

---

docs-src/faq.md
docs/faq/index.html

/kind cleanup
Fixes a broken link as reported in https://github.com/kubernetes-sigs/service-apis/pull/494#issuecomment-740358874
None
```release-note
NONE
```

fix broken link in FAQ doc

---

docs-src/releases.md
docs/releases/index.html

This clarifies that unreleased changes may be reverted. This is important to note since we continue to actively develop on our master branch.
```release-note
NONE
```

Clarifying that unreleased changes may be reverted

---

docs-src/getting-started.md
docs/getting-started/index.html

Pins the manifests being pulled to v0.1.0. This ensures that any problematic changes in the `master` branch do not affect end users immediately.
Fixes #502
```release-note
NONE
```

docs: pin to CRD manifests to v0.1.0

---

docs-src/tcp.md
docs/404.html
docs/api-overview/index.html
docs/community/index.html
docs/devguide/index.html
docs/enhancement-requests/index.html
docs/faq/index.html
docs/gatewayclass/index.html
docs/getting-started/index.html
docs/guidelines/index.html
docs/guides/index.html
docs/http-routing/index.html
docs/httproute/index.html
docs/index.html
docs/multiple-ns/index.html
docs/releases/index.html
docs/security-model/index.html
docs/simple-gateway/index.html
docs/spec/index.html
docs/tcp/index.html
docs/tls/index.html
examples/basic-tcp.yaml
mkdocs.yml

Adds a guide to demonstrate the use of TCPRoute
Fixes #488
Fixes #333
```release-note
NONE
```

docs: add guide on using TCP route

---

docs-src/spec.md
docs/spec/index.html
go.mod
go.sum
hack/api-docs/type.tpl

Document the constant values for type aliases that are used to enforce
enum validation.

Document values for named constants.

---

Makefile

Signed-off-by: Christopher M. Luciano <cmluciano@us.ibm.com>
/kind feature
Adds Makefile task for `go test`
xref: #507 
```release-note
NONE
```

build: Run go test from Make

---

CHANGELOG.md

Documents changes introduced between v0.1.0 and v0.2.0. 
None
```release-note
NONE
```
/hold

docs: add changelog for v0.2.0

---

docs-src/getting-started.md
docs/getting-started/index.html

Bumps up the version used to install the CRDs to match the latest version.
None
```release-note
NONE
```
Holding until release is out
/hold

bump up references to v0.2.0

---

docs-src/getting-started.md
docs/getting-started/index.html

Rename Services API to Gateway API in Getting Started
N/A
```release-note
NONE
```

docs: Rename Services API to Gateway API in Getting Started

---

site-src/getting-started.md
site-src/implementations.md
site-src/index.md

Adds link to getting started form the front page.
Adds link to implementations in getting started.
```release-note
NONE
```

Doc tweaks

---

site-src/implementations.md

As we are shown in SoloCon, we 've shown an WIP implementation for this Gateway API.
https://www.youtube.com/watch?v=sKdDG5YZmzc
```release-note
NONE
```

add Gloo Edge 2.0 to the list

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
RELEASE.md
site-src/gatewayclass.md
site-src/http-routing.md
site-src/httproute.md

/kind cleanup
kubernetes-sigs.github.io/gateway-api -> gateway-api.sigs.k8s.io
```release-note
NONE
```

Removing old references to GitHub Pages site

---

site-src/implementations.md

You changed the link, so so did we 🙂

---

site-src/concepts/api-overview.md
site-src/faq.md
site-src/guides/getting-started.md
site-src/guides/http-routing.md
site-src/guides/tcp.md
site-src/guides/traffic-splitting.md
site-src/index.md

/kind cleanup
I used https://www.deadlinkchecker.com/website-dead-link-checker.asp to check for dead links after #601 got merged in. This fixes those broken links.
None
```release-note
NONE
```

fix broken links after site structure change

---

site-src/api-types/gatewayclass.md

/kind cleanup
Fixes a broken link
None
```release-note
NONE
```

fix broken link to IngressClass KEP

---

site-src/guides/getting-started.md
site-src/guides/traffic-splitting.md
site-src/index.md

/kind cleanup
Since we have moved to Netlify, file links sometimes work and sometimes don't and they create quite some confusion, at least for me personally.
I audited the code and it seemed we mostly use URL links so I changed the remaining file links. This provides consistency and for future-selves and new contributors to only use URL links in markdown files.
None
```release-note
NONE
```

remove file links and use only URL links throughout the docs site

---

site-src/concepts/api-overview.md
site-src/faq.md

Replace the typo "infrastucture" with "infrastructure". Fix a broken link.
NONE
```release-note
NONE
```

Fix typo in FAQ doc

---

apis/v1alpha1/httproute_types.go
config/crd/bases/networking.x-k8s.io_httproutes.yaml

/kind cleanup
This is a small follow up to #631 that addresses some of the tiny nits that were leftover on that PR.
```release-note
NONE
```
/cc @bowei @hbagdi @youngnick

Cleaning up query param matching spec

---

site-src/guides/tls.md

Enhance Docs with the relation between Gateways, Routes and TLS
Fixes #612
```release-note
```

Enhance docs around Gateways, Routes and TLS

---

site-src/contributing/community.md
site-src/v1alpha2/contributing/community.md

This updates the meeting times based on the results of the earlier [StrawPoll](https://strawpoll.com/11g8hh8bw). This corresponds with https://github.com/kubernetes/community/pull/5764.
```release-note
NONE
```

Updating meeting times

---

site-src/references/implementations.md

- Also fixes anchor text
```release-note
NONE
```

Update GKE support for Gateway

---

deploy/admission_webhook.yaml

/kind cleanup
Uses latest tag of admission-server docker image from the staging repository. 
Fixes #487 
```release-note
NONE
```
/hold until #649 merges

use latest tag for admission server

---

apis/v1alpha2/backendpolicy_types.go
apis/v1alpha2/gateway_types.go
apis/v1alpha2/gatewayclass_types.go
apis/v1alpha2/httproute_types.go
apis/v1alpha2/tcproute_types.go
apis/v1alpha2/tlsroute_types.go
apis/v1alpha2/udproute_types.go
config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
config/crd/bases/networking.x-k8s.io_gateways.yaml
config/crd/bases/networking.x-k8s.io_httproutes.yaml
config/crd/bases/networking.x-k8s.io_tcproutes.yaml
config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
config/crd/bases/networking.x-k8s.io_udproutes.yaml

/kind bug
Makes `spec` field required for all API types as having objects without any `spec` section should be of no use in this API.
Fixes #661
```release-note
For all resources in the API, `.spec` section is now required.
```
/cc @jpeach @robscott @danehans

breaking change: make object.spec required on all resources

---

pkg/admission/server.go

/kind cleanup
Minor DRY of code
None
```release-note
NONE
```

pkg/admission: refactor to dry out deserializer instantiation

---

deploy/admission_webhook.yaml
pkg/admission/server.go
pkg/admission/server_test.go

/kind feature
Adds Gateway validation to Admission Webhook
Updates #487 
```release-note
NONE
```
//cc @hbagdi

pkg/admission: Add Gateway validation to Admission Webhook

---

hack/verify-examples-kind.sh

This was found during manual testing for #657:
```
$ kubectl apply -f examples | wc
38      76    1989
$ kubectl apply --recursive -f examples | wc
47      94    2424
```
/kind cleanup
To fix a bug in our verify script.
None
```release-note
NONE
```

hack: install examples recursively

---

site-src/concepts/guidelines.md

/kind cleanup
Fixes #355
```release-note
NONE
```

Add guidance on plural field names to Implementation Guide

---

apis/v1alpha2/gatewayclass_types.go
config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
site-src/v1alpha2/api-types/gatewayclass.md

/kind cleanup
Allows for any valid HTTP path to be part of the PATH section of the controller name. 
Fixes #330
```release-note
NONE
```

update controller field description for consistency

---

.github/PULL_REQUEST_TEMPLATE.md

This automation makes tide use squash as  the default merge method so that PR authors can make incremental commits through the review process.
None
```release-note
NONE
```

use squash as default merge behavior

---

site-src/references/implementations.md

---
labels: 'tide/merge-method-squash'
---
Add HAProxy Ingress to the downstream implementations list
none
```release-note
NONE
```

Add HAProxy Ingress as a downstream implementation

---

site-src/references/implementations.md

This refreshes the GKE gateway controller section of the implementation page

updated implementations page for GKE gateway controller

---

apis/v1alpha2/httproute_types.go
config/crd/bases/networking.x-k8s.io_httproutes.yaml

/kind cleanup
Fixes https://github.com/kubernetes-sigs/gateway-api/pull/683#discussion_r663276994
None
```release-note
NONE
```

use camelCase and not snake_case

---

mkdocs.yml
site-src/css/extra.css

Add an extra CSS file to enable text justification for all paragraphs.
This makes it a little easier to read large text blocks, at least in my
opinion :)

Justify text on the website.

---

.gitignore

/kind cleanup
#702 results in a `.venv/` directory in the working directory, this patch ignores that directory from version control.
NONE
```release-note
NONE
```

gitignore: add .venv/

---

.github/ISSUE_TEMPLATE/enhancement.md

/kind cleanup
Just a tiny wording tweak because it bugged me when I was creating new issues.
```release-note
NONE
```

Fixing wording in enhancement template

---

OWNERS_ALIASES

/kind cleanup
@youngnick has been a great contributor to Gateway API, excited to welcome him as a maintainer!
This also removes @danehans as a maintainer now that he'll no longer be able to contribute to the project in his new role. Really appreciate all his contributions to the project!
```release-note
NONE
```
Note: Once this PR merges, I'll make a follow up PR to k/org to change the groups there as well.
/cc @bowei @danehans @jpeach @hbagdi @youngnick 
/hold

Adding Nick as a project maintainer

---

mkdocs.yml

/kind cleanup
- every markdown heading as a link
- every page has an edit button to directly edit a page and submit a PR
- Github repository improvements in the header
- searched term is highlighted in the result
None
```release-note
NONE
```

minor improvements to navigation on docs site

---

examples/v1alpha2/tls-cert-cross-namespace.yaml

Fix tls-cert-cross-namespace group

---

site-src/index.md

Fix typo `It's is` to `It is`, to better the doc.
```release-note
NONE
```

Fix typo `It's is`

---

.github/ISSUE_TEMPLATE/config.yml

Example of what it looks like: https://github.com/istio/istio/issues/new/choose ("crash bug")

Attempt to slow down implementation-specific reports

---

site-src/index.md

Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
Fixes #
```release-note
```

docs: fix broken links

---

site-src/implementations.md

This PR changes HAProxy Ingress' external link to the latest branch - v0.13, which is the first controller version that implements Gateway API and was already graduated to GA.
```release-note
NONE
```

Reference HAProxy Ingress' latest branch

---

Makefile

Helps #785
/kind cleanup
Enable verbose output for more helpful CI errors.
Helps #785
```release-note
NONE
```

enable verbose output in CI

---

apis/v1alpha2/validation/gateway.go
apis/v1alpha2/validation/gatewayclass.go
apis/v1alpha2/validation/httproute.go

Fix incorrect urls which were pointing to 404
Fixes a bunch of incorrrect urls in the validation package as that would lead to incorrect urls in the docs
Fixes #884 
```release-note
Fix incorrect specification urls in validation package
```

Fix incorrect urls

---

deploy/certificate_config.yaml

/kind cleanup
Removes the outdated "version: 0.0.1" label from certificate deployment YAMLs.
None
```release-note
NONE
```

remove outdated version label

---

site-src/v1alpha1/guides/getting-started.md
site-src/v1alpha2/guides/getting-started.md

Fixes two links to the Gateway API Implementations page.
```release-note
NONE
```

Fix link to the implementations page

---

go.mod

/kind cleanup
Bump up required Go version to 1.17.
None
```release-note
NONE
```

bump go.mod to 1.17

---

site-src/implementations.md

Simple typo I noticed while browsing the docs.
```release-note
NONE
```

Fix site implementations typo

---

CONTRIBUTING.md

Updated broken link for  contributor-cheatsheet
Fixes #947 
NONE
```release-note
```

updated link for contributor-cheatsheet

---

site-src/v1alpha2/references/cross-namespace-references.md

Fix a typo in the doc.
Fixes #
```release-note
NONE
```

Add missing word in Introduction

---

site-src/implementations.md

Fix Grammar

---

site-src/v1alpha2/references/cross-namespace-references.md

Add a newline so that the Markdown list gets properly rendered as a list.
NONE
```release-note
NONE
```

Fix formatting for cross namespaces references.

---

examples/v1alpha2/http-routing/bar-httproute.yaml

The example "bar-route" HTTPRoute from the "HTTP routing" web page had a bug where both backendRefs belonged to
the same rule so traffic would either match the header in which case it
would be split 50/50 between bar-svc-canary and bar-svc, or it wouldn't
match the header in which case I'm not sure what would happen.
This PR adds a second HTTPRouteRule to the bar-route HTTPRoute so the
yaml manifest matches the descriptive text.
https://kubernetes.slack.com/archives/CR0H13KGA/p1642527563035400
```release-note
This PR fixes the bar-route example on https://gateway-api.sigs.k8s.io/v1alpha2/guides/http-routing/
```

Fix v1alpha2 "HTTP routing" example

---

site-src/v1alpha2/contributing/community.md

Update the youtube playlist to be correct on the Community page.
```release-note
NONE
```

Update Youtube playlist for recorded meetings

---

site-src/index.md

Fixes a typo that I noticed while reading through https://gateway-api.sigs.k8s.io/#gateway-api-concepts
N/A
```release-note
NONE
```

Remove redundant word in documentation

---

requirements.txt

See lukasgeiter/mkdocs-awesome-pages-plugin#49
mkdocs-awesome-pages-plugin 2.5.1 contains the fix, but 2.7.0 is the latest.
/kind bug

docs: fix build with python 3.10

---

site-src/implementations.md

Updates for the current state of Gateway support in Kong.

docs: update kong in implementations.md

---

conformance/utils/roundtripper/roundtripper.go

/kind bug
A couple small fixes for roundtripper.
```release-note
Conformance tests: Improved error handling for HTTP requests
```

Fixing error handling and typo in roundtripper

---

site-src/implementations.md

Updates the Consul info on the website's Implementations page.
```release-note
NONE
```
Even though this PR is a user-facing change on the website, I'm saying "NONE" for the release notes because it doesn't seem like the type of change that should be listed in the RNs for a new version of the spec. I'll add a release note if the Maintainers would like me to.

Update Implementations page with current Consul information

---

README.md

/kind bug
Correct the version mention in the Status in Readme
Fixes #1048
```release-note
NONE
```

Correct the version mention in the Status

---

apis/v1alpha2/httproute_types.go
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
examples/v1alpha2/simple-gateway/httproute.yaml

fix typo of urlRewrite

---

site-src/concepts/security-model.md

Fixes broken "include" statement on security model doc.
Fixes #1053
```release-note
NONE
```

Fixing broken inclusion on security model doc

---

site-src/implementations.md

/kind cleanup
Fixes a misspelling on the website's "Implementations" page
No related Issue
NONE

Fix a typo on website's "Implementations" page

---

hack/build-and-push.sh

In #1047, there's some debate about the logic here. Maybe it can simplified.
We first tag the image with the git-based tag.
We always add one additional tag - if we're on master, we use `latest`. Otherwise, we have been supplied a semver tag in `BASE_REF`, and we can use that.
The only difference in the logic vs #1047 should be that we don't set `COMMIT` in the go binary to the semver tag, which seems wrong anyway?
Before this change:
```    
$ podman run -it --restart no --rm gcr.io/k8s-staging-gateway-api/admission-server:v20220324-v0.4.0-177-g6d6fe85 -version
gateway-api-admission-webhook version: v20220324-v0.4.0-177-g6d6fe85 (6d6fe856860b2cf243ad5574b7346138636f80d6)
$ podman run -it --restart no --rm gcr.io/k8s-staging-gateway-api/admission-server:v0.4.2-test -version …
```

Simplify image tagging script

---

site-src/implementations.md

The PR adds NGINX Kubernetes Gateway to the list of the implementations in the docs.
None
None

Add NGINX Kubernetes Gateway to list of implementations

---

site-src/implementations.md

The PR adds EPIC Application & API Gateway to the list of implementations in the docs.
None
None

add acnodal epic implementation to docs

---

conformance/utils/kubernetes/helpers.go

Respects the listener port when returning a Gateway address in the conformance tests. Fixes the tests if any `Gateway` listener isn't listening on port 80.
/kind bug
```release-note
NONE
```

conformance: include Gateway port in WaitForGatewayAddress

---

site-src/v1alpha1/api-types/httproute.md
site-src/v1alpha2/api-types/httproute.md

Fix some creative spelling.
```release-note
Fix spelling errors in the docs.
```

Tweaks to HTTPRoute docs (spelling error, heading levels)

---

site-src/implementations.md

This pull request updates the Traefik implementation description, as of [v2.6](https://github.com/traefik/traefik/releases/tag/v2.6.0) we are now supporting version `v1alpha2` (`v0.4.x`) of the Gateway API specification.
None
```release-note
NONE
```

Update Traefik implementation description

---

site-src/implementations.md

This pull request fixes typos in the documentation about implementations.
None
```release-note
NONE
```

Fix typos in implementations.md

---

site-src/implementations.md

Add Kuma to the list of implementations of Gateway API

docs: add Kuma to the list of implementations

---

CHANGELOG.md

This adds a changelog for v0.4.3. By approving this PR, you approve a v0.4.3 release based on this commit.
```release-note
NONE
```
/cc @bowei @hbagdi @jpeach @youngnick

Adding Changelog for v0.4.3

---

conformance/tests/httproute-invalid-cross-namespace-parent-ref.go

Without this, other tests may be creating valid Routes that are
attached. This test can run and then immediately fail due to those
routes from other tests.
Instead, we should assert eventual consistency.
/kind cleanup
```release-note
NONE
```

conformance: allow converence time for gateway status check

---

apis/v1alpha2/validation/httproute.go
apis/v1alpha2/validation/httproute_test.go

/kind cleanup
This adds webhook validation to ensure that a path match exists when required by path modifier in filter.
Fixes #1166 
```release-note
Webhook validation now ensures that a path match exists when required by path modifier in filter.
```

Adding validation to ensure prefix path match exists for path modifier

---

site-src/implementations.md

Refreshes the state of Kong's Gateway API implementations in `implementations.md`.
```release-note
NONE
```

docs: refresh kong in implementations.md

---

CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
pkg/generator/main.go

/kind feature
This is the last set of changes required to launch v0.5.0-rc1.
```release-note
NONE
```

Preparing v0.5.0-rc1 for release

---

CHANGELOG.md

/kind cleanup
Removing "unreleased" text
```release-note
NONE
```

Fixing changelog title for v0.5.0-rc1

---

conformance/tests/httproute-hostname-intersection.yaml

/kind cleanup
YAML parsers bork this placeholder because it appears as a map instead of the string it should be interpreted as
Fixes #
```release-note
NONE
```

conformance: Use valid YAML string for gatewayClassName placeholder

---

site-src/v1alpha2/references/policy-attachment.md

Signed-off-by: Keith Mattix II <keithmattix2@gmail.com>
/kind bug
This PR adds an example of Policy attachment defaults and overrides
Fixes #1000 
```release-note
Add policy attachment example
```

Fill in missing policy attachment example

---

conformance/utils/http/http.go

Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1242
/kind flake
Fixes #
```release-note
NONE
```

conformance: wait for all conditions, not just status code

---

CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
pkg/generator/main.go

/kind feature
This will trigger one final release candidate before the v0.5.0 release.
```release-note
NONE
```

Adding changelog for v0.5.0-rc2

---

mkdocs.yml
site-src/blog/2022/graduating-to-beta.md
site-src/blog/index.md

This is a follow up to @shaneutt's PR: #1227 and mirrors https://github.com/kubernetes/website/pull/34968.
```release-note
NONE
```
/hold for release

Adding v0.5.0 blog post

---

site-src/guides/getting-started.md

Now that v0.5.0 is released, we need to update our installation instructions to install the latest version.
```release-note
NONE
```

Updating Getting Started Guide for v0.5.0

---

site-src/implementations.md

Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
Fixes #
```release-note
```

docs: Update the status of the Apache APISIX Ingress implementation

---

.github/ISSUE_TEMPLATE/bug.md

/kind cleanup
We've already gotten some implementation specific bugs filed in this repo, that will likely become more common as this project grows. Hopefully adding this kind of clarification will help users find the correct place to file each kind of bug.
```release-note
NONE
```

Clarifying which kinds of bugs should be filed in this repo

---

site-src/contributing/community.md
site-src/contributing/gamma.md

Signed-off-by: Keith Mattix II <keithmattix2@gmail.com>
Adds GAMMA meetings to website documentation
Fixes #
N/A

Add GAMMA meetings

---

site-src/implementations.md

Add Cilium to list of Gateway API implementations
Adds Cilium to list of Gateway API implementations 
N/A 
```release-note
NONE
```

[docs] Cilium Gateway API implementation

---

site-src/implementations.md

Updates Contour's "implementations" entry.
```release-note
NONE
```

update Contour's implementation entry

---

apis/v1beta1/validation/gateway.go
apis/v1beta1/validation/gateway_test.go
apis/v1beta1/validation/gatewayclass.go
apis/v1beta1/validation/gatewayclass_test.go
apis/v1beta1/validation/httproute.go
apis/v1beta1/validation/httproute_test.go

This looks like it should probably be gatewayv1b1 not gatewayv1a2.
/kind cleanup
Reduces confusion.
Not significant enough for a tracked issue.
```release-note
NONE
```

Fix import naming.

---

apis/v1alpha2/validation/httproute_test.go

/kind cleanup
Code hygiene.
Small enough that this does not seem worth a tracking issue.
```release-note
NONE
```

Remove duplicate import and fix package references.

---

apis/v1beta1/validation/httproute_test.go

/kind cleanup
Code hygiene.
N/A
```release-note
NONE
```

Remove duplicate import.

---

apis/v1alpha2/validation/httproute.go

/kind cleanup
Remove extra leading slashes from comment.
Comment formatting.
```release-note
NONE
```

Remove extra leading slashes from comment.

---

site-src/implementations.md

Link to Cilium was broken
Fixes #1308 
```NONE
```

Link to cilium updated

---

apis/v1beta1/validation/httproute.go

/kind cleanup
Docstring nit.
N/A
```release-note
NONE
```

Remove extra comment slashes.

---

apis/v1alpha2/shared_types.go
apis/v1beta1/shared_types.go
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml

`InvalidKind` and `BackendNotFound` are added to the possible failure reasons of the `ResolvedRefsCondition` in the route godoc.
Fixes #1313 
```release-note
NONE
```

All route ResolvedRefs reasons added to docs

---

site-src/api-types/gatewayclass.md
site-src/api-types/httproute.md
site-src/api-types/referencegrant.md
site-src/blog/2021/introducing-v1alpha2.md
site-src/blog/index.md
site-src/contributing/enhancement-requests.md
site-src/contributing/gamma.md
site-src/contributing/gep.md

/kind bug
Multiple links are broken under site-src folder
Fixes #1311 
```release-note
NONE
```

broken link under site_src

---

RELEASE.md
site-src/concepts/versioning.md

Small docs updates around release process
- readability updates
- fix broken links
- patch release content addition (conformance test fixes)
N/A
```release-note
NONE
```

Docs updates around release process

---

site-src/geps/gep-1324.md

Signed-off-by: Keith Mattix II <keithmattix2@gmail.com>
Addresses some wording clarifications and formatting changes for GEP 1324
```release-note
NONE
```

Address comments made after PR was closed

---

conformance/utils/http/http.go

/kind cleanup
```release-note
NONE
```

Add time elapsed message to awaitConvergence

---

site-src/concepts/versioning.md

As this project matures, it's important to document our support guarantees going forward. This proposes a set of basic commitments that I think are both safe for us as maintainers and helpful for anyone building a product with this API. 
```release-note
NONE
```

Documenting supported versions

---

conformance/utils/kubernetes/helpers.go

/kind bug
Prints expected and actual conditions incase a conformance test fails.
Helps with #1317
None

Print conditions for failed conformance tests

---

conformance/utils/kubernetes/helpers.go

/kind cleanup
This is useful for debugging failing tests.
```release-note
NONE
```

conformance: print Reason if Status doesn't match

---

config/webhook/0-namespace.yaml
config/webhook/admission_webhook.yaml
config/webhook/certificate_config.yaml

/kind bug
This PR fixes duplicate namespace definition in `config/webhook/certificate_config.yaml` and `config/webhook/admission_webhook.yaml`. It pulls out the namespace definition to a separate `0-namespace.yaml` file.
Fixes #1374 
```release-note
NONE
```

Pull out the duplicate namespace definition to a separate `0-namespace.yaml` file

---

netlify.toml

Looks like netlify previews are failing, I think this should fix it. If this one has good previews, that should do it.
/kind bug
/kind cleanup
/kind regression
Fixes #
```release-note
NONE
```

Fix PYTHON_VERSION for build image

---

config/webhook/0-namespace.yaml
config/webhook/admission_webhook.yaml
config/webhook/certificate_config.yaml

/kind bug
This PR cherry-picks #1377 to release-0.5 branch.
Fixes #1374 
```release-note
NONE
```

release-0.5: Cherry pick #1377 - Pull out the duplicate namespace definition to a separate 0-namespace.yaml file.

---

hack/update-codegen.sh

/kind cleanup
**What this PR does / why we need it**: Purely an optimization on the build process
```release-note
NONE
```

Used cached go modules for generate

---

site-src/guides/getting-started.md

Fixes #1403 
Fixes #
```release-note
```

Fix Anchor for installing Gateway API CRD manually on Getting Started Guide

---

apis/v1alpha2/httproute_types.go
apis/v1beta1/httproute_types.go
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml

Fixes a docs bug re: route conditions in v0.5.0.
```release-note
NONE
```

(release-0.5 cherrypick of #1382) replace Attached condition with Accepted in HTTPRoute docs

---

RELEASE.md
site-src/blog/2022/graduating-to-beta.md
site-src/blog/index.md
site-src/concepts/api-overview.md
site-src/contributing/gamma.md
site-src/references/policy-attachment.md

/kind cleanup
Just fixes a bunch of spelling mistakes found in the documentation.
```release-note
NONE
```

Fix some spelling mistakes

---

apis/v1alpha2/referencegrant_types.go
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
site-src/api-types/referencegrant.md

In response to some recent sig-auth feedback, this clarifies some parts of the ReferenceGrant API.
```release-note
- Clarification that changes to ReferenceGrants MUST be reconciled
```

Clarifying ReferenceGrant documentation

---

apis/v1alpha2/gateway_types.go
apis/v1alpha2/gatewayclass_types.go
apis/v1alpha2/httproute_types.go
apis/v1alpha2/zz_generated.deepcopy.go

If we have the outer List type v1alpha2 but the inner Items type v1beta1, informers get confused and end up panicing. This fixes it
Fixes #
```release-note
NONE
```

Fix List type aliases

---

hack/update-codegen.sh

Signed-off-by: Lucas Caparelli <lucas.caparelli@gympass.com>
/kind feature
Adds a guard check to ensure correct Go version when running code generation.
Fixes #1442
```release-note
NONE
```
This is a follow-up from https://github.com/kubernetes-sigs/gateway-api/pull/1436#issuecomment-1270749444

feat: add guard check for go version

---

conformance/tests/httproute-response-header-modifier.yaml

This is a typo from copy+paste, makes the test never pass
/kind bug
Fixes #
```release-note
NONE
```

Fix response header route name

---

mkdocs.yml
site-src/geps/gep-1426.md

/kind gep
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1487
```release-note
NONE
```

Add note about `port` to Mesh GEP

---

mkdocs.yml
site-src/geps/gep-1426.md

/kind cleanup
Adds missing context as raised in https://github.com/kubernetes-sigs/gateway-api/pull/1493/files#r1008592366
N/A
```release-note
NONE
```

GAMMA: add GEP-1426 to website GEP list, add producer/consumer personas

---

site-src/implementations.md

Signed-off-by: Arko Dasgupta <arko@tetrate.io>

update envoy gateway status

---

examples/experimental/basic-grpc.yaml
examples/experimental/v1alpha2/grpc-routing/gateway.yaml
examples/standard/http-redirect.yaml

/kind cleanup
Fixes example resources after merge of #1470 
```release-note
NONE
```

Fix invalid HTTPS listeners in example resources

---

site-src/implementations.md

Signed-off-by: danehans <daneyonhansen@gmail.com>
Updates Envoy Gateway details in the implementation docs page.
- Fixes a broken link.
- Fixes grammar.
- Simplifies messaging.
```release-note
NONE
```

Updates Envoy Gateway Implementation Details

---

site-src/implementations.md

Fixes #
```release-note
NONE
```

Make Istio impl as "beta"

---

hack/build-and-push.sh

/kind bug
I saw the job failed and try to fix.
The main branch job failed.

Fix job problem of build docker image

---

site-src/geps/overview.md

Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1548
```release-note
NONE
```

fix: overview meetings links

---

Makefile

Signed-off-by: bitliu <bitliu@tencent.com>
/kind bug
Add image buildx verify.
Related https://github.com/kubernetes-sigs/gateway-api/issues/1545
```release-note
None
```

chore: add docker buildx verify

---

Makefile
go.mod
go.sum

Signed-off-by: bitliu <bitliu@tencent.com>
1. Run go mod tidy
2. Clean buildx verify cmd
Fixes #
```release-note
NONE
```

chore: clean buildx verify and run go mod tidy

---

CHANGELOG.md

Signed-off-by: Nick Young <nick@isovalent.com>
This PR contains the changelog for v0.6.0-rc1. By approving this PR, you are also approving the release of v0.6.0-rc1 based on the current state of the main branch of this project and the changelog included with this PR.
/cc @bowei @shaneutt @robscott 

Update changelog to add v0.6.0-rc1

---

config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
pkg/generator/main.go

Signed-off-by: Nick Young <nick@isovalent.com>
Release v0.6.0 prep PR.

Finish preparing for v0.6.0-rc1 release

---

config/webhook/admission_webhook.yaml
hack/update-webhook-yaml.sh

Signed-off-by: Nick Young <nick@isovalent.com>
/kind bug
/kind cleanup
Fixes the webhook update script, sigh.
```release-note
NONE
```

Fix webhook update script for semver

---

CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
pkg/generator/main.go

This introduces the changelog for v0.6.0-rc2 and updates CRD approval annotations.
```release-note
NONE
```

Adding Changelog for v0.6.0-rc2, updating CRD approval annotations

---

conformance/tests/httproute-rewrite-path.go

fix backend name
/kind bug
```release-note
NONE
```

fix backend name

---

requirements.txt

/kind cleanup
[Recently](https://github.com/kubernetes-sigs/gateway-api/pull/1477) we added [dependabot](https://docs.github.com/en/code-security/dependabot) to the repository to help improve our supply-chain security. Dependabot tried to upgrade several of our older Python dependencies but had trouble doing so because we had not upgraded them in such a long time, and conflicts were encountered. In this PR I manually upgraded several dependencies to resolve the conflicts, and from here on out with a weekly dependabot update it should be easier for dependabot to provide working patches.

upgrade python deps

---

site-src/guides/http-redirect-rewrite.md

/kind cleanup
This patch makes a super tiny fix for the typo.

Fix typo around redirection

---

site-src/implementations.md

STUNner is a new implementation of the Gateway API that may be of interest to the wider audience of the Gateway API project. STUNner was presented and discussed at the 2023-01-30 community meeting.
N/A
No
```

documentation: add STUNner to the list of implementations

---

site-src/guides/migrating-from-ingress.md

fix(docs): SecretObjectReference  to HTTPPathMatch

---

conformance/utils/kubernetes/helpers.go
conformance/utils/kubernetes/helpers_test.go

Fixes: https://github.com/kubernetes-sigs/gateway-api/issues/1703
Signed-off-by: Arko Dasgupta <arko@tetrate.io>

Add explicit equality checks for SupportedKinds

---

CHANGELOG.md
RELEASE.md
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
config/webhook/admission_webhook.yaml
hack/verify-examples-kind.sh
pkg/generator/main.go

This adds the CHANGELOG for the `v0.6.1` patch release. Also adds a "patch release" section to RELEASE.md

release v0.6.1

---

conformance/tests/tlsroute-simple-same-namespace.go

/kind bug
Makes conformance tests pass without TLSRoute support
```release-note
NONE
```

conformance: require `SupportTLSRoute` feature for `TLSRoute` test

---

CHANGELOG.md
README.md
RELEASE.md
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
config/webhook/admission_webhook.yaml
hack/verify-examples-kind.sh
pkg/generator/main.go

/kind cleanup
This cherry-picks some of the documentation from the latest v0.6.1 release, and also includes some cleanup for the RELEASE.md documentation based on the experience of releasing v0.6.1.

v0.6.1 updates

---

conformance/tests/httproute-invalid-parentref-not-matching-section-name.go
conformance/tests/httproute-invalid-parentref-not-matching-section-name.yaml

Add conformance test.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1719#
```release-note
NONE
```

test: add not matching sectioName test

---

.github/ISSUE_TEMPLATE/conformance.md
.github/PULL_REQUEST_TEMPLATE.md

/kind cleanup
This adds a new issue template for conformance tests and makes related improvements to the suggested labels for new PRs.
```release-note
NONE
```

Improving PR and Issue templates for Conformance Tests

---

conformance/conformance_test.go

doc: correct conformance-test (internal) function documentation

---

Makefile
conformance/utils/kubernetes/helpers_test.go

/kind test
This adds a couple unit tests for our conformance test utilities. This is the first in a series of small PRs I intend to do to increase our test coverage iteratively, without making giant PRs. This also adds `apis` and `conformance/utils` to our `make test` directive as that was missing.

Small unit test bump

---

site-src/concepts/api-overview.md

Fix typo in the document.
Fixes #
```release-note
NONE
```

docs: fix api-overview.md typo

---

.golangci.yml
conformance/utils/roundtripper/roundtripper.go

Deprecation of package ioutil in Go 1.16
Fixes #
```release-note
NONE
```

fix: Deprecation of package ioutil in Go 1.16

---

examples/experimental/http-redirect-rewrite/httproute-redirect-full.yaml
examples/experimental/http-redirect-rewrite/httproute-redirect-https.yaml
examples/experimental/http-redirect-rewrite/httproute-redirect-prefix.yaml

/kind bug
Remove invalid redirect examples.
Part of: #1779
```release-note
```

fix: remove invalid redirect examples

---

apis/v1alpha2/grpcroute_types.go
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
conformance/tests/gateway-observed-generation-bump.go

/kind cleanup
Fix some wording issues my linter is complaining about.
N/A, very tiny change.
NONE

Fix trivial wording issues.

---

CHANGELOG.md
site-src/blog/2022/graduating-to-beta.md

fix error links of `geps`
Fixes #
```release-note
NONE
```

fix error link of geps

---

site-src/api-types/referencegrant.md

Removes experimental channel reference from ReferenceGrant doc since this resource is now part of the stable channel.
Fixes #1828
```release-note
NONE
```

Removes Experimental from RefGrant Docs

---

pkg/admission/server_test.go
site-src/api-types/referencegrant.md
site-src/concepts/api-overview.md
site-src/concepts/guidelines.md

/kind bug
Removes stale `forwardTo` references or updates the reference to `backendRefs`.
Fixes #1831 
```release-note
NONE
```

Removes ForwardTo References Throughout

---

apis/v1beta1/gateway_types.go
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml

This PR adds `Programmed` to the documentation of known `Gateway` conditions.
No issue identified
```release-note
NONE
```

Add Programmed to known gateway condition types

---

site-src/guides/index.md

Keep the list of resources on gateway API installation guide page: https://gateway-api.sigs.k8s.io/guides/ to be synchronized to the actual status in latest release. 
Fixes #1846
```release-note
Documentation: updated outdated content on list of resources in installation guide page.
```

docs: update resources included in different channels in installation guide page

---

OWNERS_ALIASES

Add myself (@sunjayBhatia) to conformance reviewers alias to add to reviewer group as recommended by @robscott.
N/A
```release-note
NONE
```

Add sunjayBhatia to conformance reviewers

---

site-src/guides/multiple-ns.md

Corrected mistake in Cross-Namespace guide.
Fixes #
```release-note
```

Minor Documentation Correction

---

site-src/faq.md

Following the feedback from @robscott on #1862, this PR consolidates some of the FAQ answers and adds links to relevant docs.
Fixes #1862
```release-note
NONE
```

Refresh the FAQ

---

geps/overview.md

Fix GEP link

---

site-src/implementations.md

AWS Gateway API Controller is a new implementation of the Gateway API that may be of interest to the wider audience of the Gateway API project. 
Fixes #
```release-note
```

doc: Add Amazon EKS to the list of implementations

---

apis/v1alpha2/gatewayclass_types.go
apis/v1beta1/gatewayclass_types.go
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml

Addresses https://github.com/kubernetes-sigs/gateway-api/issues/1411#issuecomment-1498253632
Fixes #1411
```release-note
```

Loosen requirement for GC finalizer

---

site-src/implementations.md

/kind cleanup
https://github.com/kubernetes-sigs/gateway-api/pull/1916 merged through my requests for changes, which included a fix for a link. This PR is a follow up to add those changes.

docs: fix broken link for EKS

---

site-src/index.md

Fix a minor typo in index.md.
Fixes #
```release-note
```

Fix a minor typo in index.md.

---

site-src/guides/index.md

Fix wrong grpc link in guides docs.
Fixes #1951
```release-note
NONE
```

Fix wrong grpc link in guides docs.

---

conformance/utils/roundtripper/roundtripper.go

/kind cleanup
Avoid printing the complete CertPem and KeyPem
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1903
```release-note
NONE
```

cleanup: Add String() function for roundtripper.Request

---

site-src/implementations.md

Update Envoy Gateway support in #implementations

---

conformance/utils/roundtripper/roundtripper.go

/kind test
This slightly changes previous approach, just merged in https://github.com/kubernetes-sigs/gateway-api/pull/1959
Instead of extending Request struct, extend DefaultRoundTripper. Extending Request was problematic, because Request is constructed in other function https://github.com/kubernetes-sigs/gateway-api/blob/ef75c8a50f70736bb3489e13a1357d89de8c282f/conformance/utils/http/http.go#L99 and we don't want to extend it. Plus, we still want tlsConfig to be added even for custom dialers
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1945
```release-note
NONE
```
/cc @briantkennedy

Extend DefaultRoundTripper with CustomDialContext

---

CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
hack/verify-examples-kind.sh
pkg/generator/main.go

This adds the changelog for v0.7.0-rc1. Approving this PR means that you are approving a release of v0.7.0-rc1 based on the current state of the "main" branch.
/hold

Changelog for v0.7.0-rc1

---

mkdocs.yml

Add GEP-1897 to documentation index
```release-note
NONE
```

GEP-1897 Add to docs index

---

CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
config/webhook/admission_webhook.yaml
pkg/generator/main.go

This adds a changelog for v0.7.0-rc2. By approving this PR, you're approving the release of v0.7.0-rc2.
/cc @bowei @shaneutt @youngnick 

Adding changelog for v0.7.0-rc2

---

site-src/implementations.md

Update documentation to note that Contour v1.25.0 supports Gateway API v0.6.2
N/A
```release-note
NONE
```

Update Contour implementation documentation

---

geps/gep-1426.md
geps/gep-1686.md

/kind gep
This has now met the bar to be promoted to Implementable, per https://gateway-api.sigs.k8s.io/geps/overview/?h=#process, as the GEP doc is complete. In fact, it has already been implemented by 2 vendors and has (some) conformance tests.
Fixes #
```release-note
```

mesh: mark GEPs as Implementable

---

mkdocs.yml

Adds GEP-1619 to mkdocs which adds it to https://gateway-api.sigs.k8s.io/geps/overview/ webpage
N/A
```release-note
NONE
```

GEP-1619: Add to mkdocs

---

config/crd/kustomization.yaml

/kind bug
Fixes #
```release-note
Added the missing ReferenceGrant resource the kustomization.yaml for the standard channel
```

Update kustomization.yaml to include reference grant

---

docker/Dockerfile.webhook

/kind cleanup
Go1.19 will be EOL in a few months
```release-note
NONE
```

use go1.20

---

OWNERS_ALIASES

As discussed offline, added myself (@LiorLieberman ) to conformance reviewers.
N/A
```release-note
NONE
```
/cc @robscott 
/assign @robscott

Add LiorLieberman to conformance reviewers

---

geps/gep-1282.md
mkdocs.yml

/kind cleanup
/kind gep
We are not going to complete GEP-1282, so it's better to make this formal, and decline it.
Fixes #1282 
```release-note
GEP-1282, Backend Properties, has been declined.
```

Move GEP-1282 to declined

---

mkdocs.yml

Fixes #2112
```release-note
Added missing GEPs.
```

Add missing geps to mkdocs

---

OWNERS_ALIASES

/kind cleanup
Implements the leadership change proposed in https://groups.google.com/g/kubernetes-sig-network/c/lfeAlMAgTq0
```release-note
NONE
```
---
Below is copied from [contributors/chairs-and-techleads/leadership-changes.md](https://github.com/kubernetes/community/blob/master/contributors/chairs-and-techleads/leadership-changes.md) with the section on where changes need to be made modified to reflect Gateway API project organization.
This document covers steps needed to propose changes to SIG/WG/UG leadership.
mailing list. At a minimum, the email should contain:
or concerns (current leads + [steering-private]) about the nomination
files in the respective repos: …

add Flynn as GAMMA lead, remove Mike Morris

---

site-src/contributing/devguide.md

This PR adds a link from the dev guide to the conformance test guide, which should make it easier to find for newer contributors.
None
```release-note
NONE
```

Link to the conformance test guide from the dev guide

---

apis/v1beta1/gateway_types.go
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml

List of values not displaying correctly in generated doc
Fixes #
```release-note
NONE
```

Fix list format in FromNamespaces doc

---

site-src/implementations.md

The PR adds WSO2 APK to the list of implementations in the docs.
None
None

Add WSO2 APK implementation to docs

---

site-src/api-types/httproute.md

update the matches example to avoid misunderstanding
Fixes #
```release-note
NONE
```

docs(site-src): update the example for the matches

---

site-src/implementations.md

Adds https://kuadrant.io/ to the list of Gateway API integrations.
n/a
n/a

Add Kuadrant to integrations

---

conformance/utils/suite/experimental_suite.go

This ensures they stay in sync
The Setup diverged from the main, causing issues.
* No mesh support at all
* Secrets for TLS tests missed some updates
Fixes #
```release-note
NONE
```

conformance profiles: fix divergence in experimental code

---

conformance/apis/v1alpha1/conformancereport.go
geps/gep-1709.md

Update of the `ConformanceReport` documentation to include issues link in the contact section.
Fixes #
```release-note
NONE
```

`ConformanceReport`'s contact field update

---

conformance/results/nginx-kubernetes-gateway.yaml

Adds conformance profile for NGINX Kubernetes Gateway.
```release-note
NONE
```

Add Conformance Profile for NGINX Kubernetes Gateway

---

site-src/implementations.md

Update to docs to add Azure's Application Gateway for Containers service as an implementor of Gateway API..
N/A
Fixes #
```release-note
```

Docs - Implementations - Application Gateway for Containers

---

conformance/results/kuma.yaml

Adds ConformanceReport for Kuma's main branch
```release-note
NONE
```

Add initial conformance results for Kuma

---

conformance/results/cilium.yaml

The conformance tests are run with Cilium v1.14.0.
This PR is to add the conformance report for Cilium version v1.14.0.
NA
```release-note
NONE
```

conformance: Add Conformance report for cilium

---

CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
pkg/generator/main.go

This introduces a changelog for v0.8.0-rc1.
```release-note
NONE
```
/cc @bowei @howardjohn @keithmattix @kflynn @shaneutt @youngnick
/hold

Adding changelog for v0.8.0-rc1

---

site-src/implementations.md

Updates Cilium's implementation details for the most recent release.

Update Cilium implementation details for Cilium 1.14

---

site-src/implementations.md

Fix typo in the document.
Fixes #
```release-note
```
NONE

doc:fix implementations.md typo

---

apis/v1alpha2/grpcroute_types.go
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
pkg/test/cel/grpcroute_test.go

/kind feature
CEL validation enables validation of GRPCRoute CRs without a webhook.
```release-note
Add CEL validation for GRPCRoute.
```

Add CEL validation to GRPCRoute

---

apis/v1alpha2/grpcroute_types.go
apis/v1beta1/httproute_types.go
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
hack/verify-crds-kind.sh

/kind feature
/kind cleanup
Fixes https://github.com/kubernetes-sigs/gateway-api/pull/2245#discussion_r1295302867
```release-note
NONE
```

Simplify CEL validation of the form 'X cannot be repeated' by using filter() macro

---

conformance/utils/suite/experimental_profiles.go
conformance/utils/suite/features.go

/kind bug
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2349
```release-note
Fix not-existed extended http profile features
```

fix: conformance profile not-existed extented features

---

geps/gep-1867.md
geps/overview.md

Link to `/geps/gep-XXX.md` result in broken link. Removes `.md` to become `/geps/gep-XXX`.
`geps/gep-1867.md`: Fix broken links to GEP 1651, remove references to GEP 1713, 1762
`geps/overview.md`: Fix broken link to GEP 696
/kind cleanup
Fixes broken links to GEPs in the website
N/A
N/A

Fix broken links to GEPs

---

conformance/reports/v0.8.0/projectcontour-contour.yaml
site-src/implementations.md

Updates contour implementation blurb on the site and add updated conformance report for contour v1.26.0
N/A
```release-note
NONE
```

Update Contour implementation summary and conformance report

---

conformance/reports/v0.8.0/nginxinc-nginx-kubernetes-gateway.yaml
site-src/implementations.md

Updates conformance profile for NGINX Kubernetes Gateway.
```release-note
NONE
```

Update conformance report for NGINX Kubernetes Gateway

---

site-src/implementations.md

Update Flomesh Gateway API implementation details and add links to compatibility matrix and how-to.
N/A
```release-note
NONE
```

Update Flomesh implementation details

---

geps/gep-1742.md

/kind gep
Sync with go apis.
Fixes #
```release-note
NONE
```

Update GEP-1742 with latest comments from go apis

---

Makefile

/kind cleanup
https://github.com/kubernetes-sigs/gateway-api/pull/2327 removed the experimental tag from the experimental conformance test suite. The makefile wasn't updated accordingly, therefore this PR aims at removing the experimental tag from the makefile as well.
Fixes #
```release-note
NONE
```

remove experimental tag from Makefile

---

conformance/reports/v0.8.0/envoy-gateway.yaml
site-src/implementations.md

feat: add envoy gateway conformance report

---

conformance/tests/httproute-request-multiple-mirrors.go
conformance/tests/httproute-request-multiple-mirrors.yaml

/kind bug
Fixes #2394
```release-note
NONE
```

Fix multiple mirror conformance test

---

CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
config/webhook/admission_webhook.yaml
pkg/generator/main.go
site-src/guides/index.md

This adds the changelog for v0.8.1. By approving this changelog you approve the release of v0.8.1.
```release-note
NONE
```

Adding v0.8.1 Changelog

---

conformance/reports/v0.8.0/kumahq-kuma.yaml
site-src/implementations.md

Adds Kuma conformance report for `v0.8.0`.
```release-note
NONE
```

conformance: update Kuma's conformance report and implementation badge/section

---

apis/v1alpha2/policy_types.go

/kind feature
Add the constant `gateway.networking.k8s.io/policy` used to identify a policy CRD to the policy related specs file. 
Fixes #
```release-note
NONE
```
/assign @robscott

Add policy identifier label to policy API spec

---

conformance/reports/v0.8.1/cilium-cilium.yaml
site-src/implementations.md

conformance: Add v0.8.1 conformance report for Cilium

---

site-src/implementations.md

The PR updates the WSO2 APK implementation status in the docs.
None
```release-note
NONE
```

Update WSO2 APK implementation status in docs

---

mkdocs.yml

/kind cleanup
Fixes a mistake I introduced with the implementer's guide.
Updates #2469
```release-note
NONE
```

Fix mkdocs.yml :facepalm:

---

conformance/base/manifests.yaml
conformance/mesh/manifests.yaml

/kind cleanup
This is the follow up from #2447 and should unblock https://github.com/kubernetes-sigs/gateway-api/pull/2254. 
```release-note
NONE
```
/cc @frankbu @SRodi

Adding new images for conformance tests

---

apis/v1alpha2/backendtlspolicy_types.go
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml

/kind cleanup
This will allow `gwctl` to recognize `BackendTLSPolicy`
Fixes #
```release-note
NONE
```

Add policy label to BackendTLSPolicy to make it recognizable in gwctl

---

.github/dependabot.yml

/kind feature
Reduce the number of PR with golang dependencies. 
Fixes #
```release-note
NONE
```
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>

dependabot: group k8s.io golang dependencies

---

CHANGELOG.md
config/webhook/admission_webhook.yaml

This adds the changelog for v1.0.0-rc1. By approving this PR, you're also approving the release of v1.0.0-rc1.
```release-note
NONE
```
/cc @thockin @khenidak @MikeZappa87
/assign @bowei @shaneutt @youngnick 

Adding changelog for v1.0.0-rc1

---

hack/update-conformance-image-refs.sh

/kind cleanup
/kind test
Updating the echo images and testing them locally with conformance tests is now much easier.
You can simply edit the docker files or the code then run the following commands
```
$ make release-staging
... docker build will push to $REGISTRY
$ make update-conformance-image-refs
... will look up latest tags for $REGISTRY/echo-* and update conformance manifests
```
Fixes #
```release-note
NONE
```

Updating conformance images will now respect REGISTRY env var

---

geps/gep-1911.md

Fixes #
```release-note
NONE
```

Fix many broken links in GEP-1911

---

geps/gep-1911.md
mkdocs.yml

/kind gep
With conformance tests landing marking GEP-1911 as experimental
NONE
```release-note
NONE
```

Mark GEP-1911 as Experimental

---

gwctl/README.md

Updates steps to Try It Out Guide for gwctl as current steps result in failure.
N/A no issue
```release-note
NONE
```

update steps to try it out for gwctl

---

site-src/implementations.md

Add Easegress implementation.
```release-note
NONE
```

Add Easegress implementation

---

geps/OWNERS

Add kind/gep label whenever PR contains gep files.
Fixes 
- https://github.com/kubernetes-sigs/gateway-api/issues/2431
```release-note
NONE
```

Add kind/gep owner label for geps files

---

conformance/reports/v0.8.1/nginxinc-nginx-gateway-fabric.yaml
site-src/implementations.md

Updates conformance profile for NGINX Gateway Fabric.
Fixes #
```release-note
NONE
```

Update conformance report for NGINX Gateway Fabric

---

examples/experimental/v1alpha2/backendtlspolicy-ca-certs.yaml
examples/experimental/v1alpha2/backendtlspolicy-system-certs.yaml
site-src/guides/tls.md

Add documentation for v1alpha2 BackendTLSPolicy.
Fixes #2483
```release-note
Documentation added for v1alpha2 BackendTLSPolicy.
```

Add documentation for BackendTLSPolicy

---

mkdocs.yml
site-src/api-types/httproute.md
site-src/guides/backend-protocol.md

/kind gep
This PR surfaces details of the backend protocol GEP on the user facing docs site.
```release-note
NONE
```

include a section for backend protocol in the website

---

site-src/implementations.md

/kind docs
Fixes #
```release-note
NONE
```

chore: badge updated with Kong GA

---

conformance/reports/v1.0.0/cilium.yaml
site-src/implementations.md

The report is generated by our CI run, small modification on versions
Fixes #
```release-note
NONE
```

docs: Add Cilium conformance report for v1.0.0

---

conformance/reports/v1.0.0/gloo-gateway.yaml
site-src/implementations.md

This PR adds a conformance report for gloo gateway against gateway API v1.0.0
Fixes #
```release-note
NONE
```

conformance: Gloo Gateway report for v1.0.0 

---

conformance/reports/v1.0.0/istio-istio.yaml
site-src/implementations.md

Updated information for Istio implementation.
Fixes #
```release-note
NONE
```

Update conformance report for Istio implementation

---

gwctl/cmd/main.go
gwctl/pkg/cmd/describe/describe.go
gwctl/pkg/cmd/get/get.go
gwctl/pkg/cmd/utils/printer/backends.go
gwctl/pkg/cmd/utils/printer/gatewayclasses.go
gwctl/pkg/cmd/utils/printer/gatewayclasses_test.go
gwctl/pkg/cmd/utils/printer/gateways.go
gwctl/pkg/cmd/utils/printer/gateways_test.go
gwctl/pkg/cmd/utils/printer/httproutes.go
gwctl/pkg/cmd/utils/printer/httproutes_test.go
gwctl/pkg/cmd/utils/printer/policies.go
gwctl/pkg/cmd/utils/printer/policies_test.go
gwctl/pkg/common/resourcehelpers/backends.go
gwctl/pkg/common/resourcehelpers/gatewayclasses.go
gwctl/pkg/common/resourcehelpers/gateways.go
gwctl/pkg/common/resourcehelpers/httproutes.go
gwctl/pkg/effectivepolicy/backends.go
gwctl/pkg/effectivepolicy/gatewayclasses.go
gwctl/pkg/effectivepolicy/gateways.go
gwctl/pkg/effectivepolicy/httproutes.go

/kind cleanup
-->
This PR removed unused imports and re structure imports in `gwctl`
Fixes  #2571
NONE
```release-note
NONE
```

[gwctl] Cleanup import packages in gwctl 

---

geps/gep-2162.md
mkdocs.yml

/kind cleanup
```release-note
NONE
```

 gep-2162 - small fixes + bump to experimental

---

conformance/tests/httproute-timeout-backend-request.yaml
conformance/tests/httproute-timeout-request.yaml

/kind test
```release-note
```

conformance: Update API version for timeout HTTPRoutes

---

conformance/utils/suite/experimental_suite.go

/kind bug
Generating a conformance report with `--all-features` set doesn't include any features in the `extended.supported-features` section of the report. It should include all the features that are covered by the profiles, same as if `--supported-features` was used to pass the full list instead.
Before:
```
- core:
result: success
statistics:
Failed: 0
Passed: 29
Skipped: 0
summary: ""
extended:
result: success
statistics:
Failed: 0
Passed: 12
Skipped: 0
summary: ""
name: HTTP
```
After:
```
- core:
result: success
statistics:
Failed: 0
Passed: 29
Skipped: 0
summary: ""
extended:
result: success
statistics:
Failed: 0
Passed: 12
Skipped: 0
summary: ""
supportedFeatures:
- HTTPRoutePathRedirect
- …
```

Conformance report should include supported features for AllFeatures

---

site-src/implementations.md

Avi Kubernetes Operator(AKO) now supports Gateway API. This PR adds AKO to the list of implementations
Fixes #
"None"

Add Avi Kubernetes Operator (AKO) to the list of implementations

---

site-src/concepts/gamma.md
site-src/index.md

Fixes broken links for TCPRoute references in documentation
No issue logged as this is a small fix. Happy to create one if required though!
```release-note
Fixing broken links for TCPRoute references in documentation
```

Fixing broken documentation link to TCPRoute

---

netlify.toml

- Update netlify.toml
- set `GO_VERSION` environment
- Fixes #2650 
```release-note
NONE
```

Update netlify.toml - add GO_VERSION environment

---

geps/gep-713.md

It fixes an example in GEP-713 to correctly refer to the target HTTPRoute name.
```release-note
none
```

gep-713: target ref name fixed to refer to HTTPRoute name

---

.github/ISSUE_TEMPLATE/documentation.md

/kind cleanup
This should make it easier for anyone to file a docs issue.
```release-note
NONE
```

Adding documentation issue template

---

geps/gep-713.md

Signed-off-by: spacewander <spacewanderlzx@gmail.com>
The value should be the policy type, not `true`.
Fixes #
```release-note
NONE
```

gep-713: correct label value

---

mkdocs.yml
requirements.txt
site-src/concepts/versioning.md
site-src/guides/api-design.md
site-src/guides/crd-management.md
site-src/guides/implementers.md
site-src/guides/index.md

This adds a new CRD Management Guide. This also moves other guides to the "guides" section of the documentation and makes some small tweaks to those in the process.
Fixes #2672
Fixes #2319 
```release-note
NONE
```

Adding new CRD Management Guide

---

conformance/base/manifests.yaml
conformance/mesh/manifests.yaml
conformance/tests/mesh-frontend.go

Bump conformance images

---

conformance/tests/mesh-frontend.go
conformance/utils/http/http.go

Fix a conformance test when running on ipv6

---

geps/gep-713/index.md

One of the examples uses undefined "type" field in `targetRef` which I removed. Also removed reference to "indirect" since inherited seems to be the only indirect policy attachment and inherited was already mentioned so the additional reference to "indirect" was confusing.
```release-note
NONE
```

gep-713: remove the type field from targetRef. Also remove reference to undefined 'indirect' type in text

---

RELEASE.md

docs: Update the GitHub Case

---

site-src/concepts/versioning.md

Removed .md extension from the link to make the MKDocs page work
Fix documentation link
not applicable
NONE

Fixed relative link to CRD management guide article

---

conformance/reports/v1.0.0/kong-kubernetes-ingress-controller.yaml

Add Kong Kubernetes Ingress Controller v3.0.2 conformance report
```release-note
NONE
```

conformance: Kong Kubernetes Ingress Controller v3.0.2 report

---

.openvex/templates/README.md
.openvex/templates/main.openvex.json

Adding the directory which contains the OpenVEX data for this repository.
The files stored in this directory are used as templates by
`vexctl generate` when generating VEX data for a release or 
a specific artifact.
To add new statements to publish data about a vulnerability,
download [vexctl](https://github.com/openvex/vexctl)
and append new statements using `vexctl add`. For example:
```
vexctl add --in-place main.openvex.json pkg:oci/test CVE-2014-1234567 fixed
```
That will add a new VEX statement expressing that the impact of
CVE-2014-1234567 is under investigation in the test image. When
cutting a new release, for `pkg:oci/test` the new file will be
incorporated to the relase's VEX data.
/kind feature
**Which …

add: VEX Feed to repository

---

site-src/guides/implementers.md
site-src/guides/index.md

its broken link for crd- management at multiple places
**Which issue(s) this PR fixes**: 
Fixes #2724 
NONE
```release-note
NONE
```

updated broken link for crd-management

---

geps/gep-1709/index.md

/kind gep
This PR updates GEP-1709 with the following goals:
- introduce a more structured approach to upload and store multiple conformance reports coming from different implementations.
- improve the `conformanceReport` API to include the implementation mode used during the certification process.
- introduce the `To reproduce` field in a README.md file with the steps to reproduce the claimed report. This improves the projects' accountability.
Fixes #2233 
```release-note
NONE
```

Conformance profiles modes and versions

---

conformance/reports/v1.0.0/cilium.yaml

/kind cleanup 
Related to https://github.com/kubernetes-sigs/gateway-api/issues/2550 (and somewhat: https://github.com/kubernetes-sigs/gateway-api/issues/2740. Guidelines on what fields would be required in the conformance report will help with parsing displayed results!)
Other implementations provided listing out extended supported features, adding in Cilium's so that it can help with how conformance reports are displayed. 
Fixes # n/a
```release-note
NONE
```

List Cilium's extended supported features 

---

conformance/reports/v1.0.0/kumahq-kuma.yaml
site-src/implementations.md

Adds Kuma conformance report for `v1.0.0`.
```release-note
NONE
```

 conformance: update Kuma's conformance report and badge for v1.0.0

---

conformance/reports/v1.0.0/projectcontour-contour.yaml
site-src/implementations.md

Contour v1.28.1 supports Gateway API v1.0.0, add conformance report for this version.
N/A
```release-note
NONE
```

Add contour conformance report for v1.0.0

---

.github/dependabot.yml

/kind bug
Enable dependabot for `/gwctl` and `/conformance/echo-basic/`.
/cc @youngnick @robscott 
Fixes #2780 
```release-note
NONE
```

Enable dependabot for `/gwctl` and `/conformance/echo-basic/`

---

conformance/apis/v1alpha1/conformancereport.go
conformance/experimental_conformance_test.go
conformance/utils/flags/experimental_flags.go
conformance/utils/suite/experimental_suite.go
conformance/utils/suite/experimental_suite_test.go
pkg/consts/consts.go
pkg/generator/main.go

/kind feature
Gateway API version and channel are properly discovered during experimental conformance suite runs and set in the conformance report.
Fixes #2738 
```release-note
Gateway API Channel has been added to the conformance report API. Gateway API version and channel are properly discovered during experimental conformance suite runs and set in the conformance report.
```

feat: CRD version and channel added to conformance reports

---

examples/experimental/basic-grpc.yaml
examples/standard/basic-http.yaml
examples/standard/gateway-addresses.yaml
examples/standard/http-redirect.yaml
examples/standard/simple-gateway/gateway.yaml
examples/standard/tls-basic.yaml
examples/standard/tls-cert-cross-namespace.yaml
examples/standard/wildcard-tls-gateway.yaml
geps/gep-1651/index.md
hack/invalid-examples/standard/gateway/duplicate-listeners.yaml
hack/invalid-examples/standard/gateway/hostname-tcp.yaml
hack/invalid-examples/standard/gateway/hostname-udp.yaml
hack/invalid-examples/standard/gateway/invalid-addresses.yaml
hack/invalid-examples/standard/gateway/invalid-listener-name.yaml
hack/invalid-examples/standard/gateway/invalid-listener-port.yaml
hack/invalid-examples/standard/gateway/invalid-tls-mode.yaml
hack/invalid-examples/standard/gateway/tlsconfig-tcp.yaml
site-src/guides/simple-gateway.md

* Update acme-lb with example-gatewayClass to make it more obvious that it is a placeholder gatewayClass that is intended to be replaced.
* Add explanations and reference in simple-gateway.md on Gateway and GatewayClass concepts.
Make it more clear that `acme-lb` is meant to be a placeholder, and add reference to a list of available GatewayClass.
Fixes #2697
No, it is a doc change.

Update acme-lb with example-gatewayClass.

---

gwctl/pkg/printer/gateways.go
gwctl/pkg/printer/gateways_test.go

/kind feature
/area gwctl
/cc @gauravkghildiyal 
Sort gateways by name and gatewayclass in `gwctl get gateways`.
Ref. https://github.com/kubernetes-sigs/gateway-api/pull/2805#discussion_r1509893822
Fixes #
```release-note
NONE
```

Sort gateways by name and gatewayclass

---

gwctl/cmd/get.go

/kind bug
/area gwctl
/cc @gauravkghildiyal 
The code that injects the real clock into `gwctl get policies` was accidentally missed.
Fixes #
```release-note
NONE
```

Inject a real clock into `gwctl get policies`

---

mkdocs.yml

/kind cleanup
Make the `gwctl` GEP visible in the list of all GEPs under https://gateway-api.sigs.k8s.io/geps/overview/
Fixes #
```release-note
NONE
```
/assign @youngnick

Add gwctl memorandum GEP to mkdocs

---

site-src/implementations.md

update envoy version from 0.6.0 to 1.0.0

Update envoy gateway version

---

conformance/base/manifests.yaml
conformance/tests/udproute-simple.yaml

/kind bug
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2905
```release-note
NONE
```

fix: move udp-gateway into specific test fixture

---

site-src/implementations.md

[ngrok](https://ngrok.com/) has created a Gateway API implementation. This is an entry for the implementations page listing it and providing additional information.
Fixes #2842 
```release-note
NONE
```

Adding ngrok Gateway API Implementation to Implementations page

---

gwctl/pkg/printer/namespace.go

/kind bug
/area gwctl
/cc @gauravkghildiyal 
Sort `gwctl describe namespace` outputs by name.
Ref. https://github.com/kubernetes-sigs/gateway-api/pull/2865#issuecomment-2014316086
Fixes #
```release-note
NONE
```

Sort `gwctl describe namespace` outputs by name

---

gwctl/cmd/describe.go
gwctl/cmd/get.go
gwctl/cmd/root.go
gwctl/pkg/printer/gatewayclasses_test.go
gwctl/pkg/printer/namespace_test.go
gwctl/pkg/resourcediscovery/discoverer.go

some files aren't gofumpt'd
```release-note
NONE
```

gofumpt the code

---

conformance/reports/v1.0.0/projectcontour-contour/README.md
conformance/reports/v1.0.0/projectcontour-contour/v1.28.2-report.yaml
site-src/implementations.md

Adds conformance report and implementation page update for Contour v1.28.2
N/A
```release-note
NONE
```

Add conformance report for Contour v1.28.2

---

conformance/tests/httproute-timeout-backend-request.go
conformance/tests/httproute-timeout-backend-request.yaml
conformance/tests/httproute-timeout-request.go
conformance/tests/httproute-timeout-request.yaml

/kind cleanup
/kind test
This tests includes tests cases for when the timeout is explicitly disabled 
N/A
```release-note
NONE
```

Timeouts - add test case for disabling a timeout

---

README.md
conformance/reports/README.md
site-src/concepts/conformance.md

Fixes #2322
Fixes #2921 
```release-note
```

docs: conformance suite documentation

---

conformance/reports/v0.8.1/projectcontour-contour/README.md
conformance/reports/v0.8.1/projectcontour-contour/v1.27.1-report.yaml
conformance/reports/v0.8.1/projectcontour-contour/v1.27.2-report.yaml
conformance/reports/v1.0.0/projectcontour-contour/README.md
conformance/reports/v1.0.0/projectcontour-contour/v1.28.3-report.yaml
site-src/implementations.md

Adds conformance reports and implementation page update for Contour v1.27.1, v1.27.2, and v1.28.3
N/A
```release-note
NONE
```

add Contour conformance reports for v1.27.1, v1.27.2, v1.28.3

---

conformance/base/manifests.yaml

This is already used for `infra-backend`, and is codified in Kubenetes (https://kubernetes.io/docs/concepts/services-networking/service/#application-protocol)
Fixes #
```release-note
NONE
```

gRPC conformance: specify appProtocol

---

conformance/base/manifests.yaml
conformance/mesh/manifests.yaml

Primary motivation for this is to get the GRPC conformance tests on the main images; the unofficial ones do not support ARM64.
Fixes #
```release-note
NONE
```

conformance: update test images

---

config/crd/kustomization.yaml

/kind cleanup
Since GRPCRoute has already GA, we should add it to kustomization.yaml
Fixes #
```release-note
NONE
```

chore: add GRPCRoute to kustomization.yaml

---

apis/v1/gateway_types.go
apis/v1/gatewayclass_types.go
apis/v1/httproute_types.go
apis/v1beta1/gateway_types.go
apis/v1beta1/gatewayclass_types.go
apis/v1beta1/httproute_types.go
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml

/kind cleanup
Since the resources of version v1 were already added last year and have been announced as GA, I believe we can set the storage version to v1.
Fixes #
```release-note
Change the GA resources storage version from v1beta1 to v1.
```

chore: setting GA resource storage version to v1 instead of v1beta1

---

conformance/tests/httproute-service-types.go

/kind test
/kind bug
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/2986
```release-note
NONE
```

Add the correct IP to the EndpointSlice

---

site-src/implementations.md

Hi everyone ✋. I'm one of the Kuma contributors and wanted to update the docs as Kuma's implementation of Gateway API (including GAMMA) went from experimental to GA in [2.7.0](https://github.com/kumahq/kuma/releases/tag/2.7.0). I also updated link to the docs.
Fixes #2995
```release-note
NONE
```

docs(implementations): update Kuma's implemetation status to GA

---

site-src/concepts/conformance.md

/kind bug
A couple of broken links in the docs have been fixed.
Fixes #
```release-note
NONE
```

fix: broken links in docs

---

site-src/api-types/backendtlspolicy.md

/kind cleanup
One diagram for [BackendTLSPolicy](https://gateway-api.sigs.k8s.io/api-types/backendtlspolicy/) doc is not getting rendered: 
Fixes #
```release-note
NONE
```

fix typo in BackendTLSPolicy flowchart

---

config/crd/experimental/kustomization.yaml

/kind bug
Dropped in #2955 for some reason. Since it was unrelated to that PR and had no discussion, I assume it was accidental
Fixes #
```release-note
NONE
```

Add experimental kustomize back

---

CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
conformance/utils/suite/suite_test.go
pkg/consts/consts.go

This adds the changelog for v1.1.0-rc2 and makes corresponding version bumps.
```release-note
NONE
```
/assign @shaneutt @youngnick 
/hold

Adding changelog for v1.1.0-rc2

---

conformance/reports/v0.8.1/projectcontour-contour/README.md
conformance/reports/v0.8.1/projectcontour-contour/v1.27.3-report.yaml
conformance/reports/v1.0.0/projectcontour-contour/README.md
conformance/reports/v1.0.0/projectcontour-contour/v1.28.4-report.yaml
conformance/reports/v1.0.0/projectcontour-contour/v1.29.0-report.yaml
site-src/implementations.md

Adds Contour 1.29.0, 1.28.4, 1.27.3 reports.
Fixes #
```release-note
NONE
```
cc @sunjayBhatia

Contour conformance report updates

---

config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
conformance/utils/suite/suite_test.go
pkg/consts/consts.go

Bumps CRD versions to v1.2-dev.
```release-note
NONE
```

Bumping version to v1.2-dev

---

conformance/reports/v1.1.0/istio-istio/1.22-report.yaml
conformance/reports/v1.1.0/istio-istio/README.md
site-src/implementations.md

Updates Istio status.
Fixes #
```release-note
NONE
```

Update Istio status for Istio 1.22 and GW v1.1

---

site-src/implementations.md

Forgot to bump this
Fixes #
```release-note
NONE
```

docs: fix Istio version badge

---

config/crd/experimental/kustomization.yaml

Kustomization does not install this new CRD because it is not on the list of resources.
/kind bug
Fixes installation of experimental CRDs using kustomization.
```release-note
NONE
```

fix: Add BackendLBPolicy to experimental kustomization

---

gwctl/go.mod
gwctl/pkg/common/clients.go
gwctl/pkg/printer/backends.go
gwctl/pkg/printer/backends_test.go
gwctl/pkg/printer/gatewayclasses.go
gwctl/pkg/printer/gateways.go
gwctl/pkg/printer/httproutes.go
gwctl/pkg/printer/namespace.go
gwctl/pkg/printer/policies.go
gwctl/pkg/printer/printer.go

Fixes #
```release-note
Optimize print and reduce repeated logic. Maintain agreement with print methods of other resources
```

[gwctl]Optimize Print in backends

---

examples/experimental/v1alpha3/backendtlspolicy-ca-certs.yaml

/kind bug
Fix the wrong kind in example of BackendTLSPolicy 
N/A.
Fixes #
```release-note
NONE
```

fix: kind of CACertificateRefs should be ConfigMap

---

site-src/api-types/referencegrant.md

"apiVersion" is existing in other yaml examples under api-types/.
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
Fix the example of ReferenceGrant
Fixes #
```release-note
NONE
```

Add missing apiVersion in the referencegrant API docs

---

conformance/reports/v1.1.0/cilium-cilium/README.md
conformance/reports/v1.1.0/cilium-cilium/experimental-1.16-default-report.yaml

conformance: Add Cilium report for v1.1.0
N/A
```release-note
NONE
```

conformance: Add Cilium report for v1.1.0

---

conformance/reports/v1.1.0/traefik-traefik/README.md
conformance/reports/v1.1.0/traefik-traefik/experimental-v3.1.0-default-report.yaml
site-src/implementations.md

This pull request adds the conformance report for Traefik Proxy.
```release-note
NONE
```

Add conformance report for Traefik Proxy

---

apis/v1alpha2/backendlbpolicy_types.go
config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml

/kind cleanup
Add policy label to BackendLBPolicy to make it recognizable in gwctl
Fixes #
```release-note
NONE
```

Add policy label to BackendLBPolicy to make it recognizable in gwctl

---

site-src/implementations.md

Updates website implementations page to mark Istio service mesh Gateway API support as GA.
Refs https://istio.io/latest/blog/2024/gateway-mesh-ga/
```release-note
NONE
```
/cc @howardjohn

Update Istio service mesh implementation status to GA

---

geps/gep-713/index.md

cleanup
Just fix a typo when I read the doc.
Fixes #
```release-note
NONE
```

chore: fix typo in gep-713

---

site-src/implementations.md

Updated the NGINX Gateway Fabric description in the implementations doc to clear out some unnecessary wording and add relevant docs links.
Cleans up the NGINX Gateway Fabric description and adds relevant docs links.
```release-note
NONE
```

Update NGINX Gateway Fabric description

---

OWNERS_ALIASES

@LiorLieberman has been highly active and earned a promotion from conformance reviewer to approver, thank you Lior we appreciate your efforts on Gateway API! :vulcan_salute: 
/cc @mlavacca @robscott @youngnick

docs: promote Lior to conformance approver

---

conformance/reports/v1.1.0/cilium-cilium/README.md

As Cilium v1.16.0 is released, it's better to use the official version instead of RC.
NA
```release-note
NONE
```

report: Update cilium version

---

site-src/api-types/backendtlspolicy.md

Adds the link to the RFC 3986
```release-note
NONE
```

add link for rfc 3986

---

conformance/reports/v1.0.0/projectcontour-contour/experimental-v1.28.6-default-report.yaml
conformance/reports/v1.0.0/projectcontour-contour/experimental-v1.29.2-default-report.yaml
conformance/reports/v1.1.0/projectcontour-contour/README.md
conformance/reports/v1.1.0/projectcontour-contour/experimental-v1.30.0-default-report.yaml
site-src/implementations.md

Conformance reports for July Contour releases.
Fixes #
```release-note
NONE
```
cc @sunjayBhatia

conformance reports for July 2024 Contour releases

---

site-src/implementations.md

/kind cleanup
```release-note
none
```
/cc @arkodg

Update envoy-gw link implementations.md

---

conformance/reports/v1.1.0/kong-kubernetes-ingress-controller/README.md
conformance/reports/v1.1.0/kong-kubernetes-ingress-controller/experimental-v3.3.1-expressions-report.yaml

Kong Kubernetes Ingress controller  v3.3.1 was released this week.
This PR is for adding the conformance report.
Fixes #
```release-note
NONE
```

chore(conformance): add KIC v3.3.1 report

---

hack/test-crds-validation.sh
hack/verify-all.sh

/kind cleanup
Remove the `test-crds-validation.sh` execution from `make verify` to finalize the migration to the proper prow job.
Fixes #
```release-note
NONE
```

Finalize verify->crds-validation job migration

---

CHANGELOG/1.2-CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
conformance/utils/suite/suite_test.go
pkg/consts/consts.go

Update CHANGELOG
```release-note
NONE
```

Update CHANGELOG with v1.2.0-rc2 details

---

site-src/api-types/grpcroute.md

The page does not render at https://gateway-api.sigs.k8s.io/api-types/grpcroute/
It's referencing a file that is missing from the path.
Fixes #
```release-note
NONE
```

docs: Rendering Error for GRPCRoute page

---

config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
pkg/consts/consts.go

Fixes #
```release-note
NONE
```
/cc @robscott @shaneutt

chore: bump PR version for 1.2

---

site-src/guides/index.md

Fixes #
```release-note
NONE
```

docs: update manifests and upgrade notes

---

conformance/reports/v1.2.0/cilium-cilium/README.md
conformance/reports/v1.2.0/cilium-cilium/experimental-1.17-default-report.yaml

Fixes #
```release-note
NONE
```

conformance: Add Cilium report for v1.2.0

---

conformance/reports/README.md

Fixes #
```release-note
NONE
```

docs: improve documentation about the reports version

---

hack/mkdocs-generate-conformance.py

/kind cleanup
addresses a part of https://github.com/kubernetes-sigs/gateway-api/issues/3395, where v1.0.0 doesnt capture various conformance profiles. Fix the if stmt to reflect for future releases
https://github.com/kubernetes-sigs/gateway-api/issues/3395, although v1.2 isn't displayed yet since only one implementation has uploaded their report
Fixes #
https://github.com/kubernetes-sigs/gateway-api/issues/3395
```release-note
NONE
```

Fix conformance reporting script

---

conformance/reports/v1.2.0/envoy-gateway/README.md
conformance/reports/v1.2.0/envoy-gateway/experimental-v1.2.0-default-report.yaml

/kind test
-->
Adds a Conformance Report for Envoy Gateway supporting Gateway API v1.2.0 
Fixes #
```release-note
```

Add v1.2.0 conformance report for Envoy Gateway

---

conformance/reports/v1.1.0/airlock-microgateway/README.md
conformance/reports/v1.1.0/airlock-microgateway/experimental-4.4.0-default-report.yaml
site-src/implementations.md

Adds conformance report and updates implementation page for Airlock Microgateway v1.1.0
N/A
```release-note
NONE
```

conformance: Add Airlock Microgateway report for v1.1.0

---

CHANGELOG/1.1-CHANGELOG.md
README.md
config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
conformance/utils/suite/suite_test.go
pkg/consts/consts.go

Prepare README and bundle version for 1.1.1
Fixes #
```release-note
NONE
```

[release 1.1] Prepare release 1.1.1

---

CHANGELOG/1.1-CHANGELOG.md

When we released v1.1.1, we merged the changelog directly in the `release-1.1` branch. This PR cherry picks that commit to updating the CHANGELOG in main as well.
Fixes #
```release-note
NONE
```

Port  v1.1.1 changelog to main

---

docs/stylesheets/banner.css
override/partials/header.html
site-src/overrides/main.html

Add a banner with the Gateway API survey link.
Fixes #
```release-note
NONE
```

chore: add Gateway API survey banner

---

conformance/reports/v1.2.0/istio-istio/README.md
conformance/reports/v1.2.0/istio-istio/experimental-1.24-default-report.yaml

Bump Istio conformance report to the official release version
Fixes #
```release-note
NONE
```

Bump Istio conformance report to the official release version

---

mkdocs.yml
site-src/guides/infrastructure.md

Add a Guide for the `infrastructure` field on the `Gateway` object, standard in 1.2.0.
Fixes #3437
```release-note
NONE
```

Add docs for infrastructure field

---

conformance/reports/v1.2.0/kong-gateway-operator/README.md
conformance/reports/v1.2.0/kong-gateway-operator/standard-v1.4.0-expressions-report.yaml
site-src/implementations.md

Conformance report for the Kong Gateway Operator v1.4
Fixes #
```release-note
NONE
```

chore: add Conformance report for KGO 1.4

---

CHANGELOG/1.2-CHANGELOG.md

Changelog for v1.2.1
Fixes #
```release-note
NONE
```

Changelog for v1.2.1

---

config/crd/experimental/gateway.networking.k8s.io_backendlbpolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
conformance/utils/suite/suite_test.go
pkg/consts/consts.go

Bump of the bundle version before releasing `v1.2.1`
Fixes #
```release-note
NONE
```
/cc @robscott @youngnick @shaneutt

chore: bump bundle version to 1.2.1

---

hack/build-install-yaml.sh

/kind cleanup
Minor improvements on the `build-install-yaml.sh` script, that include:
- OS detection to run the proper formatting of `sed`
- iteration over files using blobs instead of `ls`
- variables wrapping with ""
Fixes #
```release-note
NONE
```

chore: minor fixes in build-install-yaml.sh

---

CHANGELOG/1.2-CHANGELOG.md
README.md

/kind cleanup
Fixes #
```release-note
NONE
```

Update readme with last version (1.2.1)

---

site-src/api-types/gatewayclass.md

The documentation contains a `parametersRef` example which does not match the validations for the field.
None
```release-note
NONE
```

Fix typo in documentation

---

conformance/reports/v1.2.0/gloo-gateway/README.md
conformance/reports/v1.2.0/gloo-gateway/experimental-v1.18.0-report.yaml

Adds a v1.2.0 conformance report for Gloo Gateway v1.18.0.
N/A
```release-note
NONE
```

Adds v1.2.0 Conformance Report for Gloo Gateway

---

conformance/reports/v1.2.1/kong-kubernetes-ingress-controller/README.md
conformance/reports/v1.2.1/kong-kubernetes-ingress-controller/experimental-v3.4.0-expressions-report.yaml
conformance/reports/v1.2.1/kong-kubernetes-ingress-controller/experimental-v3.4.0-traditional_compatible-report.yaml
site-src/implementations.md

Fixes #
```release-note
NONE
```

chore: conformance report for Kong Ingress Controller `v3.4.0`

---

CHANGELOG/0.x-CHANGELOG.md

This PR fixes broken references to gep-852 and gep-820 
Fixes #3535
```release-note
NONE
```

fix changelog broken links to gep-851 and gep-820

---

site-src/implementations.md

The reference or ngrok kubernetes operator is obselete because the repository is archived
The new repository is: https://github.com/ngrok/ngrok-operator
Fixes #3537
```release-note
NONE
```

fix: broken reference or ngrok kubernetes operator

---

conformance/reports/v1.2.1/istio-istio/README.md
conformance/reports/v1.2.1/istio-istio/experimental-1.24-default-report.yaml
site-src/implementations.md

Fixes #
```release-note
NONE
```

Add conformance report for  1.2.1 for Istio

---

site-src/implementations.md

/kind-documentation
Updates some links to resources for the Kuadrant project.
Fixes #
```release-note
Updated some docs for the Kuadrant implementation
```

Updating some Kuadrant docs and links

---

site-src/implementations.md

Documentation
This updates the Amazon Elastic Kubernetes Service to GA to align with the GA status of the controller [as of v.1.0.0 here](https://github.com/aws/aws-application-networking-k8s/releases/tag/v1.0.0).
Fixes #3599 
```release-note
None
```

Mark Amazon Elastic Kubernetes Service as GA

---

geps/gep-1651/index.md
geps/gep-1713/index.md
geps/gep-1742/index.md
geps/gep-1911/index.md
geps/gep-2659/index.md

the link is broken.
Fixes #
```release-note
NONE
```

docs: fix broken gep status link

---

conformance/reports/v1.2.1/cilium-cilium/experimental-1.17-default-report.yaml

The recently added Cilium conformance report is still with main version, which was recently fixed in https://github.com/cilium/cilium/pull/37671.
Relates: #3578.
```release-note
NONE
```

conformance: Correct Cilium version in 1.2.1

---

hack/update-clientset.sh

/kind cleanup
Ensures consistent sort order across hosts.
Fixes #
```release-note
NONE
```

sort api versions when updating clientset

---

site-src/implementations.md

The NGINX community slack is being sunsetted in favor of the new forum.
Fixes #
```release-note
NONE
```

Update NGINX Gateway Fabric communications

---

hack/mkdocs-generate-conformance.py

Per @youngnick's point in the meeting yesterday, have clarification on the docs page that conf reports submitted with skipped tests don't appear in the conformance tables 
Fixes #
```release-note
NONE
```

Add conformance clarification of skipped tests

---

pkg/features/httproute.go

/kind cleanup
Updates the conformance feature for `HTTPRouteRequestPercentageMirror` to Standard.
```release-note
NONE
```

Update SupportHTTPRouteRequestPercentageMirror to Standard

---

Makefile
mkdocs.yml
site-src/api-types/backendtrafficpolicy.md
site-src/reference/specx.md

Adds API documentation for the experimental BackendTrafficPolicy PolicyAttachment for the 1.3 release.
Fixes #
```release-note
NONE
```

GEP 3388 XBackendTrafficPolicy API Documentation

---

CHANGELOG/1.3-CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
pkg/consts/consts.go

This is the final PR for the first v1.3 release candidate.
```release-note
NONE
```
/assign @mlavacca @shaneutt @youngnick

Bumping version to v1.3.0-rc.1

---

pkg/features/gateway.go

/kind bug
The `SupportGatewayInfrastructurePropagation` feature has not been migrated to standard when the feature graduated. This PR fixes that.
Fixes #
```release-note
The SupportGatewayInfrastructurePropagation feature has been marked as standard.
```

fix(features): GatewayInfrastructure

---

.github/ISSUE_TEMPLATE/conformance-test.md
.github/PULL_REQUEST_TEMPLATE.md

/kind cleanup
The area/conformance label has been replaced by the pair area/conformance-test and area/conformance-machinery. This PR adapts the PR and issue templates to use them.
Fixes #
```release-note
NONE
```

chore: PR and issue templates use the new conformance labels

---

conformance/reports/v1.2.1/envoy-gateway/README.md

Fixes #
```release-note
NONE
```

fix(report): broken link

---

site-src/implementations.md

- Mark as GA
- Revise description that had a typo
- Update the badge based on [successful test report](https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/reports/v1.2.1/kgateway/v2.0.0-report.yaml)
- Follow up to https://github.com/kubernetes-sigs/gateway-api/pull/3725
```release-note
NONE
```

Doc update to kgateway

---

CHANGELOG/1.3-CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
pkg/consts/consts.go

/kind cleanup
This adds a changelog for v1.3.0-rc.2.
```release-note
NONE
```
/hold until we're ready to release

Changelog for v1.3.0-rc.2

---

CHANGELOG/1.3-CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
hack/build-install-yaml.sh
pkg/consts/consts.go

/kind cleanup
As I was prepping RC2, I decided it was past time to clean up this script. This is based off of the RC2 changelog PR (https://github.com/kubernetes-sigs/gateway-api/pull/3749) because I wanted to use this to generate the manifests for RC2. 
```release-note
NONE
```
/hold until #3749 merges

Simplify hack/build-install-yaml.sh

---

CHANGELOG/1.3-TEAM.md
geps/gep-1713/metadata.yaml
geps/gep-1767/metadata.yaml
geps/gep-3171/metadata.yaml
geps/gep-3388/metadata.yaml
geps/gep-696/metadata.yaml

Add 1.3 release team and update relevant GEPs

---

CHANGELOG/1.3-CHANGELOG.md
README.md
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
pkg/consts/consts.go
site-src/guides/index.md

This adds the changelog for v1.3. Merging this PR will trigger the release of v1.3.0.
```release-note
NONE
```

Adding changelog for v1.3.0

---

README.md

/kind cleanup
Fix v1.3.0 release URL in README.md. It previously pointed to an older release tag.
Fixes #
```release-note
NONE
```

Fix v1.3.0 release URL in README.md

---

site-src/guides/http-header-modifier.md

**What this PR does / why we need it**: 
Remove duplicate explanation
```release-note
NONE
```

rm duplicate explanation

---

site-src/implementations.md

Add Cloud Service Mesh to implementations.md
```release-note
NONE
```

Add Google Cloud Service Mesh to implementations.md

---

conformance/reports/v1.2.1/airlock-microgateway/standard-4.6.0-default-report.yaml

I mistakenly included the report from an unreleased version. This PR updates it with the correct report corresponding to the released version, replacing the one generated from the CI build.
Sorry for the inconvenience.
Fixes N/A
```release-note
NONE
```

conformance: fix typo in Airlock Microgateway report

---

geps/gep-1911/index.md

It's a typo in a GEP.
Typo in table header, the header was duplicated
None
None

fix(gep-1911): remove duplicated header in table

---

geps/gep-696/index.md
geps/gep-696/metadata.yaml

/kind gep
The possible states described in https://gateway-api.sigs.k8s.io/geps/overview/#gep-states don't match what's described in GEP-696.
Fixes #
```release-note
NONE
```

gep: update the possible states in GEP-696

---

conformance/reports/v1.3.0/nginx-nginx-gateway-fabric/experimental-2.0.0-default-report.yaml

/documentation
/conformance-test
Missed a conformance test in the report that is passing.
```release-note
NONE
```

Update NGINX Gateway Fabric conformance

---

site-src/implementations.md

Docs page update for Cilium v1.18 passing gateway-api v1.3.0 conformance tests.
```release-note
NONE
```

docs: update cilium implementation docs for gateway-api v1.3.0 conformance

---

pkg/features/features.go

/kind cleanup
Follow-up to #3826, adds GRPCRouteExtendedFeatures to AllFeatures list.
Fixes #
```release-note
NONE
```

add GRPCRouteExtendedFeatures to AllFeatures list

---

pkg/features/features.go

/kind cleanup
While reviewing #4046, I also noticed that the `BackendTLSPolicyExtendedFeatures` are also missing.
N/A
```release-note
NONE
```

add BackendTLSPolicyExtendedFeatures to AllFeatures list

---

geps/gep-3155/index.md

Update the documentation for GEP after introducing changes in https://github.com/kubernetes-sigs/gateway-api/pull/4009
Related to: https://github.com/kubernetes-sigs/gateway-api/issues/3979
```release-note
NONE
```

Update index.md field after moving BackendTLS struct

---

conformance/utils/suite/conformance.go

/kind bug
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/4102
Fixes #4102
```release-note
NONE
```

conformance: fix per-test cleanup

---

CHANGELOG/1.4-CHANGELOG.md
config/crd/experimental/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xbackendtrafficpolicies.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xlistenersets.yaml
config/crd/experimental/gateway.networking.x-k8s.io_xmeshes.yaml
config/crd/standard/gateway.networking.k8s.io_backendtlspolicies.yaml
config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
config/crd/standard/gateway.networking.k8s.io_gateways.yaml
config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
pkg/consts/consts.go

This bumps us to v1.4.0-rc.2 and adds the accompanying CHANGELOG entry.

v1.4.0-rc.2
