kubernetes-sigs/gateway-api

- docs-src/devguide.md
Per the discussion last week, I've drafted some details on a release cadence. I thought putting a stake in the sand of a January 31 initial release would be beneficial for everyone.
> Release cadence for Services/Ingress API

- docs/devguide/index.html
- hack/delete-crds.sh
Commits `b2c4093` and `ff14200` added unnecessary whitespace to the dev guide. It appears that `make docs` does not clean-up whitespace. Ran `make docs` which added the "release-cadence" section to the dev guide.
> Removes whitespace introduced by commits b2c4093 and ff14200

- docs-src/.mkdocs-exclude
- docs.mk
Runs the document generation in the container and diff's it against the
files currently in the repo.
docs-src/.mkdocs-exclude contains the patterns of files to exclude from
the diff.
> Add make verify to docs.mk

- docs-src/.mkdocs-exclude
- docs.mk
- hack/verify-docs.sh
Adds a simple verify-docs command to `hack/`.
Fixes #19 
I suspect it will be pretty slow right now if there's not reuse of the build instances (I don't know enough about Prow here). I don't see any way around that without:
- Having #3 done
- changing `docs.mk` to have separate build-push and run steps, so we can just use the run step.
> Add verify-docs command

- api/v1alpha1/gateway_types.go
- api/v1alpha1/zz_generated.deepcopy.go
All other Kubernetes APIs are using specific integer sizes, so it seems
reasonable to follow suit. In particular, Service's port is using int32,
so reuse that.
Needed for https://github.com/kubernetes-sigs/service-apis/issues/11
> Use int32 instead of int for listener

- api/v1alpha1/gatewayclass_types.go
- config/crd/bases/networking.x.k8s.io_gatewayclasses.yaml
- config/crd/bases/networking.x.k8s.io_gateways.yaml
- config/crd/bases/networking.x.k8s.io_httproutes.yaml
- config/crd/bases/networking.x.k8s.io_tcproutes.yaml
- config/crd/bases/networking.x.k8s.io_trafficsplits.yaml
Gateway class is supposed to be cluster scoped but the CRD was not. In fixing this I found the CRDs were not updated. The first commit I just ran `make manifests`, the second commit I fixed the scoping and rerun that.
Related: https://github.com/kubernetes-sigs/service-apis/issues/14
> Fix GatewayClass scope

- Makefile
- examples/basic-http.yaml
- hack/install-examples.sh
Previously, the example resources failed to install. This PR updates the example to reflect the latest api changes. Additionally, the example resources are included in `make install`.
/assign @bowei 
/cc @Miciah
> Updates and Includes Example Resources in Install

- examples/basic-http.yaml
Change namespaceSelector to empty value, since empty string is not a valid key.
Add routeSelector with simple example of matchLabels.
Add same labels value to HTTPRoute in order to match gateway's routeSelector.
> Fix route selectors for the basic example

- api/v1alpha1/gatewayclass_types.go
- config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tcproutes.yaml
- config/crd/bases/networking.x-k8s.io_trafficsplits.yaml
- examples/basic-http.yaml
- kubebuilder.mk
Accomplishing this required upgrading to the newer v1 API version for CRDs. This does mean that these CRDs would only be able to be installed on clusters with Kubernetes 1.16 or newer. This also updates the example to be valid with our updated spec, and renames the CRD files to match our updated x-k8s.io API version.
This fixes https://github.com/kubernetes-sigs/service-apis/issues/142.
I'm very open to feedback on this. When I started going down this path I didn't realize it would limit us to Kubernetes 1.16+. I do think the added defaulting functionality this provides is likely worth it, in addition to using the most current API up front instead of having to upgrade later.
/cc @jpeach @youngnick @danehans @hbagdi 
/assign @bowei
> Adding CRD default for GatewayClass status

- Makefile
- hack/verify-crds.sh
Previously, commits that altered API definitions may get merged without the corresponding CRD being updated. This PR, combined with https://github.com/kubernetes/test-infra/pull/17196, will ensure CRDs are verified to match API definitions before the corresponding commit is merged.
/assign @bowei 
/cc @robscott
> Adds CRD Verification

- api/v1alpha1/gateway_types.go
Listeners have names, which can fail validation rules, so add a
`ConditionInvalidName` so that the controller can be more specific that
`ConditionInvalidListener`.
Listener names must be unique within a gateway. so add
`ConditionNameConflict` for use when this constraint is violated.
> Add Conditions for Listener name errors.

- .github/ISSUE_TEMPLATE/bug.md
Previously, all GitHub Issues were considered "Enhancements". This PR adds a template for reporting bugs.
/assign @bowei @robscott 
/cc @Miciah
> Adds a GitHub Issues template for reporting bugs

- api/v1alpha1/gateway_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
Making Gatway.status a subresource to allow for separate operations.
> Make Gateway.Status a subresource

- api/v1alpha1/gateway_types.go
- api/v1alpha1/gatewayclass_types.go
- api/v1alpha1/generated.proto
- config/crd/bases/networking.x-k8s.io_gateways.yaml
1. Make GatewayStatus.Conditions and GatewayStatus.Listeners optional fields as discussed here: https://github.com/kubernetes-sigs/service-apis/issues/174#issuecomment-624952923
> Mark Gateway status fields optional

- examples/basic-http.yaml
https://github.com/kubernetes-sigs/service-apis/pull/43 singularized the HTTPRoute hostname field. This PR updates the example accordingly.
/assign @bowei 
/cc @robscott
> Singularizes example HTTPRoute hostname

- api/v1alpha1/gateway_types.go
- api/v1alpha1/gatewayclass_types.go
- api/v1alpha1/generated.proto
- config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
- docs-src/spec.md
- docs/spec/index.html
This standardizes the status conditions to set when the "allows" fields on GatewayClass are violated. Fixes #177. 
/cc @danehans @jpeach
> Adding new status conditions covering forbidden namespaces

- api/v1alpha1/gateway_types.go
- api/v1alpha1/gatewayclass_types.go
- api/v1alpha1/httproute_types.go
- api/v1alpha1/tcproute_types.go
- api/v1alpha1/trafficsplit_types.go
- docs-src/spec.md
- docs/spec/index.html
Add a +genclient annotation to root objects that were missing it.
Remove unnecessary +genclient annotations that have no effect on
codegen.
> Update root object tags for API documentation.

- examples/examples_test.go
- hack/verify-examples.sh
It is easy to accidentally add example YAML that is not valid. Add a
verifier to ensure that we can parse all the root level Service API kinds.
> Add a verifier to parse examples.

- examples/basic-http.yaml
- examples/multiple-https.yaml
- examples/multiple-tcp.yaml
- examples/single-http.yaml
- examples/wildcard-http.yaml
- examples/wildcard-https.yaml
Previously, the examples would fail to install:
```
$ make install
/Library/Developer/CommandLineTools/usr/bin/make -f kubebuilder.mk manifests
go run sigs.k8s.io/controller-tools/cmd/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/Library/Developer/CommandLineTools/usr/bin/make -f kubebuilder.mk install
go run sigs.k8s.io/controller-tools/cmd/controller-gen "crd:crdVersions=v1" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
kustomize build config/crd | kubectl apply -f -
customresourcedefinition.apiextensions.k8s.io/gatewayclasses.networking.x-k8s.io created
customresourcedefinition.apiextensions.k8s.io/gateways.networking.x-k8s.io created …
```
> Adds route resource references in example gateway manifests

- examples/basic-tcp.yaml
Previously, `make install` would fail with:
```
The Gateway "my-gateway" is invalid: spec.listeners.routes.resource: Required value
make: *** [example] Error 1
```
This PR adds the required route resource type in  `examples/basic-tcp.yaml`.
/assign @robscott @bowei 
/cc @JeremyOT
> Adds required route resource type to tcp example

- apis/v1alpha1/forwarding_target_types.go
- apis/v1alpha1/gateway_types.go
- apis/v1alpha1/gatewayclass_types.go
- apis/v1alpha1/generated.proto
- apis/v1alpha1/local_object_reference_types.go
- config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tcproutes.yaml
- docs-src/spec.md
- docs/spec/index.html
Since required-ness is checked before defaulting is applied, all
defaulted fields should be optional. I also took the opportunity
to order the kubebuilder annotations consistently.
> Mark defaulted fields as optional.

- apis/v1alpha1/gateway_types.go
- apis/v1alpha1/generated.proto
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- docs-src/spec.md
- docs/spec/index.html
Some implementations will not support all the protocols or route types
defined in the API. Add some simple guidance to make it clear that an
implementation doesn't have to support everything and can raise
conditions for cases that it doesn't support.
This updates #234 
> Add clarifications for handling unsupported features.

- apis/v1alpha1/generated.proto
- apis/v1alpha1/httproute_types.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- docs-src/spec.md
- docs/spec/index.html
Changes:
- Move regex support from extend to custom. The details in regex make it
hard to share the support in extended or core.
- add enum based validation for match type, this can be relaxed in
future to allow for arbitrary strings
- introduce kubebuilder annotations
> httproute: correct conformance for regex support

- Makefile
Previously, running `make all` after making a change to the API, e.g https://github.com/kubernetes-sigs/service-apis/pull/250, the command fails:
```
$ make all
/Library/Developer/CommandLineTools/usr/bin/make -f kubebuilder.mk manager
go run sigs.k8s.io/controller-tools/cmd/controller-gen object:headerFile=./hack/boilerplate.go.txt paths="./..."
go fmt ./...
go vet ./...
apis/v1alpha1/generated.pb.go:3098:28: m.ForwardTo.MarshalToSizedBuffer undefined (type []ForwardToTarget has no field or method MarshalToSizedBuffer)
apis/v1alpha1/generated.pb.go:4014:18: m.ForwardTo.Size undefined (type []ForwardToTarget has no field or method Size)
apis/v1alpha1/generated.pb.go:4633:48: this.ForwardTo.String undefined (type []ForwardToTarget has no field or method String) …
```
> Reorders make all targets

- apis/v1alpha1/generated.proto
- apis/v1alpha1/httproute_types.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- docs-src/spec.md
- docs/spec/index.html
This patch changes the default `PathMatchType` in `HTTPRouteMatch` from `Exact` to `Prefix`. 
This should fix #254 .
> Update default PathMatchType in HTTPRoute to be prefix.

- apis/v1alpha1/httproute_types.go
> Fix typo in httproute_types.go.

- .gitattributes
Add the "linguist-generated" attribute to generated files so that the
Github UI shows changes in these files folded by default.
> Add linguist attribute to generated files.

- config/crd/kustomization.yaml
This was removed in
https://github.com/kubernetes-sigs/service-apis/pull/274.
This breaks 1 line installation of CRDs used by a few demos already like
`kubectl apply -k 'github.com/kubernetes-sigs/service-apis/config/crd'`
> Add back kustomize support

- Makefile
- kubebuilder.mk
- `Makefilke`: Adds support for go vet and fmt that was loist when the `controller` target was removed.
- `kubebuilder.mk `: Adds the `install` target required for `make install` from the [dev guide.](https://kubernetes-sigs.github.io/service-apis/devguide/)
Fixes Issue: https://github.com/kubernetes-sigs/service-apis/issues/287
/assign @hbagdi 
/cc @jpeach @robscott
> Fixes Install Make Target

- apis/v1alpha1/tlsconfig_types.go
- docs-src/spec.md
- docs/spec/index.html
An implementation may not have any SSL certificate as Kubernetes resource but, for example, use named certificate specified via Options field.
> Make CertificateRefs field in TLSConfig optional instead of repeated.

- apis/v1alpha1/gateway_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- docs-src/spec.md
- docs/spec/index.html
- examples/basic-http.yaml
- examples/basic-tcp.yaml
- examples/default-match-http.yaml
- examples/http-trafficsplit.yaml
- examples/multiple-https.yaml
- examples/multiple-tcp.yaml
- examples/single-http.yaml
- examples/wildcard-http.yaml
- examples/wildcard-https.yaml
This matches the corresponding naming on Ingress and PersistentVolume resources.
> Changing Gateway.Class to Gateway.GatewayClassName

- apis/v1alpha1/tlsconfig_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- docs-src/spec.md
- docs/spec/index.html
- For the "Passthrough" mode, certificateRef is not necessary as the
Gateway doesn't terminate the TLS session
- Options are meant as an extension point and should be optional.
> tls: make CertificateRef and Options optional

- apis/v1alpha1/gatewayclass_types.go
- config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
With the transition to the metav1.Condition type more values are required as part of a condition. The previous default value made the GatewayClass CRD invalid.
/cc @jpeach @hbagdi
> Fixing default value for GatewayClass conditions

- Makefile
- hack/update-codegen.sh
- pkg/client/clientset/versioned/typed/apis/v1alpha1/apis_client.go
- pkg/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_apis_client.go
- pkg/client/clientset/versioned/typed/apis/v1alpha1/generated_expansion.go
- pkg/client/informers/externalversions/apis/v1alpha1/interface.go
- pkg/client/informers/externalversions/generic.go
- pkg/client/listers/apis/v1alpha1/expansion_generated.go
This was reverted in a16ebea. This PR copies the update-codegen.sh
script from prior to that commit without modification, adds it to `make
generate`, and runs it.
> Unrevert client generation

- docs-src/concepts.md
- docs/concepts/index.html
Adds more details on how to interpret the controller field, give
an example around how versioning will work.
Fixes: https://github.com/kubernetes-sigs/service-apis/issues/229
Co-authored-by: Harry Bagdi <harrybagdi@gmail.com>
> Expands on GatewayClass.spec.controller

- apis/v1alpha1/gatewayclass_types.go
- config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
- docs-src/spec.md
- docs/spec/index.html
- examples/basic-http.yaml
- examples/basic-tcp.yaml
- examples/http-trafficsplit.yaml
This matches the scoping of the GatewayClass and matches the intention of parameters being configured with implementation specific custom resources.
Fixes https://github.com/kubernetes-sigs/service-apis/issues/144
/cc @jpeach @hbagdi
> Updating ParametersRef docs and examples to be cluster-scoped

- apis/v1alpha1/httproute_types.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- docs-src/spec.md
- docs/spec/index.html
I am not really sure if unionDiscriminator even works, but per
https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/20190325-unions.md#go-tags
the individual items should be optional. Otherwise, you need to specify
all of them which is not quite right.
> Make HTTPRouteFilter types optional

- Makefile
- apis/v1alpha1/gateway_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- docs-src/spec.md
- docs/spec/index.html
Update the condition types and reasons for the Gateway condition type.
Gateways should now expose their state using the `Scheduled` and `Ready`
conditions, providing additional information in the reason.
See conditions vocabulary doc: https://docs.google.com/document/d/17WGAL5jjjGHsmDCeMstZ3L5fFp6QGPHrIplQ9LPZ91k
/cc @robscott @danehans @hbagdi
> Update Gateway condition types.

- apis/v1alpha1/gatewayclass_types.go
- config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
Fix the `gatewayclasses` CRD by annotating the CR's `status.provisionedGateways` field's json tag with the `omitempty` option.
Before this commit, attempting to apply the CRD produced the following error message:
The CustomResourceDefinition "gatewayclasses.networking.x-k8s.io" is invalid: spec.validation.openAPIV3Schema.properties[status].default.provisionedGateways: Required value
* `apis/v1alpha1/gatewayclass_types.go` (`GatewayClassStatus`): Add `omitempty` to `ProvisionedGateways`.
* `config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml`: Regenerate.
> GatewayClass: Add omitempty to provisionedGateways

- apis/v1alpha1/gateway_types.go
- apis/v1alpha1/gatewayclass_types.go
- apis/v1alpha1/httproute_types.go
- config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
Addresses #354. This adds additional columns to print with kubectl get requests using kubebuilder annotations.
```
$ kubectl get gateway
NAME                      CLASS
default-match-gw          default-match-example
gateway                   default-class
my-gateway                acme-lb
my-trafficsplit-gateway   trafficsplit-lb
```
```
$ kubectl get gatewayclass
NAME                    CONTROLLER
acme-lb                 acme.io/gateway-controller
default-match-example   acme.io/gateway-controller
trafficsplit-lb         acme.io/gateway-controller
```
```
$ kubectl get httproute
NAME                  HOSTNAMES
default-match-route   ["default-match.com"]
http-app-1            ["baz.example.com"]
http-trafficsplit-1   ["my.trafficsplit.com"]
```
> Specify printer columns for gateway, gatewayclass, httproute #354

- apis/v1alpha1/backendpolicy_types.go
- apis/v1alpha1/gateway_types.go
- apis/v1alpha1/gatewayclass_types.go
- apis/v1alpha1/route_types.go
- config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
- config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tcproutes.yaml
- config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
- config/crd/bases/networking.x-k8s.io_udproutes.yaml
- docs-src/spec.md
- docs/spec/index.html
Patch merge strategy is not supported for CRDs, so we can drop those
markers. Apply the list-map markers to all Condition slices. Conditions
should never be optional, since a controller should ensure that all
Condition types are always present in the status field.
This fixes #342 
/cc @robscott @bowei @danehans
> Consistently apply list-map typing to Conditions slices.

- hack/delete-crds.sh
The script goes out of date easily. This patch reduces the maintainence
burden by automating the resource list.
> remove hardcoded resources in delete-crds.sh

- apis/v1alpha1/httproute_types.go
- apis/v1alpha1/route_types.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tcproutes.yaml
- config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
- config/crd/bases/networking.x-k8s.io_udproutes.yaml
- docs-src/spec.md
- docs/spec/index.html
This was suggested by @mark-church as a way to simplify blue green deployments or rollbacks. Users may want to start/end with a weight of 0 to simplify the workflow. 
/cc @danehans @hbagdi @jpeach
> Decreasing min weight from 1 to 0

- apis/v1alpha1/httproute_types.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- docs-src/spec.md
- docs/spec/index.html
ImplementationSpecific and RegularExpression are kept separate for
end-user documentation purposes. There is some expectation of
portability for some regexes across implementation in future.
> Clean up match type and add regex header match

- docs-src/community.md
- docs/community/index.html
- removes the outdated cschedule scratchpad
- removes the old design doc
> clean up community doc to removec outdated links

- docs-src/concepts.md
- docs/concepts/index.html
Concepts docs has exploded with content that could use some
re-organization.
This is small patch in a series of fixes to make this document
understandable and easy to navigate.
> fix indents and sections headers in concepts

- apis/v1alpha1/gateway_types.go
- apis/v1alpha1/gatewayclass_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- docs-src/spec.md
- docs/spec/index.html
There is nothing that prevents a user to delete a GatewayClass resource
when there are Gateway resources that refer to it.
This patch adds in recommendation to use finalizers to prevent deletion
of GatewayClass resources that are in use.
This is a secondary safety-net. The first one is based on our personas
and RBAC where for a large cluster, only a small subset of users should
have delete permissions on GatewayClass.
See #170
> add recommendation to add finalizer to GatewayClass

- docs-src/enhancement-requests.md
- docs/404.html
- docs/community/index.html
- docs/concepts/index.html
- docs/cookbook/index.html
- docs/devguide/index.html
- docs/enhancement-requests/index.html
- docs/faq/index.html
- docs/index.html
- docs/releases/index.html
- docs/security-model/index.html
- docs/spec/index.html
- docs/tls/index.html
- docs/userguide/index.html
- mkdocs.yml
This patch organizes the navbar in four main sections:
- Concepts
- Guides
- References
- Contributing
Also contains minor corrections around names and formatting.
> docs: reorganize nav bar

- hack/verify-golint.sh
This change has been verified to work in https://github.com/kubernetes-sigs/service-apis/pull/416. 
/cc @jpeach @hbagdi
> Fixing verify-golint by using mod=readonly go flag

- apis/v1alpha1/backendpolicy_types.go
- apis/v1alpha1/gateway_types.go
- apis/v1alpha1/httproute_types.go
- apis/v1alpha1/route_types.go
- apis/v1alpha1/zz_generated.deepcopy.go
- docs-src/spec.md
- docs/spec/index.html
- Defines a new type Port
- Re-use the type across all instances of port
- Change the type from int32 to uint32
I spotted this while working on #422.
Please review only the last commit here. To avoid conflicts, this PR builds on top of #422 and should be merged after that lands in.
> define a new Go type Port for consolidation 

- apis/v1alpha1/tlsroute_types.go
- config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
All of our `MaxItems` limits are a power of 2.
This patch has doesn't add much value to the API other than having consistency.
> change max items from 10 to 16 for snis in TLSRoute

- LICENSE
- README.md
The readme was written a long time ago and had outdated pointers.
This patch re-organizes and adds in relevant pointers in the readme.
> revamp readme to point to relevant resources

- apis/v1alpha1/gateway_types.go
- Updates `NamedAddressType` and `IPAddressType` in the `Gateway` API type to provide additional information when a a requested address is unsupported by an implementation.
- Introduces the "UnsupportedAddress" listener status condition reason constant.
/assign @robscott @jpeach 
Fixes #409
> Updates NamedAddressType and IPAddressType Godocs

- apis/v1alpha1/gateway_types.go
- apis/v1alpha1/httproute_types.go
- apis/v1alpha1/route_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tcproutes.yaml
- config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
- config/crd/bases/networking.x-k8s.io_udproutes.yaml
- docs-src/spec.md
- docs/spec/index.html
- Add an upper limit of 100 to the number of Gateways that will be stored in RouteGatewayStatus.
- Clarify support level of filters defined in ForwardTo.
- Increase max weight to 1 million.
- Clarify how 1 backend with a weight of 0 should be handled.
- Replace "undefined" with "unspecified"
- resource: fooroutes -> kind: FooRoute
Fixes https://github.com/kubernetes-sigs/service-apis/issues/435
/cc @danehans @hbagdi @jpeach
> Cleanup from prealpha feedback

- CHANGELOG.md
When this PR merges I'll cut RC2. Ideally I'd like to get https://github.com/kubernetes-sigs/service-apis/pull/416 and https://github.com/kubernetes-sigs/service-apis/pull/436 in first, but understand if there's still some hesitation on one or both of those PRs.
/cc @bowei @danehans @hbagdi @jpeach 
/hold for an hour or two to see if other PRs can get in first
> Adding changelog for v0.1.0-rc2

- docs-src/getting-started.md
- docs-src/guides.md
- docs/404.html
- docs/community/index.html
- docs/concepts/index.html
- docs/devguide/index.html
- docs/enhancement-requests/index.html
- docs/faq/index.html
- docs/getting-started/index.html
- docs/index.html
- docs/releases/index.html
- docs/security-model/index.html
- docs/spec/index.html
- docs/tls/index.html
- examples/basic-http.yaml
- mkdocs.yml
This PR builds on top of #425. Please review the last commit only.
> write a very simple getting started guide

- apis/v1alpha1/gateway_types.go
- apis/v1alpha1/httproute_types.go
- apis/v1alpha1/shared_types.go
- apis/v1alpha1/tcproute_types.go
- apis/v1alpha1/tlsroute_types.go
- apis/v1alpha1/udproute_types.go
- apis/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tcproutes.yaml
- config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
- config/crd/bases/networking.x-k8s.io_udproutes.yaml
- docs-src/spec.md
- docs/spec/index.html
- Renames `apis/v1alpha1/route_types.go` to `apis/v1alpha1/types.go` since the defined types are referenced by more than just `xRoute` types, i.e. `Gateway`. 
- Moves `Hostname` from `apis/v1alpha1/gateway_types.go` to `apis/v1alpha1/types.go`.
- Updates `xMatch` godocs  for the various API types.
/assign @robscott @hbagdi @bowei 
/cc @jpeach @Miciah 
Fixes #415
> Various v1alpha1 API Clean-Up

- docs-src/guides.md
- docs-src/multiple-ns.md
- docs/404.html
- docs/community/index.html
- docs/concepts/index.html
- docs/devguide/index.html
- docs/enhancement-requests/index.html
- docs/faq/index.html
- docs/getting-started/index.html
- docs/index.html
- docs/multiple-ns/index.html
- docs/releases/index.html
- docs/resources/index.html
- docs/security-model/index.html
- docs/spec/index.html
- docs/tls/index.html
- examples/routes-in-multiple-namespaces.yaml
- mkdocs.yml
A guide which illustrates how routes from multiple namespaces are targeted by a single Gateway resource.
See #333
> write a guide for routes in multiple namespaces

- OWNERS
- OWNERS_ALIASES
This mirrors the [structure that cluster-api uses](https://github.com/kubernetes-sigs/cluster-api/blob/master/OWNERS). I've left Bowei in temporarily just in case all these aliases don't end up working as expected.
/cc @danehans @hbagdi @jpeach 
/assign @bowei
> Adding sig-network leads and service-apis maintainers as approvers

- apis/v1alpha1/gateway_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- docs-src/spec.md
- docs/spec/index.html
30ca50d3f43d1760d45ee8ab3843e7b164141577 renamed `RouteSelector` to `Selector`.
Hence this patch fixes the `RouteSelector` in docs/comments.
> Update RouteSelector to Selector in Gateway

- apis/v1alpha1/gateway_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- docs-src/spec.md
- docs/spec/index.html
`ConditionInvalidRoutes` was obsoleted by b1cc891fe01d51f07833f7a0595ac012bb8d8c56.
Hence this patch replaces `ConditionInvalidRoutes` with `InvalidRoutesRef`.
> Replace obsolete status ConditionInvalidRoutes with InvalidRoutesRef

- .github/PULL_REQUEST_TEMPLATE.md
This is mostly a copy of the [Kubernetes PR template](https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md) with some of the less relevant bits removed. All I really wanted was some kind of release note automation, so if the rest of this feels like it adds too much overhead, I'm fine with simplifying this.
> Adding a PR Template

- README.md
- docs-src/api-overview.md
- docs-src/security-model.md
- docs/api-overview/index.html
- docs/security-model/index.html
https://kubernetes-sigs.github.io/service-apis/concepts renders as `404 - Not found`
"api-overview" is the first section in Concepts, so I assume it was intended to link here instead
> Fixing bad link in README.md

- docs-src/faq.md
- docs/faq/index.html
Looks like there was a big doc change and this link wasn't updated.
> Fix broken doc link

- apis/v1alpha1/httproute_types.go
- apis/v1alpha1/tcproute_types.go
- apis/v1alpha1/tlsroute_types.go
- apis/v1alpha1/udproute_types.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tcproutes.yaml
- config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
- config/crd/bases/networking.x-k8s.io_udproutes.yaml
/kind feature
As identified in #481, the initial validation on the length of ForwardTo was too restrictive. Knative has some compelling use cases for 10+ ForwardTo statements. [Further discussion](https://knative.slack.com/archives/C93E33SN8/p1606886097119400) showed that 16 would be a reasonable upper limit for them. I've also taken some time to ensure that this would also be possible for common proxies such as nginx, haproxy, and envoy. The primary reason for an upper limit here is to ensure we have no unbounded lists in our API. Increasing this limit does not appear to be an issue for any implementations I'm aware of. If it is, please let me know.
Fixes #481 
**Does this PR introduce …
> Increasing max length of ForwardTo from 4 to 16

- RELEASE.md
- docs-src/releases.md
- docs/releases/index.html
/kind cleanup
This clarifies our approach to versioning. Much of this is based on our conversation at the community meeting earlier this week.
This is related to https://github.com/kubernetes-sigs/service-apis/issues/447 but does not provide a long term solution for v1alpha2.
```release-note
NONE
```
> Clarifying approach to versioning

- docs/multiple-ns/index.html
- examples/basic-tcp.yaml
- examples/basic-udp.yaml
- examples/default-match-http.yaml
- examples/multiple-tcp.yaml
- examples/routes-in-multiple-namespaces.yaml
- examples/single-http.yaml
- examples/wildcard-http.yaml
- examples/wildcard-https.yaml
/kind cleanup
Removes any default namespace specified on resources so that users can deploy into any namespace other than "default".
Fixes #498
Signed-off-by: Steve Sloka <slokas@vmware.com>
> examples: Remove namespace from examples

- docs-src/community.md
- docs/community/index.html
/kind cleanup
Previously the links to older community meetings were more prominent than our current meeting notes and recordings. This should fix that.
```release-note
NONE
```
> Cleaning up links to meeting notes and recordings

- Makefile
While verbose output is usually helpful, in the current output in CI, it
is so verbose that it is hard to make out the exact cause of a failure.
/kind cleanup
Improve developer experience of debugging CI failures.
Fixes #522
```release-note
NONE
```
> disable verbose logging for verify target

- docs-src/api-overview.md
- docs/api-overview/index.html
Indented the api-overview.md page to 80 chars. This was originally done in https://github.com/kubernetes-sigs/service-apis/pull/514 but was recommended by @jpeach and @robscott to break out into a separate PR. I'll rebase https://github.com/kubernetes-sigs/service-apis/pull/514 on top of this one once it is merged
> indented api-overview.md to 80 chars

- docs-src/releases.md
- docs/releases/index.html
[Current doc for Releases/Versioning](https://kubernetes-sigs.github.io/service-apis/releases/#versioning) misses the link for `[Kubernetes API Versioning] (example: v1alpha1)`.
This is because the link is for `Kubernetes API Versioning` does not
match to the `Kubernetes API Version`.
This patch fixes it.
```release-note
NONE
```
> Add link to "Kubernetes API Versioning" by using correct name

- apis/v1alpha1/gateway_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- docs-src/spec.md
- docs/spec/index.html
/kind bug
Properly sets the "Terminate" default for `gateway.spec.tls.mode`.
Fixes https://github.com/kubernetes-sigs/service-apis/issues/517
Yes, sets the default TLS mode to "Terminate".
> Fixes TLS Mode Defaulting

- Makefile
- apis/v1alpha1/gatewayclass_types.go
- hack/update-codegen.sh
/kind cleanup
We were previously running codegen twice - once with controller-gen, and once with deepcopy-gen. This cleans that up a bit and ensures we're not duplicating work. This also removes some unnecessary annotations from GatewayClass. (They were useful for deepcopy-gen but not for controller-gen).
```release-note
NONE
```
> Cleaning up codegen

- README.md
- docs-src/index.md
- docs/index.html
@hbagdi suggested this in https://github.com/kubernetes-sigs/gateway-api/pull/541 and I just realized I forgot to actually update that PR. This should make it a bit clearer that this is actually the project that used to be known as "Service APIs" for anyone that might be confused.
```release-note
NONE
```
/cc @hbagdi
> Adding notes referring to previous project name

- site-src/tcp.md
Use an absolute path for the TCPRoute spec. The current relative path attempts to load `/tcp/spec/#networking.x-k8s.io/v1alpha1.TCPRoute`, but the spec actually lives at `/spec/#networking.x-k8s.io/v1alpha1.TCPRoute`:
https://gateway-api.sigs.k8s.io/tcp/spec/#networking.x-k8s.io/v1alpha1.TCPRoute
https://gateway-api.sigs.k8s.io/spec/#networking.x-k8s.io/v1alpha1.TCPRoute
```release-note
NONE
```
> Fix broken link in TCPRoute guide

- mkdocs.yml
- site-src/implementations.md
As per [k8s slack conversations][slack] and https://github.com/kubernetes-sigs/gateway-api/issues/558 this PR adds documentation to keep track of the downstream Gateway API implementations in other projects.
Fixes #558 
NONE
> Add implementations documentation

- apis/v1alpha1/validation/doc.go
- apis/v1alpha1/validation/validation.go
- apis/v1alpha1/validation/validation_test.go
/kind feature
This PR adds a validation package. It's needed so implementors no longer need to create a Gateway API validation package. This approach provides validation consistency across implementations, including the future validating webhook. The package is modeled after the Kubernetes [networking APIs validation package](https://github.com/kubernetes/kubernetes/tree/release-1.19/pkg/apis/networking/validation).
Partially Fixes # https://github.com/kubernetes-sigs/gateway-api/issues/487
```release-note
NONE
```
/cc @stevesloka @youngnick @jpeach
> Introduces a Validation Package

- apis/v1alpha1/backendpolicy_types.go
- apis/v1alpha1/gateway_types.go
- apis/v1alpha1/gatewayclass_types.go
- apis/v1alpha1/httproute_types.go
- apis/v1alpha1/tcproute_types.go
- apis/v1alpha1/tlsroute_types.go
- apis/v1alpha1/udproute_types.go
- config/crd/bases/networking.x-k8s.io_backendpolicies.yaml
- config/crd/bases/networking.x-k8s.io_gatewayclasses.yaml
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tcproutes.yaml
- config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
- config/crd/bases/networking.x-k8s.io_udproutes.yaml
/kind cleanup
This adds a gateway-api category to our CRDs as well as a new "age" column for "kubectl get" output.
Fixes #589
Also inspired by #588 
```release-note
* Gateway API CRDs are not part of the "gateway-api" category. Running "kubectl get gateway-api" now returns all Gateway API resources.
* Each Gateway API resource now includes an "Age" column in "kubectl get" output.
```
> Adding gateway-api category and age column to CRDs

- apis/v1alpha1/validation/validation.go
- apis/v1alpha1/validation/validation_test.go
- go.mod
- go.sum
A variation of this patch first appeared in #506.
This patch is derived from #506 and has been reworked to include it in
the validation package.
/kind feature
Introduces validation for HTTPRoute resource.
This is part of a patch series to get #506 merged in incrementally.
None
```release-note
NONE
```
> httproute: add duplicate filter validation

- site-src/guides/getting-started.md
fix broken link to implementations page from getting-started page
> fix broken link to implementations page from getting-started page

- apis/v1alpha1/httproute_types.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
/kind cleanup
This adds conflict resolution guidance for equivalent rules within a route.
Fixes #613 
```release-note
Adds conflict resolution guidance for equivalent rules within a route
```
/cc @stevesloka @youngnick @hbagdi
> Adding conflict resolution guidance for equivalent rules within a route

- apis/v1alpha1/gateway_types.go
/kind cleanup
This deprecates the NoSuchGatewayClass status reason. Although this was a useful concept, it was never clear who would actually set it. Although we could develop an official controller that watched Gateways and GatewayClasses and set this status, I don't think anyone has the capacity to maintain that. Alternatively, we could rely on every Gateway controller to write this status, but that could result in some fairly ugly race conditions.
I initially proposed a [new condition](https://github.com/kubernetes-sigs/gateway-api/pull/630) to replace this, but I don't think that's necessary. After discussing this with @jpeach, it seemed like the existing `ListenerConditionResolvedRefs` and …
> Deprecating NoSuchGatewayClass status reason

- apis/v1alpha1/httproute_types.go
- apis/v1alpha1/tcproute_types.go
- apis/v1alpha1/tlsroute_types.go
- apis/v1alpha1/udproute_types.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tcproutes.yaml
- config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
- config/crd/bases/networking.x-k8s.io_udproutes.yaml
/kind cleanup
This is a follow up from https://github.com/kubernetes-sigs/gateway-api/pull/620. It takes the conflict resolution guidance we added to HTTPRoute and applies it to the other route types.
```release-note
Clarifies how conflicting matches should be resolved in non-HTTP routes
```
/cc @hbagdi @youngnick
> Clarifying how conflicting matches should be resolved in non-HTTP Routes

- site-src/concepts/guidelines.md
Fix https://github.com/kubernetes-sigs/gateway-api/issues/530
```release-note
NONE
```
> Add note about "implementation-specific" vs conformance levels

- CHANGELOG.md
This adds a changelog for v0.3.0. Approving this PR indicates that you approve of a v0.3.0 release based on this commit.
```release-note
NONE
```
/cc @bowei @danehans @hbagdi @jpeach
> Adding Changelog for v0.3.0

- site-src/guides/getting-started.md
Updates the getting-started guide to use the latest v0.3.0 release.
```release-note
NONE
```
Signed-off-by: Steve Sloka <slokas@vmware.com>
> Fixup the getting-started guide to use the v0.3.0 release.

- hack/verify-golint.sh
/kind cleanup
Bumps up golangci-lint version to v1.39.0
None
```release-note
NONE
```
> bump up golangci-lint to v1.39.0

- .gitignore
- hack/verify-golint.sh
This commit adds a cache dir for golangci-lint runs.
Probably will not impact Prow CI times, but should make
running the linting locally a bit faster (my testing shows
around 40 percent faster, but results may vary).
/kind cleanup
Fixes #607
```release-note
NONE
```
> Add caching to golangci-lint

- apis/v1alpha1/validation/validation.go
- apis/v1alpha1/validation/validation_test.go
- apis/v1alpha2/validation/validation.go
- apis/v1alpha2/validation/validation_test.go
This currently comprises only of an immutability check for
`spec.controller` field. This can expanded in future.
/kind feature
This validation is a pre-requisite for #189. Once this is merged in, we can start enforcing this using a validation webhook.
None
```release-note
NONE
```
> implement validation for GatewayClass resource

- deploy/admission_webhook.yaml
- pkg/admission/server.go
- pkg/admission/server_test.go
/kind feature
This patch introduces validation for updates to GatewayClass resources.
Fixes #189
```release-note
Immutability of `spec.controller` field in GatewayClass resource is now enforced using the validation webhook.
```
/cc @robscott @stevesloka @jpeach
> pkg/admission: validate GatewayClass updates

- site-src/api-types/httproute.md
- site-src/guides/http-routing.md
- site-src/v1alpha2/api-types/gatewayclass.md
- site-src/v1alpha2/api-types/httproute.md
- site-src/v1alpha2/faq.md
- site-src/v1alpha2/guides/http-routing.md
- site-src/v1alpha2/guides/tcp.md
- site-src/v1alpha2/guides/traffic-splitting.md
/kind cleanup
This adds HTTPRoute merging documentation. This also updates some v1alpha1 references to v1alpha2 in the v1alpha2
docs.
Fixes #573
```release-note
NONE
```
> Adding HTTPRoute merging documentation

- apis/v1alpha2/shared_types.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tcproutes.yaml
- config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
- config/crd/bases/networking.x-k8s.io_udproutes.yaml
/kind feature
With this change, whenver any controller that popualates a gateway-specific
status on a XRoute resource, it must provide at least 1 condition on the
Route.
Fixes #542
```release-note
Gateway-specific status on any route type requires at least one condition to be set.
```
> RouteGatewayStatus: make conditions required

- apis/v1alpha2/httproute_types.go
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
A small update to clarify the behavior of HTTPRoute backends when they are all have weights of 0.
Fixes #596 
```release-note
NONE
```
> Clarify direction for backend weights

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/shared_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
- config/crd/bases/networking.x-k8s.io_httproutes.yaml
- config/crd/bases/networking.x-k8s.io_tlsroutes.yaml
This commit updates documentation around hostnames to make the
interaction between Gateway Listener `Hostname` and HTTPRoute
`Hostnames` field to be more clear.
Closes #654
/kind cleanup
```release-note
NONE
```
> Update documentation around hostnames for HTTPRoute and Listener

- .github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
Reverts PR template labels. It appears that this feature only works for issues. (Example: https://github.com/kubernetes-sigs/gateway-api/pull/692)
```release-note
NONE
```
/cc @hbagdi
> Revert PR template labels

- site-src/concepts/guidelines.md
- site-src/v1alpha2/concepts/guidelines.md
It looks like a recent update to docs only made it to v1alpha1. This fixes that.
```release-note
NONE
```
> Updating v1alpha2 guidelines docs to match v1alpha1

- apis/v1alpha2/gateway_types.go
- config/crd/bases/networking.x-k8s.io_gateways.yaml
/kind feature
This corresponds with the hostname field in the [upstream LoadBalancerStatus struct](https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L3547-L3550).
```release-note
Gateway status now supports a new Hostname address type
```
> Adding hostname address type

- site-src/concepts/api-overview.md
- site-src/v1alpha2/concepts/api-overview.md
This patch makes a tiny change to remove `ports` that 
current doc says user can omit it from Gateway. 
Port in Gateway is not optional.
/kind cleanup
```release-note
NONE
```
> Fix doc as user cannot omit port field in Gateway

- hack/install-examples.sh
This was found while working on #683.
This was assumed to be fixed with #670 but as it turns out we have two
kubectl apply in our shell script.
/kind cleanup
Fixes `make install ` to install v1alpha2 examples as well.
None
```release-note
NONE
```
> recursively install examples

- .github/ISSUE_TEMPLATE/enhancement.md
- site-src/contributing/enhancement-requests.md
- site-src/contributing/gep.md
- site-src/geps/gep-696.md
- site-src/v1alpha2/contributing/enhancement-requests.md
Add proposal for GEP process
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/696
/kind feature
/kind design
```release-note
NONE
```
> Add proposal for GEPs

- mkdocs.yml
- site-src/contributing/enhancement-requests.md
Looks like the suggested change didn't get into the commit
/kind cleanup
```release-note
NONE
```
> Fix broken links

- site-src/v1alpha2/contributing/community.md
/kind cleanup
Updates meeting times based on discussion in our most recent community meeting. Everyone that had been attending the EMEA meeting time was also able to attend the APAC time. (Related thread in Slack: https://kubernetes.slack.com/archives/CR0H13KGA/p1624990383109000).
```release-note
NONE
```
> Updating meeting times

- Makefile
- hack/boilerplate/boilerplate.py
- site-src/v1alpha2/contributing/devguide.md
Add a make target to create the virtualenv with mkdocs installed to make
it easier to remember how to get the right tooling. Add an example to
the contribution docs.
> Add a virtualenv convenience target for mkdocs.

- site-src/geps/gep-696.md
/kind cleanup
This GEP had a couple references to PR # instead of issue, this fixes that.
```release-note
NONE
```
> Updating GEP 696 to consistently reference newer issue

- .github/PULL_REQUEST_TEMPLATE.md
/kind cleanup
Add a `/kind gep` to the PR template.
```release-note
NONE
```
> add kind gep in PR template

- apis/v1alpha2/httproute_types.go
- config/crd/bases/gateway.networking.k8s.io_httproutes.yaml
/kind bug
As noted in #655, a core filter with extended support fields is
confusing and also seems to be incorrect.
This patch drops the extended field from the filter and is a partial fix
for the referenced issue.
HTTPRequestMirroFilter has not been patch as GEP-718 could potentially
simplify that.
Partial fix for #655
```release-note
bugfix: To avoid confusion, fields within HTTPRequestHeaderFilter are no more marked as 'extended'. All fields must be supported by implementations for this core filter.
```
> fix support level for HTTPRequestHeaderFilter

- apis/v1alpha2/httproute_types.go
- config/crd/bases/gateway.networking.k8s.io_httproutes.yaml
- site-src/v1alpha2/concepts/guidelines.md
/kind cleanup
This clarifies support levels in the Redirect filter and documents how overlapping support levels should be interpreted.
```release-note
NONE
```
> Clarifying Redirect Support levels

- mkdocs.yml
- site-src/geps/gep-709.md
/kind gep
This is a quick follow up to #711 that addresses a few leftover comments on that PR + does some minor cleanup.
```release-note
NONE
```
Deploy Preview: https://deploy-preview-722--kubernetes-sigs-gateway-api.netlify.app/geps/gep-709/
> Tweaks to ReferencePolicy GEP

- apis/v1alpha1/shared_types.go
- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/gatewayclass_types.go
/kind cleanup
This PR adds reasons for when conditions are healthy. When the conditions are positive, the healthy reason is identical to the condition name. 
```release-note
Guidance has been added for condition reasons when they are healthy.
```
Slack thread with a bit more discussion: https://kubernetes.slack.com/archives/CR0H13KGA/p1616184252018300
/cc @jpeach @howardjohn @lelenanam
> Adding suggested reasons for when conditions are healthy

- examples/basic-http.yaml
- examples/v1alpha2/basic-http.yaml
- hack/verify-examples-kind.sh
/kind bug
Missed this when I was reviewing #733 
```release-note
NONE
```
Note: I'm starting this PR to see if I can get `verify-examples-kind` to fail, will update to complete this transition and remove hold at that point.
/hold
> Moving method match to v1alpha2 example

- site-src/geps/gep-718.md
/kind gep
This adds a GEP for droping ServiceName field from RouteForwardTo(#718)
```release-note
NONE
```
> GEP-718: consolidation of ServiceName in RouteForwardTo

- mkdocs.yml
- requirements.txt
- site-src/geps/.pages
/kind cleanup
Automates the nav for GEPs
None
```release-note
NONE
```
> automate nav for GEPs

- apis/v1alpha2/httproute_types.go
- config/crd/bases/gateway.networking.k8s.io_httproutes.yaml
TLS passthrough never terminates TLS sessions, so it doesn't make
sense for TLS certificates to be required in this configuration.
/kind bug
> Remove RouteTLSConfig requirement for gateway TLS passthrough.

- site-src/geps/gep-696.md
- site-src/v1alpha2/contributing/gep.md
/kind cleanup
After writing a few GEPs, I ended up with a structure that more closely resembles this updated template. This updates the template to reflect that structure.
```release-note
NONE
```
/cc @bowei @hbagdi
> Cleaning up GEP Template

- config/crd/kustomization.yaml
/kind bug
`make install` didn't install v1alpha2 CRDs.
None
```release-note
NONE
```
> fix kustomize to install v1a2 crds

- apis/v1alpha2/gateway_types.go
/kind cleanup
The references of vendor configurations in GatewayTLSConfig confuses the users.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/759
> Remove references of vendor configurations in GatewayTLSConfig

- site-src/geps/gep-746.md
/kind gep
This adds GEP #746, as a follow up to my original [proposal doc](https://docs.google.com/document/d/1Cv95XFCL6S_9pIyS0drnsDLsfinWc2tHOFl_x3-_SWI/edit).
```release-note
NONE
```
/cc @bowei @hbagdi @howardjohn @jpeach @Miciah @youngnick
> Adding GEP 746: Replace Cert Refs on HTTPRoute with Cross Namespace Refs from Gateway

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/tcproute_types.go
- apis/v1alpha2/tlsroute_types.go
- apis/v1alpha2/udproute_types.go
- config/crd/bases/gateway.networking.k8s.io_httproutes.yaml
- config/crd/bases/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/bases/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/bases/gateway.networking.k8s.io_udproutes.yaml
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/638
Fixes #638
```release-note
NONE
```
> Clarify docs on invalid serviceName

- apis/v1alpha2/httproute_types.go
- config/crd/bases/gateway.networking.k8s.io_httproutes.yaml
Clarifies that matching behavior for multi-value headers is undefined. This seems like a very rare use-case and specifying something that may cause conformance headaches doesn't seem to be worth it.
Fixes #213
```release-note
NONE
```
> document multi-value headers as undefined

- site-src/v1alpha2/api-types/gateway.md
- site-src/v1alpha2/api-types/httproute.md
- site-src/v1alpha2/concepts/api-overview.md
- site-src/v1alpha2/concepts/security-model.md
This is a follow up to #754 and provides documentation for GEP #724.
```release-note
NONE
```
Deploy Previews:
* https://deploy-preview-762--kubernetes-sigs-gateway-api.netlify.app/v1alpha2/concepts/api-overview/
* https://deploy-preview-762--kubernetes-sigs-gateway-api.netlify.app/v1alpha2/concepts/security-model/
> Documenting Route attachment for v1alpha2

- site-src/v1alpha2/faq.md
Clarify which Kubernetes versions are supported
Fix https://github.com/kubernetes-sigs/gateway-api/issues/737
```release-note
```
> Document the supported kubernetes versions

- examples/v1alpha2/http-routing/bar-httproute.yaml
- examples/v1alpha2/http-routing/foo-httproute.yaml
- examples/v1alpha2/http-routing/gateway.yaml
- site-src/v1alpha2/guides/getting-started.md
- site-src/v1alpha2/guides/http-routing.md
This updates the examples in the `HTTPRoute` guide for `v1alpha2`, and does some spacing cleanup for the getting started guide (but that guide did not appear to need any special updating for `v1alpha2`).
Resolves the first two tasks in https://github.com/kubernetes-sigs/gateway-api/issues/783
> docs: update getting-started and httproute guides for v1alpha2

- examples/v1alpha2/basic-tcp.yaml
- site-src/v1alpha2/guides/tcp.md
This updates the `TCP` guide for `v1alpha2`.
This resolves the 5th task of https://github.com/kubernetes-sigs/gateway-api/issues/783
```release-note
NONE
```
> docs: update tcp guide for v1alpha2

- apis/v1alpha1/gateway_types.go
- site-src/geps/gep-724.md
- site-src/v1alpha1/api-types/gatewayclass.md
- site-src/v1alpha1/api-types/httproute.md
- site-src/v1alpha1/guides/getting-started.md
- site-src/v1alpha1/guides/tcp.md
These are mostly in the v1alpha1 docs. It's still good to fix them
as they show up in broken link checkers, to reduce noise.
/kind cleanup
```release-note
NONE
```
> Fixes some broken links

- apis/v1alpha2/gateway_types.go
- config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
There needs to be a newline separating paragraphs from lists to make
the markdown processor format the list as a list.
/kind cleanup
> Fix markdown list formatting.

- site-src/implementations.md
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
Fixes #
```release-note
```
> Add APISIX implementation

- apis/v1alpha2/gateway_types.go
- site-src/faq.md
The `HTTPRoute` API (specifically) doesn't support SSL Passthrough. An implementer recently [reported](https://github.com/kubernetes-sigs/gateway-api/issues/790) this wasn't clear. There is [documentation on this](https://gateway-api.sigs.k8s.io/v1alpha2/guides/tls/#clientserver-and-tls), but in order to help make this more clear/prominent this patch adds a note about it in the FAQ with links to the relevant docs and guides.
Fixes #840
```release-note
NONE
```
> docs: add ssl passthrough note in FAQ

- apis/v1alpha2/httproute_types.go
- config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
ImplementationSpecific is trappy match type: it provides an escape hatch
to do more but it doesn't take into account that multiple
implementation-specific match types could be possible. Use-cases exist
in this area but we have not thought through them deeply.
Being conservative and dropping this feature in v1alpha2 to avoid any potential
breaking change in the future. We may revisit this in the future as we gain a
better understanding.
Fixes #832
```release-note
ImplementationSpecific match types in HTTPRoute's path, query, and header matches have been removed.
```
> httproute: drop ImplementationSpecific match types

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/gatewayclass_types.go
- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/referencepolicy_types.go
- apis/v1alpha2/shared_types.go
- apis/v1alpha2/tcproute_types.go
- apis/v1alpha2/tlsroute_types.go
- apis/v1alpha2/udproute_types.go
- apis/v1alpha2/validation/gatewayclass.go
- apis/v1alpha2/validation/gatewayclass_test.go
- config/crd/v1alpha2/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_referencepolicies.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_udproutes.yaml
- examples/v1alpha2/basic-http.yaml
- examples/v1alpha2/default-match-http.yaml
- examples/v1alpha2/http-redirect.yaml
- hack/invalid-examples/v1alpha2/gatewayclass/invalid-controller.yaml
- pkg/admission/server_test.go
/kind cleanup
This takes care of another big chunk of feedback from #780 as well as some of the items in #790.
```release-note
* "Controller" has been renamed to "ControllerName"
* "Admitted" condition has been renamed to "Accepted" and now defaults to an "Unknown" state instead of "False"
```
> Another round of v1alpha2 cleanup

- site-src/v1alpha2/guides/getting-started.md
/kind cleanup
As v0.3.0 CRD does not support v1alpha2, v1alpha2 docs should use
v0.4.0-rc1 CRD.
```release-note
NONE
```
> docs: Use v0.4.0-rc1 in "Getting started with Gateway APIs" for v1alpha2

- mkdocs.yml
- site-src/v1alpha2/references/cross-namespace-references.md
- site-src/v1alpha2/references/policy-attachment.md
Adds missing references pages to docs navigation that must've gotten lost in latest navigation updates.
```release-note
NONE
```
> Adding missing references pages to docs navigation

- README.md
Fixes broken link to spec page (404) and now sends to https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/
none
```release-note
NONE
```
> Fixing broken link to spec page

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/tlsroute_types.go
- config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_tlsroutes.yaml
/kind bug
This fixes the confusing guidance (originally added by me) in HTTP and TLS Routes that suggested that conditions should be populated on Gateway Listeners. I had originally built out conditions that could be populated on Gateway and Listeners, but I'm not sure that's the right approach. I think the simplest and most straightforward answer here is to populate Route status. If Route owners can't attach to a Gateway they want to, they can simply contact the Gateway owner.
Fixes #849
```release-note
Updated guidance on how HTTP and TLS Route status should be populated when hostnames do not match.
```
/cc @youngnick @howardjohn
> Clarifying how HTTP and TLS Route status should be populated

- examples/v1alpha2/cross-namespace-routing/0-namespaces.yaml
- examples/v1alpha2/cross-namespace-routing/gateway.yaml
- examples/v1alpha2/cross-namespace-routing/site-route.yaml
- examples/v1alpha2/cross-namespace-routing/store-route.yaml
- site-src/v1alpha2/guides/multiple-ns.md
This updates the `multiple-ns.md` guide for `v1alpha2`.
Resolves the 3rd task for https://github.com/kubernetes-sigs/gateway-api/issues/783
```release-note
NONE
```
> docs: update multiple-ns guide for v1alpha2

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/object_reference_types.go
- config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_udproutes.yaml
/kind cleanup
This fixes a variety of feedback from #861 and #780, primarily focused on HTTPRoute.
```release-note
NONE
```
> Route cleanup for v1alpha2 sig-network review

- site-src/concepts/guidelines.md
This clarifies that we're using kind instead of resource for object references, and how implementations should handle that.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/816.
```release-note
NONE
```
> Adding guidance on Kind vs. Resource in implementation guidelines

- site-src/geps/gep-851.md
/kind gep
This adds GEP #851: Allow Multiple Certificate Refs per Gateway Listener.
```release-note
NONE
```
> Adding GEP 851: Allow Multiple Certificate Refs per Gateway Listener

- apis/v1alpha2/httproute_types.go
- config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
Explicitly align path prefix matching with the Ingress API by specifying
it as an prefix of path elements, not a prefix of bytes.
/kind bug
This fixes #866.
```release-note
Aligned path prefix matching with Ingress by clarifying that it is a prefix of path elements.
```
> Align path prefix matching with Ingress.

- apis/v1alpha2/httproute_types.go
The documentation for the prefix and exact path match types was attached
to the wrong constants.
Thanks @skriss!
/kind bug
Documentation mixup from #869.
> Fix HTTP path match documentation.

- apis/v1alpha2/gateway_types.go
/kind feature
Clarifies that HTTP listeners may be used for Cleartext HTTP/2.
Fixes #817
```release-note
HTTP listeners may now be used for Cleartext HTTP/2
```
> Clarifying that HTTP listeners may be used for Cleartext HTTP/2

- apis/v1alpha2/shared_types.go
- site-src/concepts/api-overview.md
/kind cleanup
This clarifies which fields must be included by all Route types. If this is sufficient for now, I can create a follow up tracking issue to track creating more detailed documentation on creating custom Route types.
Fixes #874
```release-note
NONE
```
> Clarifying the fields that all Route types must include

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/zz_generated.deepcopy.go
- config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
- examples/v1alpha2/cross-namespace-routing/gateway.yaml
- examples/v1alpha2/tls-basic.yaml
- examples/v1alpha2/tls-cert-cross-namespace.yaml
- examples/v1alpha2/wildcard-tls-gateway.yaml
/kind feature
This PR uses `CertificateRefs` to instead `CertificateRef` so that multiple certificates can be configured for a Listener. With this feature, we can support things like following items:
* When hostname is empty on the Listener, and Routes attach multiple unique Hostnames
* Providing RSA and EC certs
* Temporarily including new and old certs during an upgrade
Fixes #851 
```release-note
Use `CertificateRefs` field to instead the `CertificateRef` in `GatewayTLSConfig`.
```
> feat: support to configure multiple certificates on GatewayTLSConfig

- apis/v1alpha2/validation/gateway.go
- apis/v1alpha2/validation/gateway_test.go
This commit adds the following validations
- TLSConfig is empty when the protocol is HTTP, TCP, or UDP.
- Hostname is empty when the protocol is TCP or UDP.
kind/feature
Introduces protocol specific validations to
provide better UX
Fixes #827 
```release-note
This change introduces protocol specific validations
*  TLSConfig is empty when the protocol is HTTP, TCP, or UDP
*  Hostname is empty when the protocol is TCP or UDP.
```
> Add protocol specific validation for Gateway api

- site-src/v1alpha2/references/policy-attachment.md
This adds some clarification in our docs based on an [earlier Slack thread](https://kubernetes.slack.com/archives/CR0H13KGA/p1632419978111100) around if there was still value in custom filters now that we have policy attachment.
```release-note
NONE
```
> Reworking Policy vs. Filter Documentation

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/object_reference_types.go
- apis/v1alpha2/policy_types.go
- apis/v1alpha2/shared_types.go
- apis/v1alpha2/validation/httproute_test.go
- config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_udproutes.yaml
/kind cleanup
This PR ensures that there are no required fields that allow empty values, and that all required fields have consistent validation.
It does this by introducing a new string type alias, ObjectName, for Kubernetes object names, and by ensuring that the Listener ProtocolType has validation.
On the plus side, that was all the required types that could be zero I could find. The Port number field already has validation to ensure it's between 1 and 65535.
Fixes #867 
```release-note
Validation for Kubernetes object names has been updated
Listener ProtocolType now has validation
```
> Add validation for Kubernetes object name fields and ProtocolType

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/shared_types.go
- apis/v1alpha2/zz_generated.deepcopy.go
- config/crd/v1alpha2/gateway.networking.k8s.io_gateways.yaml
/kind cleanup
I found a comment from @khenidak that I'd missed from the original sig-network review suggesting more thorough validation here. This adds generic "AnnotationKey" and "AnnotationValue" types in hopes that they'll be useful for more than just TLS options in the future.
```release-note
* TLS options keys are now subject to the same validation as Kubernetes annotations.
* TLS options values now have a max length of 1024 characters.
```
> Adding TLS options validation as final sig-network review follow up

- README.md
LInk for getting started got change so it was broken
Fixes #887 
NONE
```release-note
```
> Corrected broken getting started

- site-src/geps/gep-917.md
/kind gep
Adds GEP-917 to document conformance principles and outline what a conformance process for the Gateway API should and must provide.
Fixes #917
```release-note
NONE
```
> Add GEP-917 to document conformance principles

- apis/v1alpha2/httproute_types.go
/kind cleanup
This is a slight clarification to PathPrefix matching based on @danwinship's feedback in https://github.com/kubernetes-sigs/gateway-api/pull/861#discussion_r724260847. Note that if/when this merges, we should make a corresponding update to the Ingress path matching documentation.
```release-note
NONE
```
> Clarifying PathPrefix matching

- site-src/geps/gep-922.md
/kind gep
This proposes a set of versioning guidelines for future Gateway API releases. This is a follow up to the [related doc](https://docs.google.com/document/d/16tvd2j-zUdL1tqzFJFHGOI2WFCWs6dosj3QPkVDAdOY/edit#) that has been discussed in gateway-api and sig-apimachinery meetings.
Related to #922, will not be fixed until this GEP moves to "Implemented"
```release-note
NONE
```
> Adding GEP 922: Gateway API Versioning Plan

- examples/v1alpha2/tls-cert-cross-namespace.yaml
/kind bug
The gateway in the docs [cross namespace certificate references](https://gateway-api.sigs.k8s.io/v1alpha2/guides/tls/#cross-namespace-certificate-references) uses a same namespace `gateway-api-example-ns1` between gateway and secret as:
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
name: cross-namespace-tls-gateway
namespace: gateway-api-example-ns1
spec:
gatewayClassName: acme-lb
listeners:
- name: https
protocol: HTTPS
port: 443
hostname: "*.example.com"
tls:
certificateRefs:
- kind: Secret
group: ""
name: wildcard-example-com-cert
namespace: gateway-api-example-ns1
```
so it does not "cross" the namespace. This patch fixes it.
**Does this PR introduce a …
> Use correct namespace for the example of cross namespace certificate references

- hack/delete-crds.sh
This patch replaces `networking.x-k8s.io` with `gateway.networking.k8s.io`
in `hack/delete-crds.sh`.
/kind cleanup
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/930
```release-note
NONE
```
> Replace networking.x-k8s.io with gateway.networking.k8s.io in hack/delete-crds.sh

- site-src/geps/gep-726.md
/kind gep
This adds GEP #726, a proposed expansion of redirect capabilities along with new rewrite capabilities. 
```release-note
NONE
```
Deploy Preview: https://deploy-preview-731--kubernetes-sigs-gateway-api.netlify.app/geps/gep-726/
> Adding GEP 726: Path Rewrites and Redirects

- Makefile
- apis/v1alpha2/validation/httproute.go
- apis/v1alpha2/validation/httproute_test.go
/kind bug
Validate tha backend refs of type Service specify a port number.
Updates #941
```release-note
NONE
```
> Validate that Service backend refs have a port.

- site-src/geps/gep-917.md
/kind gep
This is an addition to GEP #917 that provides a general structure for how we can define conformance tests. Although this could have potentially been a separate GEP, it felt sufficiently small to just bundle with the existing conformance GEP. Happy to split this out if it's easier though.
This is largely a follow up to the [earlier doc](https://docs.google.com/document/d/1QL-MpIVzqxe32Y2BZ_dYOB8zNsF9c4pnKEIB9ZLt118/edit), but it also adds a section to discuss how this could work with prepopulated Gateways. Open to other approaches here, this just seemed like it may be the simplest starting point.
```release-note
NONE
```
> Adding details to Conformance GEP

- apis/v1alpha2/httproute_types.go
/kind bug
Fixes a mistake in BackendRef docs that suggested ResolvedRefs should be set to "True" when it really should have been "False".
```release-note
Clarifies that ResolvedRefs should be set to "False" when a ReferencePolicy does not exist to allow a cross-namespace reference.
```
> Fixing BackendRef docs for ResolvedRefs condition

- config/crd/kustomization.yaml
/kind bug
/kind regression
Previously I was able to deploy the Gateway CRDs with the following one-liner in CI:
```console
$ kubectl kustomize https://github.com/kubernetes-sigs/gateway-api/config/crd | kubectl apply -f -
```
With the changes in 0d40986f4f16016a470bfde3a1f445cb9a891e52 this now fails:
```console
$ kubectl kustomize https://github.com/kubernetes-sigs/gateway-api/config/crd | kubectl apply -f -
Error: accumulating resources: accumulation err='accumulating resources from 'v1alpha2/gateway.networking.k8s.io_gatewayclasses.yaml': evalsymlink failure on '/tmp/kustomize-2449990972/config/crd/v1alpha2/gateway.networking.k8s.io_gatewayclasses.yaml' : lstat /tmp/kustomize-2449990972/config/crd/v1alpha2: no such …
```
> fix: kustomize resource paths

- apis/v1alpha2/referencepolicy_types.go
- config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
- config/crd/stable/gateway.networking.k8s.io_referencepolicies.yaml
Current docs explains about `spec.to.name` as:
```
Name is the name of the referent. When unspecified or empty, this policy
refers to all resources of the specified Group and Kind in the local
namespace.
```
However, the ReferencePolicy with empty value (like below):
```shell
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: ReferencePolicy
metadata:
name: allow-gateways-to-ref-secrets
namespace: default
spec:
from:
- group: gateway.networking.k8s.io
kind: Gateway
namespace: istio-system
to:
- group: ""
kind: Secret
name: ""
EOF
```
It gets the following error `Invalid value: "": spec.to.name in body should be at least 1 chars long` as:
```
The ReferencePolicy "allow-gateways-to-ref-secrets" is invalid: spec.to.name: Invalid value: "": spec.to.name in body …
```
> Fix ReferencePolicy docs about empty value in `spec.to.name`

- site-src/faq.md
- site-src/geps/gep-724.md
- site-src/v1alpha1/api-types/httproute.md
- site-src/v1alpha1/guides/http-routing.md
- site-src/v1alpha1/guides/multiple-ns.md
- site-src/v1alpha2/api-types/httproute.md
- site-src/v1alpha2/guides/multiple-ns.md
- site-src/v1alpha2/guides/tcp.md
- site-src/v1alpha2/references/cross-namespace-references.md
This PR fixes some further broken links after the move to the new site structure.
Fixes #787 
```release-note
NONE
```
> Fix broken site links

- site-src/geps/gep-735.md
/kind feature
/kind design
/kind gep
-->
This adds traffic matching to enable more expressive routing for `TCPRoute` and `UDPRoute`.
Fixes #735
```release-note
- TCPRouteRule now includes an optional "matches" field for traffic matching
- UDPRouteRule now includes an optional "matches" field for traffic matching
```
> GEP 735 L4 Traffic Matching

- .golangci.yml
- hack/verify-golint.sh
- pkg/util/utils_test.go
/kind cleanup
I noticed a few deprecated linter errors, so this fixes up those replacing with valid ones along with one small nit found in the revive linter for a single test. 
```release-note
none
```
> Update version of golangci-lint as well as remove deprecated linters.

- mkdocs.yml
- site-src/concepts/versioning.md
This updates versioning guidelines to allow for bug fixes in patch releases and creates a new docs page to mirror the GEP content. (This is part of the mitigation for https://github.com/kubernetes-sigs/gateway-api/issues/962).
```release-note
Clarification that bug fixes may be broader than just loosened validation.
```
> Updating versioning guidelines to allow for bug fixes in patch releases

- apis/v1alpha2/gatewayclass_types.go
- apis/v1alpha2/referencepolicy_types.go
- config/crd/v1alpha2/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/v1alpha2/gateway.networking.k8s.io_referencepolicies.yaml
- hack/invalid-examples/v1alpha2/referencepolicy/missing-ns.yaml
/kind bug
This cherry picks #909 and #964 into release 0.4 as a prerequisite for #965 and the release of v0.4.1.
```release-note
* Fixes a bug where v1alpha2 GatewayClass controller names were not being shown in the output of `kubectl get gatewayclasses`.
* Namespace can no longer be left unspecified in ReferencePolicy. 
```
> Cherrypick #909 and #964 into release-0.4

- apis/v1alpha2/validation/httproute.go
- apis/v1alpha2/validation/httproute_test.go
- pkg/admission/server_test.go
/kind bug
/kind cleanup
The HTTPRoute validation tests were directly calling internal API
functions to try to pinpoint the set of tests that they expected to
be run. This is a risky pattern, because there's nothing that ensures
that the internal functions are actually wired up to the validation
logic correctly.
This change establishes a new pattern, where each test can set up fixtures
in theor own way (for the sake of brevity), but the test is always driven
by the top-level validation call. This exposed a number of bugs where
the validation functions were not wired up correctly.
In the future, this can be improved by updating the tests to supply
specific expecations on the returned errors rather than just the error …
> Fix HTTPRoute validation tests.

- apis/v1alpha1/httproute_types.go
- apis/v1alpha1/tcproute_types.go
- apis/v1alpha1/tlsroute_types.go
- apis/v1alpha1/udproute_types.go
- apis/v1alpha2/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
- site-src/geps/gep-713.md
- site-src/v1alpha2/references/policy-attachment.md
/kind bug
/kind cleanup
This fixes the bug found by @howardjohn in #979
Fixes #979
```release-note
NONE
```
> Fixing accidental escaping of namespace/name in docs

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/shared_types.go
- apis/v1alpha2/validation/httproute_test.go
- apis/v1alpha2/zz_generated.deepcopy.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
- hack/invalid-examples/v1alpha2/httproute/invalid-httredirect-hostname.yaml
/kind bug
Update the HTTPRequestRedirectFilter.Hostname to use a Hostname type which validates the value cannot
contain wildcard characters. Updates all other references which used Hostname to use WildcardHostname
which does allow for wildcard characters.
Signed-off-by: Steve Sloka <slokas@vmware.com>
Fixes #949
```release-note
Introduced WildcardHostname which allows for wildcard characters in relevant Hostname values. 
```
> Introduce wildcardhostname field

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/shared_types.go
- apis/v1alpha2/zz_generated.deepcopy.go
- config/crd/v1alpha2/gateway.networking.k8s.io_httproutes.yaml
- hack/invalid-examples/v1alpha2/httproute/invalid-httredirect-hostname.yaml
/kind bug
This cherry-picks #956 into the release-0.4 branch in advance of a v0.4.1 release.
```release-note
Introduced PreciseHostname which prevents wildcard characters in relevant Hostname values. 
```
> Cherry Pick #956 into release-0.4

- CHANGELOG.md
This updates the changelog to include v0.4.1. Approving this PR means that you approve the release of this bundle version  of the API at this commit. 
For this to merge, #909 and #964 will first have to be cherry picked back to the release-0.4 branch. When that is complete, this PR will be rebased. Finally, immediately post release, this changelog PR will have to be cherry-picked to master.
```release-note
NONE
```
/hold
> Updating changelog for v0.4.1

- apis/v1alpha2/gateway_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/stable/gateway.networking.k8s.io_gateways.yaml
/kind cleanup
If the listener allowed kinds are not supported, the reason should be
InvalidRouteKinds, not InvalidRoutesRef.
```release-note
NONE
```
> Fix listener allowed kinds documentation.

- deploy/certificate_config.yaml
/kind bug
The admission webhook certificate generation fails on k8s v1.22, see jet/kube-webhook-certgen#30.
The jet upstream is no longer supported.
It was forked, moved into kubernetes/ingress-nginx, fixed
and is now published at k8s.gcr.io/ingress-nginx.
See also https://github.com/kubernetes/k8s.io/blob/main/k8s.gcr.io/images/k8s-staging-ingress-nginx/images.yaml
Fixes #990 
```release-note
Fix webhook deployment on k8s v1.22+
```
> Migrate kube-webhook-certgen to k8s.gcr.io/ingress-nginx:v1.1.1

- apis/v1alpha2/gateway_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/stable/gateway.networking.k8s.io_gateways.yaml
Listener names must be unique within a Gateway, but the documentation never
mentions that.
Fixes #984
```release-note
NONE
```
> Clarify that listener names are unique.

- site-src/geps/gep-957.md
/kind gep
Proposal to support destination port matching.
Fixes #957 
```release-note
Add a new field `Port` to `ParentRef` for destination port matching
```
> Adding GEP 957 for port matching support.

- site-src/faq.md
These must have been missed in #541 because a simple grep wouldn't have picked them up.
/kind cleanup
> docs: fix references to "Service APIs"

- site-src/v1alpha2/api-types/gatewayclass.md
- site-src/v1alpha2/api-types/httproute.md
/kind cleanup
`Admitted` was changed to `Accepted` for v1alpha2 and some documentation wasn't updated to reflect this.
N/A
```release-note
NONE
```
> Change Admitted to Accepted in v1alpha2 docs

- site-src/concepts/api-overview.md
A few small fixes:
- **don't specify full namespaces.selector path:** the section describing allowedRoutes.namespaces field confusingly uses the full path for the namespace selector, suggesting it's talking about different sections of the spec.
- **qualify allowedRoutes namespaces and kinds:** without qualification, we're currently suggesting that namespaces and kinds are listener fields, like hostname.
- **fix namespace typos:** the route attachment examples moved from foo-namespace and bar-namespace in commit #792
/kind cleanup
> API overview fixes

- conformance/tests/httproute-cross-namespace.go
- conformance/tests/httproute-cross-namespace.yaml
- conformance/tests/httproute-invalid-cross-namespace.go
- conformance/tests/httproute-invalid-cross-namespace.yaml
- conformance/tests/httproute-matching-across-routes.go
- conformance/tests/httproute-matching-across-routes.yaml
- conformance/tests/httproute-matching.go
- conformance/tests/httproute-matching.yaml
- conformance/utils/http/http.go
/kind feature
As suggested by @hbagdi, this is a follow up PR to add the remaining conformance tests that were initially part of #969. 
```release-note
NONE
```
> Additional Conformance Tests covering HTTPRoute and Gateway

- site-src/implementations.md
The location of the documentation for the Kong implementation
of Gateway APIs has changed from the ingress controller
repository to Kong's standard documentation site.
> docs: update kong gateway APIs URL

- conformance/tests/httproute-simple-same-namespace.go
- conformance/utils/kubernetes/apply.go
- conformance/utils/suite/suite.go
/kind feature
The conformance tests include some hard-coded file paths for testing manifests. This patch makes it possible to override them with your own file paths and additionally enables URL support so that Golang projects can more easily run the test suite by using the [Golang Package](https://pkg.go.dev/sigs.k8s.io/gateway-api).
> feat: allow URL overrides for conformance test manifests

- site-src/v1alpha2/guides/tcp.md
In #808, we documented how the tcp route match extension point can be used for metadata based tcp matching.
Soon after, in #829, this extension point was removed, but the docs remained.
Remove this section to reflect the current state of the API.
/kind cleanup
> tcp guide: remove section on metadata based tcp matches

- Makefile
- cloudbuild.yaml
- hack/build-and-push.sh
/kind cleanup
This PR adds some tooling around building admission-server images, so that we end up with:
- all images built and pushed are labelled with the standard Prow version string, like `v20220209-v0.4.0-114-g36b4551`.
- Images built for a semver branch or tag are also labelled with the branch or tag name
- Images built for a semver branch or tag that don't have a prerelease marker (like `-rc2`, `-beta1` or similar are labelled `latest`.
This will mean that we can now generate consistent manifest YAML for the admission-server when we release a bundle by tagging a branch with a semver tag, since the images will be available by `v0.4.1` or whatever.
I'll leave changing out …
> Update image generation process with more consistent naming

- conformance/tests/httproute-cross-namespace.go
- conformance/tests/httproute-invalid-cross-namespace.go
- conformance/tests/httproute-matching-across-routes.go
- conformance/tests/httproute-matching.go
- conformance/utils/kubernetes/apply.go
/kind bug
Makes the conformance tests runnable with the local manifests
```release-note
NONE
```
> fix(conformance): manifest filenames and reading from disk

- conformance/utils/kubernetes/apply.go
/kind bug
Fixes the conformance tests cleanup. Functions registered with `Cleanup` will run after `ctx` from the outer `for` loop scope has already been canceled.
```release-note
NONE
```
> fix(conformance): don't use canceled context to Delete resources

- conformance/tests/httproute-matching-across-routes.go
- conformance/tests/httproute-matching-across-routes.yaml
- conformance/tests/httproute-matching.go
- conformance/utils/kubernetes/helpers.go
/kind bug
- allows Succeeded pods to exist in conformance test namespaces
- fixes loop variable bug in parallel conformance tests
- fixes HTTPRoute hostname in the "matching across routes" conformance test
```release-note
NONE
```
> minor conformance test fixes

- Makefile
- cloudbuild.yaml
/kind cleanup
Hopefully this should fix the cloudbuild for tagged versions - we'll have to cut a 0.4.3 to test though, sadly.
```release-note
NONE
```
> Fix release-staging cloudbuild job - hopefully

- hack/api-docs/config.json
/kind bug
This updates our k8s reference docs links to go to 1.23 instead of 1.18.
Fixes #1032
```release-note
NONE
```
> Updating k8s references docs links to go to 1.23 instead of 1.18

- hack/api-docs/type.tpl
This adds anchor links in our reference docs as suggested in #1031
```release-note
NONE
```
> Adding anchor links in reference docs

- Dockerfile
- deploy/admission_webhook.yaml
- deploy/certificate_config.yaml
- hack/invalid-examples/v1alpha2/gateway/hostname-tcp.yaml
- hack/invalid-examples/v1alpha2/gateway/hostname-udp.yaml
- hack/invalid-examples/v1alpha2/gateway/tlsconfig-tcp.yaml
- hack/invalid-examples/v1alpha2/httproute/httproute-portless-backend.yaml
- hack/invalid-examples/v1alpha2/httproute/httproute-portless-service.yaml
- hack/invalid-examples/v1alpha2/httproute/invalid-filter-duplicate.yaml
- hack/invalid-examples/v1alpha2/httproute/invalid-filter-empty.yaml
- hack/invalid-examples/v1alpha2/httproute/invalid-filter-wrong-field.yaml
- hack/verify-examples-kind.sh
/kind cleanup
This PR includes 3 related changes:
1. Moves webhook deployment from gateway-api to gateway-system
2. Adds webhook deployment as part of kind e2e verification tests
3. Adds invalid examples that are only covered by webhook validation
Fixes #1040
```release-note
The Gateway API webhook is now deployed in a `gateway-system` namespace instead of `gateway-api`.
```
> Adding webhook to e2e tests with kind, moving deploy to gateway-system namespace

- site-src/v1alpha2/api-types/gatewayclass.md
@ruigulala found these outdated examples, this fixes them.
```release-note
NONE
```
> Fixing outdated examples to use controllerName instead of controller

- hack/verify-examples-kind.sh
This should fix the bug encountered by #1063 and likely triggered by a new go version in https://github.com/kubernetes/test-infra/pull/25740.
```release-note
NONE
```
> Replacing "go get" with "go install" for kind verification

- deploy/certificate_config.yaml
Small issue in #1051 - both manifests create the required namespace and we only renamed gateway-api to gateway-system in one of them.
Before:
```
namespace/gateway-system created
validatingwebhookconfiguration.admissionregistration.k8s.io/gateway-api-admission created
service/gateway-api-admission-server created
deployment.apps/gateway-api-admission-server created
namespace/gateway-api created
```
after:
```
namespace/gateway-system created
validatingwebhookconfiguration.admissionregistration.k8s.io/gateway-api-admission created
service/gateway-api-admission-server created
deployment.apps/gateway-api-admission-server created
namespace/gateway-system unchanged
```
/kind cleanup
> Avoid creating obsolete gateway-api namespace

- site-src/concepts/api-overview.md
This fixes a confusing part of our documentation that describes reencryption as being possible without clarifying that it is not currently configurable with the API. If/when this merges, I'll create a follow up issue to track the feature request/GEP for configuring reencryption.
Fixes #968
```release-note
NONE
```
> Clarifying TLS Reencryption Docs

- hack/verify-examples-kind.sh
This cherry picks #1064 into release-0.4 to fix CI. This will unblock #1071.
```release-note
NONE
```
> Cherry pick CI fixes into release-0.4

- conformance/conformance_test.go
- conformance/embed.go
- conformance/utils/kubernetes/apply.go
This allows importing the suite as a go package and running in
controller repos. This was the same stated purpose as
https://github.com/kubernetes-sigs/gateway-api/pull/1023; we would
prefer not to pull manifests from URL though. Its possible the URL
support is obsolete from this, or we can keep both depending on
feedback.
/kind feature
```release-note
NONE
```
> conformance: embed manifests in Go binary

- hack/boilerplate/boilerplate.py
I fooled myself into thinking this wasn't actually doing anything, so I figure it would be good to add a reassuring success message:
```
$ ./hack/verify-boilerplate.sh
Verified 111 file headers match boilerplate
```
It's arguable this change should go into k/k first, but perhaps a little laziness can be forgiven!
/kind cleanup
> Add a success message to verify-boilerplate

- apis/v1alpha2/validation/httproute.go
- apis/v1alpha2/validation/httproute_test.go
/kind bug
This cherry picks #946 into release 0.4. This includes a number of webhook improvements, including:
* New validation to ensure that a HTTPRouterFilter Type matches its value
* A fix to ensure that Path match validation actually works (previously the function existed but was not used)
```release-note
Improvements to HTTPRoute validation in the validating webhook:
* New validation to ensure that a HTTPRouterFilter Type matches its value
* A fix to ensure that Path match validation actually works
```
> Cherry pick webhook improvements and bug fixes into release-0.4

- site-src/concepts/api-overview.md
[gep-957](https://gateway-api.sigs.k8s.io/geps/gep-957/) proposed to add `Port` to `ParentRef`, in addition to existing fields. This PR updates existing route attachment documentation to provide more details on `parentRef`,
Fixes #1021
NONE
> Provide more details on route parentRef in documentation for routes <> Gateways attachment.

- apis/v1alpha2/gateway_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/stable/gateway.networking.k8s.io_gateways.yaml
This PR clarifies implementation of core support of Secret reference.
https://github.com/kubernetes-sigs/gateway-api/discussions/1059
I think it does not.
```release-note
NONE
```
> clarify core support of secret reference

- conformance/tests/httproute-cross-namespace.go
- conformance/tests/httproute-matching-across-routes.go
- conformance/tests/httproute-matching.go
- conformance/tests/httproute-simple-same-namespace.go
- conformance/utils/http/http.go
/kind bug
(best effort ^, is there a better option?)
We discussed in the sig meeting recently that "accepted" (or "ready" in the future) can only really indicate that the controller has synced all necessary configuration and that routes will begin working "soon".
In order for the conformance tests to support this, they must accept that HTTP requests to new routes may fail for some period of time but should become eventually consistent.
Fixes #
```release-note
NONE
```
> Support eventual consistency in conformance tests

- hack/verify-examples-kind.sh
We're installing kind in a temporary `GOPATH`, let's make sure it gets chosen over any older version installed.
I was hitting an issue with 0.7.0 previously installed earlier in my path.
/kind bug
> verify-examples-kind: reverse path order for kind binary

- site-src/geps/gep-1016.md
- site-src/geps/gep-XXXX.md
/kind gep
Propose a `GRPCRoute` resource.
```release-note
NONE
```
> Propose GRPCRoute Resource

- site-src/geps/gep-1016.md
/kind bug
It seems `mkdoc` has some issue with the double curly braces used in kubebuilder annotations:
```
INFO     -  [macros] - ERROR # _Macro Syntax Error_                                                       
_Line 337 in Markdown file:_ **expected token 'end of print statement', got ':'**
```python                                                                                                                                                                                               
// +kubebuilder:default={{matches: {{method: {{type: "Exact"}}}}}}
```                                       
```
This PR marks the markdown section as raw text to ensure proper rendering.
None. (Let me know if procedure …
> Fix markdown rendering for GEP 1016

- site-src/implementations.md
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
This PR adds a new sections "Integration Status" in the Implementations page. Currently Flagger and cert-manager are listed as integrations.
Fixes #1097 
```release-note
NONE
```
> Add integrations sections in docs

- conformance/utils/kubernetes/apply.go
/kind cleanup
I'm digging into an issue that I believe may be related to eventually consistent cleanup, and it's helpful to know when resources are being deleted in the same way we log when they're created.
Fixes #
```release-note
NONE
```
> Log when cleaning up test resources

- conformance/utils/kubernetes/apply.go
- conformance/utils/kubernetes/apply_test.go
- conformance/utils/suite/suite.go
Adds the option to label `Namespaces` and specify which ports to use for `Gateway` listeners in the conformance tests.
/kind feature
```release-note
NONE
```
> conformance: add option to pass valid ports for listeners and label Namespaces

- apis/v1alpha2/shared_types.go
- conformance/utils/kubernetes/helpers.go
/kind feature
Adds a `RouteConditionReason` type with known required reasons and renames two `RouteConditionType` constants. Not sure if the release note formatting would make more sense to split this into two separate PRs.
Fixes #1109, refs #1112
```release-note
adds RouteConditionReason type with RouteReasonAccepted, RouteReasonResolvedRefs and RouteReasonRefNotPermitted constants
```
```release-note
deprecates ConditionRouteAccepted and ConditionRouteResolvedRefs constants, adds RouteConditionAccepted and RouteConditionResolvedRefs constants
```
> api: add RouteConditionReason to v1alpha2

- apis/v1alpha2/gateway_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/stable/gateway.networking.k8s.io_gateways.yaml
/kind bug
This PR changes the support level i.e. from `Core` to `Extended` of `Gateway.Spec.Addresses`.
You may have  a look at [this comment](https://github.com/kubernetes-sigs/gateway-api/issues/1106#issuecomment-1094434674)
Fixes #1106 
```release-note
NONE
```
> Gateway.Spec.Addresses `Extended` Support Level

- Makefile
- conformance/conformance_test.go
- conformance/utils/flags/flags.go
- conformance/utils/kubernetes/apply_test.go
- conformance/utils/suite/suite.go
/kind cleanup
There was a flag called "cleanup" but that wasn't specific enough[1],
so this "cleanup-base-resources" flag does the same thing but leaves
room for other flags that will clean up other things.
This commit adds a Make variable called CONFORMANCE_FLAGS which
provides a way to pass that flag (or any other) into the conformance
tests. For example, if I wanted to override the test GatewayClass
and *not* clean up the base resources, this would be the invocation:
$ make conformance CONFORMANCE_FLAGS="-cleanup-base-resources=false -gateway-class=acndev-http4"
[1] https://github.com/kubernetes-sigs/gateway-api/pull/1078 …
> Add a "cleanup-base-resources" conformance flag, and a way to use it

- apis/v1alpha2/object_reference_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/stable/gateway.networking.k8s.io_udproutes.yaml
Mention that the BackendObjectReference.Kind default is `Service` in its godoc string. Doc generation pulls in that this is optional, but not the kubebuilder tag that indicates the default, and a BackendObjectReference with an _empty_ Kind doesn't make much sense.
```release-note
NONE
```
> Mention BackendObjectReference.Kind default in docstring

- apis/v1alpha2/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/stable/gateway.networking.k8s.io_udproutes.yaml
Add additional comment explaining that this field cannot be empty or updates to status will be rejected.  It is not immediately clear otherwise from looking at the RouteParentStatus struct that this is required.
```release-note
NONE
```
> Update RouteParentStatus.ControllerName Description

- apis/v1alpha2/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/stable/gateway.networking.k8s.io_udproutes.yaml
This removes a confusing part of the ParentRef doc. The problem was that an invalid ParentRef would mean that no implementation could possibly understand that they were the intended implementor, since the only possible link to an implementation (parentRef) was invalid. I considered leaving in "References to objects with invalid Group and Kind are not valid", but that was really just repeating what was stated in the previous paragraph.
Fixes #988
```release-note
NONE
```
> Removing confusing part of ParentRef godoc

- deploy/certificate_config.yaml
/kind cleanup
This fixes #1125 by cherry picking #991 into release-0.4. (We'll also need a corresponding 0.4 release, but I think we have enough commits backed up to justify a 0.4.3 release.
Fixes #1125
```release-note
Webhook deployment config now uses ingress nginx image for kube-webhook-certgen
```
> 0.4 Cherry Pick: Migrate kube-webhook-certgen to k8s.gcr.io/ingress-nginx:v1.1.1

- apis/v1alpha2/shared_types.go
/kind cleanup
Cleans up a confusing part of our godocs for PreciseHostname.
Fixes https://github.com/kubernetes-sigs/gateway-api/pull/1086#discussion_r846361750
```release-note
NONE
```
> Cleaning up PreciseHostname godocs

- site-src/concepts/api-overview.md
- site-src/faq.md
- site-src/v1alpha1/api-types/gateway.md
- site-src/v1alpha1/api-types/gatewayclass.md
- site-src/v1alpha1/api-types/httproute.md
- site-src/v1alpha1/guides/getting-started.md
- site-src/v1alpha1/guides/http-routing.md
- site-src/v1alpha1/guides/multiple-ns.md
- site-src/v1alpha1/guides/simple-gateway.md
- site-src/v1alpha1/guides/tcp.md
- site-src/v1alpha1/guides/tls.md
- site-src/v1alpha1/guides/traffic-splitting.md
- site-src/v1alpha1/references/spec.md
- site-src/v1alpha2/api-types/httproute.md
/kind cleanup
This documents that v1alpha1 has formally been deprecated and will be removed in an upcoming release. It also cleans up/fixes some older references to v1alpha1.
Fixes #906
```release-note
v1alpha1 has been deprecated and will be removed in a future release of the API.
```
> Documenting v1alpha1 deprecation, additional v1alpha1 cleanup

- conformance/tests/httproute-header-matching.go
- conformance/tests/httproute-header-matching.yaml
/ kind conformance-test
Add tests for various combinations of header
matches on HTTPRoutes.
Updates #1102.
```release-note
NONE
```
> conformance: add HTTPRoute header matching test

- conformance/base/manifests.yaml
- conformance/tests/httproute-listener-hostname-matching.go
- conformance/tests/httproute-listener-hostname-matching.yaml
/kind conformance-test
Adds a test that verifies that different hostnames
for different HTTP listeners that all use the same
port are matched correctly.
Updates #1104.
```release-note
NONE
```
Note, this test also creates a new Gateway, so same question as for https://github.com/kubernetes-sigs/gateway-api/pull/1130#discussion_r861332705. There will be at least one more hostname-related test coming that requires a new Gateway as well.
> conformance: add test for listener hostname matching

- conformance/tests/httproute-disallowed-kind.go
- conformance/tests/httproute-disallowed-kind.yaml
conformance test (looks like we need a new kind)
Adds a test for a route that has a parentRef to a
Gateway whose listeners don't allow the route type.
This test largely follows the pattern from "invalid cross namespace", except it creates a new Gateway that disallows HTTPRoutes.
Updates #1104.
```release-note
NONE
```
> conformance: add test for disallowed route kind binding

- deploy/admission_webhook.yaml
/kind cleanup
Bumps webhook version to v0.4.3 in preparation for release.
```release-note
NONE
```
> Bumping webhook image to v0.4.3

- apis/v1alpha2/gateway_types.go
/kind cleanup
This appears to be an artifact of the v1alpha1 configuration style where a listener selects routes directly. In v1alpha2 an unsupported route attempting to attach to a listener should instead be rejected by the gateway, and optionally set an `Accepted` RouteCondition with status `False`.
A somewhat-related mismatch between the Listener's [`AllowedRoutes`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io%2fv1alpha2.AllowedRoutes) `kinds` field and the supported [`protocol`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.ProtocolType) is explicitly expected to be expressed by …
> api: remove ListenerReasonRouteConflict

- conformance/tests/httproute-exact-path-matching.go
- conformance/tests/httproute-exact-path-matching.yaml
/ kind conformance-test
Add tests for matching exact path for HTTPRoutes.
Updates https://github.com/kubernetes-sigs/gateway-api/issues/1102.
```
NONE
```
> Add conformance test for HTTPRoute exact path matching

- conformance/utils/http/http.go
Currently WaitForConsistency requires 3 requests to succeed in a row,
and waits 1s between requests. This means each tests takes a minimum of
3s even in success. This is ok for now, but as we scale up may be quite
slow.
Instead, change the convergence logic so that we only delay on failures
/kind cleanup
Fixes #
```release-note
NONE
```
> conformance: do not delay successes

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/tlsroute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_tlsroutes.yaml
- conformance/tests/httproute-invalid-reference-policy.go
- site-src/v1alpha2/api-types/httproute.md
As suggested by @michaelbeaumont, this updates our HTTP status code guidance to require 404 status codes and removes any recommendations to return 503 status codes.
```release-note
HTTP 404 responses should be returned whenever a matching route rule does not exist or a backend reference can not be resolved.
```
Adding a hold for consensus.
/hold
> Updating HTTP status code documentation to use 404 instead of 503

- site-src/concepts/versioning.md
This adds graduation criteria for resources and fields. My starting point for this was the graduation criteria we [initially identified in our KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-network/2829-gateway-api-to-k8s-io/README.md#graduation-criteria). This builds on that and adds significantly more detail. 
Fixes #1039
```release-note
NONE
```
> Documenting graduation criteria

- apis/v1alpha2/gateway_types.go
/kind cleanup
This appears to be an artifact of the v1alpha1 configuration style where a listener selects routes directly. If I understand correctly, this is a reference to the `ExtensionRef` field on [`HTTPRouteRule`](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPRouteRule) (and other xRouteRule objects), which are the only other uses of the term `Extension` currently in the spec codebase.
`UnsupportedExtension` should likely become a RouteConditionReason instead, but I'm not quite sure with which RouteConditionType it should be used.
The intended behavior now is a bit unclear (it's an edge case not currently …
> api: remove ListenerReasonUnsupportedExtension

- apis/v1alpha2/shared_types.go
/kind feature
Adds two `RouteConditionReason` constants for `RouteConditionAccepted==false`:
- `NotAllowedByListeners` indicates that none of the Gateway's Listeners have an `allowedRoutes` that permits the route.
- `NoMatchingListenerHostname` indicates that none of the Gateway's compatible Listeners have a Hostname that matches one of the route's hostnames (and implicitly that there is no compatible Listener without a Hostname, which would match any route).
Related to #1077 
```release-note
adds RouteReasonNotAllowedByListeners and …
```
> api: add RouteReasonNotAllowedByListeners

- conformance/tests/httproute-invalid-reference-policy.go
- conformance/utils/http/http.go
- conformance/utils/kubernetes/helpers.go
- conformance/utils/suite/suite.go
- hack/verify-golint.sh
/kind bug
This fixes golangci-lint and the related presubmit.
```release-note
NONE
```
> Bumping golangci-lint, making related fixes

- CHANGELOG.md
- README.md
- site-src/v1alpha2/guides/getting-started.md
This updates our docs to reference v0.4.3 now that it's been released.
```release-note
NONE
```
> Bumping version references to v0.4.3

- conformance/tests/httproute-invalid-reference-policy.go
- conformance/tests/httproute-invalid-reference-policy.yaml
/kind bug
#1167 commented out a call to `t.Skip(...)`, however that `t.Skip(...)` call had been written in a misleading way; it was skipping _the rest_ of the test, not just the function passed to t.Skip(...) as an arg. So after commenting it out, the rest of the test now executes and uncovers a couple small issues with the test:
- fixes path prefix match YAML indentation
- removes check for HTTPRoute to be Accepted pending #1112
```release-note
NONE
```
> conformance: fixes for invalid reference policy test

- apis/v1alpha2/gatewayclass_types.go
- config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/stable/gateway.networking.k8s.io_gatewayclasses.yaml
/kind feature
Adds the status of the "Accepted" condition
to the GatewayClass print columns list.
I find myself running `kubectl describe` to see this information all the time, thought it'd be useful to add to the `kubectl get` output (and it's consistent with the `Gateway` output that shows the status of the `Ready` condition).
```release-note
Adds the status of the GatewayClass "Accepted" condition to the GatewayClass print columns list/`kubectl get` output.
```
> add GatewayClass Accepted print column

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
/kind cleanup
This cleans up and clarifies some confusing parts of our spec - thanks to @candita for finding these.
```release-note
NONE
```
> Cleaning up godocs after v0.5.0 API Review

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/zz_generated.deepcopy.go
The GatewayTLSConfig CertificateRefs member is a slice of pointer to struct which implies that the struct is optional.  Change this to a slice of struct to better fit with API type conventions.
/kind cleanup
> Fix certificateRefs optionality.

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/stable/gateway.networking.k8s.io_gateways.yaml
- config/crd/stable/gateway.networking.k8s.io_httproutes.yaml
- conformance/tests/httproute-listener-hostname-matching.go
- conformance/tests/httproute-listener-hostname-matching.yaml
This is a follow up from #1159 that clarifies that wildcard hostname matching should be considered equivalent to suffix matching. This is a change from the Ingress spec but is more widely implementable and matches the most widespread default behavior, including nginx, envoy, GCP, and Azure.
Fixes #1159
```release-note
Wildcard hostname matching behavior has been documented as equivalent to suffix matching.
```
If merged, this will cause conformance tests to start failing for some implementations, adding a temporary hold so everyone has a chance to weigh in.
/hold
/cc @bowei @shaneutt @youngnick …
> Clarifying that wildcard hostname matching is suffix matching

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/shared_types.go
- apis/v1alpha2/validation/gateway.go
- apis/v1alpha2/validation/gateway_test.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/stable/gateway.networking.k8s.io_gateways.yaml
/kind cleanup
This PR changes the AddressType type to add validation on the type itself, rather than the spec.Gateway.addresses list where it's used, and updates that validation to allow domain-prefixed strings (`example.com/CustomAddressType` or similar).
This is a validation change, so it's a breaking API change, technically. However, I've made sure that the existing valid value "NamedAddress" is acceptable, it's just moved to Custom support (which it always was anyway), which is why #958 is blocking v0.5.0.
The intent here is to give implementations an option to extend this field safely and compatibly, and then bring other options back for Extended standardization if need be.
#958 talks about having a …
> Update AddressType definition to add domain-prefixed strings as an option

- .gitattributes
- config/crd/kustomization.yaml
- config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
- config/crd/standard/gateway.networking.k8s.io_referencepolicies.yaml
- config/crd/standard/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/standard/gateway.networking.k8s.io_udproutes.yaml
- hack/build-install-yaml.sh
- hack/verify-examples-kind.sh
- pkg/generator/main.go
- site-src/concepts/versioning.md
- site-src/geps/gep-820.md
- site-src/geps/gep-922.md
- site-src/v1alpha2/contributing/devguide.md
/kind cleanup
As a follow up to https://github.com/kubernetes-sigs/gateway-api/discussions/1172, this renames the stable channel to standard channel, leaving room for a future third release channel for GA-only resources if we want that in the future.
```release-note
The stable release channel has been renamed to standard
```
> Renaming stable channel to standard channel

- apis/v1alpha2/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
/kind cleanup
This is a follow up from the [comments](https://github.com/kubernetes-sigs/gateway-api/pull/1086#discussion_r883131526) by @thockin and @aojea. Although I think we've clearly defined how the PathPrefix match works, we haven't been as clear with the corresponding path rewrite. This copies some of the text we have for prefix path matching so it's also clearly documented here.
```release-note
NONE
```
> Clarifying how ReplacePrefixMatch works

- config/crd/experimental/kustomization.yaml
- config/crd/kustomization.yaml
- hack/verify-examples-kind.sh
/kind bug
Yesterday we broken the `kustomization.yaml` for our CRDs:
```
$ make crd
kubectl kustomize config/crd | kubectl apply -f -
error: accumulating resources: accumulation err='accumulating resources from 'gateway.networking.k8s.io_gatewayclasses.yaml': evalsymlink failure on '/home/shane/Code/gateway-api/config/crd/gateway.networking.k8s.io_gatewayclasses.yaml' : lstat /home/shane/Code/gateway-api/config/crd/gateway.networking.k8s.io_gatewayclasses.yaml: no such file or directory': evalsymlink failure on '/home/shane/Code/gateway-api/config/crd/gateway.networking.k8s.io_gatewayclasses.yaml' : lstat /home/shane/Code/gateway-api/config/crd/gateway.networking.k8s.io_gatewayclasses.yaml: no such file or directory
The …
```
> fix: broken kustomize for crd deployment

- apis/v1alpha2/shared_types.go
- apis/v1alpha2/validation/gateway.go
- apis/v1alpha2/validation/gateway_test.go
- apis/v1beta1/shared_types.go
- apis/v1beta1/validation/gateway.go
- apis/v1beta1/validation/gateway_test.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind cleanup
In response to feedback on #1086, this moves validation from the webhook into the CRD.
Fixes #1202
```release-note
NONE
```
> Replacing webhook validation with CRD validation for AddressType

- conformance/tests/httproute-hostname-intersection.go
- conformance/tests/httproute-hostname-intersection.yaml
Adds a conformance test that validates hostname
intersection between HTTPRoutes and Listeners.
Updates #1104 
```release-note
NONE
```
> conformance: add hostname intersection test

- apis/v1alpha2/httproute_types.go
- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
* If there are no matching routes, a 404 should be generated
* If there are matching routes but no/missing backends/endpoints to
route to, a 500 (specifically) should be generated.
Update status code requirements to return 500 if there are no backends for the route instead of 404
Fixes #1200
```release-note
The Gateway API now requires to return http 500 status code if there are no backends for existing route
```
> Move error status code from 404 to 500

- CHANGELOG.md
This is required to release `v0.5.0`.
Fixes #1183
```release-note
NONE
```
**NOTES**
This was a very manual process that relied on the `git` history as well as Github PR history. It wouldn't be too surprising if I managed to miss some things. We should probably revisit how we manage this in the future to avoid having to do this.
> docs: add v0.5.0 release CHANGELOG entry

- config/crd/experimental/kustomization.yaml
Closes #1215.
/kind bug
Adds the ReferencePolicies YAML file back to the experimental channel's kustomization.yaml file so it's included when running `kubectl kustomize` against the directory.
Fixes #1215.
```release-note
NONE
```
> add back ReferencePolicies YAML to experimental kustomization.yaml

- site-src/v1alpha2/contributing/community.md
This is just a minor docs patch: I was reading the community page and thought it may be helpful to point our our discussions board for feedback, questions or other discussions that don't really fit into the mold of an issue.
Also I added a reminder to people viewing this page to navigate to bug reports that implementation specific bugs aren't meant to be filed here, and provided a link to the implementations page in hopes this will be a small help in getting people to the right places.
```release-note
NONE
```
> docs: minor update to community bugs and feedback

- hack/build-install-yaml.sh
/kind bug
hack/build-install-yaml.sh included kustomization.yaml in
release/experimental-install.yaml by mistake so it didn't apply
successfully. Now we screen it out when deciding which files to
include.
```release-note
This release of experimental-install.yaml will apply successfully. Previous releases had some extraneous yaml.
```
> Generate working release/experimental-install.yaml

- site-src/blog/2021/introducing-v1alpha2.md
- site-src/concepts/api-overview.md
- site-src/v1alpha2/api-types/referencegrant.md
- site-src/v1alpha2/guides/tcp.md
- site-src/v1alpha2/guides/tls.md
Signed-off-by: Keith Mattix II <keithmattix2@gmail.com>
This PR adds an warning to prominent references of resources that exist only in the experimental channel so that readers are made aware of the implications of the versioning scheme as early in their Gateway API journey as possible.
Addresses #1229
```release-note
Add warning headers for experimental resources/concepts
```
> Add experimental warning for resources that are experimental

- conformance/tests/httproute-cross-namespace.go
- conformance/tests/httproute-exact-path-matching.go
- conformance/tests/httproute-header-matching.go
- conformance/tests/httproute-hostname-intersection.go
- conformance/tests/httproute-invalid-reference-grant.go
- conformance/tests/httproute-listener-hostname-matching.go
- conformance/tests/httproute-matching-across-routes.go
- conformance/tests/httproute-matching.go
- conformance/tests/httproute-reference-grant.go
- conformance/tests/httproute-simple-same-namespace.go
- conformance/utils/kubernetes/helpers.go
/kind bug
Adds a tiny type for specifying HTTPRoute ParentRefs to Gateways
in the conformance tests.  This allows us to test cases with 2 ParentRefs (to the same Gateway).
Fixes #1219
```release-note
NONE
```
> Adds new tiny type for HTTPRoute Listeners in conformance tests

- CHANGELOG.md
- Makefile
- OWNERS
- OWNERS_ALIASES
- RELEASE.md
- cloudbuild.yaml
- hack/build-and-push.sh
- mkdocs.yml
- netlify.toml
- site-src/concepts/versioning.md
/kind cleanup
This updates references to the default branch to the up-to-date name.
Fixes #1195
```release-note
NONE
```
> chore: updates for default branch rename

- conformance/tests/httproute-listener-hostname-matching.go
/kind bug
Fixes the test (which was already broken) with the API from #1228
Is there a reason not to just derive the correct status parent ref from the `parentRefs` in the `HTTPRoute` resource?
```release-note
NONE
```
> conformance: fix HTTPRouteListenerHostnameMatching

- apis/v1alpha2/referencepolicy_types.go
- apis/v1alpha2/zz_generated.deepcopy.go
When the ReferencePolicy type was added back the list type for that resource actually returns ReferenceGrants instead of ReferencePolicy. This isn't a huge deal but a lot of code generation around k8s types assume a pattern of `XResource` with a `XResourceList` having an `Items` type of `[]XResource`
N/A
```release-note
ReferencePolicyList Items is an array of ReferencePolicy again
```
> fix ReferencePolicyList.Items type

- OWNERS_ALIASES
/kind cleanup
This adds Shane Utt as a Gateway API Maintainer. It also formally recognizes @jpeach and @danehans as emeritus maintainers and removes Tim from the list so he gets slightly less spam from GitHub now :). 
```release-note
NONE
```
> Adding Shane Utt as Gateway API Maintainer

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/validation/httproute.go
- apis/v1alpha2/validation/httproute_test.go
- apis/v1beta1/httproute_types.go
- apis/v1beta1/validation/httproute.go
- apis/v1beta1/validation/httproute_test.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind feature
Adds webhook validation to ensure that no
HTTP header or query param is matched more
than once in a given route rule. Also updates
the godoc for HTTPQueryParamMatch to be
consistent with HTTPHeaderMatch.
Fixes #1225 
```release-note
Adds webhook validation to ensure that no HTTP header or query param is matched more than once in a given route rule.
```
> apis: validate header and query param matches

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/shared_types.go
- apis/v1alpha2/tcproute_types.go
- apis/v1alpha2/tlsroute_types.go
- apis/v1beta1/httproute_types.go
- apis/v1beta1/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Some of the "Supports:" statements in the doc didn't have an empty
line preceding them so the markdown engine squashed them into the end
of the previous paragraph. More diligent people than I probably
noticed this but I missed one completely so this change ensures that
each is its own paragraph. In most cases this is simply adding a blank
line.
```release-note
Spacing has been improved around the documentation of feature-level core/extended support for better readability and clarity.
```
> Ensure that "Supports:" statements stand alone in the docs

- conformance/tests/httproute-cross-namespace.go
- conformance/tests/httproute-exact-path-matching.go
- conformance/tests/httproute-header-matching.go
- conformance/tests/httproute-hostname-intersection.go
- conformance/tests/httproute-invalid-reference-grant.go
- conformance/tests/httproute-listener-hostname-matching.go
- conformance/tests/httproute-matching-across-routes.go
- conformance/tests/httproute-matching.go
- conformance/tests/httproute-reference-grant.go
- conformance/tests/httproute-request-header-modifier.go
- conformance/tests/httproute-request-header-modifier.yaml
- conformance/tests/httproute-simple-same-namespace.go
- conformance/utils/http/http.go
Adds a request header modifier test.
Updates #1103.
```release-note
NONE
```
> conformance: add request header modifier test

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/shared_types.go
- apis/v1beta1/httproute_types.go
- apis/v1beta1/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- conformance/utils/suite/suite.go
- site-src/geps/gep-1016.md
- site-src/guides/getting-started.md
- site-src/implementations.md
- site-src/index.md
/kind cleanup
This fixes several typos, removes an obsolete Service APIs ref, and updates any remaining "Gateway APIs" refs to "Gateway API".
```release-note
NONE
```
> Fix typos and remove obsolete Service APIs reference

- RELEASE.md
I tried this process out with #1254 and it definitely simplifies things.
```release-note
NONE
```
> Updating release documentation to include release notes generator

- conformance/tests/httproute-query-param-matching.go
- conformance/tests/httproute-query-param-matching.yaml
- conformance/utils/http/http.go
- conformance/utils/suite/suite.go
Adds a conformance test for HTTP query param
matching, requiring a supported feature of
"HTTPRouteQueryParamMatching" to be specified
since this is an extended conformance feature.
Updates #1102 
```release-note
NONE
```
> add HTTP query param matching conformance test

- apis/v1alpha2/shared_types.go
- apis/v1beta1/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind bug
/kind cleanup
This returns our NamedAddress type and marks it deprecated. Unfortunately I think we went a step too far when we removed it altogether. Although we've left room to add new values to enums in new minor versions, we have not provided any precedent for removing supported enum values. Unfortunately I think removing "NamedAddress" from the list of supported values would make it so HTTPRoutes that were valid in v0.4.x would not be valid in v0.5.x, which is something we should strive to avoid. 
I think the best we can do here is continue to allow the value to be set but document that it has been deprecated in favor of domain prefixed strings. Hopefully this approach makes sense.
**Does this PR introduce …
> Returning NamedAddress type and marking it deprecated

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/shared_types.go
- apis/v1beta1/httproute_types.go
- apis/v1beta1/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind cleanup
This clarifies the rules around enum values to ensure that we document that additional values may be added in the future, and how implementations must handle unknown values.
I've left conformance tests for this behavior out for now, because it's a bit complex to test with (we'll need a way to push invalid things into Kube or some other workaround).
Fixes #1014 
```release-note
All Enum API fields have had updates to clarify that we may add values at any time, and that implementations must handle unknown Enum values.
```
> Enum details update

- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/shared_types.go
- apis/v1beta1/httproute_types.go
- apis/v1beta1/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
- conformance/tests/gateway-secret-reference-grant-specific.go
- conformance/tests/httproute-hostname-intersection.go
- conformance/tests/httproute-invalid-backendref-nonexistent.go
- conformance/tests/httproute-invalid-backendref-nonexistent.yaml
- conformance/tests/httproute-invalid-backendref-unknown-kind.go
- conformance/tests/httproute-invalid-backendref-unknown-kind.yaml
- conformance/tests/httproute-invalid-cross-namespace-backend-ref.go
- conformance/tests/httproute-invalid-reference-grant.go
- conformance/utils/kubernetes/helpers.go
/kind cleanup
- Moves reasons for an individual BackendRef to be invalid so they are included in the HTTPBackendRef struct docs ( the BackendRef field).
- Clarifies rules for handling invalid BackendRefs in the BackendRefs field of the HTTPRouteRule struct.
Fixes #1211
Updates #1112
```release-note
The rules for BackendRefs have been updated to make clear that invalid BackendRefs must produce HTTP response codes of 500 in most cases.
```
This PR is still WIP, since I will need to change the conformance tests to check for the behavior. But I wanted to check that we really are in agreement on this behavior while I work …
> Update HTTPRoute BackendRef docs to clarify error behavior

- conformance/tests/httproute-invalid-backendref-unknown-kind.go
- conformance/tests/httproute-invalid-backendref-unknown-kind.yaml
Fixes a couple of copy-paste errors in the "unknown backend kind" conformance test that were causing invalid results.
```release-note
NONE
```
> conformance: fix copy-paste errors in unknown backend kind test

- OWNERS
- OWNERS_ALIASES
/kind cleanup
This formally adds @howardjohn, @keithmattix, and @mikemorris as GAMMA leads. We'll need a corresponding PR in k/org once this merges.
```release-note
NONE
```
/assign @bowei @hbagdi @shaneutt @youngnick
> Adding GAMMA leads to OWNERS

- CHANGELOG.md
- config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
- config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- config/webhook/admission_webhook.yaml
- hack/verify-examples-kind.sh
- pkg/generator/main.go
This adds the changelog for v0.5.0 and bumps CRD and webhook versions along with that.
Fixes #1261
```release-note
NONE
```
/hold for release
/cc @bowei @hbagdi @shaneutt @youngnick
> Adding changelog for v0.5.0, bumping versions to v0.5.0

- site-src/implementations.md
This adds contact information for GKE's Gateway Implementation to avoid GKE specific issues getting filed here.
```release-note
NONE
```
> Adding GKE contact information to implementations page

- config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
- config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- pkg/generator/main.go
/kind cleanup
Now that we've released v0.5.0, we need to bump our version refs throughout to avoid future API changes being included in CRDs labeled "v0.5.0".
```release-note
NONE
```
> Bumping versions to v0.6.0-dev

- pkg/client/clientset/versioned/fake/register.go
- pkg/client/clientset/versioned/scheme/register.go
/kind cleanup
Since yesterday, our verify-codegen presubmit has been failing. The timing appears to line up with https://github.com/kubernetes/kubernetes/pull/111254 and the [corresponding message sent to kubernetes-dev](https://groups.google.com/a/kubernetes.io/g/dev/c/Z7NLSTRVE0Y/m/ROPxsEO0AwAJ). I've regenerated our code with 1.19rc2 and I'm hoping that will resolve this.
```release-note
NONE
```
> Update to go 1.19rc2 to match upstream (and fix codegen)

- site-src/concepts/security-model.md
The previous link had an .md extension, but the correct URL has no extension.
This PR fixes a broken link on the Security Model docs
Fixes #
```release-note
NONE
```
> Fixes broken link on Security Model docs

- conformance/tests/httproute-exact-path-matching.go
- conformance/tests/httproute-header-matching.go
- conformance/tests/httproute-hostname-intersection.go
- conformance/tests/httproute-listener-hostname-matching.go
- conformance/tests/httproute-matching-across-routes.go
- conformance/tests/httproute-matching.go
- conformance/tests/httproute-query-param-matching.go
- conformance/tests/httproute-request-header-modifier.go
- conformance/utils/http/http.go
/kind cleanup
Conformance Test Name Generation is Flawed
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1272
No
> Rectified Conformance Test Name Generation

- conformance/tests/gateway-secret-invalid-reference-grant.go
- conformance/tests/gateway-secret-missing-reference-grant.go
- conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
- conformance/tests/gateway-secret-reference-grant-specific.go
- conformance/tests/httproute-cross-namespace.go
- conformance/tests/httproute-disallowed-kind.go
- conformance/tests/httproute-exact-path-matching.go
- conformance/tests/httproute-header-matching.go
- conformance/tests/httproute-hostname-intersection.go
- conformance/tests/httproute-invalid-backendref-nonexistent.go
- conformance/tests/httproute-invalid-backendref-unknown-kind.go
- conformance/tests/httproute-invalid-cross-namespace-backend-ref.go
- conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
- conformance/tests/httproute-invalid-reference-grant.go
- conformance/tests/httproute-listener-hostname-matching.go
- conformance/tests/httproute-matching-across-routes.go
- conformance/tests/httproute-matching.go
- conformance/tests/httproute-query-param-matching.go
- conformance/tests/httproute-reference-grant.go
- conformance/tests/httproute-request-header-modifier.go
- conformance/tests/httproute-simple-same-namespace.go
- conformance/utils/config/timeout.go
- conformance/utils/http/http.go
- conformance/utils/kubernetes/apply.go
- conformance/utils/kubernetes/helpers.go
- conformance/utils/roundtripper/roundtripper.go
- conformance/utils/suite/suite.go
/kind feature
make timeout configurable
Fixes #1287
Yes. It enables supplying timeout configuration.
> make timeout configurable

- conformance/utils/suite/suite.go
/kind bug
Previously timeout config was passed to roundtripper before defaults
were set. When suite was run with default timeouts, for example HTTP requests were
set up with a context deadline of 0, meaning they failed immediately.
N/A
NONE
> conformance/utils/suite: Move timeout setup before building roundtripper

- conformance/tests/gateway-secret-invalid-reference-grant.go
- conformance/tests/gateway-secret-missing-reference-grant.go
/kind bug
In the "GatewaySecretInvalidReferenceGrant" and "GatewaySecretMissingReferenceGrant" conformance tests for gateways, the expected condition has been changed from `InvalidCertificateRef` to `RefNotPermitted`.
Fixes #1297 
```release-note
To be conformant with the API, if there is no ReferenceGrant that grants a listener to reference a secret in another namespace, the ListenerConditionReason for the condition ResolvedRefs must be set to RefNotPermitted instead of InvalidCertificateRef.
```
> Conformance: fix Listener ConditionReason

- conformance/utils/config/timeout.go
Some exported methods like
MakeRequestAndExpectEventuallyConsistentResponse require the
TimeoutConfig resource.  Callers may want to use this with a sensible
default, so we should expose a way to get said value without requiring
the caller to understand which timeout values need to be configured.
/kind cleanup
Make it easier to use MakeRequestAndExpectEventuallyConsistentResponse.
None
```release-note
NONE
```
> Export DefaultTimeoutConfig.

- apis/v1alpha2/shared_types.go
- apis/v1beta1/shared_types.go
Documentation: `UnsupportedValue` has been added to the set of possible reasons when the `ResolvedRefs` status condition is failing. 
Fixes #1312 
```release-note
NONE
```
> Route ResolvedRefs reason godoc updated

- README.md
This PR introduces (already released) `v0.5.0` into README.md and mentions which beta features this version supports.
> docs: update README.md about v0.5.0 release

- conformance/base/manifests.yaml
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1295
/kind feature
Updates the image to support arm64+amd64
Fixes #1295
```release-note
NONE
```
> Replace echoserver with arm64 compatible version

- apis/v1alpha2/object_reference_types.go
- apis/v1beta1/object_reference_types.go
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
* `apis/v1alpha2/object_reference_types.go` (`BackendObjectReference`): 
* `apis/v1beta1/object_reference_types.go` (`BackendObjectReference`): Clarify that the `Port` field references the service port number when the backend is a Kubernetes Service.
* `config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml`: 
* `config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml`: 
* `config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml`: 
* `config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml`: 
* `config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml`: 
* `config/crd/standard/gateway.networking.k8s.io_httproutes.yaml`: Regenerate.
-------
Clarify that …
> Clarify BackendObjectReference Port field godoc

- README.md
- mkdocs.yml
- site-src/concepts/conformance.md
- site-src/concepts/guidelines.md
This adds a new conformance page to our documentation. Much of this content was pulled from the "Implementation Guidelines" page, but that was getting pretty massive and conformance seemed broader than that.
Fixes #1274
```release-note
NONE
```
> Adding docs covering conformance

- site-src/geps/gep-1324.md
/kind gep
Mainly formatting to a GEP to make it easier to read
Fixes #
NONE 
```release-note
```
> gep-1234: Formatting fixes around use cases for GAMMA initiative

- conformance/tests/gateway-secret-missing-referenced-secret.go
- conformance/tests/gateway-secret-missing-referenced-secret.yaml
/kind feature
A new conformance test case has been added to ensure that whenever a listener references an unexisting secret as CertificateRef, the Condition ResolvedRefs is set as failed with the reason InvalidCertificateRef.
Fixes #1318 
```release-note
NONE
```
> conformance: listener references invalid secret

- hack/api-docs/pkg.tpl
We display the alpha types in the API spec before the beta types. So readers see all of our types - including experimental and deprecated - before seeing the package with the more limited set of "standard" types.
Reverse this by manually iterating the packages list so that the beta package is displayed before the alpha package.
I could buy that this is too much of a hack to be worth it though!
> docs: display beta before alpha in API spec

- conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
/kind bug
Fixes a conformance test
```release-note
NONE
```
> conformance: fix GatewaySecretReferenceGrantAllInNamespace resources

- conformance/tests/gateway-secret-invalid-reference-grant.go
- conformance/tests/gateway-secret-missing-reference-grant.go
- pkg/client/clientset/versioned/fake/register.go
- pkg/client/clientset/versioned/scheme/register.go
/kind cleanup
Cherry-pick changes for #1305 to 0.5.x release branch, so that implementations can be conformant with `main` and the latest release.
Fixes #1328
```release-note
NONE
```
> Release 0.5.x: Cherry-pick #1305

- apis/v1alpha2/util/translator/shared_types.go
- apis/v1beta1/util/translator/shared_types.go
/kind cleanup
Proposed change set are helper functions to translate to and from custom types.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/826
No
> Add utils to translate custom types

- hack/api-docs/config.json
- site-src/api-types/referencegrant.md
Remove deprecated ReferencePolicy using the hideTypePatterns config for the API docs generator.
ReferencePolicy has been renamed to ReferenceGrant, but we have retained ReferencePolicy as a deprecated type in order to make migration easier.
Keeping ReferencePolicy around in the docs is confusing for readers and probably doesn't provide any value.
Also fix path of ReferenceGrant image.
/kind cleanup
> docs: couple of ReferenceGrant cleanups

- conformance/tests/gateway-unsupported-route-kind.go
- conformance/tests/gateway-unsupported-route-kind.yaml
/kind feature
A new conformance test case has been added to ensure that whenever a listener supports a Route type incompatible with the ProtocolType, the `ListenerStatus.SupportedKinds` are updated accordingly, and the `ResolvedRefs` listener condition fails with reason `InvalidRouteKinds `.
Fixes #1320 
```release-note
NONE
```
> conformance: listener `invalidRouteKind`

- site-src/api-types/httproute.md
- site-src/api-types/referencegrant.md
- site-src/contributing/enhancement-requests.md
- site-src/contributing/gamma.md
- site-src/contributing/gep.md
As caught by @plgingembre, some of our docs links incorrectly had the "/site-src" prefix, this fixes that.
```release-note
NONE
```
> Fixing docs links that incorrectly had site-src/ prefix

- site-src/api-types/gatewayclass.md
- site-src/api-types/httproute.md
- site-src/api-types/referencegrant.md
- site-src/blog/2021/introducing-v1alpha2.md
- site-src/blog/index.md
As pointed out by @markmc when reviewing #1357, we probably want to roll back all of #1319. I think this was caused by a common point of confusion. When browsing links in site-src within the repo, they will be broken, that is intentional. The goal of site-src is to build https://gateway-api.sigs.k8s.io/, not to be useful independently of that. I'm not sure how/where to document that because I know it's confusing, suggestions welcome.
```release-note
NONE
```
> Revert "broken_site_src"

- site-src/implementations.md
This PR adds help information to the NGINX Kubernetes Gateway implementation section. It also removes the `pre-alpha` qualifier from the NGINX Kubernetes Gateway implementation status. 
NONE
NONE
> Add help info to NGINX Kubernetes Gateway implementation section

- site-src/geps/gep-1324.md
The glossary section goes to great length to create a clear understanding of some terms that are especially important in the
context of a discussion of supporting mesh use-cases in the API.
However, we don't currently define the "gateway" term. Rectify this by adding a definition that makes reference to many other terms that might crop up in this conversation - e.g. traffic translation, network elements, network endpoints, senders/receivers, consumers/producers, reachability information, routing and routing discriminators, load-balancing, filtering, encryption, NAT, proxying, encapsulation, logical gateways, distributed gateways, segmentation, North/South vs East/West, micro-segmentation and zero-trust, and ingress vs egress gateways. Phew!
Hopefully this is neither hilariously incorrect …
> gep-1324: add a definition of "gateway" to glossary

- config/webhook/admission_webhook.yaml
/kind bug
As pointed out by @markmc, we missed updating the webhook config to include v1beta1 when we released v0.5.0. 
Fixes #
```release-note
NONE
```
> Fixing webhook config to watch v1beta1

- conformance/utils/http/http.go
/kind bug
Prints expected and actual conditions incase a conformance test fails.
Helps with https://github.com/kubernetes-sigs/gateway-api/issues/1317
None
> Print conditions for failed conformance tests

- config/webhook/admission_webhook.yaml
/kind bug
Cherry-pick https://github.com/kubernetes-sigs/gateway-api/pull/1365 to 0.5.x release branch
N/A
```release-note
NONE
```
> release-0.5: Cherry pick #1365 - Fixing webhook config to watch v1beta1

- site-src/geps/gep-1323.md
Signed-off-by: Sanskar Jaiswal <jaiswalsanskar078@gmail.com>
/kind gep
Adds a GEP proposing a way of modifying response headers via a new field `responseHeaderModifier`.
Fixes #1323 
```release-note
NONE
```
> add GEP-1323: Response Header Filter

- conformance/tests/httproute-method-matching.go
- conformance/tests/httproute-method-matching.yaml
- conformance/utils/suite/suite.go
Adds an opt-in conformance test for HTTPRoute method matching (extended conformance).
Updates #1102.
```release-note
NONE
```
> conformance: add HTTPRoute method matching test

- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Ensure compatibility across Gateway implementations.
To prevent users from relying on implementation-specific behavior which could cause issues when switching implementations.
Fixes #1271
```release-note
NONE
```
> Document the edge case with repeated query params

- site-src/concepts/versioning.md
This updates our versioning guidelines to allow the following types of changes:
1. Patch versions now formally allow expanding conformance test coverage 
This is very important as we're in active development and conformance test coverage of existing features  has still not reached 100%. We should not wait to add better conformance tests until we have another minor release.
2. Minor versions now allow for changes to recommended status conditions 
Importantly this does not include changes to the structure of the API, just the values we recommend that implementations set. This also includes a corresponding allowance for conformance test changes. …
> Updating our versioning guidelines to allow additional types of changes

- apis/v1alpha2/object_reference_types.go
- apis/v1alpha2/shared_types.go
- apis/v1beta1/object_reference_types.go
- apis/v1beta1/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- conformance/tests/gateway-secret-missing-referenced-secret.go
- conformance/tests/gateway-secret-missing-referenced-secret.yaml
/kind cleanup
This cherry picks the following PRs into the release-0.5 branch:
- #1316 
- #1332
- #1334 
```release-note
NONE
```
> Cherry picking several more PRs before 0.5.1 release

- conformance/tests/httproute-disallowed-kind.go
- conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
- conformance/utils/config/timeout.go
- conformance/utils/kubernetes/helpers.go
HTTPRouteInvalidCrossNamespaceParentRef hardcodes a 15 second timeout. Utilize suite.TimeoutConfig for specifying the timeout instead.
/kind cleanup
/kind flake
The test hardcodes 15 seconds for a status condition to appear which can cause flakiness for slower controllers.  Use a configurable timeout to allow for separation of function and performance.
#1397
> Add configurable timeout conformance test.

- conformance/tests/gateway-unsupported-route-kind.yaml
- conformance/tests/httproute-hostname-intersection.yaml
- conformance/tests/httproute-method-matching.yaml
/kind bug
```release-note
NONE
```
> Update remaining v1alpha2 references in conformance tests

- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind cleanup
HTTPRoute matching precedence documentation seems a little unclear, as shown by https://github.com/kubernetes-sigs/gateway-api/pull/1370 and further discussion. This PR attempts to clarify it by:
- moving the note about hostname matching closer to the hostname field
- explicitly referencing how rules and matches interact, rather than rules alone
Fixes #1381
```release-note
NONE
```
> Clarify HTTPRoute matching precedence

- site-src/geps/gep-1364.md
/kind gep
This PR adds an implementable proposal for GEP1364 (#1364).
It's a big GEP, for a _very_ big change, that will definitely break conformance tests. But I think that it will set us up with clear rules for Conditions going forward.
It's quite opinionated, so I expect to need to defend my decisions here somewhat, don't be shy about objections.
Updates #1364 
```release-note
Status definitions have been updated across the API.
```
The release note will need something like the tl;dr in the GEP, once we all agree. 😄
> Add GEP-1364 proposal

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/gatewayclass_types.go
- apis/v1alpha2/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind cleanup
This marks v1alpha2 as deprecated for beta resources. This will provide a gentler transition than immediately removing v1alpha2 from the list of served versions. Implementations should still switch to read and write from v1beta1 as soon as possible.
```release-note
v1alpha2 has been deprecated for Gateway, GatewayClass, and HTTPRoute. This version of the API will be removed from CRDs in a future release. Implementations should update to use v1beta1 for these resources as soon as possible.
```
> Marking v1alpha2 as deprecated for beta resources

- apis/v1alpha2/httproute_types.go
- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
The HTTPRoute docs have several references to
an "Attached" condition, however this condition
does not exist for routes. Replaces these
references with the appropriate "Accepted"
condition.
The HTTPRoute docs have several references to
an "Attached" condition, however this condition
does not exist for routes. Replaces these
references with the appropriate "Accepted"
condition.
See https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1.RouteConditionType for the list of valid Route condition types and reasons.
```release-note
NONE
```
> replace Attached condition with Accepted in HTTPRoute docs

- site-src/geps/gep-696.md
/kind cleanup
I've seen this minor formatting issue creep into GEPs created from this template.
N/A
```release-note
NONE
```
> website: add closing paren to GEP template

- CHANGELOG.md
- config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
- config/crd/experimental/gateway.networking.k8s.io_referencepolicies.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- config/webhook/admission_webhook.yaml
- hack/verify-examples-kind.sh
- pkg/generator/main.go
This adds the changelog for v0.5.1. This also bumps version numbers from v0.5.0 to v0.5.1 where applicable. Approving this PR means that you're approving a release of v0.5.1 based on this commit.
```release-note
NONE
```
> Adding Changelog for v0.5.1

- CHANGELOG.md
- README.md
- config/webhook/admission_webhook.yaml
- hack/verify-examples-kind.sh
- site-src/guides/getting-started.md
This updates our documentation to account for the recent [v0.5.1 release](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.5.1).
```release-note
NONE
```
> Bumping version to v0.5.1 throughout docs

- conformance/utils/kubernetes/helpers.go
/kind cleanup
This PR adds more debug information for Route's parents in conformance tests so that a user can track which particular route(s) has(have) problems when the test is running.
```release-note
NONE
```
> tests: add more debug info in conformance tests logs

- config/webhook/kustomization.yaml
- hack/verify-examples-kind.sh
Signed-off-by: Chao Zhang <tokers@apache.org>
/kind feature
/kind cleanup
Previously, we have some workaround logics in the `hack/verify-examples-kind.sh`, it modifies the image tag in `config/webhook/admission_webhook.yaml`, so that the latest commit of admission webhook can be used.
This PR removed the hack logic by using the customization feature in Kustomize, see https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#customizing for the details. We create the `config/webhook/kustomization.yaml` file temporarily (and remove it when cleanup), which replaces the webhook image tag from `v0.5.0` (or others in the future) to `latest`.
Fixes #1366
**Does this PR introduce …
> chore: remove workaround logics in verify-examples-kind.sh

- conformance/conformance_test.go
- conformance/tests/gateway-secret-invalid-reference-grant.go
- conformance/tests/gateway-secret-missing-reference-grant.go
- conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
- conformance/tests/gateway-secret-reference-grant-specific.go
- conformance/tests/httproute-invalid-cross-namespace-backend-ref.go
- conformance/tests/httproute-invalid-reference-grant.go
- conformance/tests/httproute-reference-grant.go
- conformance/utils/flags/flags.go
- conformance/utils/suite/suite.go
/kind feature
This PR add flags for SupportedFeatures and ExemptFeatures in conformance tests.
Examples:
```
// conformance tests with supported features 
go test ./conformance --gateway-class nginx -v -supported-features ReferenceGrant
go test ./conformance --gateway-class nginx -v -supported-features ReferenceGrant,HTTPRouteQueryParamMatching,HTTPRouteMethodMatchig
// conformance tests with exempt features
go test ./conformance --gateway-class nginx -v -exempt-features ReferenceGrant
```
Fixes #1391
```release-note
1. Add flags for SupportedFeatures and ExemptFeatures in conformance tests.
2. Remove suite.SupportReferenceGrant as the …
```
> Add flags for SupportedFeatures and ExemptFeatures in conformance tests.

- apis/v1alpha2/gateway_types.go
- apis/v1beta1/gateway_types.go
The `ListenerReasonRefNotPermitted` documentation has been improved to specify that this reason can be triggered by either an unpermitted `BackendRef` or an unpermitted `CertificateRef`. Besides, the `ListenerReasonInvalidCertificateRef ` documentation has been improved to specify better what makes a listener `CertificateRef` invalid
Fixes #1362 
```release-note
NONE
```
> Improve the Gateway `ResolvedRefs` condition documentation

- site-src/geps/.pages
This will order the navigation menu for approved GEPs.
Fix is using the support from the already installed `mkdocs-awesome-pages-plugin`
configured as it is given here:  https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin#customize-navigation
Now it order the nav items in chronological order:
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1428
```release-note
NONE
```
> website: render approved GEPs in chronological order

- site-src/implementations.md
Add Flomesh Service Mesh Ingress to the downstream implementation list. https://github.com/flomesh-io/fsm/issues/18 is used to track the progress of implementation.
none
```release-note
NONE
```
> Add Flomesh Service Mesh as a downstream implementation

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/grpcroute_types.go
- apis/v1alpha2/httproute_types.go
- apis/v1alpha2/shared_types.go
- apis/v1alpha2/tcproute_types.go
- apis/v1alpha2/tlsroute_types.go
- apis/v1alpha2/udproute_types.go
- apis/v1beta1/gateway_types.go
- apis/v1beta1/gatewayclass_types.go
- apis/v1beta1/httproute_types.go
- apis/v1beta1/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- site-src/api-types/httproute.md
- site-src/concepts/conformance.md
- site-src/concepts/guidelines.md
- site-src/geps/gep-1016.md
- site-src/geps/gep-718.md
- site-src/geps/gep-735.md
Signed-off-by: Lucas Caparelli <lucas.caparelli@gympass.com>
This PR merges the concepts of `custom` and `implementation-specific` conformance into `implementation-specific` only in order to simplify the spec. All `custom` conformance mentions were replaced by `implementation-specific`.
Fixes #640 
```release-note
Changes "custom" conformance level to "implementation-specific"
```
> docs: merge 'custom' and 'implementation-specific' conformance

- apis/v1alpha2/gateway_types.go
- apis/v1beta1/gateway_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind cleanup
Implements the recommendation in [GEP-1364](https://gateway-api.sigs.k8s.io/geps/gep-1364/) to replace `GatewayConditionScheduled` with `GatewayConditionAccepted`
Refs #1111, #1364
```release-note
Adds GatewayConditionAccepted and GatewayReasonAccepted
Deprecates GatewayConditionScheduled and GatewayReasonScheduled
```
This status condition does not appear to be currently checked in conformance tests, which mostly rely on the`Ready` condition instead. We could either add checks for this condition now, or in a subsequent pull request.
> add GatewayConditionAccepted and GatewayReasonAccepted

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/grpcroute_types.go
- apis/v1beta1/gateway_types.go
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
/kind cleanup
Implements the switch from `ListenerConditionDetached` to a new `ListenerConditionAttached`, as recommended in [GEP-1364](https://gateway-api.sigs.k8s.io/geps/gep-1364/).
Fixes #1110, refs #1364 
```release-note
Adds `ListenerConditionAccepted` and `ListenerReasonAccepted`
Deprecates `ListenerConditionDetached` and `ListenerReasonAttached`
```
Now that we've settled on the expected behavior, these expectations should likely be added to relevant conformance tests.
> add ListenerConditionAccepted, update docs from "Detached"

- site-src/geps/gep-1364.md
/kind cleanup
/kind gep
Fixes the last round of feedback on GEP-1364 (from #1383). Thanks @mikemorris for the review.
Updates #1364
```release-note
NONE
```
> Fix last round of feedback on GEP-1364

- apis/v1alpha2/gateway_types.go
- apis/v1alpha2/gatewayclass_types.go
- apis/v1alpha2/shared_types.go
- apis/v1beta1/gateway_types.go
- apis/v1beta1/gatewayclass_types.go
- apis/v1beta1/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind cleanup
This adds a `Pending` Reason to:
- GatewayClass
- Gateway
- Listener
- Route
And deprecates the old Reasons associated with `Unknown` state.
Fixes #1449 
```release-note
A `Pending` Reason has been added to Conditions to harmonize the unreconciled state across objects.
GatewayClass, Gateway, and Route `Accepted` Conditions have been updated.
```
> Add Pending reason to GatewayClass, Gateway, Listener, and Routes

- apis/v1beta1/gateway_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
#1297 and #1362 have clarified that a cross-namespace certificate reference without a `ReferenceGrant` permitting it should use `RefNotPermitted` instead of `InvalidCertificateRef`; however, there is one remaining reference to `InvalidCertificateRef` for this purpose in the docs.
```release-note
NONE
```
> Use correct reason in docs when no ReferenceGrant for cert ref

- conformance/tests/gateway-unsupported-route-kind.go
- conformance/tests/gateway-unsupported-route-kind.yaml
/kind bug
The resources created by the `GatewayUnsupportedRouteKind` test aren't valid because if protocol is HTTPS, the TLS field must be set. I think #1460 would have caught this.
They don't need to be HTTPS for this test however.
```release-note
NONE
```
> conformance: fix GatewayUnsupportedRouteKind HTTPS listeners without TLS config

- site-src/implementations.md
Signed-off-by: Nick Young <nick@isovalent.com>
Adds Envoy Gateway to the Implementations page.
v0.2.0 is due out any day, which includes initial support.
```release-note
NONE
```
> Add Envoy Gateway to implementations page

- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Add `Support: Extended` comment for `HTTPRouteMatch.QueryParam`, so the documentation is less confusing. As it is now, the  `HTTPRouteMatch.QueryParam` is a list of `HTTPQueryParamMatch`, that has a `Type` field that can be Exact (Support: Extended, default value) or  RegularExpression (Support: Implementation-specific). The gateway implementation does not need to implement RegularExpression type to be conformant. As such, it seems `HTTPRouteMatch.QueryParam` should be marked as extended support.
Fixes #1466
```release-note
NONE
```
> Mark `HTTPRouteMatch.QueryParam` as extended

- site-src/implementations.md
This PR updates Contour's implementation status and the supported Gateway API version.
* Contour implements Gateway API v0.5.1 - see [contour](https://github.com/projectcontour/contour/blob/main/go.mod#L43)
* Moving the status to `beta` as contour implements the beta resources and are passing all conformance tests.
FYI, I work with @skriss and @sunjayBhatia.
```release-note
NONE
```
> docs: update Contour implementation status

- apis/v1alpha2/validation/gateway.go
- apis/v1alpha2/validation/gateway_test.go
- apis/v1beta1/validation/gateway.go
- apis/v1beta1/validation/gateway_test.go
/kind feature
- Add a validation to validate TLS config must be set when protocol is HTTPS or TLS.
- Remove TLS validate duplicate code and tests in v1alpha1 and include that from v1beta1.
Fixes #1467 
```release-note
NONE
```
> Webhook: validate TLS config must be set when protocol is HTTPS or TLS.

- apis/v1alpha2/validation/grpcroute.go
- apis/v1alpha2/validation/grpcroute_test.go
- pkg/admission/server.go
/kind feature
- Initial GRPCRoute apis validations
- Add a validation to validate that at least one of the fields Service and Method of GRPCMethodMatch to be specified
Fixes #1098 
```release-note
NONE
```
> Webhook: validate at least one of GRPCRoute.Rules.Matches.{Method,Service} is supplied

- mkdocs.yml
- site-src/geps/gep-735.md
/kind gep
At Kubecon 2022 in our working sessions, we decided to explicitly mark this GEP as declined so as to not cause any confusion whether we have any specific plans to implement it in an upcoming release, and to document the reasoning why it has been declined.
NONE
> docs: mark GEP-735 as declined

- examples/standard/reference-grant.yaml
- site-src/blog/2021/introducing-v1alpha2.md
- site-src/concepts/security-model.md
- site-src/guides/tls.md
* These broken links are causing rendering issues on the published docs and also show up when runnning `make docs`.
* For everything except the v1alpha2 blog I simply updated the link
* For the v1alpha2 blog I copied the actual yaml from when the blog was posted.
* Example of https://gateway-api.sigs.k8s.io/blog/2021/introducing-v1alpha2/ right now:
* `make docs` now reports no errors when I run it locally.
```release-note
NONE
```
> Fix Broken Links in Docs Causing Rendering Failures

- apis/v1beta1/object_reference_types.go
- apis/v1beta1/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Clarifies the current default behavior when the `Group` field is unspecified for a `ParentReference`, and how to set the core API group for a `Service` referent (which will be relevant for GAMMA implementations).
For `BackendObjectReference`, `SecretObjectReference` and `LocalObjectReference`, disambiguates the behavior of an unspecified `Group` field from an empty string.
Updates the example `Group` values to `gateway.networking.k8s.io` (from `networking.k8s.io`) - this may not be necessary, but felt like it would be a more common value when the `Group` field is set explicitly.
N/A
```release-note
NONE
```
> apis: update Group default docs and examples for *Reference types

- apis/v1beta1/httproute_types.go
- apis/v1beta1/validation/httproute.go
- apis/v1beta1/validation/httproute_test.go
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Documents restrictions on header filters and how implementations should handle invalid filters. Header filters cannot modify the same header twice. When users require multiple values for the same header, they must specify the comma-separated values in configuration.
~Adds a conformance test confirming that invalid headers result in a false `Accepted` Condition with reason `RouteReasonUnsupportedValue`.~
Adds a webhook rule that rejects header filters that violate the single action per header rule.
Fix #480. Order of operations is a moot point if there is only one action for a given header, and there are no outcomes that actually require multiple actions.
**Does this …
> Add and test single filter action per header restriction

- Dockerfile
- README.md
- hack/build-and-push.sh
Update Dockerfile to support different OS archs support, and update related script.
/kind feature
More requirements for ARM support.
> Add Docker image support multi OS archs

- conformance/base/manifests.yaml
- conformance/tests/httproute-cross-namespace.go
- conformance/tests/httproute-exact-path-matching.go
- conformance/tests/httproute-header-matching.go
- conformance/tests/httproute-hostname-intersection.go
- conformance/tests/httproute-invalid-backendref-nonexistent.go
- conformance/tests/httproute-invalid-backendref-unknown-kind.go
- conformance/tests/httproute-invalid-cross-namespace-backend-ref.go
- conformance/tests/httproute-invalid-reference-grant.go
- conformance/tests/httproute-listener-hostname-matching.go
- conformance/tests/httproute-method-matching.go
- conformance/tests/httproute-query-param-matching.go
- conformance/tests/httproute-reference-grant.go
- conformance/tests/httproute-request-header-modifier.go
- conformance/tests/httproute-response-header-modifier.go
- conformance/tests/httproute-response-header-modifier.yaml
- conformance/tests/httproute-simple-same-namespace.go
- conformance/utils/http/http.go
/kind bug
/kind cleanup
Fixes logic in `HTTPRouteResponseHeaderModifier` conformance test.
Previously, the test conflated request and response headers.
Changes in this PR along with updated echoserver (see https://github.com/kubernetes-sigs/ingress-controller-conformance/pull/100) allow test to modify what response headers the backend app returns, to ensure modifications an implementation makes as a result of the ResponseHeaderModifier Filter are correct.
Also does some minor cleanup and changes/fixes assertions around headers.
This PR is verified with a local build of the echoserver image from https://github.com/kubernetes-sigs/ingress-controller-conformance/pull/100 as well as this spike on Contour to implement the …
> conformance: Fix logic in HTTPRouteResponseHeaderModifier test

- conformance/tests/gateway-invalid-tls-certificateref.go
/kind bug
Makes the test actually run all 4 tests instead of run 1 test 4 times
NOTE: Istio is actually not conformant here so I didn't test that the new tests actually work as expected
```release-note
NONE
```
> conformance: fix invalid `for` loop in InvalidTls test

- OWNERS
- OWNERS_ALIASES
- README.md
/kind cleanup
This PR does 2 things:
- Merges Gateway API Admins and Maintainers: This will not have any real effect until we make the same change in k/org. At that point, Gateway API maintainers will get slightly more GitHub access.
- Moves @hbagdi to emeritus: A huge thanks for all his contributions over the years, unfortunately he doesn't have the same level of bandwidth to contribute to the project anymore.
I've checked in with everyone that would be affected by these changes, and they're all onboard.
```release-note
NONE
```
/cc @bowei @hbagdi @shaneutt @thockin @youngnick
> Merging Gateway API Admins and Maintainers, Moving Harry to Emeritus

- site-src/implementations.md
Added a section for the LiteSpeed Ingress Controller
Announce LiteSpeed Ingress Controller Gateway API support.
Fixes #
yes
```release-note
Announce LiteSpeed Ingress Controller Gateway API support.
```
> chore: cleanup litespeed section on implementations page

- apis/v1alpha2/gateway_types.go
- apis/v1beta1/gateway_types.go
- conformance/tests/gateway-secret-missing-reference-grant.go
- conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
- conformance/tests/gateway-secret-reference-grant-specific.go
- conformance/tests/httproute-cross-namespace.go
- conformance/tests/httproute-disallowed-kind.go
- conformance/tests/httproute-exact-path-matching.go
- conformance/tests/httproute-header-matching.go
- conformance/tests/httproute-hostname-intersection.go
- conformance/tests/httproute-invalid-backendref-nonexistent.go
- conformance/tests/httproute-invalid-backendref-unknown-kind.go
- conformance/tests/httproute-invalid-cross-namespace-backend-ref.go
- conformance/tests/httproute-invalid-reference-grant.go
- conformance/tests/httproute-listener-hostname-matching.go
- conformance/tests/httproute-matching-across-routes.go
- conformance/tests/httproute-matching.go
- conformance/tests/httproute-method-matching.go
- conformance/tests/httproute-query-param-matching.go
- conformance/tests/httproute-reference-grant.go
- conformance/tests/httproute-request-header-modifier.go
- conformance/tests/httproute-response-header-modifier.go
- conformance/tests/httproute-simple-same-namespace.go
- conformance/utils/kubernetes/helpers.go
- conformance/utils/suite/suite.go
/kind feature
**What this PR does / why we need it**: Make necessary changes to Gateway and Listener conditions in order to implement [GEP-1364](https://gateway-api.sigs.k8s.io/geps/gep-1364/).
Fixes #1454 
```release-note
Added "Programmed" Gateway and Listener conditions, moved "Ready" to extended conformance
```
> Add "Programmed" Gateway condition, move "Ready" to extended conformance

- apis/v1alpha2/grpcroute_types.go
- apis/v1alpha2/zz_generated.deepcopy.go
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
/kind bug
This PR fixes some minor issues in the `GRPCRoute` GEP, namely:
- Includes const values for `GRPCRouteMethodMatchType`
- Correctly interprets unsupplied `Service` and `Method` fields
- Adds support for `ResponseHeaderModifierFilter`, which was recently added to `HTTPRoute`
```release-note
NONE
```
> Minor GRPCRoute implementation fixes

- site-src/implementations.md
In https://github.com/kubernetes-sigs/gateway-api/pull/1529 we accidentally undid some changes @robscott had made to the Google section of the implementations page. This PR cherry-picks the original commit back on top to fix that mistake while also keeping authorship and attribution intact.
> fix: cherry pick to re-apply google implementations page

- apis/v1beta1/shared_types.go
- conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
- conformance/tests/httproute-invalid-parentref-not-matching-listener-port.yaml
- conformance/utils/suite/suite.go
/kind feature
Fixes #1511
```release-note
- Add `RouteReasonNoMatchingParent` reason for `Accepted` condition set on routes when no matching parent has been found
```
> feat: add `RouteReasonNoMatchingParent`

- conformance/tests/httproute-partially-invalid-via-reference-grant.go
Fixes the manifest file name for a recently renamed conformance test.
See https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/tests/httproute-partially-invalid-via-reference-grant.yaml
N/A
```release-note
NONE
```
> conformance/tests: fix manifest file name

- hack/build-and-push.sh
/kind bug
Build job failed, not sure what compatibility problem for this, after changed and tested successful now in local:
> Remove -f to use default value for docker build job fix

- cloudbuild.yaml
Signed-off-by: bitliu <bitliu@tencent.com>
/kind bug
Fixes #1514
```release-note
NONE
```
> fix: multi-push ci failed

- site-src/api-types/referencegrant.md
There is a typo in the documentation for ReferenceGrant. Using the example does not work unless you change networking.gateway.k8s.io -> gateway.networking.k8s.io in the from.group field.
```release-note
NONE
```
> Typo in ReferenceGrant documentation.

- apis/v1alpha2/util/translator/shared_types.go
- apis/v1beta1/util/translator/shared_types.go
This PR corrects documentation for all the string to type xx' translater functions.
```release-note
NONE
```
> Correct util/translator function documentation

- site-src/geps/gep-1323.md
fix: typo: indent
fix typo in document.
Fixes #
```release-note
NONE
```
> fix: typo: indent

- apis/v1alpha2/grpcroute_types.go
- apis/v1alpha2/referencegrant_types.go
- apis/v1alpha2/util/translate/httproute.go
- apis/v1alpha2/util/translate/httproute_test.go
- apis/v1alpha2/util/translate/shared_types.go
- apis/v1alpha2/util/translate/shared_types_test.go
- apis/v1alpha2/validation/common.go
- apis/v1alpha2/validation/gateway.go
- apis/v1alpha2/validation/grpcroute.go
- apis/v1alpha2/validation/httproute_test.go
- apis/v1beta1/httproute_types.go
- apis/v1beta1/referencegrant_types.go
- apis/v1beta1/shared_types.go
- apis/v1beta1/util/translate/httproute.go
- apis/v1beta1/util/translate/httproute_test.go
- apis/v1beta1/util/translate/shared_types.go
- apis/v1beta1/util/translate/shared_types_test.go
- apis/v1beta1/validation/gateway.go
- apis/v1beta1/validation/httproute_test.go
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
This includes several smaller cleanup items from feedback on #1538
> chore: cleanup for #1538

- site-src/concepts/security-model.md
Fixes a minor typo in the documentation
None
```release-note
Fixed typo in security model documentation
```
> Update typo in security-model.md

- apis/v1alpha2/grpcroute_types.go
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- Remove rationales
- Be more explicit about h2, h2c, prior knowledge, and ALPN.
/kind cleanup
```release-note
NONE
```
> Rework GRPCRoute API docs.

- conformance/OWNERS
- site-src/geps/OWNERS
This change makes it so that mesh leads wont be pulled in for
every review, but instead just for GEPs and conformance tests
which for the moment are the most relevant to them. This was
done in response to a plea from mesh leads in the community
sync to reduce the amount of reviews they get assigned to for
subjects that might not be relevant.
> chore: remove mesh leads from * reviews

- mkdocs.yml
- site-src/geps/gep-1364.md
/kind gep
Updates GEP-1364 (#1364) to implemented in the Standard channel.
Fixes #1364.
> Update GEP-1364 to Standard implementation

- conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
/kind bug
/kind cleanup
Conformance test cannot be run, fails with: `open tests/httproute-invalid-backendref-not-matching-listener-port.yaml: file does not exist`
N/A (but can open if needed)
```release-note
N/A
```
This should also be applied to the 0.6.0 release
> Fix filename in HTTPRouteInvalidParentRefNotMatchingListenerPort test

- conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
- conformance/tests/httproute-invalid-parentref-not-matching-listener-port.yaml
The manifest for not matching listener port is rejected by admission webhook due to missing port for Service reference. While the test is to verify some other behavior (i.e. parent gateway port is not matching), it's better to have valid resource to avoid any confusion or any implementation expectation, not to mention to be consistent with other conformance tests (e.g. invalid-cross-namespace-parent-ref).
This commit also updates gateway name used in verification step to be consistent of the gateway used in HTTPRoute resource.
Signed-off-by: Tam Mach <sayboras@yahoo.com>
```release-note
conformance: Update HTTPRouteInvalidParentRefNotMatchingListenerPort
```
Testing was done by running the whole conformance suite with below command with …
> conformance: Update HTTPRouteInvalidParentRefNotMatchingListenerPort

- conformance/conformance_test.go
- conformance/tests/httproute-request-redirect.go
- conformance/tests/httproute-request-redirect.yaml
- conformance/utils/http/http.go
- conformance/utils/roundtripper/roundtripper.go
/kind feature
Add tests for core redirect features 
Issue #1103 
NONE
> added redirect tests for core redirect features

- hack/verify-examples-kind.sh
/kind cleanup
Updates kind to `v0.17.0`
Fixes `hack/verify-examples-kind.sh` to work on Mac. `wc -l` on Mac has whitespaces so the check will never succeed, `xargs` takes care of that.
Also adds a `cleanup` in case there's a timeout.
```release-note
NONE
```
> Bump kind to v0.17.0

- apis/v1alpha2/gateway_types.go
- apis/v1beta1/gateway_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind cleanup
Replaces the Ready condition with the Programmed
condition as a print column for Gateways since
Programmed is core conformance and Ready is not.
This seems like a desirable change to me but others
should obviously weigh in too.
```release-note
Display the Programmed condition instead of the Ready condition in the output of `kubectl get gateways`.
```
> use Programmed instead of Ready for Gateway print column

- site-src/contributing/devguide.md
It was requested by several members in the community in our recent syncs that we start utilizing priority labels more to help members understand better the expected priority of various issues.
I also took a second to rework how the guidance on milestones read to be more inline with how we use milestones today.
> docs: dev notes about prio labels

- apis/v1alpha2/grpcroute_types.go
- apis/v1alpha2/httproute_types.go
- apis/v1beta1/gateway_types.go
- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind cleanup
- Adds the `Programmed` Condition to the Gateway default condition list. (https://github.com/kubernetes-sigs/gateway-api/pull/1538#discussion_r1024619384)
- Adds conformance information to all the type selectors that have values like `Exact` and `RegularExpression` to ensure that `RegularExpression` is clearly `ImplementationSpecific` conformance. (#1581)
Fixes #1581 
```release-note
- The Gateway default conditions list now includes the Programmed condition.
- `RegularExpression` type selectors have been clarified to all be `ImplementationSpecific` conformance.
```
> Update types to fix API review feedback

- config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
- config/webhook/admission_webhook.yaml
- hack/verify-examples-kind.sh
- pkg/generator/main.go
This makes the remaining changes needed to release `v0.6.0-rc2`.
> Finish preparing for v0.6.0-rc2 release

- site-src/implementations.md
> Update istio implementation info

- conformance/tests/gateway-observed-generation-bump.go
- conformance/tests/gateway-observed-generation-bump.yaml
- conformance/tests/gatewayclass-observed-generation-bump.go
- conformance/tests/gatewayclass-observed-generation-bump.yaml
- conformance/tests/httproute-observed-generation-bump.go
- conformance/tests/httproute-observed-generation-bump.yaml
- conformance/utils/kubernetes/apply.go
- conformance/utils/kubernetes/apply_test.go
- conformance/utils/kubernetes/helpers.go
- conformance/utils/suite/suite.go
/kind cleanup
This PR ensures Gateway Resources and their conditions update observedGeneration as described in the GEP.
Current it tests
Fixes: https://github.com/kubernetes-sigs/gateway-api/issues/1584
```release-note
Conformance tests now assert observedGeneration is incremented in Status.Conditions (GatewayClass, Gateway, HTTPRoute)
```
> Assert observedGeneration is incremented in Status.Conditions.

- CHANGELOG.md
Adds the `CHANGELOG` entry for the `v0.6.0` release.
Fixes #1613
> docs: add v0.6.0 changelog entry

- conformance/utils/roundtripper/roundtripper.go
This is a global variable. Since we import the tests and then run other tests, this broke our other tests which depend on DefaultClient.
/kind bug
Fixes #
```release-note
```
> conformance: do not use (and mutate) DefaultClient

- site-src/implementations.md
The PR adds BIG-IP Kubernetes Gateway to the list of the implementations in the docs.
None
None
> Add BIG-IP Kubernetes Gateway to list of implementations

- conformance/utils/roundtripper/roundtripper.go
- pkg/admission/server.go
/kind cleanup 
The package `io/ioutil` has been deprecated from g0 1.16: https://go.dev/doc/go1.16#ioutil
> cleanup: remove ioutil for new goversion

- conformance/tests/httproute-rewrite-host.go
- conformance/tests/httproute-rewrite-host.yaml
- conformance/tests/httproute-rewrite-path.go
- conformance/tests/httproute-rewrite-path.yaml
- conformance/utils/http/http.go
- conformance/utils/suite/suite.go
/kind feature
Add tests for http rewrite 
Issue #1103 
```
- Added: conformance tests for http rewrite host and path filters.
```
> Http rewrite conformance

- conformance/tests/httproute-matching.go
/kind cleanup
Adds some test cases (from Contour e2e tests) for edge cases in path matching.
In consolidating this set of test cases: https://github.com/projectcontour/contour/blob/76521b7dbc562815083ec207abef686bc02614ce/test/e2e/gateway/path_condition_match_test.go#L69-L84
We found we can eliminate all but a few that do not have overlap with the upstream conformance tests, so added tests for the following cases:
- trailing slash on path prefix should match
- path prefixes are path segment matches not string prefix matches
- test to ensure a path containing the prefix is not matched
N/A
```release-note
NONE
```
> conformance: Add additional path matching edge cases

- apis/v1beta1/object_reference_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
According to the doc:
> A single CertificateRef to a Kubernetes Secret has “Core” support. Implementations MAY choose to support attaching multiple certificates to a Listener, but this behavior is implementation-specific.
and the line below
```
+kubebuilder:default=Secret
```
It looks like Secret should be the default implementation of the SecretObjectReference. And `HTTPRoute` or `Service` is certainly not a secret store.
> Doc: SecretObjectReference use "Secret" as Kind

- examples/standard/simple-http-https/bar-route.yaml
- examples/standard/simple-http-https/foo-route.yaml
- examples/standard/simple-http-https/gateway.yaml
- examples/standard/simple-http-https/tls-redirect-route.yaml
- mkdocs.yml
- site-src/guides/index.md
- site-src/guides/migrating-from-ingress.md
As part of the guides section of the docs (https://gateway-api.sigs.k8s.io/guides/), add a "Migrating from Ingress" guide to help Ingress users adopt the Gateway API.
The Gateway API resources are quite different from the Ingress resource, so explaining the differences and how to translate the Ingress resource to Gateway API resources will hopefully reduce the friction for Ingress users when they try to migrate to the Gateway API.
Fixes #1427
enter a release note below:
```release-note
NONE
```
> Add migration guide from Ingress

- apis/v1beta1/validation/httproute.go
Adding `[%][0-9a-fA-F]{2}` as an option to find Hex values. Also adding `@` as a value to find as well.
The subset of single characters can be selected in addition to the set of all Hex values, hence the `(?:<pattern1>|<pattern2>)`
/kind bug
Complies with RFC-3986 "p-char" characters.
Updates this PR [#1599](https://github.com/kubernetes-sigs/gateway-api/pull/1599)
It might, but not really.
```release-note
update route validation to comply with RFC-3986 "p-char" characters.
```
> update regex to comply with RFC-3986

- site-src/geps/gep-696.md
Status definitions were pointing to the wrong file
> Fix GEP template - status link was wrong

- apis/v1beta1/shared_types.go
- requirements.txt
In the GO documentation, `NoMatchingParent` has been added to the possible reasons for which the route Accepted condition can be false.
Fixes #
```release-note
NONE
```
> reason `NoMatchingParent` added to the documentation

- conformance/tests/gatewayclass-observed-generation-bump.go
- conformance/utils/kubernetes/helpers.go
- conformance/utils/suite/suite.go
* enhance `GWCMustBeAccepted` to pass a status value along, an empty string indicates, any status value is matched.
* Loosen the check within `GatewayClassObservedGenerationBump` to wait for the `Accepted` condition to have any status value
Relates to https://kubernetes.slack.com/archives/CR0H13KGA/p1673836949189379?thread_ts=1673599220.709819&cid=CR0H13KGA
Signed-off-by: Arko Dasgupta <arko@tetrate.io>
Fixes #
```release-note
```
> Loosen `Accepted` check in GWC Obs Generation test

- hack/boilerplate/boilerplate.py
/kind bug
Noticed this in https://github.com/kubernetes-sigs/gateway-api/pull/1673
```release-note
NONE
```
> Fixing verify-boilerplate to work with latest build images

- site-src/geps/gep-713.md
/kind feature
/kind gep
Updates GEP-713 with recommended conditions and reasons that can be set in the policy status.
https://github.com/kubernetes-sigs/gateway-api/issues/1641
> Define recommended conditions for policies

- site-src/geps/gep-1426.md
/kind gep
This also clarifies parentRef namespace boundries which were under-specified.
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/1480
```release-note
NONE
```
> Mesh: define namespace boundaries for parent and backend

- config/webhook/certificate_config.yaml
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
/kind bug
ClusterRoleBinding should not be namespaced
Fixes  https://github.com/kubernetes-sigs/gateway-api/issues/1681
```release-note
```
> fix: remove ClusterRoleBinding's namespace field

- apis/v1beta1/shared_types.go
Issue #1670
The condition needs to be added in order to prevent crossname-space parentref
> Add condition in Failed accepted reasons

- conformance/utils/kubernetes/helpers.go
* Find the expcted SupportedKind element in the actual SupportedKind slice instead of doing an exact match because the actual/implementation populated SupportedKinds field might support more Kind that defined in the test.
Fixes: https://github.com/kubernetes-sigs/gateway-api/issues/1691
Signed-off-by: Arko Dasgupta <arko@tetrate.io>
> Fix SupportedKinds check

- pkg/admission/server.go
Signed-off-by: Kante Yin <kerthcet@gmail.com>
/kind cleanup
What commits in this PR:
1. Remove redundant `return` who conflicts with go-staticcheck
2. Validate admission Kind first for saving performance in Unmarshal. Maybe bit improves but better than not.
Fixes #
```release-note
None
```
> Validate admission Kind first for efficiency

- conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
- conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
When the `HTTPRoute` is not accepted because the cross-namespace `parentRef` is not granted, the specific reason `ParentRefNotPermitted` is used.
/kind feature
Fixes #1688 
```release-note
The conformance test HTTPRouteInvalidCrossNamespaceParentRef now requires the HTTPRoute accepted condition to be failing with the ParentRefNotPermitted reason.
```
> `ParentRefNotPermitted` route reason in conformance test

- conformance/conformance_test.go
- conformance/utils/flags/flags.go
- conformance/utils/suite/suite.go
/kind feature
It adds `all-features` flag to add ability to enable all supported feature conformance tests. For example:
```
go test ./conformance --gateway-class istio --debug --all-features
```
Fixes #1638 
```release-note
1. Add `all-features` flag to enable all supported feature conformance tests.
```
> Add `all-features` flag to add ability to enable all supported feature conformance tests.

- site-src/guides/tls.md
/kind cleanup
[TLS Configuration](https://gateway-api.sigs.k8s.io/guides/tls/?h=ciphers#listeners-and-tls) mentions about `hostname.match`
but it is not available in the current version.
e.g. [v0.1.0-rc1 seems to have it](https://github.com/kubernetes-sigs/gateway-api/blob/v0.1.0-rc1/config/crd/bases/networking.x-k8s.io_gateways.yaml#L71-L88) but it is not found in the current version.
Hence this patch removes the sentence.
```release-note
NONE
```
> Drop obsolete sentence about `hostname.match`

- apis/v1beta1/shared_types.go
- conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
- conformance/tests/httproute-invalid-parentref-not-matching-listener-port.go
While testing v0.6.1 we found that we had included a new type that was not needed. This PR reverts the relevant changes.
Special thanks to @skriss and @mlavacca for your assistance!
> Remove ParentRefNotPermitted

- conformance/utils/kubernetes/helpers_test.go
/kind cleanup
Adds one more test case to specifically test the bug from #1703.
This test case fails with the old code, and passes with the new code from #1707.
Fixes #
```release-note
NONE
```
cc @shaneutt
> add additional unit test case for #1703

- conformance/tests/httproute-invalid-cross-namespace-parent-ref.go
Checks for the NotAllowedByListeners reason on
the HTTPRoute's Accepted: false condition in
the HTTPRouteInvalidCrossNamespaceParentRef
test.
Checks for the NotAllowedByListeners reason on
the HTTPRoute's Accepted: false condition in
the HTTPRouteInvalidCrossNamespaceParentRef
test.
Fixes #1705
```release-note
Checks for the NotAllowedByListeners reason on
the HTTPRoute's Accepted: false condition in
the HTTPRouteInvalidCrossNamespaceParentRef
conformance test.
```
> conformance: check reason in HTTPRouteInvalidCrossNamespaceParentRef test

- site-src/geps/gep-1324.md
Fix list nesting underneath [this section](https://gateway-api.sigs.k8s.io/geps/gep-1324/#use-cases) of the GEP.
These 3 items e, f, and g should be under d
> cleanup: GEP-1324 Typo - Fix indentation

- config/webhook/certificate_config.yaml
As per https://github.com/kubernetes/k8s.io/issues/4738 this resolves our usage of the [now deprecated k8s.gcr.io registry](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/).
> chore: replace usage of the deprecated k8s.gcr.io registry

- conformance/tests/gateway-observed-generation-bump.go
- conformance/tests/httproute-disallowed-kind.go
- conformance/tests/httproute-hostname-intersection.go
- conformance/tests/httproute-listener-hostname-matching.go
- conformance/tests/httproute-observed-generation-bump.go
- conformance/utils/config/timeout.go
- conformance/utils/kubernetes/helpers.go
- conformance/utils/suite/suite.go
/kind test
This adds a requirement in conformance tests that Gateways must be "Programmed" (previously this was just "Accepted"). Note that this only covers the top level "Programmed" condition, not each Listener.
Fixes #1722
```release-note
Conformance: Gateways must publish the "Programmed" condition.
```
> Requiring "Programmed" condition in conformance tests

- conformance/utils/kubernetes/helpers_test.go
I have added the unit test for listenersMatch in conformance utils
Fixes #
```release-note
```
> unit test for listenersMatch in conformance utils

- apis/v1beta1/gateway_types.go
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
/kind bug
The Gateway default conditions have been updated to always use `accepted` with `pending` reason and `programmed` with `pending` reason by default. Before this, the deprecated `NotReconciled` reason was still used by default when the `Gateway` status was not set.
Fixes #
```release-note
NONE
```
> Gateway default conditions updated

- site-src/geps/gep-1709.md
/kind gep
This is one of several issues needed in support of #1709.
This is meant to be a small initial iteration to make sure we have alignment on the "what" and "why" by way of the tldr, goals and introduction, but not bothering yet with the how. The hope is that if we have alignment follow up iterations can be responsible for filling in the "how". Please feel very free to add suggestions for anything you want to see changed or added, I want to incorporate and co-author this with anyone with ideas and interest.
> docs: add goals and intro for conformane profiles GEP

- RELEASE.md
- site-src/guides/index.md
Noticed in https://github.com/kubernetes-sigs/gateway-api/issues/1543, this updates some links to versions that got left behind in recent releases and updates the `RELEASE.md` instructions so they wont be left behind in the future.
> Update version links in guide

- apis/v1alpha2/grpcroute_types.go
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
/kind bug
GRPCRoute: drops method match defaults to allow for either no matches to be specified in order to match all requests, or header-only matches.
Fixes #1751 
```release-note
Removes GRPCRoute method match defaulting to allow for matching all requests, or matching only by header.
```
> drop default method matches from GRPCRoute

- conformance/utils/kubernetes/helpers.go
- conformance/utils/kubernetes/helpers_test.go
While waiting for GatewayClass to be ready, log the Generation / ObservedGeneration since it gives a useful signal on whether the controller is stuck, or trying to converge forever.
/kind cleanup
/kind tet
Improve conformance debug.
Minor improvement, no issue filed.
```release-note
NONE
```
> Log Generation / Observed generation.

- geps/gep-1709.md
- mkdocs.yml
/kind gep
This contributes to #1709 and #1329 by adding the initial ideas for an implementation of conformance profiles to the relevant GEP.
Please note that the GEP remains in `provisional` state for this iteration so nothing that merges here is necessarily set in stone. Therefore if you have some lingering questions or concerns there will be more time to voice those concerns, and ideally even make your own PR making the changes that you want to see and helping co-author the GEP to pull in your ideas!
> GEP 1709: initial implementation ideas

- geps/gep-1709.md
/kind gep
There was an existing TODO in GEP 1709 to determine how we can validate `ConformanceReport` resources. This small patch clarifies how that will be done, and that CI will validate and lint these reports when submitted by maintainers.
> GEP 1709: ConformanceReport validation

- geps/gep-1709.md
/kind cleanup
/kind gep
This adds some cleanup and clarifications for GEP 1709.
It **does not add or change concepts or context**, just an attempt to improve how it reads.
In particular, we had mentioned `implementation-specific` conformance in the doc previously, but that was mostly because we wanted to point out we consider that a future possibility. This clarifies that by adding it to the alternatives considered section as a note for follow-up iterations.
Relates to #1709
> GEP 1709: small cleanups and clarifications

- geps/gep-1709.md
- geps/overview.md
- mkdocs.yml
/kind gep
This supports #1709 by moving the GEP into a new `Prototyping` status, indicating that we're going to be doing some active testing and experimentation to see how we like things and ultimately feed back into further iterations on the GEP.
> **NOTE**: Originally I went for `Experimental` to make a clear indication to the community that we're going to be doing some
> experimentation before we seek consensus and move to `implementable`, however we use `Experimental` for something
> somewhat specific right now so there was some concern this would be confusing. The new `Prototyping` status is simply
> an extension of `Provisional` intended to allow community members to signal the intent to incorporate prototyping as …
> docs: GEP 1709 change status to new prototyping GEP status

- mkdocs.yml
- requirements.txt
- site-src/geps/gep-1742.md
/kind gep
This PR adds a first attempt at systematizing the discussion around timeouts in Gateway API.
It also adds support for Markdown tables and MermaidJS diagrams to our mkdocs installation.
Updates #1742
```release-note
NONE
```
> GEP: Add Timeouts GEP first cut

- apis/v1alpha2/grpcroute_types.go
- apis/v1alpha2/validation/grpcroute.go
- apis/v1alpha2/validation/grpcroute_test.go
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
/kind bug
Removes validation for service and method fields in GRPCMethodMatch to allow use of regular expressions.
Fixes #1746
> Removes field validation from GRPCRoute Method/Service fields

- site-src/implementations.md
Updates Cilium implementation status now that Cilium 1.13 has been released.
```release-note
NONE
```
> Update Cilium implementation status

- conformance/tests/gateway-observed-generation-bump.go
- conformance/tests/gatewayclass-observed-generation-bump.go
- conformance/tests/httproute-observed-generation-bump.go
/kind feature
Using `Update` can lead to Conflict errors that fail the test:
```
the object has been modified; please apply your changes to the latest version and try again
```
Another option would be to use something like https://pkg.go.dev/k8s.io/client-go/util/retry#RetryOnConflict but just using `Patch` seems a simpler option for this case.
```release-note
NONE
```
> conformance: use Patch to make ObservedGeneration tests robust against conflicts

- conformance/tests/gateway-invalid-route-kind.go
- conformance/tests/gateway-invalid-tls-certificateref.go
- conformance/tests/gateway-secret-invalid-reference-grant.go
- conformance/tests/gateway-secret-missing-reference-grant.go
- conformance/tests/gateway-secret-reference-grant-all-in-namespace.go
- conformance/tests/gateway-secret-reference-grant-specific.go
- conformance/tests/gateway-with-attached-routes.go
- conformance/tests/gateway-with-attached-routes.yaml
/kind feature
Add attachedRoutes to conformance tests.
Fixes #1543
NONE
> conformance: add attachedRoutes to conformance tests

- geps/gep-1709.md
/kind gep
There's been a lot of feedback from the community in community meetings and on recent PRs that there's a preference for named profiles to correspond directly with `*Route` APIs, and move down a level in granularity from `Layer 4` and `Layer 7`. This PR makes the language changes necessary to support that desire.
> docs: GEP 1709 profiles at the *Route granularity level

- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
Relates to https://github.com/kubernetes-sigs/gateway-api/discussions/1725
> Clarify semantics when port_redirect is unset

- conformance/tests/httproute-cross-namespace.go
- conformance/tests/httproute-disallowed-kind.go
- conformance/tests/httproute-exact-path-matching.go
- conformance/tests/httproute-header-matching.go
- conformance/tests/httproute-hostname-intersection.go
- conformance/tests/httproute-listener-hostname-matching.go
- conformance/tests/httproute-matching-across-routes.go
- conformance/tests/httproute-matching.go
- conformance/tests/httproute-method-matching.go
- conformance/tests/httproute-observed-generation-bump.go
- conformance/tests/httproute-query-param-matching.go
- conformance/tests/httproute-redirect-host-and-status.go
- conformance/tests/httproute-redirect-path.go
- conformance/tests/httproute-redirect-port.go
- conformance/tests/httproute-redirect-scheme.go
- conformance/tests/httproute-reference-grant.go
- conformance/tests/httproute-request-header-modifier.go
- conformance/tests/httproute-response-header-modifier.go
- conformance/tests/httproute-rewrite-host.go
- conformance/tests/httproute-rewrite-path.go
- conformance/tests/httproute-simple-same-namespace.go
- conformance/utils/kubernetes/helpers.go
/kind feature
In the conformance tests, the ResolvedRefs condition existence is always checked, even when true.
Fixes #1314 
```release-note
The conformance tests always check that the HTTPRoute ResolvedRefs condition is enforced, even when the status is true.
```
> conformance: HTTPRoute resolvedRefs condition always checked

- site-src/contributing/index.md
The code jam meeting has been regularly attended by several people
since it's inception. Given that success this patch makes it more
official by advertising it on our meetings page.
> docs: add code jam to meetings

- geps/overview.md
- hack/make-docs.sh
This updates the GEP overview page to add a state diagram and clarify some steps.'
Also includes cleaning out the `site-src/geps` directory because I was having problems getting it to update properly.
```release-note
NONE
```
> Update GEP overview to clarify the GEP process

- CHANGELOG.md
- README.md
- config/crd/experimental/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/experimental/gateway.networking.k8s.io_gateways.yaml
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_referencegrants.yaml
- config/crd/experimental/gateway.networking.k8s.io_tcproutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_udproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
- config/crd/standard/gateway.networking.k8s.io_gateways.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
- config/webhook/admission_webhook.yaml
- geps/gep-1709.md
- hack/verify-examples-kind.sh
- pkg/generator/main.go
- site-src/guides/index.md
Now that [v0.6.2](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v0.6.2) is released this brings some of the changes from the release branch back into `main` so that we're documenting the latest release properly in the `README.md`, e.t.c.
> docs: update latest release to v0.6.2

- .yamllint.yaml
- conformance/apis/v1alpha1/conformanceprofile.go
- conformance/apis/v1alpha1/conformancereport.go
- conformance/apis/v1alpha1/doc.go
- conformance/apis/v1alpha1/result.go
- conformance/apis/v1alpha1/statistics.go
- geps/gep-1709.md
/kind feature
/kind gep
/kind test
This supports #1784 by adding an experimental version of the `ConformanceReport` as described in [GEP 1709](https://gateway-api.sigs.k8s.io/geps/gep-1709/). Because the GEP is currently considered to be in the `Prototyping` status, the [rules](https://gateway-api.sigs.k8s.io/geps/overview/#status) we've set for that status indicate content must not be distributed in a release, so this PR introduces the idea of using [Golang build tags](https://www.digitalocean.com/community/tutorials/customizing-go-binaries-with-build-tags) as the mechanism to ensure the prototype content is not directly distributed as part of any upcoming release.
> GEP 1709: ConformanceReports prototype API

- site-src/guides/tls.md
Aligns the TLS example to the current API.
certificateRef does not exist anymore. It's called certificateRefs and is an array.
I don't think we need a separate issue for this.
```release-note
NONE
```
> site: fix TLS example

- conformance/tests/gateway-modify-listeners.go
- conformance/tests/gateway-modify-listeners.yaml
/kind test
Adds a conformance test that tests adding and removing listeners. 
https://github.com/kubernetes-sigs/gateway-api/issues/1607
Fixes #1607
```release-note
NONE
```
> Add a conformance test that checks adding and removing listeners

- mkdocs.yml
- site-src/contributing/contributor-ladder.md
- site-src/contributing/index.md
This adds a contributor ladder. This nearly identical to the [original doc](https://docs.google.com/document/d/19l77HW0jfOOu_ckMqu16-CC6W3GrQDiO8lmU9cj9LDc/edit#heading=h.s2dc1trxu6gv).
```release-note
NONE
```
> Adding a Contributor Ladder

- site-src/geps/gep-1619.md
/kind gep
Add a GEP for session persistence that establishes the foundation for describing it and establishing a common language.
Doesn't fix, but supports https://github.com/kubernetes-sigs/gateway-api/issues/1619
N/A
Markdown Preview: https://github.com/gcs278/gateway-api/blob/gep-1619/site-src/geps/gep-1619.md
> GEP-1619 Session Persistence and Session Affinity

- site-src/api-types/referencegrant.md
Fix grammar in ReferenceGrant implementation guidelines. Before this PR a sentence is truncated prematurely with a period, and the two chunks of the intended sentence make no sense in isolation. The PR rejoins the two chunks by replacing the period with a comma.
Fixes a grammar mistake in the documentation.
```release-note
Fix grammar mistake in ReferenceGrant implementation guidelines.
```
> Fix grammar in implementation guidelines

- apis/v1alpha2/grpcroute_types.go
- apis/v1alpha2/httproute_types.go
- apis/v1beta1/httproute_types.go
- apis/v1beta1/shared_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind bug
Add pattern for query param name in HTTPQueryParamMatch like other items' names to avoid illegal names.
Fixes #1729 
```release-note
Yes, illegal names like " " will be not allowed for query param name in HTTPQueryParamMatch.
```
> Add shared type `HeaderName` and use it for `GRPCHeaderName`, `HTTPHeaderName` and `QueryParamMatchName`

- OWNERS_ALIASES
- conformance/OWNERS
This adds @arkodg, @michaelbeaumont, @mlavacca, and @Xunzhuo as reviewers for conformance tests. Thanks to all of them for volunteering for this role!
```release-note
NONE
```
/cc arkodg @michaelbeaumont @mlavacca @Xunzhuo
> Adding Conformance Reviewers

- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
This PR clarifies Port Redirect Semantics for HTTP and HTTPS in the `HTTPRequestRedirectFilter.Port` doc.
Fixes #1806 
```release-note
NONE
```
> Clarify HTTPRequestRedirectFilter.Port Semantics

- apis/v1beta1/validation/gateway.go
- apis/v1beta1/validation/gateway_test.go
Signed-off-by: muyuan0 <127020730+muyuan0@users.noreply.github.com>
/kind bug
Check if the listener names are unique within a Gateway
Fixes #1845
```release-note
NONE
```
> Ensure listener name must be unique within a Gateway

- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
- conformance/tests/httproute-path-match-order.go
- conformance/tests/httproute-path-match-order.yaml
/kind bug
Path matches in following orders:
1. Exact
2. Prefix
Fixes #1770
```release-note
* Updated spec to clarify that Exact matches have precedence over Prefix matches and RegularExpression matches have implementation specific precedence.
* Added conformance test to verify that path matching precedence is implemented.
```
> feat: add support for path matching precedence

- geps/gep-713.md
- site-src/references/policy-attachment.md
/kind cleanup
/kind gep
This updates the Policy Attachment documentation as per the discussion in https://docs.google.com/document/d/1p_kmAOmqebX8zyHnXW5I58cD8ZhNX4QNSa_gw8uAYxw/edit?usp=sharing
There's an update to the original GEP, and to the site documentation.
> Policy attachment update

- conformance/tests/gateway-modify-listeners.go
- conformance/tests/gateway-observed-generation-bump.go
- conformance/utils/config/timeout.go
- conformance/utils/kubernetes/helpers.go
/kind feature
support configurable timeout for GatewayObservedGenerationBump
Fixes #1883
```release-note
support configurable timeout for GatewayObservedGenerationBump
```
> feat: support configurable timeout for GatewayObservedGenerationBump

- site-src/implementations.md
The PR changes the implementation name 'BIG-IP Kubernetes Gateway' to 'BIG-IP Kubernetes Gateway (beta)'.
Also add slack channel link in the description.
None
None
> Add beta indication to the BIG-IP Kubernetes Gateway project name

- RELEASE.md
- hack/update-webhook-yaml.sh
/kind cleanup
Configures and documents image promotion process for `admission-server` (and any other future components)
Corresponding change within kubernetes/k8s.io: https://github.com/kubernetes/k8s.io/pull/5030
Fixes https://github.com/kubernetes-sigs/gateway-api/issues/916
No
> Configure and document image promotion process

- apis/v1alpha2/grpcroute_types.go
- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_grpcroutes.yaml
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind feature
The graduates GEP-1323: Response Header Modifier to standard.
Fixes #1875 
```release-note
GEP-1323: Response Header Modifier has graduated to standard
```
> Graduating GEP-1323: Response Header Modifier to standard

- apis/v1beta1/httproute_types.go
- config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
- config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
/kind cleanup
This is a follow up to address some of the limitations of the current spec discovered in https://github.com/kubernetes-sigs/gateway-api/pull/1880. Specifically this adjust the spec to say that port shouldn't be added in these cases, not that it needs to be unset/removed.
```release-note
Clarification that port redirects should not add port number to Location header for HTTP and HTTPS requests on 80 and 443.
```
> Clarifying Port Redirect Behavior

- geps/overview.md
Seems like GitHub doesn't render the flow chart when the mermaid block is right under the div tag
/kind cleanup
> Fix mermaid diagram rendering

- conformance/tests/gateway-modify-listeners.yaml
- conformance/tests/gateway-with-attached-routes.yaml
/kind bug
The `GatewayWithAttachedRoutes` and `GatewayModifyListeners` conformance tests specify invalid BackendRefs (likely copy-pasted from the examples). This PR fixes them and sets the correct `BackendRefs`
Fixes #
```release-note
NONE
```
> `BackendRefs` fixed in `HTTPRoute` conformance tests

- apis/v1beta1/validation/gateway.go
- apis/v1beta1/validation/gateway_test.go
/kind feature
Add validation to validate the combination of port, protocol, and hostname are unique for each listener.
Fixes #847
```release-note
NONE
```
> Webhook: validate the combination of port, protocol, and hostname are unique for each listener.

- examples/standard/multicluster/0-namespaces.yaml
- examples/standard/multicluster/httproute-gamma.yaml
- examples/standard/multicluster/httproute-hybrid.yaml
- examples/standard/multicluster/httproute-location.yaml
- examples/standard/multicluster/httproute-method.yaml
- examples/standard/multicluster/httproute-referencegrant.yaml
- examples/standard/multicluster/httproute-simple.yaml
- geps/gep-1748.md
- mkdocs.yml
**_Recommend reviewing deploy preview so examples are inlined: https://deploy-preview-1843--kubernetes-sigs-gateway-api.netlify.app/geps/gep-1748/._**
/kind gep
This formally defines the relationship between Gateway API and Multi-Cluster Services as part of #1748.
I think the changelog notes should be saved for actual implementation PR, but open to ideas:
```release-note
NONE
```
Want at least one LGTM each from SIG-MC, GW API maintainers, and GAMMA leads before removing hold. Feedback from everyone (including people not directly mentioned below) is very appreciated.
SIG-MC:
/cc @lauralorenz @JeremyOT @pmorie 
GW API:
/cc @bowei @shaneutt @youngnick …
> Adding GEP-1748: Gateway API Interaction with Multi-Cluster Services
